### ISSUE TITLE
Audit DOM APIs that do layout reflows

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#10027]
We should audit the usage of any DOM api on this list and at least limit the usage. 
For example in APP_WINDOW_UPDATED we could do everything once and cache it.
https://gist.github.com/paulirish/5d52fb081b3570c81e3a

**Comment by jonathansampson** [comment]
Related: https://csstriggers.com/

**Comment by cezaraugusto** [comment]
<img width="382" alt="screen shot 2017-07-18 at 3 11 53 am" src="https://user-images.githubusercontent.com/4672033/28302974-ef453fd0-6b66-11e7-8746-cd9d6f589743.png">

**Comment by diracdeltas** [comment]
these are used all over the place in the Brave content scripts

**Comment by cezaraugusto** [comment]
I'll make use of this as a tracking issue there's a lot of room for improvement.

**Comment by cezaraugusto** [comment]
* Stick with compositor layers whenever needed
  * for tab previews
  * for new tab's first paint
  * for loading icon

* prefer using Intersection Observer API to track intersected elements instead of window size and getBoundingClientRect
  * for tabs (replace tab's breakpoint)
  * for downloads bar (replace current calculation)
  * for bookmarks toolbar (replace current calculation)

* wip

**Comment by zentagonist** [comment]
Spoke with @cezaraugusto - the bulk of the effort is completed. Setting milestone to 0.21.x
