### ISSUE TITLE
pinned tab disappears by reordering and unpinning

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10037]
## Test plan

https://github.com/brave/browser-laptop/pull/10531#issue-250554691

----

**Describe the issue you encountered:** pinned tab disappears by reordering and unpinning

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.17.17

- Steps to reproduce:
    1. Open github.com in a tab
    2. Open twitter.com in a new tab
    3. Pin github
    4. Pin twitter
    5. Reorder the two pinned tabs
    6. Unpin github
    
- Actual result: twitter, the other pinned tab, disappears

- Expected result: it should not disapper

- Any related issues:

**Comment by luixxiul** [comment]
the bug can be reproduced with any sites, including about pages

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/i-unpinned-one-tab-and-another-tab-disappeared/5268

**Comment by jamesray1** [comment]
I noticed a similar bug. I just tried to pin a tab and it disappears, when I have five other pinned tabs. I then unpinned a tab (the far right pinned tab) and two of the pinned tabs next to it disappeared. I was then able to pin a tab. I guess I'll have to not reorder pinned tabs until this bug is fixed.
