### ISSUE TITLE
URL shorteners should be set as exceptions for script blocking

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#10091]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
URL shorteners should be handled as exceptions when using script blocking because it seems that they use a script to redirect you to the site, when using script blocking you need to disable it on that site to be redirected 😅
For example twitter uses t.co to redirect you but you just get stuck there until you disable blocking for t.co 😕 This should be standard across iOS and android too 🙂
- Platform (Win7, 8, 10? macOS? Linux distro?):
All, even iOS and Android
- Brave Version (revision SHA):
All with JavaScript blocking enabled
- Steps to reproduce:
    1. Load a shortened link from example t.co
    2. See how you get stuck on t.co without redirect
    3.
    
- Actual result:
Stuck
- Expected result:
The most know URL shorteners should be set as for exceptions
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes until you disable script blocking
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
What if t.co is hacked by someone and malicious code is loaded on the browser, which could be avoided if scirpts of t.co were blocked? I believe one of the intents of users to block scripts globally is to prevent such a case. I don't think we should add exceptions by default because we don't (and cannot) know at all which shorteners are *always* safe.

That kind of stuff should be added with an extension, and I think it is a good idea :-D

**Comment by Jacalz** [comment]
You are totally right, maby adding it as an option in the advanced settings?

**Comment by Jacalz** [comment]
It has somewhat a different user case in iOS, I think users more use script blocking to use less data there but for desktop you are absolutely right 🙂
