### ISSUE TITLE
Automated performance tests

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#10115]
It would be really helpful to have automated tests measuring performance for common user profiles and tasks. We could run the tests with CI on every PR and release, and they would help us find performance issues and prevent regressions.

Example test ideas:
- Startup
- Use tabs (Open, Close, Switch)
- Browse websites
- Bookmark websites
- Bookmark manager
- History manager

Example user profiles:
- Fresh
- 300 tabs
- 1000 bookmarks

#9389
#9826

**Comment by lukemulks** [comment]
Suggestion:
- 1 run with default shields up. 
- 1 run with shields down. 

^we may be able to use this for marketing, by messaging as "Brave Shields increase perf by x%"
(Less emphasis on other browsers, more emphasis on how our features enhance our own performance.

I am probably posting this on the wrong issue, but wanted to add since you had listed test scenarios.

**Comment by diracdeltas** [comment]
#1252

**Comment by bbondy** [comment]
See also https://github.com/brave/browser-laptop/issues/1252

**Comment by bsclifton** [comment]
Closing as `wontfix`. If we did address this, we'd want to do so in [Brave Core](https://github.com/brave/brave-browser)

**Comment by bsclifton** [comment]
update: opened issue in brave-core: https://github.com/brave/brave-browser/issues/814
