### ISSUE TITLE
0.19.x: Private tabs are broken by the new tab page

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10182]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
I cannot get private tabs to work at all in 0.19.x. Selecting Menu > New Private Tab, File > New Private Tab, and Shift+Cmd+P do not work.
Based on the severity of the problem, I'm assigning it release/blocking and a 0.19.x milestone.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.19.1 (2ee7a49)

- Steps to reproduce:
    1. Open a new Brave window.
    2. Try creating a new private tab with Menu > New Private Tab.
    
- Actual result:
Nothing happens.

- Expected result:
A new private tab is created.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
No.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Open a new Brave window.
    2. Try creating a new private tab with Menu > New Private Tab.
    3. A new private tab should be created.

- Screenshot if needed:
Not applicable.

- Any related issues:
None.

**Comment by NejcZdovc** [comment]
I see this problem as well, let me take a look. On a first glance there are no errors, so could be related to muon / chromium

**Comment by NejcZdovc** [comment]
ok found the problem. Problem is that we are not creating a new private tab, but we are just setting active tab id to the existing opened tab. https://github.com/brave/browser-laptop/blob/master/app/browser/reducers/tabsReducer.js#L153 (this statement is triggered) instead of https://github.com/brave/browser-laptop/blob/master/app/browser/reducers/tabsReducer.js#L155

This problem was introduced with #9965

cc @bridiver

**Comment by srirambv** [comment]
This is an issue only during the initial launch. The focus sets to the new tab when you try opening a new private tab(either via menu/kb shortcuts). Closing the `about:welcome` tab or the new tab, allows to open a new private tab(via menu/kb shortcuts).

@cezaraugusto  @bradleyrichter  Is the `NewTab`  really necessary on first launch? Can we just show `about:welcome` so that user can choose to open newtab/private tab after launch?

**Comment by Liunkae** [comment]
@srirambv Yes, it looks like it's only an problem with the new tab page. The problem continues as long as at least one new tab is open.

It also happens if you do the following on macOS:

1. Open Brave.
2. Close all Brave windows (without quitting the Brave app itself).
3. Try to create a new private tab with Menubar > File > New Private Tab.
4. Notice that a new window opens with a normal tab instead of a private tab.

**Comment by NejcZdovc** [comment]
@bridiver can you please check out this comment https://github.com/brave/browser-laptop/issues/10182#issuecomment-318576031

**Comment by bridiver** [comment]
this issue description isn't 100% accurate. The new tab menus only fail to work when there is an existing newtab page open (only url matters, not private/session/etc...)
