### ISSUE TITLE
Metamask: Menu items are not shown properly

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10213]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Metamask: Menu items are not shown properly

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Name | Version
-- | --
Brave | 0.19.1
rev | f630692
Muon | 4.4.4

- Steps to reproduce:
    1. Enable MetaMask and generate password
    2. Click on the Buy button
    3. Text is trimmed off not properly shown
    
- Actual result:
See screenshot

- Expected result:
Should show properly

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/28784038-1d6846c0-760a-11e7-8565-6aba4198eb50.png)

- Any related issues:
cc: @jonathansampson @kevinlawler

**Comment by alexwykoff** [comment]
If this is fixed soonish we can move it back up to 0.19.x

**Comment by jonathansampson** [comment]
This issue is related to scaling; it can be reproduced in Brave by setting the _Toolbar and UI elements scaling_ to _Larger_. This scales the popup to 125% (roughly).

This issue exists organically (without setting _Toolbar and UI elements scaling_) on high-resolution displays, like the Surface Book where the OS/Display-scaling is set to any value above 100%.

**Comment by jonathansampson** [comment]
Closing in favor of #7051
