### ISSUE TITLE
Add user manager (for profile switching)

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10324]
From @mursalal https://github.com/brave/browser-laptop/issues/10303#issuecomment-320437781

> Hello! Please add user manager, so that all users have own cookies. Then the password manager will not be needed. All password managers working bad.

**Comment by kenorb** [comment]
I'm after this feature if I understood this correctly. This is kind of blocker for me to switch from Chrome. I see this feature as equivalent functionality to _People_ in Chrome.

For example in Chrome I'm using different user profiles for my private web browsing, e-mails, per each account on the same service (e.g. multiple gmail, GitHub accounts, banks, PayPal), work, companies (finance and accounting), IT projects, social activities, shopping, friends (when I do some stuff on behalf of them), sometimes per specific area of expertise and so on, so all my browsing history, passwords, cookies, bookmarks, downloaded files in different location, or even active plugins/extensions are separated from other different/non-related activities. So  Facebook or other ads providers doesn't track my activity when I'm doing non-Facebook activities, and my personal links or history isn't mixed with company profile where I work. Having different plugins per profile also helps with performance and for privacy reasons (so access from plugins are limited to certain group of activity). This also helps when I'm finishing certain contract or IT project to close that user profile, so I know that everything related to it is cleaned up properly (like internal addresses won't be shown in some personal history profile, and other way round) including private downloaded files aren't mixed with files downloaded at work as I can setup different download folder for each profile. I hope that make sense. If this issue is not exactly about it, then I can raise a new one.

Currently I'm using about 35 different user profiles and here is the example how I'm using this on Chrome:
![screen shot 2017-08-15 at 12 46 00](https://user-images.githubusercontent.com/266306/29314837-c568e83a-81b7-11e7-806f-ba45b70487d3.png) ![screen shot 2017-08-15 at 12 44 39](https://user-images.githubusercontent.com/266306/29314838-c56cd33c-81b7-11e7-9eba-03e42ad50595.png)

**Comment by jimtendo** [comment]
+1

Lack of this is also a deal-breaker for me. That aside, great browser.

**Comment by BraveSauce** [comment]
I'm not sure what this has to do with password managers.

Just my 5c, I quite like the fact that there are no browser-wide accounts. Perhaps make it so "New Session Tab" remembers the cookies for each different profile?

**Comment by mursalal** [comment]
@BraveSauce how to be if my PC uses several users?

**Comment by BraveSauce** [comment]
@mursalal If you are referring to my recommendation about it remembering the cookies for each session tab, then it would be as simple as choosing one to use for each user. But that's only a suggestion anyway.

**Comment by hollenberry** [comment]
I'd also like to drop by and add that this is a must have feature for me. I can't wait to start using Brave, but unfortunately will have to wait until this is implemented. 

I'll keep trying to remember to use it for a personal profile in the meantime, but share the sentiment of several users from this thread. https://community.brave.com/t/support-for-multiple-user-or-launch-profiles/3893/16

**Comment by bsclifton** [comment]
+1 from @jamesray1 via https://github.com/brave/browser-laptop/issues/12270

**Comment by BrendanThompson** [comment]
Any update on this, really keen to have support for multiple profiles!

**Comment by jamesray1** [comment]
@BrendanThompson I've been using session tabs, they are pretty useful, and there's then no need to have different windows.

**Comment by BrendanThompson** [comment]
Hey James yeah I started using that too. Keen to at least get colouring or labels with them.

Is there any keyboard shortcuts for creating new session tabs?

Sent from my iPhone

On 16 Jan 2018, at 17:45, James Ray <notifications@github.com<mailto:notifications@github.com>> wrote:


@BrendanThompson<https://github.com/brendanthompson> I've been using session tabs, they are pretty useful, and there's then no need to have different windows.

**Comment by srirambv** [comment]
>Is there any keyboard shortcuts for creating new session tabs? 

You can use Ctrl+Shift+S to create new session tabs. It creates subsequent session tabs and once it reaches session tab 9 it continues with that

**Comment by jamesray1** [comment]
@srirambv, awesome, it'd be good if you could put that shortcut in the new tab dropdown menu. Yes it wouldn't fit, but you could make the menu bigger?

**Comment by srirambv** [comment]
Here's a list of keyboard shortcuts for Windows 😉 
https://community.brave.com/t/brave-browser-shortcuts-currently-for-windows-only/10001

**Comment by BrendanThompson** [comment]
Looks good although running a Mac :)

Sent from my iPhone

On 16 Jan 2018, at 22:50, Sriram Bellur Venkataram <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's a list of keyboard shortcuts for Windows 😉
https://community.brave.com/t/brave-browser-shortcuts-currently-for-windows-only/10001

**Comment by bsclifton** [comment]
This should be addressed in [brave-core](https://github.com/brave/brave-browser) 😄

**Comment by jessetan** [comment]
@bsclifton Your link text is brave-core, but the actual link points to brave-browser. Where should this be filed?

**Comment by Liunkae** [comment]
@jessetan `brave-core` is the Brave functionality itself; `brave-browser` is the tool to build the browser. New issues should be filed at `brave-browser`.

This issue is tagged `addressed-with-brave-core`, which means the problem may be fixed with the new version of Brave (but it has not been confirmed).

**Comment by bsclifton** [comment]
@jessetan if you wanted to try an experimental build, you can go to the `Releases` tab for `brave-browser`. There, you'll see the downloads for what will be the upcoming version of Brave (what we're in the process of switching over to)
