### ISSUE TITLE
Open links in the background doesn't work when 'Switch to new tabs immediately' is enabled

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#10492]
Brave: 0.18.14 
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8 
Muon: 4.3.6 
libchromiumcontent: 60.0.3112.78 
V8: 6.0.286.44 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 16.0.0 
OS Architecture: x64

This is a feature request which exists in Chrome, Firefox and similar web browsers by default.

- Steps to reproduce:
    1. Enable _Switch to new tabs immediately_ at about:preferences#tabs
    2.  Go to: http://example.com/
    3. Hold (CMD on macOS, Control on Windows) a key and on click the link.
    4. By holding above key, I expect tab to open in the background.
    
- Actual result:

The tab is open and switched as active, so there is no difference when holding Ctrl/CMD key.

- Expected result:

I expect the tab would be open in the background.

**Comment by NejcZdovc** [comment]
@kenorb could you please try this in our latest version 0.18.21 (preview)? I tried it on the master and it's working correctly. You can enable previews in about:preferences -> Advanced -> Update to preview releases. Because this is still a preview, I would suggest to backup your session, just in case :smiley:

**Comment by NejcZdovc** [comment]
I am not sure, so I am cc @bradleyrichter
