### ISSUE TITLE
pinned tabs disappear until close/relaunch

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10510]
## Test plan

https://github.com/brave/browser-laptop/pull/10531#issue-250554691

----

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Using clean profile, if I pin a couple of sites from new tabs, reorder, and then 'reuse' the about:welcome tab and pin a site, the previously pinned sites disappear until close/relaunch.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
found with 0.18.22, exists in 0.18.14 also.

- Steps to reproduce:
    1. Clean profile
    2. launch Brave
    2. Don't close or use either of the tabs. Leave as is.
    3. Open a new tab
    3. visit a site
    3. pin the tab
    4. Open another new tab
    4. visit a different site,
    4. pin the tab
    4. Move this tab to the first position.
    5. Click on the about:welcome tab.
    5. Change the URL to a different site.
    6. Pin this tab.
    7. two previously pinned tabs are not displayed.
    
- Actual result:
Previously pinned tabs are not displayed. Must close/relaunch Brave to see them.

- Expected result:
Pinned tabs should not disappear.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![missingpinnedtabs](https://user-images.githubusercontent.com/28145373/29332866-8d95601a-81cf-11e7-9a65-2646b7682f48.gif)

- Any related issues:

**Comment by luixxiul** [comment]
duping to #10179?

**Comment by petemill** [comment]
Can reproduced when just moving any previously-pinned tabs then creating a new tab, visiting a url and pinning the new tab. All previously-pinned tabs disappears.
Can also reproduce most times when I have more than 7 or so tabs pinned, close and reopen the window, then try to pin a new tab with a different url.

The event app-tab-close-requested is being dispatched so I've been tracing where from. It's been an education in to the flow of the action dispatcher(s) and the browser window ipc communication. Pretty sure that the bug is in `updatePinnedTabs` in app/browser/window.js. Working on a fix now.
