### ISSUE TITLE
add a way to view TLS certificates

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1057]
There should be some way to at least view/download the raw TLS certificate on an HTTPS site. However, AFAICT the cert is only exposed to javascript when there is a certificate error event. 

For sites where there is a cert error, the frame security state includes 
```
       cert: {
            data: Uint8Array,
            issuer: string
        }
```

This should be visible somewhere in the UI - either by clicking on the lock icon in the URL bar, or as an advanced option on `about:certerror`.

**Comment by ramSeraph** [comment]
I came here after seeing the good-first-bug label. Can I have a go at this?

**Comment by diracdeltas** [comment]
Go for it; let me know if you have questions

**Comment by ramSeraph** [comment]
Sure, Will do

**Comment by ramSeraph** [comment]
Do we need to show the TLS cert only when there is a cert error or do we want to show it always?

Even for the error case, the comment on this [line](https://github.com/brave/browser-laptop/blob/master/js/components/frame.js#L328) seems to suggest that the ommision of the raw TLS cert was intentional for the "about:certerror" page. Should I go ahead and send the cert anyway or is there a way to pull the TLS cert lazily when required?

For the case when there is no cert error, if we really want it, we can probably make changes to electron to make the TLS cert available. I don't mind giving this a shot as long as I don't need to touch chromium :).

**Comment by diracdeltas** [comment]
> Do we need to show the TLS cert only when there is a cert error or do we want to show it always?

For now, I think it's fine to just show it when there's an error. Eventually it will be nice to show it always, but as you mentioned, that requires changing Electron. :)

https://github.com/brave/browser-laptop/blob/master/js/components/frame.js#L328 was happening as of a few Electron releases ago; i would try sending the cert anyway in hopes that the crash has been fixed now.

if it still crashes, you can make the about:certerror page send a message to the main process asking for the cert for a given URL. Similar to [this code path](https://github.com/brave/browser-laptop/blob/master/js/about/certerror.js#L29). Then in `app/index.js`, add an IPC listener for that message and return the cert to `e.sender`.

**Comment by ramSeraph** [comment]
Ack. Fixing problems with my dev env currently( I have a gnome ban, the gnome-keyring dependency was unexpected ). Will send a PR when done.

**Comment by kenorb** [comment]
The certificate can be checked in _DevTools_ in _Security_ tab, however clicking on _View certificate_ in _Overview_ does nothing. Same for _Secure Origins_ pages below, where _Open full certificate details_ doesn't do anything.

**Comment by cezaraugusto** [comment]
@ramSeraph are you still working on this issue?

**Comment by ramSeraph** [comment]
Nope. Sorry. Got busy elsewhere

**Comment by darkdh** [comment]
@ramSeraph , would you mind if I take it from here?

**Comment by luixxiul** [comment]
Is this in 0.11.2?

**Comment by bbondy** [comment]
yep not this release but next
