### ISSUE TITLE
intermittent - audio indicator is not shown

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#10611]
Sometimes even with audio playing, the tab audio indicator is not shown. Restarting Brave solves the issue. Intermittent issue without proper STR. Labeling as needs investigation.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version (revision SHA): 0.18.23
- Steps to reproduce: needs investigation

**Comment by srirambv** [comment]
I believe the issue comes from pinned tabs.  
STR 
1. Open YoutTube in a tab
2. Play any video, ensure the speaker icon is shown
3. Pin that YouTube tab, ensure the audio indicator is shown
4. Unpin YouTube tab, audio indicator/speaker is not shown, If there are tab pages, no noisy tabpage indicator
5. Switch focus on tab pages, speaker icon and noisy tab indicator is shown
