### ISSUE TITLE
Clear Cache + reload page (button/shortcut) - suggestion

### ISSUE THREAD

**Issue by guategeek** [brave/browser-laptop#10693]
Clear Cache+reload page option

As a web developer its annoying to have to go into preferences to clear the cache. It would be nice if you could hit the reload button with a modifier key held down to reload the page with a clear cache automatically done before hand. And/Or have a keyboard shortcut for clearing the cache and then reloading the page.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS 10.12.5

- Brave Version (revision SHA):
0.18.23

**Comment by bsclifton** [comment]
@guategeek you can actually force a clean reload with <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> 😄  
(Windows is <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> - but this functionality seems to be broken at the moment, see https://github.com/brave/browser-laptop/issues/10256)

Another option is to right click the reload icon and a menu will show `reload` and `clean reload`

**Comment by AndersBH** [comment]
Just wanna notify it's not exactly solved. On Chromium when you have the DevTools open you can right click on the reload button and you get "Normal Reload", "Hard Reload", "Empty Cache and Hard Reload". The 3rd button is missing on Brave.

**Related issue, there's probably already a ticket:**

I have also noticed when I change for example style.css, it doesn't reload like it normally would on other browsers, which probably has something to do with Brave trying to be faster than other browsers, and therefore is caching way more than you normally would. Normally I think it only starts caching when the same file is received a bunch of times.

As a web dev this would mean I would have to add a random string to the end of the filename like for example: style.css?9479584930494 which is a rare occurrence on normal browsers even if the file changes often. On Brave I would have to do this a lot to not make my site not break on Brave, and many other sites are probably already broken on Brave because of this.

So maybe not cache as much.

**Comment by joeclark-phd** [comment]
@bsclifton This begs the question: what *is* a "Clean Reload" if that doesn't mean clearing the cache and making a fresh request for the page files?  As @AndersBH comments, developers need an "Empty Cache and Hard Reload" option.  In Chrome this is achieved by holding CTRL and clicking the refresh button or hitting F5.  I hate to have to keep switching back to Chrome in order to test my changes to javascript files.  Is Brave going to get this feature?

**Comment by bsclifton** [comment]
@joeclark-phd if you use Shift + Ctrl + R or right click the reload button and pick `Clean Reload`, this should be working. Ctrl + F5 not working is a known bug captured with https://github.com/brave/browser-laptop/issues/10256

**Comment by joeclark-phd** [comment]
@bsclifton No, it doesn't work.  If you have dev tools open and look at the "network" screen, try a "Clean Reload" and you'll see that some or all JS and CSS will be reloaded from cache.  However, there's a "Disable Cache" checkbox which you may have checked by default that prevents this behavior.  It's tricky, though, because that checkbox only disables the cache while the DevTools is open!  (So, like a naughty but clever child, the Clean Reload will appear to be behaving correctly, but only when you're watching.)

**Comment by SirElTomato** [comment]
Just come across the same issue. 

@joeclark-phd fix works! Thanks!

Have dev tools open, tick 'disable cache' checkbox, perform clean reload

My context:

Brave | 0.20.30
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Comment by kgriffs** [comment]
Brave appears to send an if-none-match to check the etag even when doing a clean reload. I would prefer if it behaved as Chrome does and performed a regular GET request when the cache is disabled, to help me test caching proxy behavior.

---
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
