### ISSUE TITLE
private wallet data in ledger state files should be encrypted using password manager

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#10705]
The wallet private key and passphrase are as sensitive as most passwords, so we should use the Brave password manager encryption key to encrypt them before saving to disk.

related: https://github.com/brave/browser-laptop/issues/8449

cc @darkdh @mrose17

**Comment by alexwykoff** [comment]
@diracdeltas how would you rank this re: security? high/med/low?

**Comment by diracdeltas** [comment]
med

**Comment by hugobuddel** [comment]
Related #11419

**Comment by bridiver** [comment]
this shouldn't have been closed by the muon PR, it still needs to use the new api calls

**Comment by NumDeP** [comment]
Hi @alexwykoff I'd argue this is bordering on high on a med-high scale.

I'd also argue that restricting just the password wallet data to be encrypted as opposed to a couple of other items in that preference area as well may is you don't mind me saying built-in obsolescence. 

I stipulate a suggestion of allowing a feature in about:preferences#security where it would be appropriate to have a ‘PIN’ feature above ‘Data Privacy’ and under this you allow Security - Payments - Extensions (and future security orientated features/technologies) essentially making it invisible to guests and un-entered pin users (if that makes sense) once the password (pin) has been set for the browser.

Rather than having to type the entire post I created in the community, would you mind skimming though the information I pasted. Thanks.
 - https://community.brave.com/t/enhancing-private-data-security-braves-built-in-about-passwords/9858

**Comment by tanevanwifferen** [comment]
Priority has increased a lot lol. Beware of spectre peeking in through a malicious piece of javascript.

**Comment by bsclifton** [comment]
I think 0.21.x would be perfect 👍

**Comment by NejcZdovc** [comment]
@diracdeltas @darkdh do we plan do this before 1.0?

**Comment by diracdeltas** [comment]
probably wait to just do this in chromium-fork

**Comment by diracdeltas** [comment]
^ unless @darkdh has cycles to do this before then

**Comment by darkdh** [comment]
prefer doing that in chromium-fork, thanks.

**Comment by NejcZdovc** [comment]
added label post-v1

**Comment by bridiver** [comment]
@bsclifton was this ticket migrated to brave-browser? If not it needs to be.

**Comment by bsclifton** [comment]
Created https://github.com/brave/brave-browser/issues/2555 to track in brave-core 😄 👍
