### ISSUE TITLE
Create a downloads bottom toolbar to show in progress downloads

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1076]

**Comment by bbondy** [comment]
From @bradleyrichter 
<img width="997" alt="screenshot 2016-03-14 17 21 17" src="https://cloud.githubusercontent.com/assets/831718/13760360/31b75fe6-ea09-11e5-8bde-b4a42a1d7fcc.png">

**Comment by bradleyrichter** [comment]
@bbondy Here is a bit more detail...

For v1, I don't see the need for an about:downloads page since the list is represented in the downloads folder until you clear it manually. 

I noticed that Chrome's download list can be cleared but it doesn't remove the actual download from the finder. There may be a security reason for this that I am not aware of.

Safari does not maintain a download list at all. Only the toolbar status and door hanger which is similar to the bottom bar.


More verbose spec:

[laptop_downloads_bar.pdf](https://github.com/brave/browser-laptop/files/172904/laptop_downloads_bar.pdf)

**Comment by nathanbl** [comment]
https://addons.mozilla.org/en-US/firefox/addon/download-status-bar/

**Comment by bbondy** [comment]
Nathan please post a follow up task (or multiple) for those extra things. That would be very helpful but not in the initial first pass of this.
