### ISSUE TITLE
Brave freezes when opening tabs while a window is loading

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10866]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Brave freezes if you try to open tabs when a window has not loaded.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x.

- Brave Version (revision SHA):
0.18.29 (85f059d)

- Steps to reproduce:

    1. Open Brave.
    2. While the window is still loading (while it is completely white), rapidly press Cmd+T to open new tabs.

    Or macOS-only:
    1. Open Brave.
    2. Close the window without quitting Brave
    3. Rapidly press Cmd+T to open new tabs.
    
- Actual result:
Brave freezes.

- Expected result:
The tabs should be opened.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Not sure.

- Is this an issue in the currently released version?
Yes, 0.18.29.

- Can this issue be consistently reproduced?
Almost all the time.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
None.

- Any related issues:
Might be related to one of the freezing issues.

**Comment by Liunkae** [comment]
Duplicate of #10749.

**Comment by bbondy** [comment]
I think this is different from #10749 so re-opening. I'm going to move this to 0.19.x and move #10749 to 0.20.x

**Comment by Liunkae** [comment]
Sounds good! Please remove the duplicate tag.

**Comment by NumDeP** [comment]
This issue has become too common of an occurrence and it seems its happening more regularly than before with fewer tabs than usual as well. The unresponsiveness was always an issue but the crashes weren't as regular as they have been recently meaning before they used to wither because there was a lot of tabs available or very few tabs but the browser not having been refresh in long while.

Strange thing is I can still access the contents within the page, essentially make the last viewed website function almost properly with the exception of the url bar as you can see from the gif.

![2017-09-16_07h54_01](https://user-images.githubusercontent.com/31957540/30515017-8f1bf2fc-9b18-11e7-8843-dbc746fec940.gif)

**Comment by bsclifton** [comment]
@NumDeP good catch- this bug is crashing the UI and you can get the specific error message by pressing Shift + F8 to open the Browser developer tools and viewing the console tab (which should help us find the issue!) 

If it happens again, a screenshot is appreciated 😄

**Comment by NumDeP** [comment]
Hi @bsclifton any particular part of the console you'd like me to highlight because it's literally just occurred now. All I can see is the information in this screenshot. 

![2017-09-18_20h20_32](https://user-images.githubusercontent.com/31957540/30560197-a2971f3e-9ca6-11e7-8ba4-9a71e9a140f2.png)

**Comment by bsclifton** [comment]
@NumDeP thanks for capturing that- seems that no error is being logged ☹️  But it looks like @bbondy has [found the root cause and fixed](https://github.com/brave/browser-laptop/commit/912560e5c2bdb7f21ec6a5b6a586d3e9e7e0cf53)!  Stay tuned
