### ISSUE TITLE
Throttling autoupdate

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10863]
**Describe the issue you encountered:** 

From https://github.com/brave/browser-laptop/issues/1877#issuecomment-271341198

> I'd suggest a new issue for adding options for throttling or only do updates in certain connection types, but not disabling.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #1877 #5736

**Comment by bbondy** [comment]
let's summarize user-stories for things people want this for in the first comment.
For example:
As a user, I'd like to be annoyed less often when there are updates.
As a user, I don't want updates downloading when I'm on certain connection types.
As a user, I don't want to update during these hours of the day because my internet provider charges more. (I don't know if that's actually a thing for some places in the world, but just providing examples).

**Comment by cnst** [comment]
TBH, folks just want a disable button for the autoupdates.  Haven't seen anyone specifically interested in throttling.

IMHO, the correct interface should be a double-alert dialogue, asking the user for permission to download and automatically install the updates before the first update is ever downloaded; if accepted, we're done — download and install all you please; if declined, provide another window confirming they're absolutely sure to take the non-recommended approach of manual updates.

Subsequently, time-based update might be interesting, but is probably overengineering; what'd probably be more useful is button to temporarily disable updates for two weeks, e.g., when the person is on vacation, or is about to go on one.

In either case, the starting point should be a normal on/off switch (Mozilla already implements this).

**Comment by luixxiul** [comment]
implementing delta update would reduce the bandwidth consumption. See: https://github.com/brave/browser-laptop/issues/5736

**Comment by luixxiul** [comment]
+1 to the last option above:

> As a user, I don't want to update during these hours of the day because my internet provider charges more. (I don't know if that's actually a thing for some places in the world, but just providing examples).

https://community.brave.com/t/disable-automatic-updates/8157?u=suguru

> I’m from south asia, with internet charges & data limits I normally update my software using night time data.

**Comment by jjiimm64** [comment]
If Brave continues to auto-update...  I will auto-not use it anymore.

**Comment by bsclifton** [comment]
This is something we won't fix with our current browser (Muon). If folks wanted to try our new [developer release channel build](https://brave.com/download-dev) and check out the update experience, you may consider opening an issue for that repo too (if updates are too disruptive)

**Comment by cnst** [comment]
@bsclifton can you kindly clarify what you mean by your comment about the update experience in the new release / new codebase?  Is it no longer mandatory?

I trusted Brave and was a big fan, promoting it at various events, until I found out that you explicitly don't care about issue 1877 causing havoc on our systems.  Do you really expect the numerous folks for whom mandatory autoupdate was a dealbreaker to just "try" the new browser without first being assured that the mandatory autoupdate issue was addressed in the first place?  I'd need an assurance that you're not going the Chrome way here before I'd consider trusting you again.  (Firefox doesn't require mandatory autoupdate.)  Locking the other issue from new comments from your disgruntled users doesn't exactly instil that much trust, either.

P.S.  Also, on the practical side, the download links on your website don't actually work — I'm getting an "Unable to connect" error.

**Comment by bsclifton** [comment]
@cnst download links should definitely be working; you're not able to download via https://brave.com/download ?

This repository will go back into archived state after one final update. This version (`browser-laptop` or Muon) of the product is no longer maintained and is severely out of date.  There aren't any download links, because want folks to use the newer version of Brave. The current version of Brave (what is found on brave.com/download) can be found on GitHub at https://github.com/brave/brave-browser

RE: turning off auto-updates, I personally don't see that being something that we address. @diracdeltas may be able to give a better worded response, but basically it's important to us to deliver the most up-to-date software for our users as possible. When exploits are found and fixed, they need to be patched.  The newer version of our product (what is on brave.com, not the older Muon product that this repository is for) has much more seamless updates

Advanced users can always block access at the DNS level by making the host/IP used for updated non-routable. You'd do this by editing your /etc/hosts (or similar on Windows) and routing that host/ip to `0.0.0.0`

**Comment by cnst** [comment]
I don't think we're on the same page here, then.  "Seamless" updates doesn't sound like something that folks from this or the prior issue #1877 are looking for.  Thanks, but no thanks.

P.S. Also, I'm confused why you don't believe me that your download links really don't work.  The actual download links from https://brave.com/download are most definitely broken:

```
% curl -v https://laptop-updates.brave.com/latest/osx
* About to connect() to laptop-updates.brave.com port 443 (#0)
*   Trying ::2...
* Failed to connect to ::2: Network is unreachable
* Undefined error: 0
* couldn't connect to host
* Closing connection #0
curl: (7) Failed to connect to ::2: Network is unreachable
%
```

**Comment by bsclifton** [comment]
@cnst never said I didn't believe you, I just stated they should be working. I alerted our devops team to investigate. Thanks for sharing the above information

RE: the updates, I think you'll have to try the new product (once the download link is working for you). Since GitHub is working for you, you can download the latest release here:
https://github.com/brave/brave-browser/releases/tag/v0.62.51

For this new version of the product, let's create an issue:
https://github.com/brave/brave-browser

This GitHub issue that we're chatting in is regarding the old deprecated product, which we no longer support. For this old deprecated product, you won't have to worry about updates because there won't be any 😛 (well, we may have one more, but that's it)

**Comment by bsclifton** [comment]
Locking conversation - all relevant details have been shared. Head over to https://github.com/brave/brave-browser if you'd like to create a new issue

Thanks all 😄
