### ISSUE TITLE
History limit in the state

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10895]
**Describe the issue you encountered:**

With site split PR I accidentally removed history limit in the state, so right now we are saving all history sites in the state without any limitations.

**Comment by luixxiul** [comment]
On packaged build based on the latest master I notice the URL bar performance gets worse clearly. Is it  because of this bug?

**Comment by NejcZdovc** [comment]
@luixxiul I don't think that we already have packaged build based on the latest master

**Comment by luixxiul** [comment]
`CHANNEL=dev npm run build-package`

**Comment by NejcZdovc** [comment]
channel dev is 0.20.x, nightly is 0.21.x == the latest master

**Comment by luixxiul** [comment]
I think `CHANNEL=dev` is not renamed to the latest status, because when you run `git fetch upstream master && git rebase upstream/master && CHANNEL=dev npm run build-package` you get

Brave: 0.20.0 
V8: 6.1.534.31 
rev: 1eca241de5ed44fedee98bb7ed365c683425b08f 
Muon: 4.4.15 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 61.0.3163.71

I am pretty sure it is based on the latest master as #10238 is applied.

**Comment by bsclifton** [comment]
@luixxiul @NejcZdovc when we create 0.20.x, we likely didn't increment the version of master to 0.21.0.  I went ahead and did that right now with https://github.com/brave/browser-laptop/commit/59d1627763290fc55b9194ffc08f8b1963efea14

**Comment by bsclifton** [comment]
@luixxiul also: `dev` is now displayed as `Release` thanks to @prasanthp96 via https://github.com/brave/browser-laptop/pull/10387 😄

**Comment by NejcZdovc** [comment]
ok back to the original comment from @luixxiul. Is this performance problem only with packaged build or is the problem on regular development run as well?

**Comment by luixxiul** [comment]
I haven't tried the same profile on `npm run watch` so I am not sure.

**Comment by NejcZdovc** [comment]
@luixxiul can you please try this scenario so that we know if the problem is limited to package. Thank you

**Comment by luixxiul** [comment]
reproduced on npm run watch as well

**Comment by NejcZdovc** [comment]
ok, can you please define STR, so that I can test it as well
