### ISSUE TITLE
Brave menu bar hardly visible with default Ubuntu MATE theme

### ISSUE THREAD

**Issue by orschiro** [brave/browser-laptop#11109]
I was told to by the Ubuntu MATE team to report this error here. 
Original bug report: https://bugs.launchpad.net/ubuntu-mate/+bug/1718859

Tested with Brave 0.18.36-1.

![image](https://user-images.githubusercontent.com/170947/30770976-d6747546-a03d-11e7-9d2c-35221c03a185.png)

**Comment by hugobuddel** [comment]
Also the case in 0.19.48. It seems as if the menu background is taken from the MATE theme (dark), but not the text color (black). Have not tried switching themes to verify.

Also, it seems not possible to use the menu with just the keyboard. Most Linux apps will allow one to type Alt-<letter> to open a menu, like Alt-F for the file menu. Brave for Windows allows the user to move through the menu with the arrow keys. Both are not possible in Brave 0.19.48 on Ubuntu 16.04.3 using MATE.

Furthermore, the menu bar is often there when starting brave or when opening a new window even though the option is unticked. As if 'alt' is pressed, but it isn't. Sometimes it disappears automatically. (This was actually what lead me to this bug report, because I don't use the menu normally.)

**Comment by Liunkae** [comment]
+1 with Brave 0.19.88 on Ubuntu 17.10 with GNOME. Black text on a dark gray background is not very readable.

**Comment by fubuloubu** [comment]
+1 Brave 0.22.721 on Ubuntu 18.04 LTS w/ GNOME

**Comment by scottbomb** [comment]
Why was this closed? "addressed-with-brave-core" shows nothing ("No results matched your search."). That doesn't look like a resolution. Is it that hard of a change to make? No other browsers have this problem so I don't think that blaming the OS is helpful. Using version 0.24.0 on Ubuntu Mate 16.04.

**Comment by hugobuddel** [comment]
The Brave team is rewriting major parts of the browser to use a new backend (called brave-core). That new browser (named brave-browser, instead of brave-laptop) does not have this menu-color issue. (brave-browser has a Chrome-like menu instead of the old menu, because it is based on Chromium.) They apparently decided that they will not fix this bug for brave-laptop, because it is not severe and will not be relevant in the near future.

I'm not part of the Brave team. I learned all this because I had a similar reaction to a different issue; so just sharing my knowledge. You can find developer versions of the new browser on github: https://github.com/brave/brave-browser/releases (those are not officially supported and might be buggy and such)

**Comment by bsclifton** [comment]
@scottbomb what @hugobuddel said is correct- we're in the process of moving the product to a new code-base. We just released our beta the other day actually, which (besides the above link) you can get here:
https://brave.com/download-beta
