### ISSUE TITLE
Suggestion: replace the payment heart icon with the BAT symbol

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11163]
### Description

Replace the payment heart icon with the BAT symbol. 

Based on the feedback here https://github.com/brave/browser-laptop/issues/4634#issuecomment-332379472 and the discussions on our community site, it looks like the heart icon does not seem to be telling some people what it stands for.

![](https://discourse-cdn-sjc1.com/standard2/uploads/brave/original/2X/0/00f54a0ecb6a57f5987cbb051c2367c3ad1dce43.png)

- https://community.brave.com/t/hexagon-heart/4973/6

Since we have the icon much more meaningful, why wouldn't we replace the heart icon with it? 

### Brave Version

**about:brave info:**

 
Brave: 0.19.17 
rev: e7e4365f727619a0f2f895c814411de06de9b7d8 
Muon: 4.4.20 
libchromiumcontent: 61.0.3163.98 
V8: 6.1.534.39 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
This is a great suggestion 😄 
cc: @bradleyrichter @alexwykoff @jenn-rhim

**Comment by bradleyrichter** [comment]
I was considering this recently but we still need tooltips on this. I swear we had them originally? Or was it never implemented?  cc @cezaraugusto ?

**Comment by luixxiul** [comment]
the tooltip is displayed on master branch, probably since https://github.com/brave/browser-laptop/commit/8717c971af9ca5480753a9325f7c8b48c8886f6a#diff-cef414c4e6eb695ee32038859bba26ccR39.

**Comment by NejcZdovc** [comment]
yeah I fix it, so that is working again. It was a regression

**Comment by NejcZdovc** [comment]
tooltips were fixed few versions ago

**Comment by eljuno** [comment]
+1 from community to avoid confusion with Torrent viewer https://community.brave.com/t/extensions-torrent-viewer-extension-disabled-but-still-working/28226?u=eljuno

**Comment by bsclifton** [comment]
I believe this will be fully fixed with Brave Core, where we will officially transition from `Brave Payments` over to `Brave Rewards`

You can see a preview of what things look like in Brave Rewards by checking out this PR by @NejcZdovc adding the needed controls to our [UI toolkit library](https://github.com/brave/brave-ui):
https://github.com/brave/brave-ui/pull/36

When visiting a website, there will be a BAT logo which is clickable which brings up some of the interface in a small modal. Maybe @bradleyrichter, @jenn-rhim, or @karenkliu can share an example here? 😄
