### ISSUE TITLE
Support importing bookmarks from Pinboard

### ISSUE THREAD

**Issue by onmyouji** [brave/browser-laptop#1120]
I tried to import bookmarks from a HTML file (I got this file from my Pinboard account).

The bookmarks don't show up on Bookmarks Manager or Toolbar. But when I tried to open some of the links from the HTML file, I can see the red star icon next to the URL bar (which means it did get imported).

Can anyone help me to troubleshoot this? I run Win 7.

Thanks.

**Comment by bbondy** [comment]
Which browser did you import from? We don't support Safari yet.

**Comment by onmyouji** [comment]
Oh okay. I import it from [Pinboard](http://i.imgur.com/jTk31m2.png), a bookmarking website (https://pinboard.in/).

**Comment by bbondy** [comment]
Likely once we fix Safari it'll also fix this, but I'll leave this open to verify.

**Comment by bbondy** [comment]
Is it possible to have a sample of a pinboard export?  If you'd rather you could also email it to brian@brave.com.

**Comment by onmyouji** [comment]
I just email you the sample.

**Comment by bbondy** [comment]
These import into Other Bookmarks now inside of bookmarks manager.   Note that we don't support multi selections yet on the bookmarks manager so maybe moving fthem from there to the bookmarks toolbar will be a bit tediuous until we have it.
Fixed in: https://github.com/brave/browser-laptop/commit/e79cfab945527290a48c0ea525589309eeb8e356
