### ISSUE TITLE
Brave wallet backup key 2 overflows

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11292]
### Description

Brave wallet backup key 2 has a wrong value

### Steps to Reproduce

  1. Open about:preferences#payments
  2. Open advanced settings
  3. Click `Backup your wallet`

**Actual result:**

<img width="988" alt="screenshot 2017-10-05 22 05 50" src="https://user-images.githubusercontent.com/3362943/31228726-6e5e714c-aa19-11e7-9b95-7fde0ab40e59.png">

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

2ca88153090ed241b97e08dffb9b37d2e1067250

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
this is not the correct value. We shouldn't be changing css, but we have problem with keys

**Comment by NejcZdovc** [comment]
more info:

current master is working correctly (d6447e8f595ad42d9bc47407d1727c75c7b239cf), problem is only `bat-integration` branch. And that's because we changed the logic, how we are getting passphrase.

Master: https://github.com/brave/browser-laptop/blob/d6447e8f595ad42d9bc47407d1727c75c7b239cf/app/browser/api/ledger.js#L1563

BAT: https://github.com/brave/browser-laptop/pull/11231/files#diff-3cdfdb124f718787d584e9e2b82fcedcR1554

Problem is that logic changed in bat library.
ledger-client: https://github.com/brave/ledger-client/blob/master/index.js#L215
bat-client: https://github.com/brave-intl/bat-client/blob/master/index.js#L248

**Comment by NejcZdovc** [comment]
after talking with @mrose17 about it, this is new way of doing things

**Comment by NejcZdovc** [comment]
fixed with #11231

**Comment by srirambv** [comment]
Added QA/checked as the workflow is changed to single key and this is obsolete

**Comment by luixxiul** [comment]
the single key should not overflow anyway.

**Comment by bsclifton** [comment]
Removed milestone because this screen was reworked- this is no longer valid

**Comment by luixxiul** [comment]
This line of #11291 actually prevents the overflow. 

https://github.com/brave/browser-laptop/blame/master/app/renderer/components/preferences/payment/ledgerBackup.js#L92

The hack with `max-content` which I have added will be removed with https://github.com/brave/browser-laptop/pull/11344 so `no-qa-needed` for this issue anyway.
