### ISSUE TITLE
Close tear off window causes other windows to background 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11445]
### Description
Close tear off window causes other windows to background 

### Steps to Reproduce

  1. Open brave and couple of other app
  2. Tear off a tab into another window 
  3. Close the tear-off tab window
  4. Brave main window is backgrounded and other app becomes active

**Actual result:**

Close tear off window causes other windows to background 
**Expected result:**
Focus should be on the other brave winfow and should not switch focus to other apps
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

Brave | 0.19.39
-- | --
rev | ebcd280
Muon | 4.4.27

**Reproducible on current live release:**

Yes 
### Additional Information

cc: @bsclifton

**Comment by bsclifton** [comment]
@srirambv do you have more info on this? I've tested on macOS and Windows and in both cases, I can't reproduce.  I tried the two following scenarios:
- Have multiple tabs. Drag one out, so that a new window is made. Close that new window.
- Have multiple tabs. Drag one out, so that a new window is made. Drag another tab from original window to this new window. Close new window
