### ISSUE TITLE
[Suggestion] Open link in silent tab

### ISSUE THREAD

**Issue by iampox** [brave/browser-laptop#11491]
Hello,

I'm currently using Brave browser on my macOS laptop and I think it's really great.  
I see more and more functionalities and extensions (Bitwarden yeah!).  
Do you plan on developing something that'll enable using Chrome/Firefox extensions with Brave?  
Any plan to integrate an "open link in silent tab" feature like this [Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/open-link-in-silent-tab/)?

Thanks!

**Comment by bsclifton** [comment]
@iampox we are tracking the extensions that users request here:
https://github.com/brave/browser-laptop/projects/1

We're tracking these because we don't have support for all extensions (yet).  We're pulling in Chromium code as needed, with @jonathansampson and @kevinlawler working hard on implementing that

This feature request should be easy enough to handle with an extension.  I did a quick search and found these three, which may or may not solve the problem:
https://chrome.google.com/webstore/search/silent%20tab

Let us know if any of those look like they solve your issue!  We can then make sure it gets added to our extension list 😄
