### ISSUE TITLE
QR codes not being displayed when creating a new wallet

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11492]
### Description

When creating a new wallet, you'll notice that the QR codes are not being displayed under the "Add Fund" manager.

### Steps to Reproduce

  1. launch the latest brave (`0.19.48` was being used in this instance)
  2. create a new wallet under `about:preferences#payments`
  3. select "Add Funds" and click on any cryptocurrency that's listed in the manager

**Actual result:**

<img width="723" alt="screen shot 2017-10-12 at 1 16 59 pm" src="https://user-images.githubusercontent.com/2602313/31510195-002aa91e-af52-11e7-8f82-d6279c662f3a.png">

QR code isn't being displayed.

**Expected result:**

QR code should be visible as another way of adding funds into the wallet.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.48 
> rev: de939f6dcd1647f43de544b22dfdd103585b4ec2 
> Muon: 4.4.28 
> libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

No, part of BAT which is being introduced in `0.19.x`

**Comment by bsclifton** [comment]
I think this error in the console is related:
`Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>. See p > ... > p.`

**Comment by bsclifton** [comment]
I believe I found the issue

This call should be generating the code- it's never getting called:
https://github.com/brave/browser-laptop/blob/a314b4e1c83cfbcc6b958bdc7ce6d00837c7cb4c/app/browser/api/ledger.js#L1735

I believe this was broken here:
https://github.com/brave/browser-laptop/commit/c96500235aa9d1f431b67edfae875b1d56bad528

Because the unconfirmed amount is 0 (which matches the state), it returns without making the call.  Looking into a fix...

**Comment by kjozwiak** [comment]
Also checked the following under Ubuntu 17.04 x64:

* ensure that the QR codes are appearing when creating a new wallet with a clean profile under `0.19.52`
* ensure that the QR codes are appearing when upgrading from `0.19.36` -> '0.19.52'
* esnure that the QR codes are appearing once a wallet as been recovered under '0.19.52'
