### ISSUE TITLE
Netflix Error Code M7121-1331-P7

### ISSUE THREAD

**Issue by MirRaonaq** [brave/browser-laptop#11560]
### Description
Netflix cannot be played, looks the issue is resolved with the actual Brave browser download but not with this GitHub repository.

  1. Search Netflix.com and logged into my Netflix account.
  2. Played an episode of the office and the error came up.

**Comment by bsclifton** [comment]
@MirRaonaq does the issue happen in another browser? (FireFox, Safari, Chrome?)

**Comment by MirRaonaq** [comment]
Works fine in other browsers

**Comment by kjozwiak** [comment]
@MirRaonaq when you say:

> but not with this GitHub repository.

Do you mean a build that you've compiled from GitHub? If that's the case, Netflix doesn't work on builds that have been compiled from GitHub has they haven't been singed with the Widevine certificate.  Only builds that are available for download are signed.

**Comment by MirRaonaq** [comment]
@kjozwiak Ohh that makes sense, is there any way I can get Netflix to work on the one I compiled on Github?

**Comment by bsclifton** [comment]
Great catch, @kjozwiak 😄   I'll mark this issue as `wontfix`

@MirRaonaq unfortunately there is not. The details regarding the Widevine DRM are protected by an NDA unfortunately.  Our official build process (in order to accommodate Widevine) includes some steps which are not open source

We should definitely update our documentation to call this out
