### ISSUE TITLE
Flash still not working after following the troubleshoot page

### ISSUE THREAD

**Issue by gmlpaci** [brave/browser-laptop#11663]
### Description
Flash still not working

### Steps to Reproduce
I have followed all the steps on [https://github.com/brave/browser-laptop/wiki/Flash-Support-Deprecation-Proposal#troubleshooting-flash-issues](url)

  1. Download the flash .rpm files on Adobe site
  2. Copy the instructed files into the usr/lib/pepperflashplugin-non free
  3. Restarting both Brave and my Laptop

**Actual result:**
The flash option still disable

**Expected result:**
Flash should be working fine because I followed all those steps
### Brave Version
Brave: 0.19.53 
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.8.0-52-generic 
OS Architecture: x64

**Comment by netroby** [comment]
+1 flash player not load. plugin load failed.

**Comment by Rocket-Wolf** [comment]
**Flash still fails to operate**. Unable to change the setting in preferences to "enable flash support" because the slider is greyed out, verified that files libpepflashplayer.so and manifest.json from chrome profile are copied into /usr/lib/pepperflashplugin-nonfree/, brave wiki suggesting to use homestarrunner.com to test flash just shows how out of date the wiki is because that site no longer uses flash content therefore attempted to load a flash site at https://get.adobe.com/flashplayer/about/ and fails to start. Flash works perfectly in Chrome, Firefox, and Opera. 

System:   Host: Gigabyte500 Kernel: 4.15.11-041511-generic x86_64 (64 bit) Desktop: MATE 1.18.0
                Distro: Linux Mint 18.3 Sylvia
Machine: System: Gigabyte product: N/A
                Mobo: Gigabyte model: H170M-D3H-CF v: x.x Bios: American Megatrends v: F2 date: 07/27/2015
CPU:       Quad core Intel Core i5-6600K (-MCP-) cache: 6144 KB clock speeds: max: 3900 MHz 1: 1600 MHz 2: 1600 MHz 3: 1600 MHz 4: 1599 MHz
Graphics: Card-1: Intel HD Graphics 530
              Card-2: Advanced Micro Devices [AMD/ATI] Curacao PRO [Radeon R7 370 / R9 270/370 OEM]
              Display Server: X.Org 1.18.4 drivers: ati,radeon,intel (unloaded: fbdev,vesa)
              Resolution: 1600x900@60.00hz, 1600x900@60.00hz
              GLX Renderer: AMD PITCAIRN (DRM 2.50.0 / 4.15.11-041511-generic, LLVM 5.0.0)
              GLX Version: 3.0 Mesa 17.2.8
Audio:    Card-1 Intel Sunrise Point-H HD Audio driver: snd_hda_intel Sound: ALSA v: k4.15.11-041511-generic
              Card-2 Advanced Micro Devices [AMD/ATI] Cape Verde/Pitcairn HDMI Audio [Radeon HD 7700/7800 Series]
              driver: snd_hda_intel
              Card-3 Tenx driver: USB Audio
              Card-4 Microsoft LifeChat LX-3000 Headset driver: USB Audio
              Card-5 Logitech Webcam C270 driver: USB Audio
Network:Card: Intel Ethernet Connection (2) I219-V driver: e1000e
               IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: 40:8d:5c:47:37:a1
Drives:    HDD Total Size: 1500.3GB (18.6% used) ID-1: /dev/sda model: CT500BX100SSD1 size: 500.1GB
               ID-2: /dev/sdb model: ST1000DM003 size: 1000.2GB
Partition: ID-1: / size: 458G used: 34G (8%) fs: ext4 dev: /dev/sda2
               ID-2: swap-1 size: 17.00GB used: 0.00GB (0%) fs: swap dev: /dev/sdb3
               ID-3: swap-2 size: 1.02GB used: 0.00GB (0%) fs: swap dev: /dev/zram0
               ID-4: swap-3 size: 1.02GB used: 0.00GB (0%) fs: swap dev: /dev/zram1
               ID-5: swap-4 size: 1.02GB used: 0.00GB (0%) fs: swap dev: /dev/zram2
               ID-6: swap-5 size: 1.02GB used: 0.00GB (0%) fs: swap dev: /dev/zram3
RAID:     No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 29.8C mobo: 27.8C gpu: 47.0
               Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 242 Uptime: 27 min Memory: 2368.4/7771.8MB Client: Shell (bash) inxi: 2.2.35

**Comment by pemartins1** [comment]
Flash Player is still not working for me either.

Kubuntu 18.04.1 LTS

Brave | 0.23.79
-- | --
V8 | 6.8.275.24
rev | 51b4905
Muon | 8.0.7
OS Release | 4.15.0-30-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

Flash is enabled in browser.
pepperflashplugin-nonfree is installed.
/usr/lib/pepperflashplugin-nonfree/ exists and has both libpepflashplayer.so and manifest.json required files.

Running brave from the command line I get the following error while trying to run flash:

> [1:1:0811/222341.541206:ERROR:ppapi_thread.cc(302)] Failed to load Pepper module from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so (error: /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so: cannot open shared object file: Operation not permitted)
