### ISSUE TITLE
Setup a Debian repository

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1170]
https://wiki.debian.org/HowToSetupADebianRepository

**Comment by nashe** [comment]
Taking it.

**Comment by mrose17** [comment]
Duplicate, closed.

**Comment by mrose17** [comment]
sorry, my bad, wrong issue.

**Comment by zmanian** [comment]
I'm curious what direction the brave team would go like to go for this.

An alternative would be do something like what SublimeText does in Linux and simply pop up a dialog when a new release is available and direct people to the releases page to manually download and install.

I really prefer being notified about a release by the app rather than manually checking the releases page periodically.

If this is of interest, I'd be willing to work on a linux platform handlers for browser-laptop/app/updater.js.

**Comment by bbondy** [comment]
Notifying with the update bar that we have directing people to the download page would be great.  Maybe direct them to this page though.
https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md

You can move to this issue though, and keep this issue open for the repository. 
https://github.com/brave/browser-laptop/issues/1470

**Comment by Szalacinski** [comment]
I would personally rather have this install and update using a PPA or a repository rather than a manual install.  One of the great things about Linux is centralized updates.  If I have to update every single application manually by going to a website, then It feels like I'm on Windows.  I also dislike snap packages, because they encourage poor security with the "it's sandboxed" excuse.  If I want a security patch for OpenSSL, then I shouldn't have to update 20 different individual apps along with the system libraries.  Go ahead and do a snap package for the eventual users of the Ubuntu Phone, but please make a PPA or something similar for those of us that enjoy the simplicity of standard deb packages.

**Comment by Szalacinski** [comment]
I would also rather Brave set up their own repository so we can put our trust behind them instead of J. Random on the Internet.

**Comment by dandart** [comment]
Until then, has anyone PPA'd this?
I discovered I was using 0.9.x and even asked about updates and it said there were no new updates, then I went to the website and it said there was an 0.11.5... has that issue been fixed in between then and now?

Bog standard ubuntu 16.04

I agree with Szalacinski - a PPA/deb repository would be much better than manually downloading - as it all comes down in one lump.

Even consider submitting to Debian and Ubuntu's real repository - for instance into universe...

**Comment by mslinn** [comment]
+1 for publishing to a PPA. Best if it was universe, but anything is better than nothing

**Comment by bkjohnson** [comment]
Any word on this?  I currently run brave by periodically updating my cloned repo and building it.  It would definitely be nice if this was in a PPA or universe so I could just rely on apt.

**Comment by posix4e** [comment]
I just setup a nightly repo and more stable one. Future apt and rpm releases will have a repo. Please keep a look out

**Comment by keverets** [comment]
I followed the directions at https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md but the apt repo doesn't seem to be well-formed:

```
Get:30 https://s3-us-west-2.amazonaws.com jessie/main amd64 Packages              
Err https://s3-us-west-2.amazonaws.com jessie/main amd64 Packages           
  HttpError403
Get:31 https://s3-us-west-2.amazonaws.com jessie/main i386 Packages         
Err https://s3-us-west-2.amazonaws.com jessie/main i386 Packages            
  HttpError403
```

**Comment by posix4e** [comment]
@keverets tell me what line it added to your apt? 

For me it on ubuntu it looks like
```
posi@posi:~$ cat /etc/apt/sources.list|grep brave
deb https://s3-us-west-2.amazonaws.com/brave-apt xenial main
```
For you it should look like
```
deb https://s3-us-west-2.amazonaws.com/brave-apt jesse main
```

**Comment by tilgovi** [comment]
Working fine here with `xenial`, but I'm running `yakkety`. @posix4e which releases can be expected to be supported?

**Comment by posix4e** [comment]
oh hi @tilgovi ! For now we have tested trusty, xenial, jesse and stretch.

**Comment by keverets** [comment]
@posix4e it contains:

```
deb https://s3-us-west-2.amazonaws.com/brave-apt jessie main
```

I see you typing "jesse", but the repo is actually for "jessie" (with an 'i'). Wonder if that's relevant.

**Comment by posix4e** [comment]
That explains that, It was a bug I carried over from another workaround it should be fixed in the next releases. I will completely rebuild those repositories.

**Comment by ywum7fhv0skqh07h** [comment]
The page [here](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md) is completely useless. You can't use lsb_release without covering all releases or making it clear which ones are available.

I am using Debian Sid and it's ridiculous that I have to trial and error release names to find the most up-to-date release available. Missing releases: "Experimental", "Unstable" (current codename Sid), "Sid", "Stable" (current codename Jessie), "oldstable" (current codename Wheezy). 

The repositories also appear to be missing source and Release files (https://wiki.debian.org/SecureApt#Signed_Release_files).

You really have to get your act together if you want Linux users to treat your browser properly.

**Comment by posix4e** [comment]
I added a list of releases we support.

**Comment by posix4e** [comment]
In addition,

posi@posi:~$ aws s3 ls brave-apt/dists/trusty/
                           PRE main/
2016-12-15 12:36:52       2316 InRelease
2016-12-15 12:36:52       1448 Release
2016-12-15 12:36:52        819 Release.gpg
posi@posi:~$

We seem to have a releases file. I'll attempt to fix this soon for jessie.
