### ISSUE TITLE
Implement React Hot Loader

### ISSUE THREAD

**Issue by rickyrauch** [brave/browser-laptop#1171]
## Comment by @bsclifton
We can consider implementing React Hot Loader:
http://gaearon.github.io/react-hot-loader/

## Original post
Hello,

I'm trying to make a skin for Brave, while I'm developing the whole app refreshes and the live editing is not working. Do you have a starting point to find out what's the problem? 

This video is when I try to modify the css https://cloudup.com/cQYrU8W0TSP

**Comment by bobvanluijt** [comment]
Curious to know, can you share a bit more info how you are planning to use and distribute the skin? Is it on your Github? Thx

**Comment by bridiver** [comment]
This is the correct behavior. Webpack reloads on js/css changes.

**Comment by rickyrauch** [comment]
@bridiver no, it is not. 
http://gaearon.github.io/react-hot-loader/

**Comment by bridiver** [comment]
it doesn't look terribly difficult to implement, but it's definitely not a high priority for us right now. If you want to try it out and submit a PR we will definitely look at it

**Comment by jide** [comment]
Hi,
I wanted to help so I tried implementing hot reload.

I tried different approches ([react-hot-loader](https://github.com/gaearon/react-hot-loader) 1 and 3), but ran into problems because the root component rendered at init [is passed initial props from ipc](https://github.com/brave/browser-laptop/blob/master/js/entry.js#L81), which makes this difficult.

I then found that hmre works without issues, though some warnings like "[HMR] unexpected require(271) from disposed module 853" can pop, but they can be safely ignored to my knowledge.

**Comment by bsclifton** [comment]
@luixxiul was there a reason this was re-opened? This behavior is part of webpack

**Comment by luixxiul** [comment]
I read the comment above https://github.com/brave/browser-laptop/issues/1171#issuecomment-253723383 and thought it should be reopened for landing http://gaearon.github.io/react-hot-loader/

**Comment by bsclifton** [comment]
@luixxiul ah ok- let me update the title a bit here
