### ISSUE TITLE
WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11721]
### Description
http://slither.io

### Steps to Reproduce
1. Navigate to http://slither.io
2. Attempt to join/play game

**Actual result:**
Game does not play. Console states 

> WebSocket connection to 'ws://206.221.181.242:444/slither' failed: WebSocket is closed before the connection is established.

**Expected result:**
Game plays.

**Reproduces how often:**
100%

### Brave Version
0.19.70

**about:brave info:**
```
Brave: 0.19.70 
rev: d4b94c6215bb130250fe5245787a5884dc9b51fe 
Muon: 4.5.9 
libchromiumcontent: 62.0.3202.62 
V8: 6.2.414.32 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64
```

**Reproducible on current live release:**
Yes

### Additional Information
Reproduces even when Site Shields are disabled.

**Comment by eljuno** [comment]
+1 from me when switching between multiple Slack teams. :)

Brave 0.19.70 on Win 8.1 x64

**Comment by rvagg** [comment]
I had to switch to the Slack app on macOS with the 0.19.70 release due to websockets problems preventing it from fully loading, although it seems to be working now so I can't explain that, cache maybe?

I also get an error on IRCCloud although they seem to have a fallback at least so it's mostly working (I've been made offline a couple of times and had to reload the tab):

![Uploading Screen Shot 2017-10-31 at 11.08.52 am.png…]()

**Comment by eljuno** [comment]
Related #11716?

**Comment by luixxiul** [comment]
I'd agree. Closing as dupe.
