### ISSUE TITLE
Mouse cursor not rendered on some UI elements during HTML5 video playback

### ISSUE THREAD

**Issue by fuchst** [brave/browser-laptop#11742]
### Description
Mouse cursor not rendered over certain UI elements when watching HTML5 video (e.g. Netflix, Plex) after the web players overlay fades out. Clicking on Elements still works fine.
**Important:** Hovering over the URL bar stops the bug.

### Steps to Reproduce

  1. Start video playback (e.g. Netflix)
  2. Move mouse outside of frame
  3. Wait for video player overlay to disappear
  4. Hover mouse over elements (e.g. Brave Shield Panel Icon, Tabs)

**Actual result:**

Mouse cursor not rendered above certain elements

**Expected result:**

Mouse cursor should be rendered

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

 
Brave: 0.19.71 
rev: 3b03f08434111cf5cdcdabeed00a0996de4658ad 
Muon: 4.5.12 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Reproducible on current live release:**

Yes

**Comment by Goodelle** [comment]
Sorry to bother you guys, this topioc seems to be related to video playbakc issues? I have a question. Recently I got an video file titiled with .RM and I couldn't play it in Windows Media Player. So, after I searched on the internet, I read this article about "convert rm to mp4" ([](http://www.videoconverterfactory.com/tips/convert-rm-to-mp4.html)). As you can see, it asks me to convert RM file to some more common and compatible formats like MP4 and AVI. But I don't have idea why after the conversion process is finished, the video quality gets badly down, I changed the bit rate and resolution but nothing different. Is that because the mp4 is a compression format?
--

**Comment by srirambv** [comment]
When you say mouse cursor not rendered do you mean to say it should change from pointer to cursor? Could you record a gif image of what you see? You can use LiceCap(free tool) to record gif

**Comment by fuchst** [comment]
![mouse](https://user-images.githubusercontent.com/5565175/32379628-5207f896-c0ae-11e7-91e8-130ce8404015.gif)
![mouse2](https://user-images.githubusercontent.com/5565175/32380070-72a837e0-c0af-11e7-8727-26bac3432049.gif)


Here are two gifs of the issue. Thank you for the great tip regarding LiceCap.
It should be visible that the cursor is not visible in any form on some elements and the tab bar.
The second one better shows the connection with the player UI.

**Comment by forgetso** [comment]
Hi, I have the same issue in Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit) running Ubuntu 18.04.1 LTS. The issue was resolved using https://askubuntu.com/questions/1062967/ubuntu-18-04-not-working-with-intel-integrated-graphics

**Comment by bsclifton** [comment]
Thanks for posting a work-around, @forgetso 😄 Sounds like this may still be an issue in the new version of the Brave browser (this repo is for the old one). If this happens to other folks (and the work-around above doesn't work), let's open an issue in the new repo:
https://github.com/brave/brave-browser
