### ISSUE TITLE
Tor support for Private Browsing

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1185]
It would be great to have Private Browsing mode provide similar security guarantees to Tor Browser. mikeperry has a doc (possibly out of date) re: changes that would have been needed in Chrome to make this possible:  https://trac.torproject.org/projects/tor/wiki/doc/ImportantGoogleChromeBugs. We should look into which of those apply to Brave.

Depends on #1111 #770 #242 #694 #474

**Comment by eljefedelrodeodeljefe** [comment]
So key would be to have a reliable SOCKS5 connection I guess, right? I was hoping that the Tor lib has something in the repo, but I couldn't find anything. Excuse me, since I am new to Tor, but building clients doesn't seem to be that easy or really encouraged (by documentation) unfortunately. My guess though is that `node` itself has capabilities to run a decent connection, since there are nice samples in `libuv` (see [here](https://github.com/libuv/libuv/blob/764877fd9e4ea67c0cbe27bf81b2b294ed33b0f5/samples/socks5-proxy/client.c ))

I'll research a little bit.

**Comment by eljefedelrodeodeljefe** [comment]
Just to be clear: the above would suggest, to run it through a node connection somehow skipping the chrome specific parts. This will probably in any case be quite the task.

**Comment by SJ-Diamond** [comment]
That idea is a good one, i would love to see something like that for sure.

**Comment by Arandhras** [comment]
I am absolutely supporting this. It would be something more that makes Brave unique with respect to all the other browsers out there.

**Comment by eljefedelrodeodeljefe** [comment]
@diracdeltas if you have a strong case for seeing this in node-core here would be the place https://github.com/nodejs/node/issues/1490 . I think i would rather settle on implementing this with [tools like this and friends](https://github.com/TooTallNate/node-proxy-agent) but both seems possible. There already is a electron plugin available, just wrapp tootallnate's tool. So implementation would be fairly easy, i guess.

**Comment by dominhhai** [comment]
How did it go?

**Comment by diracdeltas** [comment]
Update: we are investigating the idea of running Tor on a per-tab basis, described here: https://github.com/brave/browser-laptop/wiki/Brave-Tor-Support#running-tor-in-tabs. One major challenge is overcoming https://bugs.chromium.org/p/chromium/issues/detail?id=80722 on MacOS and Windows. Without it, Tor is still useful for censorship resistance and hiding IP from websites, but not fully useful for anonymity from a network attacker.

@eljefedelrodeodeljefe We are actually moving away from depending on Node in Brave and are fully using the Chromium networking stack at this point.

**Comment by balupton** [comment]
As an alternative to this. What about a standard VPN feature that Opera has: http://www.opera.com/blogs/desktop/2016/04/free-vpn-integrated-opera-for-windows-mac/

**Comment by Raindeer44** [comment]
@balupton I like that idea a lot, especially because of the easy added security for less technical people. However, I'd prefer it as well as Tor rather than as an alternative.

**Comment by NumDeP** [comment]
@balupton @Raindeer44 @blacktop there's a better discussion here and more related to your topic - https://community.brave.com/t/2-of-3-several-necessary-extensions-addons-vpn-proxy/1753/46

I was curious and it's probably silly but firstly would Brave's blocking engine still remain active in a Tor tab because I'm surprised in the proper Tor they just haven't integrated a fork of uBlockOrigin excluding the track of course to make it as lite and efficient as possible?

How will some secure email exchanges such as Protonmail and Tutanota as well as other security orientated services work in a TPB if 'Javascript is disabled' seeing as they require for initial log-in?

In the future when you've implemented the task bar icons 'New window - New Private window - New TPB', preferentially if TPB was continuously used, would an update still push if that was the only tab being opened every time?

**Comment by Raindeer44** [comment]
@NumDeP The Tor Browser Bundle does have a uBlock Origin fork in it, but the Tor protocol itself doesn't have any inherent blocking (at least as far as I'm aware). Similarly for Javascript, in that the TBB has it disabled by default but the protocol doesn't care, So if Brave just implements the protocol, it doesn't necessarily need to include the other security features TBB has, though it may end up being less secure. However, if your aim is for great security, a good VPN plus the TBB should be your choice anyway.

In the very specific case of Protonmail they actually run their own .onion site, but that's definitely the exception rather than the rule.

**Comment by NumDeP** [comment]
@Raindeer44 it's funny you bring up the suggestion of a 'good VPN plus TBB should be your choice' because' it's been highly recommended and up-voted - https://community.brave.com/t/2-of-3-several-necessary-extensions-addons-vpn-proxy/1753 

It would be interesting to see how they manage to make it work not just singularly but together even.

I'm also curious as to whether it's a great concern regarding the browser revealing its dimensions. Currently in TBB it notifies users that 'Maximizing Tor Browser can allow websites to determine your monitor size, which can be used to track you.'

I can sort of understand why it wasn't included as a blocking feature as it may act like 'Block Script' more often than none but would the size of the screen be a great cause for concern?

**Comment by flamsmark** [comment]
Brave should use Tor by default for private tabs. When a user opens a private tab, they should see an informative note about protecting their browsing with Tor, along with a toggle switch where they can turn it off.

**Comment by so-lost** [comment]
hey is possible to add built in language translation?

**Comment by NumDeP** [comment]
I can remember the advertisements for @flamsmark for incognito/private and indicated that those that wanted to purchase something discreetly for a spouse quite quickly without anybody finding out should use that feature. I mention this because I'm certain it was strictly recommended that users never should use the Tor network to input banking information, making private/amnesiac tabs default to Tor would sort of corrupt it, would it not?

In relation to new documentation about Private/Incognito/Off the Record tabs, your suggestion of Amnesiac seems better to be honest and makes for a fitting anagram.

- New Window
- New Amnesiac Window
- (TAB) Tor Amnesiac Browsing

**Comment by NumDeP** [comment]
This isn't regarding the above question but I think it's sort of relative in that one other important note to highlight without coming across as vulgar is the excessive usage of the Tor functionality - meaning wouldn't it greatly slow down the network given that many may become accustomed to Tor in Brave and will continuously use it as a requisite, so how is Brave going to manage to counteract this in case Brave gets negative report from other kind of users?

**Comment by Raindeer44** [comment]
Using Tor is inherently slower than using the Internet without it, simply due to the server hopping it necessarily performs. @NumDeP are you asking what Brave should do to address this slowdown, especially if it's used often?

**Comment by NumDeP** [comment]
Hi @Raindeer44 yes sort of, though not exactly, I did invite a similar issue curtailing that #12989 

It was related to the stress on the Tor network (so yes 'if it's used often') and was more so a concern because of the teams' brilliant implementation of the Tor feature and baking it into private/amnesiac tabs will significantly increase the load on the Tor network. Would it not? Especially considering those that keep their 'History' in settings to an absolute minimum practically use Private/Incognito-in-RAM mode will ever more technically without a thought from the user be connecting to the Tor network  which will greatly increase its usage.

I know I'm making sound like it's a bad thing when I actually think the opposite, especially considering most people that use those particular tabs expect it to be more secure/private (actually private in this sense not just locally) So my point was/is, what is Brave going to to alleviate the stress?

Cons:

- Constant restriction on 'sites that force you to select multiple similar images correctly before allowing access to the site which takes the pi** (sorry I forget what that page is called)

- Blocked by Google because of the network the user is on (technically a con though they should be using a more private service though perhaps they're wanting to search for images)

**Comment by diracdeltas** [comment]
@kjozwiak i thought we were waiting until #14143 was merged to close this but if not, it can be closed

**Comment by kjozwiak** [comment]
@diracdeltas fair enough! We'll wait till #14143 is merged 👍

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14143

**Comment by user18x** [comment]
Can i disable tor???

**Comment by thornjad** [comment]
You can still open a private tab without tor, if that's what you mean.

**Comment by NumDeP** [comment]
@user18x I think you'd be able to in the next release which comes with ['Feature request: expose the options to disable/enable Tor'.](https://github.com/brave/browser-laptop/issues/14603)
