### ISSUE TITLE
Transition is still occurring after update to 0.19.88 for some users

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11936]
### Description
Some users are still reporting seeing the transition after updating to 0.19.88
https://twitter.com/stshank/status/929846370835378183

### Steps to Reproduce
TBD - further information needed.

**Actual result:**
Transition is still occuring

**Expected result:**
When not needed, transition should not occur.

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**
0.19.88

**Reproducible on current live release:**
Yes

### Additional Information
cc @kjozwiak

**Comment by BrendanEich** [comment]
We need a timeout to stop the endless spinner in a way that the user can grok, and take better action in response to.

**Comment by bsclifton** [comment]
OK- after some investigation, I've found at least one fatal issue which we need to handle

A different user shared logs and ran into this scenario:
- they were a long time user (not a new user)
- they upgraded to this new release, which has the transition to BAT
- in the code, they qualified to transition (and call was made)
  - transition was not done because ledger client marked itself as busy
  - ledger client does not retry

The ledger client was stuck in a busy situation for this user because their workplace blocked the "privateinternetaccess.com" used for reconciling. We contact this service to get timestamps for when reconciliation needs to happen, so it's not specific to the transition

There are two actions I'm going to try and take to resolve this issue:
1. Update the transition code to retry after a delay (15 mins, for example)
2. Update the Payments screen to show fatal errors which are preventing the ledger from working (corrupt file, can't reach server, etc)
