### ISSUE TITLE
new tab background image jumps when closing tabs

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12128]
### Description
When closing tabs, the background image 'jumps' a bit.

### Steps to Reproduce

  1. Open about 2 pages worth of tabs, making sure you let the image load for each one when you open it
  2. Once you have 2 pages worth of tabs, go back to the first tab page and select a new tab near the beginning of the tab bar.
  3. Start closing the tabs one by one using the "x"

**Actual result:**
Tab background image jumps: https://youtu.be/LjkKEstwtjQ

**Expected result:**
Background image should not move

**Reproduces how often:**
Easily on MacOS/Linux, not as easily on Win

### Brave Version
Brave | 0.19.98
rev | 1909179
Muon | 4.5.16

**Reproducible on current live release:**
Yes, repro's on 0.19.95

### Additional Information
Originally found by @kjozwiak - able to repro on MacOS/Linux/Win
I was able to repro with these steps instead of the ones above:
* open about 2 pages worth of tabs but make sure you let the image load for each one when you're opening them
* once you 2 pages worth of tabs, go back to the first page and select about:welcome
* start closing tabs one by one via the "x"

**Comment by bsclifton** [comment]
cc: @petemill

**Comment by petemill** [comment]
Doesn't look like a regression as the current release has similar behavior. My guess is that this is caused because the page frame changes size depending on whether or not you have multiple pages or not, due to the page indicators. This may also happen if you simply turned the bookmarks toolbar on and off. If that's the case, this wouldn't be restricted to the new tab page, but also any website. Will investigate further...
