### ISSUE TITLE
Long lags and general slowness when interacting with tabs on MacOS

### ISSUE THREAD

**Issue by paddor** [brave/browser-laptop#12132]
### Description
It can take a solid 2 seconds until I see a new tab after pressing Cmd-T, and takes almost as long to close a tab. Even switching tabs is this slow. It's become really inconvenient to use this Browser, especially after upgrading to High Sierra. When I look at Activity Monitor during those actions, there's always some Brave Helper process at the top using 150%+ CPU for those 2 seconds.

### Steps to Reproduce
1. Hit Cmd-T to open a new tab, or click on another tab to switch to it, or press its X-button to close it

**Actual result:**
A lag of 2+ seconds until the action completes.

**Expected result:**
Quasi instant result, or use a spinner or something, as per [Response Times: The 3 Important Limits](https://www.nngroup.com/articles/response-times-3-important-limits/).

**Reproduces how often:**
Every time.

### Brave Version
```
Name | Version
-- | --
Brave | 0.19.95
rev | cc0ebad
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.2.0
OS Architecture | x64
```

**Reproducible on current live release:**
Yes, it's the same on:
```
Name | Version
-- | --
Brave | 0.19.99
rev | 43f7a01
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.2.0
OS Architecture | x64
```

### Additional Information
I have all unnecessary address bar completion and crap like that deactivated, no extensions enabled other than PDF Viewer, and also _Dashboard->Show images_ disabled. Still unbearably slow.

**Comment by Liunkae** [comment]
What does Activity Monitor show for Brave (CPU, memory, etc.)? How does the speed of Brave compare to other browsers?

**Comment by luixxiul** [comment]
The slowness should be better on 0.20.x.

**Comment by jgcoding** [comment]
I hope I am adding to the appropriate issue. If not please forgive and instruct. 
1) very fond of this browser
2) Use MacBook Pro, OS recently updated to High Sierra (maybe a factor?)
3) always load several tabs on startup as resources for web development
4) excellent experience and performance until High Sierra update
5) after several minutes, the browser under-performs markedly
6) eventually, my entire system becomes unstable then becomes unusable, requiring reboot. This has never happened before under any circumstances since I have used this MacBook
7) reduced tab count down to a single, known benign site, then others with no relief
8) Sadly, the only solution was to avoid using the Brave browser, my system performance has been restored and maintained since.

I would really love to resume using Brave as soon as possible. Anything I can do to assist.

List of sites I have used with no issues until the above referenced Mac OS update:

http://www.di.fm/
https://lodash.com/docs/4.17.4
https://shancarter.github.io/mr-data-converter/
http://www.cleancss.com/json-minify/
http://www.bodurov.com/JsonFormatter/
https://www.freeformatter.com/json-formatter.html
http://bluebirdjs.com/docs/api-reference.html
https://expressjs.com/en/4x/api.html
https://nodejs.org/dist/latest-v6.x/docs/api/
https://www.w3schools.com/w3css/default.asp
https://repl.it

**Comment by rothos** [comment]
Same issue here. The lag when adding tabs has caused me to start using Chrome for many tasks, which makes me sad. It even takes >1s to open a tab for Brave preferences/downloads/history. This needs to get fixed.

 
Brave: 0.19.105 
rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 15.5.0 
OS Architecture: x64

**Comment by modusops** [comment]
+1 to this request, I often type the new page destination before the tab has completed loading. By the time the new tab loads, only a fraction of the new URL is captured in the input field. If that could be fixed, I'd be ok with a small delay. 

 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Comment by bsclifton** [comment]
@petemill would you feel comfortable saying this is fixed with the single webview release?

**Comment by bsclifton** [comment]
I'm going to close this issue as we've released some significant performance increases with recent versions of Brave. If you're still experiencing this, please reopen the issue and we'll check it out 😄
