### ISSUE TITLE
PW Manager: multiple entries for same domain, login, password

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#1217]
After logging in to facebook manually a 2nd time, the prompt showed up  to ask to save the PW, I agreed and ended up with 2 entries:
<img width="220" alt="screenshot 2016-04-01 09 45 16" src="https://cloud.githubusercontent.com/assets/5495083/14208659/772600e4-f7ee-11e5-80bb-ec761aa79151.png">

Expected result:
- check if PW is the same, and if so, don't prompt to save a 2nd time
- if PW not the same, ask to update the password for this domain+login

**Comment by diracdeltas** [comment]
Do the two entries have different usernames?

If the PW is not the same but the username is, it should be updating the password (but the dialog says "save" instead of "update" which may be confusing).

This is all assuming the form actions and origins are the same. If not, the password manager can't tell whether the two login forms are different.

**Comment by diracdeltas** [comment]
I think I managed to repro this; what's happening is that Facebook's login form action is different on each attempt. Ex: https://www.facebook.com/login.php?login_attempt=1&lwv=110 and https://www.facebook.com/login.php?login_attempt=1&lwv=111. i guess we can ignore the URL query params.

**Comment by garvankeeley** [comment]
confirmed fixed
