### ISSUE TITLE
New blank tab is dark

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12194]
### Description

The new blank tab is dark, which has been white.

### Steps to Reproduce

  1. Open about:preferences
  2. Change the new tab setting to ~`blank tab`~ `Blank page`
  3. Open a new tab

**Actual result:**

The dark tab is opened.

**Expected result:**

I ~~don't think~~ wasn't sure this change is intentional. Should it be reverted to white? If it shouldn't, let's close the issue and add the wontfix label.

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

 
Brave: 0.19.105 
rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Reproducible on current live release:**

Yes.

**Comment by NejcZdovc** [comment]
I also think that tab should be white and only content of the new tab should be black

cc @petemill

**Comment by petemill** [comment]
This is intentional. Dark was chosen since the text on the ‘new tab page’ is light color and set on a dark gradient background until the image loads. With the dark background, that dark gradient does not stand out and the image appearing is smooth rather than jarring. Plus this avoids white flashes between tab opens. This iteration was chosen by the design team with a view to see how it is received (especially the tab also being dark due to the theme color), so the feedback I’m sure is appreciated.

**Comment by NejcZdovc** [comment]
@petemill not sure if @luixxiul is also talking about the same think as I am, but I was referring to new tab tab. New tab page is great with this new black

![image](https://user-images.githubusercontent.com/9574457/33651772-4b8d3594-da67-11e7-8f77-1d8ea434eae5.png)

**Comment by NejcZdovc** [comment]
Now that I am reading it again I think that you also answered tab tab color :smiley:

**Comment by NejcZdovc** [comment]
@luixxiul sorry :smiley:

**Comment by luixxiul** [comment]
Still https://github.com/brave/browser-laptop/issues/12194#issuecomment-349568553 was included as well 😄

**Comment by srirambv** [comment]
I don't see the black tab however if the image is not yet loaded hovering over the new tab does show the dark overview similar to https://github.com/brave/browser-laptop/issues/12194#issuecomment-349597330

**Comment by petemill** [comment]
About:blank being dark is a side effect of sharing the same underlying url as about:new. I.t is possible they can be separated but for now the design team approved it being dark and wants to see user feedback, which this is definitely part of.

**Comment by davidtemkin** [comment]
Really? Doesn't make visual sense given overall browser appearance (i.e., no "dark theme"). @bradleyrichter @bsclifton

**Comment by petemill** [comment]
@davidtemkin Are we talking about an issue with the tabs being dark when active, which is if you have the themed-tabs-when-active setting on (which it is by default) - the newtab page is a dark page, so it takes that color;
Or are we talking about an issue the homepage being dark when you have the setting 'A new tab shows Blank Page' (which is not by default and may not be hugely used)? The reason for that occuring is because a previous architectural decision was to combine those pages and just hide the content, so now that we have removed the white flash and kept it dark all the time, it stays dark.

If the former, we can override the tab color for active new tabs. Personally, I think the newtab page is dark, so it should respect the setting and blend like all the other tabs do when active.

If the latter, then we could put some work in to separating the blank page from the dashboard page, and make the blank page always white. The overall goal behind the project, and I think a desired priority, was to avoid a white when opening new tabs, which was occurring because the default frame background was always white, yet the new tab loaded in with a dark background, before fading in the image, which has a dark overlay and white text over the top. Also, I'm not sure the user impact since the option to choose a blank tab has to be specifically chosen in preferences.

**Comment by davidtemkin** [comment]
@petemill I was referring to the the case in which the user sets "A new tab shows..." to "blank page". Dark background makes perfect sense for the dashboard (default) case. And you are quite possibly right that it's rarely used; given current usage data collection, we have no way of knowing.

**Comment by petemill** [comment]
@davidtemkin yeah I bought up the issue with @bradleyrichter at the time and asked if it was worth the delay / effort in changing the architecture to achieve a white 'blank page'. His opinion was try this first. If this is the ensuing user-backlash then let's schedule it :-)

**Comment by bsclifton** [comment]
Re-closing as `wontfix`; we can address with brave-core
