### ISSUE TITLE
Fullscreen mode not reliably filling full screen (kickstarter.com)

### ISSUE THREAD

**Issue by midi** [brave/browser-laptop#1232]
Fullscreen mode here: https://www.kickstarter.com/projects/hexlox/hexlox-anti-theft-for-saddles-wheels-and-more-made does not reliably fill the whole screen.

Pressing fullscreen mode and accepting the two pop ups with yes/allow, sometimes only fills the center of the screen.

Youtube works fine now after the latest fixed and always fills the screen.

Using latest 0.8.3. on OSX 10.11.4.

<img width="1280" alt="screen shot 2016-04-02 at 19 36 34" src="https://cloud.githubusercontent.com/assets/1421440/14228074/892996a2-f90b-11e5-9da3-e49eba2ed5bf.png">
<img width="1280" alt="screen shot 2016-04-02 at 19 36 46" src="https://cloud.githubusercontent.com/assets/1421440/14228075/8977af90-f90b-11e5-9b9f-8ede64cc5d1d.png">

**Comment by bbondy** [comment]
I guess we are always making the whoel webview full screen and need to do the element instead.

**Comment by luixxiul** [comment]
Was this fixed?

**Comment by stmr** [comment]
Well.. rev	fba98fc
![bug](https://user-images.githubusercontent.com/1045974/27012641-e41bfa5e-4ed3-11e7-918b-1893b9766de4.png)

**Comment by NumDeP** [comment]
Rather than creating another issue as well can I also add to this @luixxiul that full screen button is allowed on some webpages which allow video content to be shown from vimeo or youtube like on crowdfunding platforms even though it has the full screen icon available.

One other thing I'd like to make mention of is that it is excruciatingly slow to enter and exit full screen mode anywhere. 
The individual that worked on the improvement of torn tabs and the re-attachment of torn tabs did a fantastic job, more quickly than usual as well I might add, could they perhaps be assigned to fixing this as well. 
Furthermore, it would be brilliant if you could sort of combine these issues and release the fixes together are they interconnected #9044 #4384 #7428 and would be great to test out whether it still poses an error. Thanks.
