### ISSUE TITLE
saved site permissions are revealing your browsing history from private mode

### ISSUE THREAD

**Issue by Alino** [brave/browser-laptop#12428]
- Show notifications
- Open external applications
- Autoplay Media

these kinds of saved permissions, are revealing information that you did visit a specific website even in private mode.
If you go to Preferences/Security and scroll down, you can see the list of saved site permissions.

Expectation: private mode should not be able to save site permissions, nor there should be prompts to do so.

**Comment by srirambv** [comment]
The site settings will be removed when you close the private tabs. 

cc: @diracdeltas @bridiver

**Comment by Alino** [comment]
Not true, I have 0 private tabs opened, and they websites that I visited only in private tabs are still in the list of saved site permissions.

Also one more thing,
I have set Autoplay Media to "Always allow"
and when I am browsing the web, websites are automatically being added to the saved site permissions list. Which makes no sense for me to be constantly adding domains to this list if the settings is set to "Always allow" it should just simply always allow, without maintaining a never-ending list of websites that I have visited. This is browsing history leak.

**Comment by Alino** [comment]
You should get inspired from chromium regarding private/incognito mode.
**Never store any browsing data on disk.** As far as I know, the whole incognito mode saves the downloaded resourced during your browsing session to RAM.

![image](https://user-images.githubusercontent.com/763194/34411327-4ba3b640-ebd6-11e7-91ba-c7499f66bc1c.png)

**Comment by srirambv** [comment]
>Not true, I have 0 private tabs opened, and the websites that I visited only in private tabs are still in the list of saved site permissions 

If you have visited the site in a normal tab before and changed settings that gets saved. Try visiting a site in private tab for the first time and change shields settings and close it and see if you are still able to see the saved site settings. Next visit the same site in normal tab and change the shields settings **only then** it gets saved. Here's how it works.
![12428](https://user-images.githubusercontent.com/17010094/34411553-343bc2f6-ebcf-11e7-9385-61755cf5d95f.gif)

What ever site settings you make in normal tab those settings are valid for the same site visited in private tabs. Not the other way around. Hope the above screencap resolves the confusion.

>I have set Autoplay Media to "Always allow" and when I am browsing the web, websites are automatically being added to the saved site permissions list.

This will be fixed in 0.20.x Reference issue: https://github.com/brave/browser-laptop/issues/9008

**Comment by Alino** [comment]
Thank you for your explanation.
It doesn't work when you have settings on autoplay media to "always allow"
in that case if you open a website for the first time in private mode, and close it, it will stay in the list.
But it logically should be also fixed by the fix in 0.20.x as you mentioned.

So one more question, are the saved permissions saved to the disk or RAM while in private mode?

**Comment by diracdeltas** [comment]
saved permissions are never written to disk unless you pick an 'always allow/deny' option
