### ISSUE TITLE
PDF not loaded when browser is relaunched

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12483]
### Description
PDF not loaded when browser is relaunched

### Steps to Reproduce

  1. Open a PDF file in a new tab
  2. Close the browser and reopen it, pdf shows as file not found
  3. Reload the tab, PDF loads again

**Actual result:**
PDF not loaded when browser is relaunched

**Expected result:**
Should load the PDF when browser restarts

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.14
-- | --
V8 | 6.3.292.48
rev | 5d75826
Muon | 4.5.33
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108

**Reproducible on current live release:**
No

### Additional Information
Reproduces on all platfrom 
#12408

**Comment by bsclifton** [comment]
@diracdeltas have you gotten a chance to check this one out? I'm wondering if we should move it to 0.21.x

**Comment by diracdeltas** [comment]
@bsclifton i think it can be moved, though i'll try to get to it after doing security issues

**Comment by petemill** [comment]
This also happens when you navigate back from a PDF and then forward again, or when a tab is discarded (to release memory) and then loaded again.

More detail on what's causing this:
For some reason, after the page is rendered, muon is changing its stored url from:
`chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/web/viewer.html?file=http%3A%2F%2Fwww.pdf995.com%2Fsamples%2Fpdf.pdf`
to:
`chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/http://www.pdf995.com/samples/pdf.pdf`, hence 404

@bridiver mentions that there is now `setURLHandler` and `setReverseURLHandler` in the browser-side extension api to replace all the url handlers we have in browser-laptop, but that this should be able to be fixed in browser-laptop.
