### ISSUE TITLE
Trezor passphrase being saved to password list and offered by auto fill without permission.

### ISSUE THREAD

**Issue by higzac** [brave/browser-laptop#12563]
### Description
Just upgraded to the new version. Turned on strict site isolation. Plug Trezor in and now my passphrase is available via autofill. The Trezor had been added to the saved passwords list. I didn't ok that. I deleted the pass phrase and the Trezor from the saved password list, entered it again into the Trezor and brave saved the passphrase again without asking. I've since shutdown auto fill and password management via brave. 
This behavior started after the update. i'd used the Trezor multiple times today without this issue until the update was made.

### Steps to Reproduce
  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

Brave | 0.19.131
-- | --
rev | da2f347
Muon | 4.5.36
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**

**Comment by srirambv** [comment]
cc: @darkdh @diracdeltas

**Comment by higzac** [comment]
I'm referring to the passphrase for a particular wallet account not the mnemonic.
If you enable passphrase protection on the trezor you can create separate accounts that are accessed by the specific passphrase.

**Comment by diracdeltas** [comment]
probably related to the other password autofill changes that were in the last release, not strict site isolation.

**Comment by darkdh** [comment]
@higzac would you mind turning off strict site isolation and try again? It helps us narrow down that it is another password manager changes in the same release.

**Comment by darkdh** [comment]
There are 2 issues:
1. Built-in password manager couldn't actually be turned off (https://github.com/brave/browser-laptop/issues/10566)
2. chromium password manager will save the following form as bravetest/bravetest
![screen shot 2018-01-09 at 11 12 53 am](https://user-images.githubusercontent.com/11330831/34739436-22e53de6-f531-11e7-8711-7f994b78d324.png)

These two issues have already been there since we migrate to chromium password manager and https://github.com/brave/browser-laptop/issues/12489#issuecomment-355350464 exaggerates it upon page load because we will popup the USERNAME which about to fill to users
![screen shot 2018-01-09 at 11 40 37 am](https://user-images.githubusercontent.com/11330831/34739699-f2cea466-f531-11e7-9714-faacb5f7a52c.png)


However, I couldn't reproduce the automatically save because it will ask every time
![screen shot 2018-01-09 at 11 36 40 am](https://user-images.githubusercontent.com/11330831/34739519-6985bc6c-f531-11e7-8131-0eda68be76b4.png)

@bsclifton we might need https://github.com/brave/browser-laptop/issues/10566 in this milestone

**Comment by higzac** [comment]
Sorry for the delay in getting back to you. 
Had a chance to play around to get a better idea of what happened.
I can repeat the problem with (strict site isolation) Enabled or disabeld

Looking at what I can repeat this is what is happening

Connect trezor and log into account.
Option to save password presents itself.
I must have clicked ok to this accidentally 
Log out of trezor. Then log back in.
I'm now offered the (use password for option) where the user is my password.
Log out of the trezor
Open preferences in brave and go to password settings.
Delete the entry for the trezor.
Connect trezor.
I'm offered the user name password option again where the user name is the password even though I just deleted it from password settings in brave..
Enter my password again log in.
New entry with my username password added back to password settings in brave.
The is no dialogue to ok adding it, its just added back.
This happens if you don't close brave down after deleting the user name password.
If you stay in the same session you don't get a promt from brave when it adds the password back to its list.
If i close brave after deleting the password then restart all the correct prompts happen to warn me brave is saving the password

**Comment by darkdh** [comment]
Test plan:
a.

Make sure built-in password manager is enabled
Male sure passphrase is set on trezor wallet
Plugin trezor and open wallet
Type passphrase and submit
Brave shouldn't prompt any messages to save password
b.

Make sure built-in password manager is enabled
Sign up account for https://trac.torproject.org
Brave should ask users to save password, click deny
Logout and Login
Brave should ask users to save password, click allow
Change password
Brave should ask users to update password, click allow
Logout and use the save credentials to login
It should be able to login sucessfully

**Comment by srirambv** [comment]
Test plan B works on Windows.

**Comment by LaurenWags** [comment]
Test Plan B works on MacOS as well.

**Comment by jumde** [comment]
Test Plan A works on MacOS and Windows with 0.19.132

**Comment by kjozwiak** [comment]
Test Plan B works under Ubuntu 17.10 x64.

**Comment by diracdeltas** [comment]
checked on debian 8 and el capitan
