### ISSUE TITLE
Username for password saving can be saved as blank, should that be allowed?

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1271]
I have an entry in password manager like this:
site: http://twitter.com 
username:
password: ****

I'm not sure how I got in that state but should we allow blank usernames?

**Comment by bbondy** [comment]
CC @diracdeltas

**Comment by weems** [comment]
Interesting I see this also on my end in 0.8.3 on Win7 @bbondy

**Comment by diracdeltas** [comment]
That's intentional right now. The only requirement that *something* be saved is that there is a password field on the page. There is a best-effort heuristic to find the username associated with the password element, but it sometimes fails. Actually I just noticed it fails on https://twitter.com/login/error?username_or_email=test&redirect_after_login=%2F, which is probably how you got the blank twitter username.

**Comment by diracdeltas** [comment]
Twitter issue might be fixed by https://github.com/brave/browser-laptop/commit/d687a0ebf265d6da3b115fd3b976aab8f98114e3. Let me know if you see blank usernames on any other sites.

**Comment by bbondy** [comment]
Will do closing this.
