### ISSUE TITLE
Read installer executable name (EXE) and output to profile directory

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12787]
During the EXE file install for a Release channel build (not BETA/DEVELOPER/NIGHTLY), a custom script should run. This script needs to do the following:
- Read executable name (ex: `Setup-Brave-x64-ABC999.exe`)
- Look for / parse out a promotion code (ex: `ABC`)
- Put this promotional code into a file `promoCode` in the profile directory (ex: `%APPDATA/brave`)

**Comment by petemill** [comment]
Hitting a bit of a wall with this in terms of injecting a 'script' in to the install process. See below for options.

As far as I understand it, here's the details of Brave's Windows installer:

### How does the Brave Windows installer work?
- Run Setup-Brave-xxx.exe
   - Ensures .net 4.5 is installed, downloads and installs it if not
   - Creates `%LocalAppData%\Brave` directory
   - Extracts `Update.exe` to `%LocalAppData%\Brave` <-- Squirrel's exe to perform updates, etc after install
   - Extracts Brave.xxx.nupkg to `%LocalAppData%\Brave\packages\temp` <-- our app
   - Runs `Update.exe /install` (from its new destination) which then:
      - Copies the app from the temp directory to a versioned subdirectory e.g. `Brave\app-22.0.0`
      - Runs `Brave.exe --squirrel-install 0.22`
      - Runs `Brave.exe --squirrel-firstrun`

### How do we create the Setup-xxx.exe installer?
 - Assemble our Brave.exe and related resource files
 - Provide a .nuget file which packages all the executable files in to a single .nupkg file
 - Ask Squirrel to create a Setup-Brave.exe via `Squirrel --releasify` (Squirrel exe is bundled in /vendor/)
   - Bundles our Brave.nupkg app package
   - Bundles `Update.exe` for Squirrel to perform actions after install

### Where can we hook in?
[Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) provides no hooks in the setup process, apart from running the Brave app at the end of the install with the flag `--squirrel-install`. Seems ideal that we also pass in the name of the setup executable file name here. That would need to be retrieved via the setup executable itself `Setup-xxx.exe`, then passed through to Squirrel's `Update.exe` and then finally passed through to `Brave.exe`  In order to do this we would need to patch both Squirrel's Setup.exe (a C++ bootstrap application) and Update.exe (a .net c# application), and replace the dependencies in [`muon-winstaller`](https://github.com/brave/muon-winstaller/tree/master/vendor). From rough research it seems a c++ app can get its executable filename via [`GetModuleFileName(NULL)`](https://social.msdn.microsoft.com/Forums/en-US/21d69a2c-c3eb-4ae6-b94a-f90b726d0c28/how-to-get-the-path-and-filename-of-the-currently-executing-program-in-visual-c?forum=vcmfcatl)

### Other options?
- Use a different installer system (msi, nsi, ...)
   - Large change
- Create our own Setup.exe app that self-packages (again) the existing Squirrel setup.exe. This app would extract and run the Squirrel setup.exe as above, but first would read it's exe name and copy that to the expected location. This app would likely need to be written in c++ and be signed when built. We wouldn't need to sign the normal Squirrel setup.exe anymore.
- Embed the promo code as a file, and insert that file in to the package dynamically
  - Promo / download server would need receive raw build assets and package separately for each promo / version combination for both 64-bit and 32-bit.

**Comment by kjozwiak** [comment]
Went through the following test cases:

* install `BraveSetup-x64-JOZ789.exe` and ensure that `promoCode` was created and includes `JOZ789`
* install `BraveSetup-x64-abc123.exe` and ensure that `promoCode` was created and includes `abc123`
* install `BraveSetup-ia32def456.exe` and ensure that `promoCode` was created and includes `def456`
* install `BraveSetup-ia32POL234.exe` and ensure that `promoCode` was created and includes `POL234`

Platforms being used:

- Win 10 x64 VM - PASSED
- Win 10 x64 Desktop 1 - PASSED
- Win 10 x64 Desktop 2 - PASSED
- Win 10 x86 VM - PASSED
- Win 8.1 x64 VM - PASSED
- Win 7 Pro x64 VM - PASSED
- Win 7 Pro x86 VM - PASSED

@srirambv seems to be working for me on all my VM's including two different Win 10 desktops. Can you give it another go and see if you're still not getting the `promoCode` file?
