### ISSUE TITLE
Update test plan for PKG format

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12802]
Update the QA steps for checking (macOS) if build is signed

**Comment by petemill** [comment]
I've observed that the pkg installer will see any existing Brave app **anywhere** on disk as an existing installation (that it assumes was moved from `/Applications`) and attempt to upgrade it, instead of installing a fresh copy to `/Applications`, even if the other Brave app is named `Brave-old-test-1.app` (or anything!). Suggest we make sure it does not overwrite any side-by-side beta, developer or nightly installed versions.

**Comment by petemill** [comment]
Here's some more info about, and how to test / mitigate pkg installers overwriting .app files (or seemingly doing nothing) https://stackoverflow.com/questions/19283889/osx-pkg-installer-sometimes-does-not-install-app-file

**Comment by kjozwiak** [comment]
Going to close this for now.. Wrote it down as a TODO... Created https://github.com/brave/qa-resources/issues/50 which is the repo for the manual runs.
