### ISSUE TITLE
UX & wording for Tor tabs on about:newtab

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#12922]
How do we communicate Tor tabs to the user? Do we separate "Tor" tabs from "Private" tabs?

Much of the user research suggests that people expect private/incognito tabs to protect against ISP-level snooping, rather than just forgetting what's stored locally. <https://spreadprivacy.com/is-private-browsing-really-private/> <https://www.elie.net/blog/privacy/understanding-how-people-use-private-browsing>.

**Comment by flamsmark** [comment]
One implementation option:
- "private" or "incognito" (or our own new label) tabs using Tor to protect against network snooping
- "off the record" or "amnesiac" tabs doing what private/incognito tabs do now: avoid making a durable record on the local machine

**Comment by riastradh-brave** [comment]
A broader UX question is how to organize these essentially independent concepts.

Users, _e.g._ doing research on controversial topics, might want to maintain ordinary browser history, site logins, _etc._, while disguising from their ISPs what they're browsing, and disguising from sites they don't log into who they are -- for all this they need Tor, but not everything else in off-the-record mode.

Other users, on, say, shared family or library computers, might just want to avoid leaving a scare for the local machine -- for this they want off-the-record mode.  Maybe this should _imply_ Tor as well -- but there's a cost to that, in performance and Cloudflare captchas

(...though if that would cause users to put pressure on Cloudflare to make their captcha work better, maybe that's a good thing...)

**Comment by NumDeP** [comment]
@flamsmark I like you amnesiac suggestion more and if you do go with amnesiac it should retain the same functionality as private/incognito essentially separate to Tor. 

I encourage this option more so because a significant number of users in community.brave.com have suggested many extension based encrypted VPNs /otherwise SPDY VPNs and it seems logical that many users would always automatically connect via the extension when starting the browser and many will also want to sometimes quickly browse something without it making a log of any kind and they wouldn't be able to do so if Amnesiac is only offered as an option with Tor and it doesn't make much sense to strain the Tor network. 

Please don't be annoyed given that I've already suggested this but it was in reference to those particular issues when I suggested that the following options should be included:

- New Window
- New Amnesiac Window (this will function like Private and Incognito in other browsers)
- (TAB) Tor Amnesiac Browsing

**Comment by diracdeltas** [comment]
assigning @bradleyrichter for the MVP task, which is deciding what the text for the Tor switch is on about:newtab. for reference this is what i wrote:

![screen shot 2018-02-26 at 10 02 01 am](https://user-images.githubusercontent.com/549654/36686708-27104426-1adc-11e8-82a7-9f6ff82afe48.png)

**Comment by bradleyrichter** [comment]
@flamsmark @diracdeltas 

new mockup with some layout changes and latest text revision from gdoc:

changes from current shipping layout:
- brave icon has been removed
- fine print moved to the bottom with more Tor detail added
- layout of titles, switch, logo, copy has been updated

![image](https://user-images.githubusercontent.com/13509546/37435219-ac32e6ac-279f-11e8-851a-d6337a60b42c.png)

**Comment by NumDeP** [comment]
I hope you don't mind me making a small criticism @bradleyrichter starting from the bottom up. 

1) After 'experience' wouldn't it be better to remove the full stop and include a 'comma so', and removing 'Browser instead', for 'feature or switch.'

2) Remove the second paragraph under 'More about private tabs' because it's almost congruent to the paragraph below 'Make private tabs much more private with Tor'. 

3) What was wrong with initial mock-up below 'This is a Private Tab'? You should retain the original mock-up with the exception of the title (not DDG but Tor)

4) Removing the bit before it, 'Tor can slow ... prove you're human,' should be the second paragraph under 'More about private tabs' after the other is removed.

5) This may be just a technicality but in regards to your first paragraph you may want to cc @flamsmark because I'm sure an aspect of Tor will be loaded in History in case a specific page is accidentally loaded via a non-anon route.

Thanks

**Comment by bradleyrichter** [comment]
@NumDeP Thanks for looking into the details and providing feedback. 

To summarize, you prefer the original layout with the Brave shades icon and intro paragraph? 

We needed to add more fine print which ended up pushing the Tor switch below the fold. This drove the layout change putting the fine print at the bottom. 

Also, the longer Tor switch label "Make private tabs much more private with Tor" (also considering translations) pushed the Tor icon to the far right and would drop to a second line if the text wraps.

Other than these 2 issues, I think the original mockup worked fine as well.


@flamsmark did the final text editing. Tom - perhaps you can review the suggestions above. TY.

**Comment by bradleyrichter** [comment]
quick mocks using a french Tor title in the original layout:


not wrapping:
![image](https://user-images.githubusercontent.com/13509546/37559095-1a4cceb6-29dd-11e8-9272-35ecd05df6ff.png)

wrapping:
![image](https://user-images.githubusercontent.com/13509546/37559105-46ec2494-29dd-11e8-96ad-6b012439090c.png)

**Comment by bradleyrichter** [comment]
I wasn't part of the original Tor switch label discussion but it certainly was shorter!

**Comment by bradleyrichter** [comment]
Here is the newly proposed layout that will work better for line breaks from translations. 

![image](https://user-images.githubusercontent.com/13509546/37570331-e940066a-2aab-11e8-820f-7bc3948bbd8e.png)

**Comment by NumDeP** [comment]
Actually @bradleyrichter forget it. I like what you did with the frame and the fact you switched the icons and switches over. That size of that duck on the right was freakish before :)

**Comment by petemill** [comment]
The switches are off by default AFAIK, so we should probably show that in any mockups intended to make us comfortable with usability / ease of scanning for the toggles.
