### ISSUE TITLE
Detect existing Tor processes

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#12931]
For the basic Tor tabs prototype, we should detect whether there's an existing Tor process running on this machine by making a request to https://check.torproject.org over socks5://127.0.0.1:9050 . If there's no existing process, the attempt should fail.

**Comment by riastradh-brave** [comment]
As a very rough prototype, perhaps we could just make the new tab page for Tor tabs _be_ https://check.torproject.org/.

(This is definitely not a long- or even medium-term approach, because the page has a warning saying that even though you're using Tor you're not using the Tor Browser -- maybe something to bring up with the Tor team to see whether we can have an https://check.torproject.org/brave endpoint or whether we should just run our own, which can't be all that difficult since there are easy ways to query the list of current exit nodes.)

**Comment by flamsmark** [comment]
I don't think we can use <check.torproject.org> because the open page for private tabs explains private tabs and the toggles for DuckDuckGo and Tor. Onion Browser (iOS) uses <onionbr5zulufnuj.onion> which has been down the last few times I've checked. I like that approach because using an onion service is a better guarantee of Tor-ness than enumerated exits. Unless we're worried about onions working while regular sites have leaks?

I like the idea of running a Brave tor-check onion endpoint because it's a useful way to run a simple large-scale onion service and avoids putting additional load on parts of Tor's infrastructure which may not scale as well as the overall network.

**Comment by diracdeltas** [comment]
We decided to remove this in the MVP prototype in favor of bundling Tor. https://github.com/brave/browser-laptop/commit/88b2075e02b97d927b42298b77248dbf7814e965
