### ISSUE TITLE
Folders under "Other Bookmarks" don't show up as dropdown options in the "Add Bookmark" or "Add Folder" dialogs

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#12962]
### Description
When adding a bookmark or folder in the Bookmark Manager, any folders listed under "Other Bookmarks" do not show up as options in the target folder dropdown. See screenshots below.

### Steps to Reproduce
  1. Open the Bookmark Manager.
  2. Add folders underneath "Other Bookmarks"
  3. Start adding a bookmark or a folder.
  4. Check the "Folder" dropdown. The folders under "Other Bookmarks" aren't there.

**Actual result:**
The folders should be available as dropdown options.

**Expected result:**
The folders are not available as drop down options.

**Reproduces how often:**
100% reproducible.

### Brave Version

**about:brave info:**
 
Brave: 0.20.29 
V8: 6.4.388.40 
rev: 4fc3c8ff3bcb6af75088b125e00d3a70382b9bec 
Muon: 4.7.9 
OS Release: 17.3.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Reproducible on current live release:**
Yes

### Additional Information

<img width="824" alt="screen shot 2018-01-31 at 1 42 10 pm" src="https://user-images.githubusercontent.com/133786/35644034-8faf7e2e-068d-11e8-8c6a-32410e13f48d.png">
<img width="839" alt="screen shot 2018-01-31 at 1 42 35 pm" src="https://user-images.githubusercontent.com/133786/35644035-8ff6bdca-068d-11e8-8545-fdc034201018.png">

**Comment by echosa** [comment]
I'll also point out that the dialog titles aren't consistent. One starts with "Create", and the other doesn't. Probably want to make them both the same, either with or without "Create".

**Comment by bsclifton** [comment]
+1 from @markoshust via https://github.com/brave/brave-browser/issues/625

**Comment by markoshust** [comment]
thanks @bsclifton.

does no one use bookmarks on brave? this is kindof a major issue for me :/

**Comment by bsclifton** [comment]
@markoshust people do- but I know personally I prefer to use the folders in the bookmarks toolbar (maybe other users feel similarly? not sure)

We are moving to a Chromium based UI (Brave Core) and I have confirmed this issue is resolved there.  Here's a screenshot from our latest version which shows the folders under `Other bookmarks` being shown prominently in the bookmark modal:
![screen shot 2018-07-22 at 12 49 41 pm](https://user-images.githubusercontent.com/4733304/43049506-dcae9d2a-8dad-11e8-88ca-869926c5e798.png)

We are still working on this (it's not officially released yet). Brave Core should make it's debut in a few months (hang in there! 😄 )
