### ISSUE TITLE
Tor toggle in shields

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#12966]
Shields should provide a toggle for Tor usage, just like scripts, fingerprinting. This is the next step after private tabs (#1185).

**Comment by NumDeP** [comment]
Do you intend to keep a separate header in about:preferences because it could arguably be better to maintain everything separately if information is kept online.

It would also be pretty unique if you could allow a setting whereby the current Brave icon can act as a discreet Tor button which turns purple or green and purple after a prolong click to recognize which tabs are under Tor and which are not.

One aspect of maintaining everything in a different header/separate in a sort of discreet manner that isn't necessarily a benefit and may come across as shallow but personally I don't think the Tor functionality should be very blatant. The Tor browser gains a bad reputation as it is and their representatives always having to defend the need for the browser, I don't think this speculation should ever arise in Brave and should come across like the many obfs apps and less so Tor 2.0, do you know what I mean? Scrap this entire comment if you disagree.

**Comment by flamsmark** [comment]
I'm not sure what you're talking about, but it sounds like you're proposing a very different set of features. Could you open new issues for those instead?

**Comment by NumDeP** [comment]
It was in reference to other feature/tor issue which propose configurations and I'm assuming later-on after it's been implemented other settings and feature may be deployed and I doubt they'll be filled in the browser's menu, so I was asking because I thought it was necessary, will there be an addition such as 'about:preferences#tor' to include 'Tor is censored in my country' and additional features such as 'Configure circuits' and any other that may arise per the teams advice or user suggestion.

As of now of now it seems like upon your recommendation that there is going to be a toggle in Shields, another in Private tabs similarly to DuckDuckGo and one more in jump lists #6094 which may be more desirable considering more than one session won't need to be created and less hassle for toggling.

I apologies, 3 days ago it made more sense when I hdan't read most of the tor labels.

**Comment by flamsmark** [comment]
@NumDeP I appreciate your enthusiasm for privacy features in Brave. I have two requests to make it easier for me to follow your suggestions and incorporate them into our roadmap where applicable.

I have a lot of difficult parsing your comments. Long sentences with lots of dependent clauses are hard work to read. Please try to slow down and write shorter sentences. Consider proof-reading before you post. Try to keep comments to one idea or fewer per sentence, and one idea per paragraph. The book [_Several Short Sentences About Writing_ by Verlyn Klinkenborg](https://www.goodreads.com/book/show/13155290-several-short-sentences-about-writing) really helped me write more clearly.

I try to file single issues describing individual blocks of work. If you have related ideas or suggestions, please file them as separate issues. Having a lot of discussion of maybe-related possible features doesn't make it easier to implement the things we're working on. Feel free to @-mention me if you think that an issue should be part of our security & privacy work. When filing issues, please keep it to one idea per ticket. Focus on expressing the proposed feature concisely.

**Comment by tomlowenthal** [comment]
Per-site Tor preferences are no longer on the horizon.
