### ISSUE TITLE
Autotype feature of KeePass2 password manager doesn't work with Brave

### ISSUE THREAD

**Issue by BertHyman** [brave/browser-laptop#1313]
Brave 0.9.0
Windows 7 Pro SP1 64-bit

Password manager KeePass 2 ([http://keepass.info/](url)) has an "auto type" feature to send userid and password to text fields of an open browser window using simulated keypress ([http://keepass.info/help/base/autotype.html](url)).

This feature works correctly with IE, Chrome and Firefox.

With Brave, the keystrokes are sent to the open browser window, but don't go to the userid and password text fields.

**Comment by maks1823** [comment]
With some websites it works, for example mega. Nz but mostly not. Maybe also a KeePassX support?

**Comment by sanecito** [comment]
+1 request for KeePass support

**Comment by rooflack** [comment]
Using Brave 0.12.3 and having sort of the same problem... except it seems to be related to the "two-channel auto-type obfuscation" feature in KeePass (which basically combines clipboard copy-paste operations and simulated keystrokes, including arrow keys to move the cursor, in order to avoid possible password hijack by keylogging software).
It works well in FF and Chrome, but when using it in Brave, it seems to somehow get in the browser window's main menu, and I can then see menus popping up and moving, and the username/password fields get populated, but the letters are all scrambled (because the cursor moves weren't processed).
Usually at the end a new tab opens too... but I suspect this is only a side effect of the return key being hit (or simulated, rather) while the main menu has the focus.
When using it without this feature, it looks like it works, so I'm just using it this way now, but it's a bit odd.
Anyway... hope this could help solve the thing or get a lead to the source of the problem. Please let me know if you'd like me to do more tests or anything...

Cheers, and keep up the good work!
G.

**Comment by valtt** [comment]
+1 for Keepass integration. It's a weird choice not having full Keepass integration, while non open source pasword managers (Lastpass, Dashlane etc) are supported.

**Comment by HLFH** [comment]
+1 for Keeweb integration. https://github.com/jhass/nextcloud-keeweb

**Comment by stefnats** [comment]
+1 for Keepass / Keeweb (macOS) integration

**Comment by zaleb** [comment]
+1 for KeePass

**Comment by osilvab** [comment]
+1 for Keepass integration

**Comment by CryptoNite19** [comment]
+1 for KeePass integration, working Chrome extensions exist

**Comment by jobyone** [comment]
+1 for KeePass integration

**Comment by czebiniak** [comment]
+1 for KeePass integration

**Comment by davidak** [comment]
I just auto-typed the GitHub login with KeePassXC.

Official integration of KeePassHTTP would be amazing.

**Comment by sentry-** [comment]
+1 for KeePass integration

**Comment by jytou** [comment]
+1 for keepass integration.

**Comment by dbeltranruiz** [comment]
One year and still not supported :(.. :+1:  from my side to keepass integration.

**Comment by misterigl** [comment]
Same here, would be nice :)

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/include-keepass-for-password-management/789

Let's keep the discussion there :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
