### ISSUE TITLE
'delayed scrolling' triggers zoom

### ISSUE THREAD

**Issue by Licenser** [brave/browser-laptop#1317]
This might be a bit hard to explain so please bare with me. I'm not sure if it affects anything but OS X either. When scrolling in OS X the scroll can continue once letting loose of the trackpade, I think the functionallity is meant to emulate the feeling of giving the page a nudge and it starts moving and slowly comes to a halt. Now weather that is nice or annoying is surely up to the person using it, but (there is always the but) when using the command key while the page is still moving (for example for swithcing applicaitons command+tab) the scroling movement also causes the page to zoom in or out (adjusting the size).

To reproduce:
* find a (sufficient long) page ( https://github.com/brave is long enough for me to reoproduce this reliably)
* start scrolling and let go quick enough so the page continues a bit on it own (this takes a bit of practice to do it on purpose)
* once letting go of the touch pad press the command key (as in command tab to switch)
* observe the page to either zoom in or out  (depending on scroll direction)

**Comment by loranger** [comment]
I have the same issue, using a macbook air trackpad. This bug is really annoying. I used to switch page using cmd+alt and arrows, but as soon as I try to switch tab, the page randomly zooms.

I can reproduce on this page :

- I scroll using my trackpad. The page stops scrolling as it reached its bottom
- I remove my fingers from trackpad
- I count two seconds
- I press cmd (+alt) and the page zooms out

**Comment by bbondy** [comment]
ok we'll try to tweak or disable th scroll zooming for 0.9.2
