### ISSUE TITLE
Resume after pause on twitch media does not resume timer

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13257]
### Description

When testing https://github.com/brave/browser-laptop/pull/13142, I realized that timer for time spent on a twitch video is not resumed when you click PLAY after pausing a video

### Steps to Reproduce

  1. Watch a twitch video; confirm time spent is showing in ledger
  2. Click pause; confirm time spent was updated
  3. Click play again; wait for a minute
  4. Notice time does not increment

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by srirambv** [comment]
Seeing a different behaviour on Windows. 
Visited this link and started playing video https://www.twitch.tv/videos/230977648
Played the video for 3min20sec and paused, ledger showed 3min52secs as time spent
Paused the video for 2 mins and then resumed to play
Played the video for 4min53sec and paused, ledger showed 6min39secs

**Comment by srirambv** [comment]
Even seeking video to  a different position the time spent is recorded

**Comment by NejcZdovc** [comment]
Tried your scenario, this is what happened for me:

Played the video for 3min20sec and paused, ledger showed 3min21secs as time spent
Paused the video for 2 mins and then resumed to play
Played the video for 4min53sec (which is total of 8m13s) and paused, ledger showed 8min15secs

That 2s more is expected and happens because of the nature that we are logging twitch time

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.7 https://github.com/brave/browser-laptop/commit/8bb7e77f69bca186429aafda4bc6ba4d82a5de47
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
