### ISSUE TITLE
CryptoTokenExtension shown with broken icon on about:extensions

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13252]
### Description
CryptoTokenExtension shown with broken icon on about:extensions

### Steps to Reproduce
  1. Clean install 0.21.11
  2. Open `about:extensions`
  3. Shows CryptoTokenExtension with broken icon 

**Actual result:**
![cryptoextension](https://user-images.githubusercontent.com/17010094/36534147-b438d8b6-17eb-11e8-8b87-7f0a8e693412.gif)

**Expected result:**
Not sure what is expected

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.11
-- | --
V8 | 6.4.388.41
rev | e146cd8
Muon | 5.0.5
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
No

### Additional Information
cc: @bsclifton @evq

**Comment by evq** [comment]
the icon has always been broken since I added the extension for u2f support

**Comment by bsclifton** [comment]
Since it's not shown on `about:preferences#extensions`, I don't think we need to worry about the icon being shown properly.  However, it couldn't hurt to pass a manifest here with a path to a valid icon:
https://github.com/brave/browser-laptop/blob/12aa8bb6a6494dc0406e2ffe978b037d7ef3af8a/app/extensions.js#L527

Although, it would be a problem if this overrides what is detected when loading
