### ISSUE TITLE
import bookmarks doesn't have extension option with html

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13372]
### Description
Per (second) test case c 'Import bookmark from HTML' from https://github.com/brave/browser-laptop/pull/11906 - when importing bookmarks from HTML file the dialog should have an extension option with html

### Steps to Reproduce

1. Menu->Bookmarks->Import Browser Data.. and select HTML file
2. The default path should be your download path
3. 

**Actual result:**
The dialog does not have an extension option with html.
![screen shot 2018-03-02 at 11 36 56 am](https://user-images.githubusercontent.com/28145373/36910194-08a99a20-1e0e-11e8-8edc-e674d49a3d40.png)

**Expected result:**
The dialog should have extension option with html and the default extension should be html

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.21.654
V8 | 6.5.254.26
rev | bc6272c
Muon | 5.1.3
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.88

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
If I hit the `Options` button in the bottom left (macOS):
![screen shot 2018-03-09 at 10 57 47 am](https://user-images.githubusercontent.com/4733304/37221949-c84fc924-2388-11e8-9526-ce2cf9c3ae73.png)

It shows the extension (as expected):
![screen shot 2018-03-09 at 10 57 21 am](https://user-images.githubusercontent.com/4733304/37221962-cfd7994c-2388-11e8-914b-46713226f512.png)

On Windows, it works as expected:
![screen shot 2018-03-09 at 10 59 43 am](https://user-images.githubusercontent.com/4733304/37222024-05d56718-2389-11e8-9d7b-a74d42f2cd86.png)

@darkdh is this expected behavior? (having to click `Options` in order to see the extension that is being filtered). The filter itself is working, you just need to click `Options` to show it

**Comment by darkdh** [comment]
yes, please click on `Options` and you can't choose files other than html. so this is correct behavior
