### ISSUE TITLE
Brave doesn't finish downloading in Edge in 14316

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1338]
from @ericlaw1979:  "FYI: Brave doesn't finish downloading in Edge in 14316. I think if you dual-sign with SHA1 and SHA256 that bug goes away."

i thought #396 was resolved though? eric, did you mean dual sign the installer or the TLS cert?

**Comment by weems** [comment]
What are the steps to verify the timestamp is assigned, We should be able to confirm this rather easily if a timestamp is being applied, right?

**Comment by ericlaw1979** [comment]
To be clear, Brave's installer is now signed with a SHA256 file digest--_only_ SHA256. It's generally a good practice to sign with *both* SHA1 and SHA256 digests, because older platforms can't do SHA256. Now, ordinarily that may not matter (you guys may not care about platforms without SHA256) but it *appears* that Win10 14316 introduced a bug whereby:

1> Files signed with SHA1 and SHA256 file digests work fine
2> [Files signed with only SHA1 file digests are deemed "Corrupt signature"](https://textslashplain.com/2016/04/10/sha256-and-authenticode-redux2/)
3> Files signed with only SHA256 fail to complete downloading (hanging at 99%)

**Comment by bbondy** [comment]
thanks for the heads up

**Comment by weems** [comment]
I think the scenario where files with only SHA1 are deemed corrupt is valid. Not good that people are unable to access on older platforms, but older platforms are not secure. So is our priority supporting all possible OS versions, or the most secure ones for reasons of Privacy and Security? :8ball:

**Comment by diracdeltas** [comment]
There's no security downside to dualsigning with sha1 and sha256; sha256 clients presumably just ignore the sha1 sig.

**Comment by weems** [comment]
I didn't mean to imply that it was, but that *only* SHA1 platforms are not secure 👍

**Comment by luixxiul** [comment]
How about now?

**Comment by ericlaw1979** [comment]
The Edge download bug was fixed in the next build of Windows 10. I still think it makes sense to dual-sign the installer but this is no longer causing the issue described in the original report.

**Comment by luixxiul** [comment]
OK, closing.
