### ISSUE TITLE
seattletimes.com - anti-adblock content-blocking

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#13430]
### Description
seattletimes.com has an anti-ad blocking countermeasure that blocks content unless shields are dropped. 

observed on win10, but likely global.

they also counter script blocking, as blocking scripts will prevent the content from loading. 

### Steps to Reproduce

  1. go to https://seattletimes.com
  2. get blocked
  3.

**Actual result:**

![brave-adblock-detected-seattletimes-03122018](https://user-images.githubusercontent.com/8979240/37324746-152c61be-2648-11e8-9d9e-6979194ecc5b.PNG)

**Expected result:**
should be able to view content 

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**
 ```
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Reproducible on current live release:**

yes

**Comment by Stosswalkinator** [comment]
I noticed that I can view the homepage, but if I click on an article I have to take shields down to view content. Can you confirm?

I would agree that it's probably a universal thing because it's a site issue not a browser issue.

Steps to Reproduce
go to https://seattletimes.com
view article
get blocked

Actual result:

![screenshot from 2018-03-13 14-59-30](https://user-images.githubusercontent.com/2595146/37366767-603d841c-26cf-11e8-8967-c163df142642.png)

Brave Version
about:brave info:

Brave | 0.21.18
-- | --
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 4.15.0-10-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by jonathansampson** [comment]
The ad-blocker works by detecting the blocking of `ad-test.js`; this file executes a small script which creates an object stud, and populates a few specific properties. This object is assumed to exist in a particular state later in the page life-cycle, and if it is not in that state the user is assumed to be using an ad-blocker.

The following is the script contained in `ad-test.js`:

```js
(function() {
  // Detects ad block
  // See the plugin st-privacy-detection for the usage of the baitLoaded value
  window.SEATIMESCO = SEATIMESCO || {};
  window.SEATIMESCO.browser = SEATIMESCO.browser || {};
  window.SEATIMESCO.browser.adBlock = SEATIMESCO.browser.adBlock || {};
  window.SEATIMESCO.browser.adBlock.baitLoaded = true;
} ());
```

If this script is injected and executed prior to loading `st-detect.min.js`, no ad-blocker message is shown. It may be the case that all we need to do is permit `ad-test.js` to load, since it contains no malicious or ad-generating logic.

**Comment by jonathansampson** [comment]
uBO has the following fix:

https://github.com/uBlockOrigin/uAssets/blob/0441a7e0a6c626f91c5b750c55be180a15d526b1/filters/filters.txt#L3579-L3580

**Comment by lukemulks** [comment]
resolved here https://github.com/brave/adblock-lists/commit/a6e1a2051f596da6e8b1fecd604375e9b06dbf12#diff-3d05cf908db454bc68b7983ddc029cb0
