### ISSUE TITLE
new ledger contribution delayTime

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13531]
### Description

currently the delayTime is a random time in the range between 1 and 10 minutes to avoid correlating ledger contribution votes using timing. https://github.com/brave/browser-laptop/blob/master/app/browser/api/ledger.js#L2356

 i think [10s, 4m] would be an appropriate range.

copied from #13462

**Comment by kjozwiak** [comment]
@NejcZdovc is there a way QA and test and verify this change?

**Comment by NejcZdovc** [comment]
@kjozwiak So what was changed here is interval of the calls. So what you can do is add ledger verbose and create contribution. You would then need to check out (time) requests when contribution is in the progress to make sure that is not just 1min, but that it varieties. If you want to test this out I can specify even more detailed plan?

**Comment by kjozwiak** [comment]
@NejcZdovc that sounds great! If you could add/specify a detailed plan, that would be super helpful. From the sounds of it, we would do a contribution and while using `LEDGER_VERBOSE=true`, ensure that the delayTime isn't a minute but varies correct?

**Comment by kjozwiak** [comment]
Same results on Mint 18.3 x64 using `0.22.667` rev: 0433b26a03c8daf9b181057cd2ffa7b530496faf:

* launch `0.22.667` using `LEDGER_VERBOSE=true` via the terminal
* on launch, received `ledger client run: clientP=true delayTime=282707`
* second ping --> `ledger client run: clientP=true delayTime=0`
* third ping --> `ledger client run: clientP=true delayTime=0`
* closed brave and re-launched using `LEDGER_VERBOSE=true` via the terminal
* on launch, received `ledger client run: clientP=true delayTime=246945`
* second ping --> `ledger client run: clientP=true delayTime=0`
* third ping --> `ledger client run: clientP=true delayTime=0`

@NejcZdovc is this the expected behaviour? @srirambv seeing the same thing on Win 10 x64 as well.
