### ISSUE TITLE
Problem in signing into "Pocket" extension

### ISSUE THREAD

**Issue by IKishan** [brave/browser-laptop#13595]
### Description

Problem in using Pocket extension available on the brave browser for laptop since the sign in process (especially with google) never gets completed.

### Steps to Reproduce

  1. Open brave browser and enable the pocket extension from the list of extensions available
  2. Click on the extension to open a sign up or log in page for https://getpocket.com
  3. Use Login with google option - The sign in process never gets completed (displays: one moment please or just continues signing in infinitely)

**Actual result:**
![screenshot 66](https://user-images.githubusercontent.com/16862783/37879870-12911e04-309d-11e8-94fd-2cf48f2f910c.png)
![screenshot 67](https://user-images.githubusercontent.com/16862783/37879872-12c26888-309d-11e8-8f86-d34e260d82b4.png)

**Expected result:**
The extension should allow the sign in process readily. The same can be achieved on other browsers in a much convenient manner

**Reproduces how often:** Everytime (100%)

### Brave Version

**about:brave info:**
 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:** Yes

### Additional Information

The problem is not only with the extension but infact the actual site https://getpocket.com - sign in with google is not possible. But no such issue can be found when using Firefox or Chrome.

**Comment by tony-ho** [comment]
This looks to be related to an issue with Google OAuth 2.0 Sign-In when third party cookies are disabled.

I was able to complete the sign in process successfully after editing the site shield settings for getpocket.com and changing the **Cookie Control** setting from *Block 3rd party cookies* to *Accept all cookies*.

The issue is reproducible in Chrome when *Block third-party cookies* is set.

References:
https://developers.google.com/identity/sign-in/web/troubleshooting
https://github.com/google/google-api-javascript-client/issues/260

**Comment by IKishan** [comment]
Yes, actually the browser blocked all third party cookies and hence the sign was unable to complete. The permissions were granted in **Preferences>Shields>Cookie Control>Allow all cookies**
Thanks for the help @tony-ho
