### ISSUE TITLE
[FEATURE REQUEST] Add an option to disable WebRTC in about:preferences

### ISSUE THREAD

**Issue by MkllTech** [brave/browser-laptop#13668]
### Description
Add an option to disable WebRTC in the settings menu (about:preferences).

**Why**: WebRTC can leak IP addresses even behind VPN.

**Comment by BrendanEich** [comment]
This came up on reddit and our advice to use fingerprinting protection was not useful due to auth systems that do canvas readback (slider captchas etc). I think we must fix this issue so users do not face the bad choice of logging in over a vpn with such a captcha, leaking home ipaddr, and too late then enabling f.p. Cc: @diracdeltas

**Comment by diracdeltas** [comment]
https://github.com/brave/browser-laptop/pull/13713
