### ISSUE TITLE
New Tab doesn't work without an open window on macOS

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#13689]
### Test plan
See https://github.com/brave/browser-laptop/pull/13749

### Description
If there is no open window, New Tab (and New Private Tab and New Session Tab) does not work until New Window is selected.

This was working correctly in version 0.21.x but broke in 0.22.x.

### Steps to Reproduce
macOS only
  1. Open Brave.
  2. Close the window without quitting Brave.
  3. Select Menubar > File > New Tab

**Actual result:**
Nothing happens.

**Expected result:**
A new window with the tab should open.

**Reproduces how often:**
Always

### Brave Version

**about:brave info:**
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
Yes, 0.22.13.

**Comment by bsclifton** [comment]
I believe @armaanahluwalia has identified the cause of this issue:
https://github.com/brave/browser-laptop/pull/13242#issuecomment-375803798

See https://github.com/brave/browser-laptop/issues/8164 for more info

@armaanahluwalia would you be up for trying a fix? 😄

**Comment by armaanahluwalia** [comment]
@bsclifton Absolutely would be my pleasure to work on this project. Will begin working on it tomorrow and try to send up a fix soon.

**Comment by petemill** [comment]
@armaanahluwalia Apologies, but I had to fix this as we want to get it in to the next release. I also noticed that the fix was a bit more complicated than I had originally thought since on Windows, the code is called by a different process which does not have access to the internal window API. That's because on Windows, the main menu is part of each window process, whereas on other platforms the main menu is part of the application process. It would be great if you could take a look at my PR for the fix at #13749. Thanks for looking in to this issue and finding the cause! If you would like to contribute to any other features / fixes, I'd be happy to help.

**Comment by armaanahluwalia** [comment]
@petemill No worries at all. Thanks for taking this on. TBH a bit busy at the moment with job interviews. Anyway, I'm not sure I'd be able to contribute productively to reviewing this PR since I haven't had the time to parse the overall structure of the application code yet. I will do soon. Thanks for the shout out.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/file-new-tab-does-not-work-since-latest-update/19357?u=eljuno

**Comment by LaurenWags** [comment]
+1 from https://twitter.com/rkavalap/status/982127674087751681

**Comment by LaurenWags** [comment]
Multiple +1s in community

**Comment by LaurenWags** [comment]
Removed macOS label - linked test plan can mostly be checked on all platforms and does include a specific Windows check to be completed.

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 with
0.22.665 https://github.com/brave/browser-laptop/commit/bc13ab63f87b22dce366175927ffef54cb5cd201
Muon 5.2.5
libchromiumcontent 66.0.3359.117
