### ISSUE TITLE
Bookmark is not shown after adding bookmark

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13695]
### Steps to Reproduce
  1. Clean install
  2. Open Brave
  3. Bookmark the page

**Actual result:**
Bookmark toolbar is not shown
Resizing Brave window shows the bookmark but overflow indicator does not properly show.

![image](https://user-images.githubusercontent.com/34715963/38252950-b998ef42-3755-11e8-9367-632e99f073c3.png)

**Expected result:**
Bookmark toolbar is shown

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.22.103 
V8: 6.5.254.41 
rev: 2324f5563110b178304d30b81f3cfae965ae4a03 
Muon: 6.0.0 
OS Release: 6.1.7601 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Comment by LaurenWags** [comment]
Reproduced on MacOS

**Comment by petemill** [comment]
This was because calculating the text width of the bookmark item was not running due to muon's `executeScriptInTab` not working against a window's WebContents, which technically it shouldn't anyway. I'd love to remove all the bookmark textCalc logic and do a simpler css implementation, but for now we have a potential muon fix. Let's check when we get the next muon build (probably 6.0.2).

**Comment by btlechowski** [comment]
Verified Win7 x64 v0.22.108
