### ISSUE TITLE
crash on startup for Linux users who have installed via snap

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13748]
### Description
Reported via community:
https://community.brave.com/t/brave-immediately-crashes-when-i-try-to-start-it-it-pops-up-and-then-closes/19267
https://community.brave.com/t/braqve-crashes-on-launch/19279

Several users who have installed Brave via snap are reporting that Brave crashes upon launch.

### Steps to Reproduce

  1. Have Brave installed via snap
  2. Launch Brave
  3.

**Actual result:**
Crash

**Expected result:**
Should not crash

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**
0.22.13

**Reproducible on current live release:**
yes

### Additional Information

cc @w0ts0n

**Comment by LaurenWags** [comment]
Update: snap has been reverted back to previous version, 0.21.24 for the time being while investigation continues.

**Comment by hugobuddel** [comment]
My computer crashed (well, mounted / read-only) because the root file system was full. Turned out that there was a 70GB `.xsession-errors` file in my home directory full with lines like
<pre>
[1:1:0610/053401.568108:ERROR:command_buffer_proxy_impl.cc(101)] ContextResult::kFatalFailure: AllocateAndMapSharedMemory failed
[1:1:0610/053401.568161:ERROR:broker_posix.cc(103)] Error sending sync broker message: Broken pipe (32)
</pre>

Exactly the errors you mention above. Brave was still running though, but not responding anymore. Brave installed through apt though. Brave does start normally though.

Googling the error message gave only a single other hit about a Steam custom wallpaper. I probably was running Steam as well, but not using any custom wallpapers, so I believe the problem is Brave.
  
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 4.13.0-43-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
