### ISSUE TITLE
Enhancement: Add a button for get mobile-fingerprints

### ISSUE THREAD

**Issue by HotelBellaMuerte** [brave/browser-laptop#13762]
Could brave team add a button for get a mobile fingerprint ? **and let mouse  use touchevents**

?

the reverse of a feature tthat has some android browsers *view this as a pc*

**Comment by bsclifton** [comment]
@bn0785ac can you give an example of this?

Are you basically asking for a feature that folks can enable where the browser treats mouse events like touch events? ex: clicking is like a push, etc.  Or are you asking if the browser can send a mobile User-Agent (so that the mobile page is sent instead)?

If your request is the first, that sounds like a fairly complex feature- I'd be interested in an example.  The second (changing user-agent) is captured here if you wanted to give it a +1:
https://github.com/brave/browser-laptop/issues/6983
