### ISSUE TITLE
Make private tabs pass the grep test

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#138]
visit a site you've never been to before (goodeggs.com) in a private tab and then grep for goodeggs in /Users/yan/Library/Application Support/Brave. Found matches in /Cache/data_1 and /Cache/data_3.

**Comment by diracdeltas** [comment]
I think I figured out two reasons that this is happening:

1. favicons from private tabs (which are loaded outside of the webview partition) are hitting the cache. i confirmed that disabling `setFavicon` and `faviconUtil.getFavicon` made private tabs pass the grep test.
2. independently, searching via cmd+k while a private tab is active seems to be writing the search query to cache. this is probably because we are sending one XHR per keystroke to the search autocomplete URL from the urlbar, which is also outside of the webview partition.

**Comment by bbondy** [comment]
Nice finds.
