### ISSUE TITLE
master password for password manager

### ISSUE THREAD

**Issue by dschneiderch** [brave/browser-laptop#1385]
it would be nice to protect visibility of the passwords in the password manager with a master password. similar to firefox.

**Comment by tommasosotte** [comment]
This would be really helpful

**Comment by indigo0086** [comment]
I think this would be more than helpful as this is one flaw I see in Brave's mission of keeping your browsing experience more secure.  If we click the eye, we should be prompted to enter our user account password similar to how chrome does so (works for windows and mac).

**Comment by diracdeltas** [comment]
fwiw you can do this right now by locking the system keychain since passwords are encrypted with a master password that is in the keychain.

**Comment by diracdeltas** [comment]
@NejcZdovc noticed that Chrome prompts for system keychain access when you click to show a password in chrome://settings/passwords. I'm not a huge fan of this approach because it seems like it would give users a false sense of security (since the attacker can just go to the site,  have it autofill, then copy the autofilled password into a visible field, given a few more seconds of attack time). However it's another option we could consider.

**Comment by bramvanoost** [comment]
Also very pro a master password feature, like Firefox has.

**Comment by NumDeP** [comment]
+12 Upvotes, 10 Likes, 475 Views and counting in the community 

- https://community.brave.com/t/password-protect-browser/4463

- https://community.brave.com/t/master-password/289

- https://community.brave.com/t/storings-passwords-to-password-manager/8129

**Comment by NumDeP** [comment]
@bramvanoost What would you change or want improved in the description below 
- https://community.brave.com/t/password-protect-browser/4463

**Comment by fermulator** [comment]
In https://www.reddit.com/r/braveproject/comments/7r6awh/brave_password_manager_vs_others/?st=jcjuitcx&sh=13114369, I asked why I should or shouldn't use one manager over another (brave built-in vs. others) - I suppose this is one reason? (lack of master password)

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/mickasuk/status/965984637318246400

**Comment by axmichail** [comment]
+1

**Comment by gallegosart** [comment]
+1
Is there any progress here at all or still just feature request? Seems like a huge offline privacy hole.

**Comment by globalqss** [comment]
+1 here
I think this is a big security issue as commented here:
https://community.brave.com/t/big-security-issue-with-chrome/29221/3

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/i-think-need-request-to-improve-brave-s-password-management/32112

**Comment by bsclifton** [comment]
This is fixed with our [Developer channel release](https://brave.com/download-dev) 😄 

When you visit chrome://settings/passwords and try to expose the password by clicking the eyeball, you'll get prompted for your password:
![screen shot 2018-09-13 at 10 01 50 am](https://user-images.githubusercontent.com/4733304/45503661-53ffe480-b73c-11e8-85a6-e92552780f3a.png)

**Comment by StuartLRM** [comment]
I'm not sure that the fix described above actually addresses this request. It appears that the approach implemented is to use the keychain, similar to Safari's implementation. This request mostly is about implementing a master password that is independent of the user's local account credentials in the same way that Firefox does. I'm in favour of the master password approach.
