### ISSUE TITLE
webrequest filtering functions not working in Tor mode

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14021]
STR:
1. open tor tab
2. go to nytimes.com
3. notice that no ads are blocked in the shields panel

It looks like the partition is initialized, but the webrequest listeners in the Tor session do not fire.

cc @darkdh @riastradh-brave

**Comment by lukemulks** [comment]
Was testing on Windows 10 - observed some behavior worth noting in case it helps with this.  

I began browsing with scripts disabled to get a feel for the edges between ads and no ads with the Tor connection, and observed a tracking pixel being blocked with scripts disabled. Details and STR below. 

==================
profile
==================
Brave: 0.23.2 
V8: 6.6.346.26 
rev: c09cbf6ad24cabd9d4bf5a9f52ce8c3d8a04585c 
Muon: 6.1.0 
OS Release: 10.0.16299 
Update Channel: Developer 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
==================
to repro
==================
 - open tor tab
 - once connected, go to https://www.techwalla.com
 - click on the site-level shield settings, disable scripts
 - reload
 - navigate to: https://www.techwalla.com/tablets, or any other subpage within the parent domain. 
 - observe quantserve tracking being blocked in shield menu. 
```
 Quantserve tracking request (blocked) https://pixel.quantserve.com/pixel/p-4dIM5nVs2rFio.gif
```
![brave-desktop-win-tor-tab-dev-build-05052018-1block-noscript](https://user-images.githubusercontent.com/8979240/39669819-b2a0c466-50ab-11e8-86f7-bfc164383e77.PNG)

I opened a new tab after checking 2 additional pages, and noticed that the Brave Stats that display on the new tab page showed 4 Trackers Blocked, instead of the expected Ads and Trackers Blocked stat. 

![brave-desktop-win-tor-tab-dev-build-05052018-brave-stat](https://user-images.githubusercontent.com/8979240/39669835-3a520bae-50ac-11e8-8b01-96d8beb56e73.PNG)

I went back to the page where the quantserve tracking request was blocked, enabled scripts and reloaded the page. I observed what appears to be a mix of ad and tracking calls blocked on that page (scripts re-enabled): 
![brave-desktop-win-tor-tab-dev-build-05052018-scripts-enabled](https://user-images.githubusercontent.com/8979240/39669871-f0e0791e-50ac-11e8-8cf4-70832903a1af.PNG)

I navigated to the homepage, and observed ad and tracking requests being blocked on the homepage with scripts enabled: 

![brave-desktop-win-tor-tab-dev-build-05052018-scripts-enabled-hp](https://user-images.githubusercontent.com/8979240/39669905-83129a60-50ad-11e8-84d6-9851981ce14a.PNG)

When I attempted to repro the same way from a separate Tor tab (same str as listed above) - I'm observing different results, zero requests blocked across all shield stats. 
![brave-desktop-win-tor-tab-dev-build-05052018-scripts-enabled-hp-tab-2](https://user-images.githubusercontent.com/8979240/39669923-0db6d064-50ae-11e8-85f3-a0ba89b3594a.PNG)
Note: I tested from this tab without a new Tor circuit, and with, and observe the same result. 

I navigated to an article page from the same tab that showed zero blocking and did not observe any blocked ads or tracking from an article page. 

Note that I have site isolation enabled in this build as well. 

Not sure why I'm seeing different results from the same steps to repro in different Tor tabs, but fwiw did not recall observing tracking protection working until after I began disabling scripts for the tor tab that began blocking things.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/750df850852a0bd8f01dcdcd9f190fb040a5e6f3 which will be available in muon 6.1.1

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
