### ISSUE TITLE
Pinned tab is lost when URL is different and another tab is pinned / unpinned

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14032]
### Description
Pinned tab is lost when unpinning an unfocused pinned tab

### Steps to Reproduce
  1. Clean install 0.22.702
  2. Open a bunch of tabs and visit sites in them
  3. Open preferences and pin preferences page
  4. Pin a bunch of other tabs that are opened
  5. Set tabs set to 6 and keep preferences tab as active tab
  6. Unpin one of the inactive pinned tab, preferences tab is lost

**Actual result:**
![pinned tabs](https://user-images.githubusercontent.com/17010094/39653179-f5a05ea0-4fbd-11e8-9986-aeb749ce9da3.gif)

**Expected result:**
Should not lose any pinned tabs 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.702
-- | --
V8 | 6.6.346.26
rev | e4a853d
Muon | 6.0.7
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
No

### Additional Information
cc: @petemill @bsclifton

**Comment by petemill** [comment]
This is actually an existing issue in release, and this is to do with the fact that there is an issue with comparing which pinned tabs are already open and which pinned tabs should be closed. When the URL of the pinned tab changes, the comparison algorithm thinks it is a different tab, and that it should be closed since a tab with that (new) URL was not meant to be pinned. It then notices that there is no tab with the original URL and creates it. However, because this is an about:preferences tab, the default behavior is to switch to an already-existing tab, which at the time of the alogorithm, is the about-to-be-closed pinned preferences tab.

When activating different sections of the preferences page, the url changes. In this case, it changes to `about:preferences#tabs`.

I believe this should be looked at in another issue. The solution is to compare the desired-pinned-url to the _original_ tab url, not the _current_ tab url.

**Comment by petemill** [comment]
To add: This problem occurs when you pin _any_ tab and click a link, and then change the pinned tabs collection by pinning or unpinning another tab - the tab is lost and re-created (except from Preferences). Focused / unpinning is not required.

**Comment by petemill** [comment]
After talking through how navigation URLs are passed through from muon with @bridiver, the solution I would take would be to store the tab's original url (potentially pre-redirection / link clicking) at the time of pinning. If the tab was created as pinned: get the first navigation handle's initial URL from the redirect chain (only accessible during navigation). If the tab was pinned after creation (potentially after navigating through different URLs): use the current display url. Once this property is set in the tab state, don't replace it, and make sure to preserve that across tab replacement (e.g. from discard).

We could then use that URL to compare with the list of URLs we want to be pinned, instead of blindly comparing the tab's current url.
