### ISSUE TITLE
Recovering a corrupted seed using valid key creates a new wallet

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14063]
### Description
Recovering a corrupted seed using valid key creates a new wallet

### Steps to Reproduce

1. Clean install
2. Create Wallet in about:preferences#payments
3. Exit Brave
4. Delete seed 20 and 21 in ledger-state.json
5. Run Brave again
6. Click "Recover your Brave wallet"
7. Then successfully recover the wallet with:  `vower obovoid menace tobogganist hoyle honoree pixel pestilently disconcertment sellable ruffing supervision zoroastrian based coparent slackened`
8. Click on backup wallet, shows a different set of recovery code

**Actual result:**
Recovering a corrupted seed using valid key creates a new wallet

**Expected result:**
Should show recovery code that was used to recover from corrupted seed value

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.703
-- | --
V8 | 6.6.346.26
rev | 903b8d0
Muon | 6.0.8
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
N/A

### Additional Information
#13645
cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
So what is happening is that you are importing key that is NICEWARE `vower obovoid menace tobogganist hoyle honoree pixel pestilently disconcertment sellable ruffing supervision zoroastrian based coparent slackened` (16 words), but when we recover wallet we are using now BIP39 which has 24 words and you get `wasp broken strong analyst until tray olympic arrow input bicycle gun settle prepare tissue road try sustain husband width brave section obey country area`.

As far as I know this is expected behaviour now what we switched to bip39 so we are basically just migrating backup keys to new format.

cc @diracdeltas @bsclifton for confirmation

**Comment by NejcZdovc** [comment]
Also tried recovered with new bip39 passphrase and passphrase is not changed and it stayed the same

**Comment by diracdeltas** [comment]
@NejcZdovc @srirambv this is expected behavior. when you import an old key, it will be migrated to the new format (bip39). you can verify that if you import the old key again, you get the same new key.

**Comment by NejcZdovc** [comment]
closing as this is expected
