### ISSUE TITLE
Failed to return real IP when converted IP into Long/Decimal On Homepage

### ISSUE THREAD

**Issue by apapedulimu** [brave/browser-laptop#14071]
**Summary:**
Failed to return real IP when converted IP into Long/Decimal,

**Detail :**

http://74.125.24.139/ = http://google.com/
this is ip of google.com [74.125.24.139 ] converted into Long/Decimal using http://www.smartconversion.com/unit_conversion/IP_Address_Converter.aspx
http://1249712267/ = will return http://74.125.24.139/
1249712267/ = not return to http://74.125.24.139/

**Products affected:**
Brave 0.22.669

**Steps To Reproduce:**

- Go to setting , Set http://1249712267/ as home page and it 'll return to real IP. 
- Compare with when you input 1249712267/ in the homepage, it wouldn't return to real IP. 

So, when it's not http:// on the first time it'll not return to real IP, same like homograph on : https://hackerone.com/reports/268984 , it'll will not return as homograph, when at the first time not add by http://

**Supporting Material/References:**
Video : https://youtu.be/b9uUzfob6p4 ( Unlisted )

**Comment by bsclifton** [comment]
Thanks for the report, @apapedulimu! I can confirm the issue and have verified it's fixed in Brave Core (what we'll be transitioning to from browser-laptop).  For the time being, I'm going to mark this as a `wontfix`

You can read more about the upcoming Brave Core project here:
https://brave.com/development-plans-for-upcoming-release/
