### ISSUE TITLE
Disappearing Bookmark Folder

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#14093]
### Steps to Reproduce
Note: Best to watch the video
1. Clean install
2. Create Bookmark folder
3. Drag the bookmark folder onto its content modal
![disappearing_content_modal](https://user-images.githubusercontent.com/34715963/39893670-d19be27c-54a4-11e8-989e-58c9c57488ba.gif)

**Actual result:**
The bookmark folder disappears with all its content(will not be shown after restart).
The bookmarks under the bookmark folder still exist because the pages are marked as bookmarked.
For end user this will look like bookmarks randomly disappear.

**Expected result:**
Cannot drag bookmark folder onto its content modal

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117
```
Reproduced on Win and Lin.
@LaurenWags Could you check Mac?

**Reproducible on current live release:**
Yes, 0.22.669 

Cc @kjozwiak @srirambv @LaurenWags @petemill @bsclifton

**Comment by LaurenWags** [comment]
Reproduces on macOS using `0.22.669`

**Comment by btlechowski** [comment]
+1 from community: https://community.brave.com/t/bookmarks-disappearing-from-toolbar-occasionally/21679

**Comment by ajohnsen** [comment]
I had this same thing happen on my mac too.. I checked the session-store1 json file and in there the bookmarkfolder referenced itself in the parendId attribute.

This issue might be related/fixed earlier for the about:bookmark page: https://github.com/brave/browser-laptop/issues/4751

**Comment by misterjib** [comment]
Thanks for reporting this, curiously although the bookmark link is no longer present in the dropdown / bookmark manager, if you navigate to URL that is affected by this bug the bookmark star is still in nav bar is still present. 

Does anyone know how I can restore? an xml file maybe? 

Exporting does not include affected.

This bug is a proper nause.

**Comment by Balancingrock** [comment]
I experience something slightly worse: I have several bookmarks in a folder. When I select one of these and keep the mouse key down so the link is dragged just a little, it will disappear when the mouse key is released.
However after that, I am unable to create a new bookmark for the same website. (It seems as if brave still knows the bookmark exists, so it does not add a new one, but at the same time also will not display the old one)

I have tried looking for a bookmarks file, but have not found any.

Brave | 0.23.39
-- | --
V8 | 6.7.288.46
rev | 3ee14b0
Muon | 7.1.6
OS Release | 15.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Comment by bsclifton** [comment]
Confirmed fixed with [brave-core](https://github.com/brave/brave-browser)

For folks having this issue: for a work-around, you can go to the bookmarks manager and search for one of the bookmarks you know was lost (even if you don't remember full name, just type a letter). You should then be able to find/drag it back into the root folder

A second work-around would be to manually open the `session-store-1` file which is stored at `%APPDATA%\brave` / `~/.config/brave/` / `~Libraries/Application Support/brave` and find the bookmarks in the session JSON (make sure to close browser before editing- backing up this file is a good idea too)
