### ISSUE TITLE
Mouseover Tabs Preview Documents

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-laptop#14317]
### Description
When moving the cursor over any inactive tab, that tab's docuent is shown after a delay.  This causes usability problems. Due to timed delay, errors occur when switching tabs, whereby the wrong document will be shown (issue #14258)

### Steps to Reproduce

  1. Load up a bunch of tabs with heavy apps like TradingView, YouTUbe, etc
  2. Move cursor over inactive tabs

**Actual result:**
document view change to show flashes of other documents, sometimes white/grey

**Expected result:**
No change in default view

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**

**Comment by GarrettS** [comment]
![image](https://user-images.githubusercontent.com/56098/40889085-47e2d6ac-6715-11e8-9f5e-500be5be8e6f.png)

**Comment by bsclifton** [comment]
@GarrettS there are some known issues with the wrong tab being displayed (as you've noted in https://github.com/brave/browser-laptop/issues/14258).

Turning off the tab preview functionality seems to help. You can access it from about:preferences#tabs:
![screen shot 2018-06-04 at 2 07 41 pm](https://user-images.githubusercontent.com/4733304/40941811-f5957cc8-6800-11e8-9572-1e0b99bf1408.png)

Since this issue is known (and already captured with your other issue), I'll close this one as a duplicate

**Comment by GarrettS** [comment]
Bug #14258 was closed by me. So now you have two closed bugs. And you’ve also Mark this is a duplicate of the other closed bug. You’re avoiding the problem; pretending that it doesn’t exist.

Mouse over feature problem is a bug. 

The preview feature is a usability mistake. Hover is not a user intentional action, So why do you treat it as such when to do so is a problem?

When typing into a text field and user thumb happens to touch the trackpad, pushing the cursor over another in active tab, that should not interfere with user intentional action of typing into that text field. But it does. And not only does it provide a visual distraction, it prevents the typing. 

This is a bug.Perhaps we should call it, oh I don’t know, “mouse over preview prevents typing”. 

But you’re going to have an explosion of mouse over preview related bugs, for what? So that you can carry-on with the featured problem?

Mouse over feature problem is a bug. 

Mouse over preview problem causes many other problems. 

One other problem that that problem causes is the timing issue that is shown in the screenshot I posted on both closed bugs. That happens with moving the cursor across the Tab strip, Activating a tab (by clicking on it), and then seeing the wrongDocuments loaded. I know brave is a new browser so there’s bound to be some bugs but this is a new feature introduced by Brave. Do you think chrome, Microsoft, or Apple would ship such bugs? Try to imagine a Safari release that did that. 

You are being dismissive and not acknowledging the severity of this problem. 

The most logical course of action is to acknowledge that mouse over preview problem is a bug that needs to be fixed. The way to fix it is to remove it.

I don’t want to hear any other talk about how you can make it less bad, user preferences to address the problem, or any other euphemistic bull 💩 until the featured problem has been removed.

It’s clear that Brave doesn’t have anybody Who understands user interface design on board. The answer to, “we have a usability bug“ is not “we’ve created a separate configuration to help avoid this usability bug“. That is yet another usability problem. Get rid of the featured problem; eradicate it completely from the codebase. You’ll have less code, simpler code, fewer bugs, and you won’t have to deal with special configuration settings to deal with your feature. (I remember a horribly complicated preferences manager for Firefox.)

**Comment by bsclifton** [comment]
@GarrettS your feedback is appreciated and has been passed on to the design team (I'll ask them to respond). As you noticed, I re-opened your original issue since there is a problem and tagged two developers, hoping they'd take a peek at it

If you don't like the feature, why haven't you disabled it yet? We definitely haven't gotten this much negative feedback before about it.  Starting with version 0.22.714, we had some refactorings which increased performance of the browser. Unfortunately, there were some bugs and we're actively trying to find and fix those bugs

We have a new Chromium based UI in the works (Brave Core) and you'll be pleased to know that it does not have tab preview (at least not yet- I created an issue to capture it with https://github.com/brave/brave-browser/issues/275). If this feature is implemented there, maybe it can be an opt-in feature (ex: you have to enable it) instead of being enabled by default

**Comment by GarrettS** [comment]
![image](https://user-images.githubusercontent.com/56098/41255778-80f3af3a-6d7c-11e8-99e6-f7f5f9bb52e6.png)
Wrong document for that tab
