### ISSUE TITLE
Brave does not quit when I hit 'q' or say 'quit' in the menu (OS X, Linux)

### ISSUE THREAD

**Issue by ctrlzjones** [brave/browser-laptop#1449]

**Comment by acosta07** [comment]
Same problem on OSX 10.11.4. When using Brave more than a couple hours it simply doesn't quit. To quit Brave I need to Force Quit.

**Comment by bbondy** [comment]
If anyone finds short steps to reproduce this it would be very helpful to getting a fix.

**Comment by ctrlzjones** [comment]
to reproduce:
open Brave, let it be there +7 hours. try to close it …

other than that, I am not sure what ‘short steps’ you’re asking for ...

**Comment by bbondy** [comment]
Thanks, but specifically I just mean we can get t a fix faster if someone can find a way to reproduce, say within a minute.  We want this fixed too.

**Comment by ctrlzjones** [comment]
I totally understand. 
But for (at least for) me it is what it is … takes hours to happen …

**Comment by acosta07** [comment]
I don't know if it will help or not, but I open Console and after all normal Quit ways doesn't work, console shows too many lines like that:
Brave Helper: CGAffineTransformInvert: singular matrix.

At the moment I try to Quit this lines:
05/05/16 20:54:17,416 Brave[23556]: BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d

05/05/16 21:03:19,000 kernel[0]: process Brave Helper[23600] caught causing excessive wakeups. EXC_RESOURCE supressed due to audio playback

05/05/16 21:17:12,478 bird[863]: LaunchServices: Failed to create bundleProxy for bundle com.electron.brave.helper

![brave-close](https://cloud.githubusercontent.com/assets/19167726/15069805/8e7b4e06-1356-11e6-8e38-347ee6d9a18b.png)

**Comment by luixxiul** [comment]
It does not work with Brave 0.9.5 on Ubuntu 14.04 too.

**Comment by luixxiul** [comment]
It does work on Windows 10.

Isn't it related with https://github.com/brave/browser-laptop/pull/1630#issuecomment-218525130?
> ![](http://i.imgur.com/JbrvmRj.jpg)

**Comment by adrianblynch** [comment]
I'm finding the same on OSX 10.10.5. Brave info:
```
Brave: 0.9.6
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev
```
