### ISSUE TITLE
Support for Picture-in-Picture (macOS)

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#14595]
### Feature Request

A [user on Twitter](https://twitter.com/_adryd/status/1012396020351856640) requested support for [macOS' _picture-in-picture_ feature](https://www.imore.com/how-use-picture-picture-macos-sierra).

![image](https://user-images.githubusercontent.com/815158/42052881-a25f4754-7ad5-11e8-8198-1984259bdf97.png)

This could potentially be handled with an extension.

**Comment by TeoMorabito** [comment]
I would love picture in picture, 
but please NO default use of the media keyboard keys for brave (or at least an option to disable it) I have iTunes music playing in the background most of the time, and use the media keys to control that. I stopped using safari mainly because trying to pause iTunes actually pauses the media played in the browser.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/824
