### ISSUE TITLE
Unable to scroll down bookmarks tab when populated beyond initial display boundry

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-laptop#14606]
**Description**
After updating (0.23.19) users are unable to scroll down a list of bookmarks when the bookmarks tab is open (and populated with enough links to require scrolling)

**Steps to Reproduce**

1. Open Brave
2. Add as many links to bookmarks drop-down tab can display before scrolling (can display ~25 before the need to scroll, correct me if I'm wrong)
3. Add [at least] one more bookmark
4. Actual result:
5. Bookmark is added but no scroll bar displays

**Expected result:**
Scroll bar should appear after 1 or more bookmarks added, allowing you to move down tab to see new additions

**Reproduces how often:**
Always

**Brave Version**

about:brave info:
Despite asking nobody provided their about:brave info, but I was able to reproduce the error so we'll use mine:
Brave: 0.23.19
V8: 6.7.288.46
rev: 178c3fb
Muon: 7.1.3
OS Release: 10.0.16299
Update Channel: Release
OS Architecture: x64
OS Platform: Microsoft Windows
Node.js: 7.9.0
Tor: 0.3.3.7 (git-035a35178c92da94)
Brave Sync: v1.4.2
libchromiumcontent: 67.0.3396.87

**Reproducible on current live release:**
Yes

**Additional Information**
Seems to be a regression as far as I can tell. I was unable to reproduce error one previous release and can produce error 100% on live release.

**Comment by eljuno** [comment]
+1s from community and Discord channel
https://community.brave.com/t/bookmark-toolbar-menus-wont-scroll-after-update/26453?u=eljuno
https://community.brave.com/t/list-of-links-under-a-tab-will-not-scroll-down/26499?u=eljuno

**Comment by eljuno** [comment]
+1 from @defcon1776  via brave/brave-browser#455

**Comment by eljuno** [comment]
+1 from Reddit https://www.reddit.com/r/brave_browser/comments/8viehz/the_favourite_list_is_having_a_scrolling_issue/

**Comment by NejcZdovc** [comment]
+1 from me

**Comment by NejcZdovc** [comment]
This was broken with https://github.com/brave/browser-laptop/commit/681349dddddfcee96dd81f26da20688c86c67019 where `bookmarksToolbarWithFaviconsHeight` was renamed, but it's still use it https://github.com/brave/browser-laptop/blob/master/app/renderer/components/common/contextMenu/contextMenu.js#L325 and because of that we get
![image](https://user-images.githubusercontent.com/9574457/42181580-93422836-7e3b-11e8-8b2d-c3ab444f29e5.png)

cc @bsclifton @petemill

**Comment by petemill** [comment]
@NejcZdovc thanks for the find. This should probably be simply positioned at `bottom: 0` since the 'top' position is already calculated, with an automatic `overflow: scroll`. In order to do that the styles for the context menu containing box should move to the parent. I would make that change if this component were to survive for much longer, but since its time is limited, I will make this simple change, even though it is somewhat flakey and does not cover every scenario (such as notifications or menu bar)

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/voxtis/status/1014591450380562432

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.32 1d1df96
* Muon 7.1.5
* libchromiumcontent 67.0.3396.103

**Comment by kjozwiak** [comment]
+1 from a private PM on community.brave... mentioned that it's been fixed and will be released sometime Monday 👍
