### ISSUE TITLE
Allow for different default search engines based on region

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#14647]
## Original issue description
Brave should use region detection when considering how to set the default search engine (globally and for private tabs)

For example, if I'd like to default to bing.com for Brazil, this should be possible. Currently, the default search is applied regardless of region

The region detection should happen via Node (ex: looking at the computer settings)

**Comment by kjozwiak** [comment]
I couldn't get this working after spending a few hours on it last night using both `Win 10 x64` and `macOS 0.13.6 (17G65) x64`. Quick summary:

**Prerequisites:**

* changed my machines region to `Mexico` and changed the language to `Spanish Mexico (es-MX)`
* created a new Apple ID that belonged to the `Mexico` region, logged in and restarted the machine

<img width="705" alt="captura de pantalla 2018-08-15 a la s 01 01 01" src="https://user-images.githubusercontent.com/2602313/44154213-340c6cd2-a078-11e8-96d6-1ad07696efd3.png">

<img width="812" alt="captura de pantalla 2018-08-15 a la s 00 59 50" src="https://user-images.githubusercontent.com/2602313/44154225-3aac8c52-a078-11e8-9259-b95b07b698e9.png">

Once the above was completed, I double checked and ensured that my machine was using the correcr regions:

```
Kamils-MBP:browser-laptop kjozwiak$ defaults read -g AppleLocale
es_MX
```

```
Kamils-MBP:browser-laptop kjozwiak$ defaults read NSGlobalDomain AppleLanguages
(
    "es-MX"
)
```

I also checked the adblocker in `brave-core` under `chrome://adblock` and noticed that I was automatically using `EeasyList Spanish` which means that the code within `brave-core` is working correctly when it comes to detecting locales, example:

<img width="196" alt="captura de pantalla 2018-08-15 a la s 00 19 56" src="https://user-images.githubusercontent.com/2602313/44154444-bd41ff8a-a078-11e8-80a2-2789814279b2.png">

Using the instructions in https://github.com/brave/browser-laptop/pull/14713, I commented out the required checks under `js/constants/config.js#L49-L50` and built from source using the `0.23.x-release5` branch.

Every time I launched brave, it would select GitHub meaning that Brave still thinks I'm on `en-US`. I ensured I removed the profile on every restart but every time brave was launched, GH was being selected rather than YouTube. After 2-3 hours, I reverted the back to my locale, example:

```
Kamils-MBP:browser-laptop kjozwiak$ defaults read -g AppleLocale
en_CA
```

```
Kamils-MBP:browser-laptop kjozwiak$ defaults read NSGlobalDomain AppleLanguages
(
    "en-CA"
)
```

After reverting back to my original locale, I attempted re-launching brave several times after removing the profile and I still got GitHub rather then Google. From the looks of the code, I should only be getting GitHub on `en-US` which isn't the case as I'm on `en-CA` which should default to Google.

@GeetaSarvadnya and @srirambv weren't able to get this working on Linux/Windows either.

@bsclifton I think we should just move this out for now unless we want to spend the time debugging to figure out what's going on and why it's always using `en-US` and picking GitHub as the default search engine.

**Comment by bsclifton** [comment]
Thanks for digging in, @kjozwiak 😄 I agree - we can move this out

The code (as-is) works fine and shouldn't need to be reverted. Removing milestone

**Comment by bsclifton** [comment]
Needs more investigation

**Comment by kjozwiak** [comment]
@bsclifton let me know if you need anymore help investigating/looking at this!

**Comment by kjozwiak** [comment]
Verified on Ubuntu `18.04 x64` using the following build:

* `0.23.106` 0241c0224c01581f699f4fcba1eca36d2ded3ec3 
* muon: `8.0.10`
* libchromiumcontent: `68.0.3440.84`

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.204 b71d170
* muon 8.1.3
* libchromiumcontent  69.0.3497.81
