### ISSUE TITLE
[hackerone] #374969 - permission prompt with window.open

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14681]
https://hackerone.com/reports/374969

**Comment by diracdeltas** [comment]
Removing sec-high because the prompt doesn't say anything about Google.com asking for permission; I think the only confusing part is that the prompt is scoped to a tab which contains Google.com whereas the permission being requested is not specific to Google.com.

The simple solution is just to move the notification from the tab area to the global notification area so it cannot be associated with any specific origin.

**Comment by srirambv** [comment]
Verified on Ubuntu 18 x64 using
* 0.23.80 53a429f
* Muon	8.0.8
* libchromiumcontent	68.0.3440.84

**Comment by Metnew** [comment]
@tomlowenthal @diracdeltas Could you check/resolve this report on H1?
