### ISSUE TITLE
can load bookmark in tor tab before tor finishes loading

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14680]
## Test plan
See https://github.com/brave/browser-laptop/pull/14709

## Original issue description
STR:
1. open tor tab
2. before Tor is done initializing, click on a bookmarked site in the bookmarks toolbar
3. the site loads

expected result:
the site does not load until tor finishes initializing

**Comment by riastradh-brave** [comment]
Just to be clear: Does this actually load without going through the Tor SOCKS proxy?  If so, what is the mechanism by which it does that?  We can merge #14709 but I would like to fix the root of the problem if there is a path by which in the profile/partition/context of a private tab with Tor we can _ever_ bypass the proxy, ideally at the level of muon, rather than block stuff at a high level in browser-laptop like this.

In particular, if we just haven't processed the notification that tor is online yet, but the request still goes through the Tor SOCKS proxy, I don't think it's really a problem.

**Comment by diracdeltas** [comment]
@riastradh-brave pretty sure it goes through the proxy, so the page loader spins indefinitely

**Comment by riastradh-brave** [comment]
@diracdeltas Oh, so the problem is that the page loader interferes with the Tor progress indicator, not that this is a leak?

**Comment by LaurenWags** [comment]
@diracdeltas @riastradh-brave question on this issue, the expected result seems to be “these loads should be blocked until tor finishes initializing”. In the terminal I see `Blocking page load until Tor tab is initialized` and nothing happens on the UI. Even after Tor is loaded, I have to click on the bookmark or home button again to get the page to load. Just want to confirm this is expected.

**Comment by diracdeltas** [comment]
@riastradh-brave i thought it was a leak when i first opened it but then i couldn't repro it. 🤷‍♀️

**Comment by diracdeltas** [comment]
@LaurenWags that's expected - the PR does nothing to retry the page load. it just blcoks it.

**Comment by LaurenWags** [comment]
great, thanks for the confirmation @diracdeltas! :+1:

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.33 f3426e8
* Muon 7.1.5
* libchromiumcontent 67.0.3396.103
