### ISSUE TITLE
Recover your Brave BAT wallet failed

### ISSUE THREAD

**Issue by crrobinson14** [brave/browser-laptop#14733]
### Description

I was in the process of transferring my Brave wallet to a new computer. I'm not sure the version on the old computer, the new version is 0.23.31. I used the Backup your wallet function, which produced a text file with two recovery keys. I transferred this file to the new computer, but the Recover your wallet function says Recovery failed: please re-enter keys or try different keys.

On the old computer I noticed an update to the browser was available. Perhaps the backup/recovery process was changed. So I upgraded it, thinking to re-backup the wallet. But THIS time when going into the payment settings my wallet is gone on the OLD computer too!

Ironically I was telling a colleague how smooth this all was at the time, so I have screen shots of the process including my address if that's helpful at all, but didn't want to paste them here in case that was a bad idea.

### Steps to Reproduce

  1. Older version -> Settings -> Payments -> Advanced -> Backup your wallet.
  2. Transfer this file to new computer with 0.23.31 installed.
  3. New version -> Settings -> Payments -> Advanced -> Recover your wallet.
  4. Select the file produced from step 1 above. Receive this error.
  5. Old computer, receive "update available". Upgrade the browser.
  6. Old computer -> Settings -> Payments [OMG WALLET IS GONE HERE NOW].

$125 wallet lost in this process. This is make or break for trust in a system like this. What is the expected next step if Brave refuses to accept the recovery keys produced by an older version?

**Comment by LaurenWags** [comment]
@crrobinson14 all versions after 0.18.x (I *think* versions after 0.18.36 specifically) use the new recovery format. This changed when we switched from BTC to BAT wallets which you can read about here: https://brave.com/bat-mercury-launch/ . In this blog post you'll notice that anyone using the Bitcoin proof of concept wallet (the two recovery keys you mention) will have their BTC converted to BAT. Since this was in October of least year, earlier this year we stopped the automatic conversion of BTC to BAT. What this means is that you need to work with someone on the Brave team (I can help! 👋 ) to do this process manually. So, shoot me an email (I'm lauren [at] brave [dot] com ) and we can get this rolling.
