### ISSUE TITLE
What is the difference between brave-browser and brave-laptop?

### ISSUE THREAD

**Issue by givanse** [brave/browser-laptop#14756]
Mainly asking to know where to report bugs.

**Comment by srirambv** [comment]
browser-laptop is the repo where you need to report issues for current release builds. brave-browser is still in works and if you are building that from source and running then report the issues in that repo. For all other issues it needs to be reported here. 

Closing the issue but feel free to respond here

**Comment by NumDeP** [comment]
I don't know whether you've checked out their [blog](https://brave.com/development-plans-for-upcoming-release/) already @givanse but they're moving away from their fork of Electron (Moun) to Chromium and I believe the place is brave-core for that which they'll be working on in the long run and coherently to make the switch seamless in the coming months.

I think brave-browser is related to the new brave-core and brave-laptop is related to the current, temporary, soon to be deprecated moun.

I've been hesitant asking the same question for a while because it was confusing at first why they still have the browser-laptop still open. I feel bad the team putting so much effort into fixing bugs and enhancing along the way when they know they're going to deprecate it soon.

**Comment by NumDeP** [comment]
Sorry @srirambv I had the comment open but didn't save before you commented.

**Comment by srirambv** [comment]
>Firstly, will you be removing brave-laptop after v1.0 because I'm assuming we should soon after report all the common bugs at brave-browser?
>
>Secondly, does it matter where the payment / ledger issues are reported (in b-laptop or b-browser) because that is a client in and of itself, isn't it, which will be exactly the same in brave-core?

cc: @bsclifton for more info

**Comment by bsclifton** [comment]
Hi there folks,

Right now, this is the right place to log bugs 😄 
https://github.com/brave/browser-laptop/issues

When we switch over to Brave Core (which will happen in the next few months), bugs would then be reported at https://github.com/brave/brave-browser/issues

The way you can tell? Visit about:brave and click the `rev` link:
![screen shot 2018-07-22 at 12 59 51 am](https://user-images.githubusercontent.com/4733304/43043544-9c755996-8d4a-11e8-9f78-fc9057eca569.png)

For my current browser, this takes me to:
https://github.com/brave/browser-laptop/commit/3ee14b026f09d7d71c1985b4a9c9a11d78ab8f49

Based on the URL, we can see that `browser-laptop` is the current repository.  This process could definitely be easier!
