### ISSUE TITLE
Decide about strict site isolation by default

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14766]
C68 enables strict site isolation by default.  We should consider following suit, but proceed carefully because it apparently breaks a lot of sites, e.g. the Cloudflare captcha as in #14765.

**Comment by diracdeltas** [comment]
i'm in favor of enabling it by default given that c67 enabled it for 99% of users

however i'm curious whether we are experiencing more site breakage than chrome for some reason

**Comment by NumDeP** [comment]
Would it help to understand which sites break? 

I've starting noticing it recently but didn't realize that a couple of sites with video content didn't function at all because of strict isolation. Anticipating v1.0 I just figured it was a Moun bug and not point reporting. 

One other thing, for the benefit of other users, wouldn't enabling this by default annoy the hell out of Macintosh-laptop users even more so on top of the current energy/cpu issues considering it uses at least a 100MB more memory.

**Comment by diracdeltas** [comment]
@NumDeP that's helpful. it also helps to know which of those sites work in Chrome with site isolation enabled.

**Comment by Liunkae** [comment]
List of Brave issues caused by strict site isolation: #12907

**Comment by bsclifton** [comment]
Closing as `wontfix` - we won't be changing this default with Muon as there are a large number of issues caused (thanks for the link, @Liunkae). [brave-core](https://github.com/brave/brave-browser) should be using this by default (since Chromium 68)
