### ISSUE TITLE
False Positive on Canvas Fingerprinting Protection?

### ISSUE THREAD

**Issue by mlhaufe** [brave/browser-laptop#14773]
I created a simple <canvas/> demo a number of years ago. I noticed today that Brave prevents this from working by flagging it under Fingerprinting. I believe this is a false positive, but would like to know what aspect of this triggers the blocking.

https://thenewobjective.com/demos/water.html

### Brave Version

Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Comment by bsclifton** [comment]
@mlhaufe it gets blocked with `Block all fingerprinting` because it creates a canvas (which could be used for fingerprinting). If you click the lion icon and then click the fingerprinting methods blocked number, it'll show why it was blocked:
![screen shot 2018-07-23 at 1 12 57 pm](https://user-images.githubusercontent.com/4733304/43100466-484ded48-8e7a-11e8-9d23-64f92521d026.png)

You can read more here:
https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode
