### ISSUE TITLE
Buttons doesn't change to Primary button when clicked

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14827]
### Description
Clicking Send and then clicking other buttons doesn't highlight it correctly 

### Steps to Reproduce
  1. Build from #14734 
  2. Enable ethwallet
  3. Click on Contracts, button is a primary button
  4. Click on Wallets, button is a primary button (orange)
  5. Click on Send, Click on Wallet, button is primary button
  6. Click on Wallets, click on Send, Click on Contracts, Contract button is secondary button(Secondary) should be primary button
  7. Click on Fund Brave Wallet,  Send button becomes primary button

**Actual result:**
![button highlight](https://user-images.githubusercontent.com/17010094/43155728-247738a8-8f46-11e8-89eb-376a38b04658.gif)

**Expected result:**
Selected button should switch to primary button

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
ac4c649

**Reproducible on current live release:**
N/A

**Comment by btlechowski** [comment]
Issue is only reproducible without any wallets. If a wallet is created, the issue does not occur.

**Comment by kjozwiak** [comment]
@tomlowenthal I managed to reproduce this using `0.25.0` aff1a96c4b130d7e878446820ded477b469f0609 which is on `master`. As @btlechowski mentioned above, it only happens when there's no wallets created and you can reproduce this by quickly pressing the buttons before you're prompted to create a master password. Example:

![ethselection](https://user-images.githubusercontent.com/2602313/44166662-f07d8b00-a099-11e8-9f3b-997bc7c2e68a.gif)

We would solve this issue if we lock the entire UI and don't allow any user interactions until either the master password is created or a password is inserted when a user revisits `about:preferences#ethwallet`.

**Comment by Slava** [comment]
This should no longer happen since we always create at least one wallet when the feature is used first time
