### ISSUE TITLE
Hide operating system in user-agent with fingerprinting protection enabled

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14852]
Currently Brave's user-agent string always reports the true operating system under which it is running.  This partitions the anonymity set of users by operating system.  When fingerprinting protection is enabled, it should always report the same user-agent string, including the same operating system, for everyone.  For comparison, the Tor Browser always reports Windows and the Firefox ESR version on which it is based: `Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0`

To resolve this issue, we must first decide what colour to paint this bike shed, of course.  @flamsmark has opened the discussion by suggesting we paint it GNU/Hurd.

**Comment by ciampolo** [comment]
> When fingerprinting protection is enabled, it should always report the same user-agent string, including the same operating system, for everyone. For comparison, the Tor Browser always reports Windows and the Firefox ESR version on which it is based: 

Do you (or @flamsmark , your so called security/privacy coordinator) really not understand that this provides MORE entropy? There is a reason why Tor can do this but why non-Tor Browsers CANNOT.
But let me guess uniquely identifing the users is is an objective of Brave Software (or at least its investors). 

Also using Tor connections outside of Tor Browser inside a Browser that is specifically easy to fingerprint. Is Brendan Eichs main investor the NSA/GHCQ or some big data broker or what?

If some of the devs here are really clueless why I am so butthurt: This and many other concepts (including the other issue I opened) are very easy concepts that are done right in Firefox but are done the most dumbest way possible (ie the way that provides the most entropy for the advertiser) in Brave. Not even proprietary Google Chrome provide that much entropy... I highly doubt that the devs of an entire project (including a guy that calls himself security/privacy coordinator) are all that incompetent.

**Comment by bsclifton** [comment]
Hi there @ciampolo

This is an issue tracking a feature request. It's not something we're even committed to doing and it's open for discussion 😄 Thanks for noticing it and providing your feedback

That said, can you please leave the personal attacks out of your comments? I understand where you're coming from, but making comments like that doesn't do anyone any good. Let's keep the discussion on-topic please

**Comment by riastradh-brave** [comment]
If Windows and Mac users report different user-agent strings, then the advertisers and NSA/GCHQ and anyone else watching can distinguish Windows and Mac users simply by looking at the user-agent strings.

If Windows and Mac users all report that they are using GNU/Hurd, then the advertisers and NSA/GCHQ and anyone else watching has to try harder to tell who's using Windows and who's using a Mac.

Forcing them to try harder is what fingerprinting protection does.

If you want to phrase it in terms of entropy, suppose a web server doesn't know _a priori_ whether a user is a Windows or Mac user.  If there is a nonzero probability that the user-agent string reports Windows and a nonzero probability that the user-agent string reports Mac, then the user-agent string has positive entropy.  If, on the other hand, there is a 100% chance that the user-agent string says GNU/Hurd, then the user-agent string has zero entropy.

(The entropy of a probability distribution is the sum of -P(x) log P(x) for each possibility x, where P(x) is the probability of the possibility x.  When there is only one possibility, say GNU/Hurd, P(GNU/Hurd) = 1 and log P(GNU/Hurd) = 0 so the entropy is -P(GNU/Hurd) log P(GNU/Hurd) = -1*0 = 0.)

**Comment by riastradh-brave** [comment]
Migrated to https://github.com/brave/brave-browser/issues/701.

**Comment by ciampolo** [comment]
@bsclifton 
I am sorry for my attitude but you have to understand I opened an issue months back about how easy it is to fingerprint and track Brave users aroudn the web. And that issue got pretty much ignored. I mean imagine a Browser that advertises itself as "Fast/Private/Secure" and fails on all of those lines miserably. I am a sole private end user and it can't be that people hired for money have less clue on their own subject being payed for than me. Especially since those aren't hard concepts to grasp meaning I have to assume Brave being a high level scam. If not please convince me otherwise.

As to why this issue specifically is beyond ridicolous: If you ping a server that server knows instantly your OS and can guess your OS version. Networking stacks are impleneted differently in Linux, BSD (Darwin), Windows. Just b y pinging a server that server knows your OS. Now imagine what happens if a BSD, Linux or Windows user goes to an website with a "Hurd user agent".. Not that hard to imagine right?

Do you get my point why I am so frustrated with Brave? Do you understand why to me it seems like a literal Scam, a way for Brendan Eich to return money/private data to investors and abuse the users?

I just would love to know why Brave developers keep advertising it as "Private Browser" etc. while it does the exact opposite. Brave is the browser with the highest entropy on the market. You guys seemingly just ignore some entropy values again putting me to think this is a scam. If I am wrong with anything I said please enlighten me.

Also to add I am especially frustrated since Firefox jumped so far ahead with v60 in terms of fingerprinting protection/tracking protection etc.. Just the container isolation coupled with privacy.ResistFingerprinting protects against more than any other Browser (specifically Brave) could ever imagine. 

Just the sole fact that a stock Chrome on stock Windows 10 is harder to uniquely identify than stock Brave on stock Windows 10 shows it all doesn't it?

**Comment by bsclifton** [comment]
@ciampolo I'm not an expert in fingerprinting or associated tech, so I can't answer your questions

I understand the frustration, but let's try to capture tangible things which can be addressed

- Is stock Chrome on stock Windows 10 harder to identify than stock Brave on stock Windows 10? You say it's a fact, but it would be good if you can add to the conversation why you believe this is the case
- You claim there is a high amount of entropy in the browser which makes Brave users susceptible to fingerprinting. Do you have examples of this? 
- Can you please link to your original issue (the one you mention was ignored)?

All of the code for Brave (and its infrastructure) is on GitHub. There's nothing to hide. Did we (paid employees and unpaid contributors who submit pull requests) miss anything? Probably. We have a Would we address those issues if they were captured somewhere? Absolutely

Can you capture your specific concerns (minus the opinions) in issues in the brave-core issue log? 
https://github.com/brave/brave-browser/issues/

You can also report these via our hackerone (where you'd be eligible for a paid bounty)
https://hackerone.com/brave

Again, let's keep the developer/company/product bashing out of here. We'd love to understand more of your concerns... but please realize we're a small group of folks and there are over 2,400 issues in the backlog
