### ISSUE TITLE
permission prompt strings need to be localized

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1493]
https://github.com/brave/browser-laptop/pull/1484/files/ab22e9fce12e1e4babd23b589fe82249dd9ca453#r61201771

**Comment by cezaraugusto** [comment]
Hi @diracdeltas. IIUC @bbondy's comments on the referenced PR, the best way to get it done is to create a function which returns an array of located strings, since `rendererIdentifiers` seems to be only for top and context menus, and then reference it on the `action` inside `registerPermissionHandler` (filtering.js)?

**Comment by diracdeltas** [comment]
i think @aekeus is fixing this already, actually. sorry!

**Comment by aekeus** [comment]
Yes. The permission strings have been localized in PR 1919.

**Comment by luixxiul** [comment]
It is still not enough. Please have a look at #2540

**Comment by luixxiul** [comment]
I think #2612 will make the permission prompt localized finally :)
