### ISSUE TITLE
Actual Size Keyboard Shortcut "Ctrl+0" not working with Keypad

### ISSUE THREAD

**Issue by iowbeoibewio** [brave/browser-laptop#15021]
Have you searched for similar issues?  Yes, find nothing

Description
When You Zoom In "Ctrl+Plus" or Zoom Out "Ctrl+-" in any page with keyboard that have a side keypad is working fine (by clicking + or - in keypad), but when you try to Actual Size "Ctrl+0" with keypad is not working, but with numbers in same keyboard is working fine.

Steps to Reproduce
  1. try to zoom in "Ctrl+Plus" in any page with keypad
  2. try to Actual Size "Ctrl+0" and be sure to press "zero" in keypad, won't work
  3. try to Actual Size "Ctrl+0" and be sure to press "zero" is in keyboard numbers, working fine!

**Actual result:**
Nothing happen

**Expected result:**
work and set page to actual size 100%

Brave Version

Brave: 0.23.79 
V8: 6.8.275.24 
rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
Muon: 8.0.7 
OS Release: 10.0.14393 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

Additional Information
Chrome and firefox working fine with Ctrl+0 in keypad, didn't try other browsers

**Comment by bsclifton** [comment]
Duplicate of https://github.com/brave/browser-laptop/issues/4815 (which was closed as stale)

This will be fixed with [brave-core](https://github.com/brave/brave-browser) 😄 The problem was upstream if I remember correctly. Since we won't be using Muon anymore, this is fixed (I verified on latest version of brave-core)
