### ISSUE TITLE
GNU/Linux Xubuntu (xfce) no brave icon on taskbar

### ISSUE THREAD

**Issue by crysman** [brave/browser-laptop#15149]
### GNU/Linux Xubuntu (xfce) - there is no brave icon on taskbar, just a simple window icon like this: 
![image](https://user-images.githubusercontent.com/5269350/45034992-30aca980-b059-11e8-8a28-456af7f0b1a8.png)

### Steps to Reproduce

  1. run Brave (from menu or terminal, does not matter)
  2. see the icon - it is not correct Brave icon

### Version
Brave | 0.23.105
V8 | 6.8.275.24
Xubuntu 18.04.1

### Additional info
see this:
```
❱ cat /usr/share/applications/brave.desktop 
[Desktop Entry]
Name=Brave
Comment=Brave laptop and desktop browser
GenericName=Web Browser
Exec=sh -c "brave --user-data-dir-name=brave -- %U"
Icon=brave
Type=Application
StartupNotify=true
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
```

- it is actually running "sh", not Brave - that might be the problem (?) ...
...BUT when you run it from terminal directly (`brave`) - same result :(
debug info:
```
❱ which brave
/usr/bin/brave
```

**Comment by crysman** [comment]
@bsclifton > please, provide some more info. Why closed as wontfix? I know it's detail, but very annoying. Moreover, Brave is the ONLY application I've ever experienced on Xubuntu (since 13.10) having a wrong taskbar icon...

**Comment by bsclifton** [comment]
@crysman we're winding down development on the `browser-laptop` repo in favor of our new code-base (`brave-core`) which you can download / try out now if you'd like. We're getting close to a beta stage with it and then it will eventually replace what we have now on the release channel

With this new version, the issue should be fixed. With the `browser-laptop` code-base, I don't think we'll be able to address this because resource-wise, we're limited

The install guide for the new version is here:
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

**Comment by crysman** [comment]
Understood, thanks.
When you think @bsclifton the new brave-core will then be part of official Ubuntu/Debian repos?
