### ISSUE TITLE
Presearch in the list of search engines

### ISSUE THREAD

**Issue by MrAcalf** [brave/browser-laptop#15167]
### Description
I want use https://presearch.org/ as standard search because it pay me 0.25 for each search.

### Steps to Reproduce
I would like to search in the address bar and that my search had the search as search pattern

  1. Write the subject to be searched
  2. Start the search using https://www.presearch.org/search?term=%s as standard
  3. Receive the results and earn 0.25 PRE

**Actual result:**
I cannot add new search engines into brave search list

**Expected result:**

To be allowed to use presearch

### Brave Version
 
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 0.23.105dev 
Muon: 8.0.9 
OS Release: 4.14.67-1-MANJARO 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Comment by bsclifton** [comment]
Thanks for the report @MrAcalf! This problem is fixed in our developer channel if you wanted to give that a try (it's still in an experimental state, but we'll be moving to beta and then release channel soon enough).  You can download it here:
https://brave.com/download-dev

In this new build, you can open settings and go to `Manage search engines`. You'll be able to add any that you'd like (pages you visit will detect engines with OpenSearch and automatically add them under `Other search engines`)
![screen shot 2018-09-06 at 10 25 21 pm](https://user-images.githubusercontent.com/4733304/45200075-f0e5ed80-b223-11e8-9929-8f469a5cece6.png)
