### ISSUE TITLE
Spotify Web Player not working.

### ISSUE THREAD

**Issue by PhilMarlin** [brave/browser-laptop#15339]
This stopped working as of the Chromium update.

![](https://user-images.githubusercontent.com/13716824/47889847-f63a6f80-de43-11e8-9bb0-3d7cf99d1b53.png)

**Comment by bsclifton** [comment]
@PhilMarlin you're using the new version of Brave (this repo is for the old Muon version)

I think the root cause may be that Widevine is not enabled. You might try visiting https://netflix.com or https://hulu.com and looking for a puzzle piece in the right side of the omnibar (the URL bar). You can then click it to opt in to enabling Widevine.  We have an issue captured to make this more obvious, which you can track here:
https://github.com/brave/brave-browser/issues/1940
