### ISSUE TITLE
Make Code of Conduct

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1771]
In preparation for troubles...

eg: https://github.com/ampproject/amphtml/blob/master/CODE_OF_CONDUCT.md

**Comment by SJ-Diamond** [comment]
Shouldn't it be logically that no one should be harassed or discriminated? I really find that "code of conduct" thing totally confusing, for something which is, already logical enough.

**Comment by Anon66** [comment]
How about these:
https://github.com/domgetter/NCoC/blob/master/CODE_OF_CONDUCT.md
https://github.com/domgetter/NCoC

**Comment by SJ-Diamond** [comment]
Wouldn't it be also insulting to create a certain feature which one user group could understand but another one not? The only product which fits all because it is so simple is Google Chrome itself.

I really believe that a code of conduct only opens the door for massive abuse and could backfire against the planned ideas/visions and is not actually as protecting as one may hope that it is.

**Comment by luixxiul** [comment]
Closing for now. Please do understand I just opened the issue for a discussion and was not familiar with the ongoing controversy around it in English-spoken communities.
