### ISSUE TITLE
Back button stops working

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#180]
STR: not sure what I did to cause this
Video shows back button not working as i go to 3-4 different links

**Comment by jiangyang** [comment]
Run into this too. The console error points to `this.activeFrame.goBack()` where `this.activeFrame` is `undefined`, same for the forward button. One way to repro is to open 2 tabs, clicks to close one of the tabs and the remaining tab's back/forward would break.

The reason seems to be that clicking the tab close button also triggers the tab to be set active so eventually the closed tab is set to active. Attempted a fix here https://github.com/brave/browser-laptop/pull/222
