### ISSUE TITLE
about: pages fail load in private tabs

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1817]
started happening today or yesterday

**Comment by diracdeltas** [comment]
actually looks like any `about:` page in a private tab will just redirect to `about:error`. @bridiver thoughts?

**Comment by bridiver** [comment]
opening a private tab triggers a did-fail-load event with for addressUnreachable (-109). Not sure why

**Comment by bridiver** [comment]
it's really only failing the provision load, but electron fires did-fail-load and did-fail-provisional-load in that method. I'm not sure why it only happens with private tabs, but I have a workaround until we can figure it out.

**Comment by bridiver** [comment]
maybe not. The workaround still doesn't actually load the page for about:preferences and other non-blank pages

**Comment by bridiver** [comment]
This is actually not a new issue, we just never noticed that the page didn't actually load. Trying to view about:preferences in a private tab results in a blank page. It probably doesn't make sense to view about pages (other than newtab) in a private session because they don't have their own set of persistent preferences, bookmarks, etc... The workaround I have will at least show newtab instead of error, but I think we should open other about:* pages in a new tab if the url is manually entered into a private tab. about:certerror will also display a blank error page in a private tab.

**Comment by bbondy** [comment]
Moving t 0.10.1 since there's as workaround

**Comment by diracdeltas** [comment]
> The workaround I have will at least show newtab instead of error, but I think we should open other about:* pages in a new tab if the url is manually entered into a private tab. about:certerror will also display a blank error page in a private tab.

Thanks @bridiver. I believe at least the following pages should be displayable in a private tab:
* about:blank (needed for X-XSS-Protection block mode, and maybe some site functionality)
* about:newtab
* about:certerror
* about:error
* about: safebrowsing

In FF, all the about:about pages are displayable in a private window. In Chrome, at least settings, history, and bookmarks (but not downloads) open in a regular window if you try to open them in incognito mode.

**Comment by bbondy** [comment]
Moving t 0.10.5 for now.

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/commit/cc51723258d4fb9a3115a656e66595985cacb0bc

Was due to incognito manifest setting of spanning not allowing main frame url loads.
