### ISSUE TITLE
Implement sync

### ISSUE THREAD

**Issue by scottstensland** [brave/browser-laptop#1854]
Does Brave support sync ?       linux  Brave: 0.10.0 

I see sync mentioned in your code base yet sync does not appear in Preferences

**Comment by bbondy** [comment]
sync is still pending. See the wiki on this repo for the development roadmap timeline.
https://github.com/brave/browser-laptop/wiki/Brave-Development-Timeline
We can leave this open t track Sync though :)

**Comment by pedro7** [comment]
According to the [Development Timeline, sync has been postponed to at least after 08/26/16](https://github.com/brave/browser-laptop/wiki/Brave-Development-Timeline#082616).

People that:

1. don't use password managers integrated with browsers (such as: KeepassX, SpiderOak Encryptr, maybe: Keepass);
2. rely on the browser sync to login on websites on mobile (because they still use complicated passwords generated by KeepassX for example).

won't be able to fully migrate Brave because they have big generated passwords and don't want to copy and paste them all on Android.

Granted, this is probably not many people.

**Comment by midi** [comment]
I'm not sure I read the timeline correctly.
Is the plan to have sync between iOS and MacOS for example be live in 1.0?
(Looking to switch from Firefox, this is essential for me)

**Comment by pedro7** [comment]
I don't know. I've decided to wait until 2017 before I consider again migration to Brave.

**Comment by bricep** [comment]
Where do we stand on sync?

**Comment by Liunkae** [comment]
Based on the branch called `syncing-0.13.1` (https://github.com/brave/browser-laptop/tree/feature/syncing-0.13.1), I assume sync will be released in version 0.13.1. That's two versions from now (and probably in a month or two away).

**Comment by HLFH** [comment]
I hope the sync feature on the server side could be selfhosted like the outdated Firefox Sync.

**Comment by bsclifton** [comment]
Moving to 0.13.3...  If merge conflicts can be sorted out we may be able to include some backend code with 0.13.2

**Comment by diracdeltas** [comment]
There are currently no merge conflicts.

**Comment by pedro7** [comment]
Can someone confirm sync has been delayed?

**Comment by luixxiul** [comment]
@diracdeltas @ayumi On the first post please add links to the PRs which have additional test plans if any, for example, #6625. Thanks!
