### ISSUE TITLE
Tab cycling order needs to update when tab is pinned

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#1983]
**Describe the issue you encountered:**
When I converted a tab to a pinned tab, using allt/cmd-tab to cycle among them treated it as if it were in its original unpinned position.

**Expected behavior:**
Pinned tabs should move to the first tabs in the cycling order (when starting from the leftmost tab)

- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows 10 and OS X

- Brave Version:
Brave: 0.10.0
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

- Steps to reproduce:
    1. Pin tab among a group of tabs. Tab shifts left to the pinned area
    2. Use cmd-tab to cycle among tabs

Related #149

**Comment by bradleyrichter** [comment]
I think this is related: (see lonely pinned tabs)

![image](https://cloud.githubusercontent.com/assets/13509546/15654130/66d4c65e-2646-11e6-9943-85aaaf84ffb0.png)

In this case, the tab set should have collapsed to the first set, not stay on an empty #2 set.

Pinned tabs need a different rule set (or more rules) so that they don't intervene with the normal expected tab behaviors.
