### ISSUE TITLE
File extensions not auto added to some downloads

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1985]
I have a user report from support that file extensions are not being added for downloaded files.  The user says they have to guess the file extension so the file gets saved.

**Comment by luixxiul** [comment]
Actually extensions are added automatically when downloading, but they are cleared if you change the file name of it.

STR: 

1. On Windows.
1. Download a file with the default file name -> extension is added automatically
2. Download a file, changing the file name -> default extension is cleared and you have to guess which file type it is.

I think this is a windows-only issue, which I think annoys a lot of users.

**Comment by Attrash-Islam** [comment]
+1

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/no-automatic-extension-when-downloading-document/3563/2

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/graphics-and-images-download-file-type/3856)

**Comment by luixxiul** [comment]
+1 from https://community.brave.com/t/issue-with-picture-downloads-not-saving-as-jpeg-png-etc/6117/2?u=suguru

**Comment by jonathansampson** [comment]
This issue is indeed limited to Windows, and also affects the _Save Page as…_ option.

I suspect the issue here is with the prompt receiving little more than a filename ([source](https://github.com/brave/muon/blob/57ecc85913296dc29d6bce708aba77018884e9bc/atom/browser/api/atom_api_web_contents.cc#L1515,L1527)).

```cpp
void WebContents::DownloadURL(const GURL& url, bool prompt_for_location) {
  auto browser_context = web_contents()->GetBrowserContext();
  auto download_manager = content::BrowserContext::GetDownloadManager(browser_context);
  auto params = content::DownloadUrlParameters::CreateForWebContentsMainFrame(web_contents(), url);
  if (prompt_for_location)
    params->set_prompt(prompt_for_location);
  download_manager->DownloadUrl(std::move(params));
}
```

In Brave, this results in a _All Files_ dialog, whereas Chrome filters on the extension. Note the different values for _Save as type_ in both of the screenshots below.

![image](https://user-images.githubusercontent.com/815158/29785693-26c22fde-8bee-11e7-8e75-a19f1e22b3b0.png)

![image](https://user-images.githubusercontent.com/815158/29785706-2fd33afa-8bee-11e7-8664-d86f5b210989.png)

If you replace the filename in Brave, you have no way of telling what the proper extension ought to be. In Chrome, the extension will be enforced by the _Save as type_ option, even if the new filename lacks an extension.

macOS pre-selects the filename up to, but not including, the extension. This reduces the likelihood that the user will unintentionally mess up the extension.

![image](https://user-images.githubusercontent.com/815158/29786004-2a6b1a50-8bef-11e7-9fb0-63afd0090859.png)

A `showSaveDialog` method is [defined](https://github.com/electron/electron/blob/66a5ac4d67a046004d3e6d8b1847733aa6b29108/docs/api/dialog.md#dialogshowsavedialogbrowserwindow-options-callback) in Electron, and [preserved in Muon](https://github.com/brave/muon/blob/c193923dffae55ef67aa86b11c4dfe3191364c0c/atom/browser/ui/file_dialog_win.cc#L241,L255), that we might prefer. This method accepts a `filters` argument, allowing the _Save As_ dialog to focus exclusively on particular file types. Presumably, this is more than just a way to filter what is shown, but to enforce what can be saved.

**Comment by jonathansampson** [comment]
Adding this to 0.20.x under the assumption that it's fairly straight-forward to use an alternative approach that supports explicit filter lists. If this isn't as straight-forward, please feel free to bump to another milestone.

**Comment by bsclifton** [comment]
When investigating this, it might be good to check this out: https://github.com/electron/electron/issues/10121

**Comment by luixxiul** [comment]
@zentagonist Is this not a proper STR? https://github.com/brave/browser-laptop/issues/1985#issuecomment-250883580

**Comment by darkdh** [comment]
@bsclifton , the long term solution will be this **https://github.com/brave/muon/issues/242**
And I made some progress on it.

**Comment by jonathansampson** [comment]
+1 from Twitter: https://twitter.com/meta_gear/status/945817220944363522:

> _@brave Why does the browser not save files with their proper extensions? When I save an image it's just a generic file, not a .jpg or .png or whatever_

**Comment by jonathansampson** [comment]
@darkdh I was just checking out that PR :) Any idea when that will be merged?

**Comment by darkdh** [comment]
It requires https://github.com/brave/muon/pull/385 to be merged first. Muon PR is currently under reviewed

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/emacosc/status/953217720878796800

**Comment by bsclifton** [comment]
+1 from @bravefan via https://github.com/brave/browser-laptop/issues/12878

**Comment by srirambv** [comment]
Blocked on #13230 #13228

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍
