### ISSUE TITLE
Brave Password Manager Inserts the Wrong Password When Using Multiple Accounts on Gmail.

### ISSUE THREAD

**Issue by vannevar-morgan** [brave/browser-laptop#2001]
**Did you search for similar issues before submitting this one?**
Yes, couldn't find any prior description of this issue or similar.

**Describe the issue you encountered:**
When using the Brave password manager to manage two accounts on gmail, the Brave password manager inserts the password for the first account when logging into the second account.  Obviously the login fails if the passwords are different.  

I haven't tested on sites other than gmail.
I haven't tested with more than 2 gmail accounts.
I haven't tested with the 1Password or Dashlane managers.

To be more specific, note that this happens when a first account is managed by Brave Password Manager, and attempting to login with a second account (entering the 2nd username and password on the gmail login), upon clicking 'Sign In' the password for the first account is inserted regardless of whether a password is already entered.  If I allow Brave Password Manager to manage the 2nd account, the password retained for the 2nd account is the same password as the 1st account.

I can still login to any personal gmail account by not managing passwords with Brave Password Manager.

**Expected behavior:**
Passwords for different accounts on the same site should not interfere with each other.  Brave Password Manager shouldn't insert the password of the first account for the second account.  Password retained for the 2nd account should be the password for the 2nd account, not the password for the 1st account.  This should be the behaviour for an arbitrary number of accounts on the same site.
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Ubuntu 14.04
- Brave Version:
  Brave: 0.10.0
  Electron: 0.37.8
  libchromiumcontent: 50.0.2661.102
  V8: 5.0.71.48
  Node.js: 5.10.0
  Update channel: dev
- Steps to reproduce:
  1.  Allow Brave Password Manager to manage a 1st account on gmail.
  2.  Sign out of gmail.
  3.  Enter login information for a different account (with a different password)
  4.  Click "Sign In" on the gmail login page.
- Screenshot if needed:
  N/A
- Any related issues:
  N/A

**Comment by cezaraugusto** [comment]
Hi @vannevar-morgan thanks for reporting it.

Could you tell me if this issue persists with the current (0.10.3) version?

**Comment by vannevar-morgan** [comment]
Hi @cezaraugusto yes I just tested and the issue persists in version 0.10.3

Cheers,

**Comment by deputt** [comment]
It happens on other sites as well when trying to sign in using different accounts, such as twitter.com. I'm using Brave 0.12.5 (in Linux Mint 18).

**Comment by cezaraugusto** [comment]
Related #2829, #1323

**Comment by bkarlan** [comment]
My thread was closed with no answer and just a reference to this thread, which apparently, has no answer.

**Comment by bsclifton** [comment]
@bkarlan apologies for the other issue being closed without a solution

While we do know this issue exists (and it's happened to me several times), we haven't found consistent steps to reproduce.  If there are more clues or steps which can help, that information would be very much appreciated :smile: 

I'm curious (and you don't have to respond unless you're comfortable), do both accounts have the same password? If so, I wonder if that is related to the root cause

**Comment by bkarlan** [comment]
Yes, two of the accounts have the same password.

On Nov 7, 2016, at 4:15 PM, Brian Clifton <notifications@github.com<mailto:notifications@github.com>> wrote:


@bkarlan<https://github.com/bkarlan> apologies for the other issue being closed without a solution

While we do know this issue exists (and it's happened to me several times), we haven't found consistent steps to reproduce. If there are more clues or steps which can help, that information would be very much appreciated 😄

I'm curious (and you don't have to respond unless you're comfortable), do both accounts have the same password? If so, I wonder if that is related to the root cause

**Comment by Wagsworld** [comment]
I'm having this problem also have two gmail accounts. Similar address (wagsworld@gmail and wagsworld2@gmail) different passwords and when trying to sign in the second account it automatically switches to 1st and signs in

**Comment by tfantina** [comment]
I'm having the same problem whenever I try to log into my gmail after my wife logs into hers.

**Comment by deputt** [comment]
I believe the later versions of Brave has solved it, at least for me. I'm also using LastPass to manage my multiple logins.

**Comment by tfantina** [comment]
Haven't used Brave in about a month because of this, just updated and I still can't get into GMail.
