### ISSUE TITLE
Market graph on wsj.com

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2102]
From support: Market graph on wsj.com does not work,

Confirmed on http://www.wsj.com/asia. Disabling Bravery shields does not help. On console:
````
POST http://api.wsj.net/api/michelangelo/timeseries/history?hash=452753711&ckey=57494d5ed7 400 (Bad Request)
asia:1 POST http://api.wsj.net/api/michelangelo/timeseries/history?hash=452753711&ckey=57494d5ed7 400 (Bad Request)
nr-943.min.js:1 Uncaught TypeError: Cannot read property 'api' of undefined
````

**Comment by bbondy** [comment]
This is fixable by calling `cb({})` inside session.webRequest.onBeforeSendHeaders(function (details, cb).
For some reason even if you call `cb({ requestHeaders: details.requestHeaders })` it causes the graph to not show up.   I'm not sure what would be different because of this though.  I guess the callback is causing something else different, maybe like the HTTP Method or something else to also change. cc @diracdeltas @bridiver

**Comment by bridiver** [comment]
fixed by https://github.com/brave/electron/commit/5f11d5304817562ea844b1b27b8c2fde3ddc7e82

**Comment by bbondy** [comment]
mystery solved 👍
