### ISSUE TITLE
Trying to build on Windows 10. Build failed.

### ISSUE THREAD

**Issue by leahnnovash** [brave/browser-laptop#215]
npm run build-win64 failed.
Build error told me to add the content of the debug file to the issue text.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-win64' ]
2 info using npm@2.14.12
3 info using node@v4.2.5
4 verbose run-script [ 'prebuild-win64', 'build-win64', 'postbuild-win64' ]
5 info prebuild-win64 brave@0.7.7
6 info build-win64 brave@0.7.7
7 verbose unsafe-perm in lifecycle true
8 info brave@0.7.7 Failed to exec build-win64 script
9 verbose stack Error: brave@0.7.7 build-win64: `node ./build-win64.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid brave@0.7.7
11 verbose cwd C:\Users\leahnnovash\browser-laptop
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-win64"
14 error node v4.2.5
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error brave@0.7.7 build-win64: `node ./build-win64.js`
17 error Exit status 1
18 error Failed at the brave@0.7.7 build-win64 script 'node ./build-win64.js'.
18 error This is most likely a problem with the brave package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./build-win64.js
18 error You can get their info via:
18 error     npm owner ls brave
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by bbondy** [comment]
Did you do these steps first?
https://github.com/brave/browser-laptop/blob/master/README.md#installation

**Comment by leahnnovash** [comment]
Yes, I did. I have no idea whether they worked correctly, though.

**Comment by j-burt** [comment]
I was able to build using the following steps on Windows 10 (64-bit) Build 10586 (not sure if all options I chose are necessary):

1.  Installed Git-2.7.0-64-bit.exe (choosing "use Git and optional Unix tools...").
2.  Installed node-v5.5.0-x64.msi
3.  Upgraded npm using powershell as admin:
	npm install -g npm-windows-upgrade
	Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
	npm-windows-upgrade
	(choose version 3.6.0)
4.  Install python-2.7.10.amd64.msi (turned on feature "Add python.exe to Path")
5.  Install Visual Studio 2013 community ed. w/ update 5 (used iso vs2013.5_ce_enu.iso)
6.  Ran app "Git CMD" as admin
7.  Since I wanted to beta test I used the:  git clone --depth 1 https://github.com/brave/browser-laptop
8.  Opened the working directory (browser-laptop) with Microsoft Command Prompt as admin and ran command npm install
9.  I also ran the npm run build-win 64, but didn't create the NSIS based installer (wasn't so sure about the certs needed)

**Comment by arthur-peka** [comment]
Dependencies (such as Python) should be specified in build instructions I think.

**Comment by bbondy** [comment]
Thanks for the steps.
@PFCKrutonium is adding a prerequisites file and linking it from the readme for Windows, see the work so far here:
https://github.com/brave/browser-laptop/pull/288
Closing this since that pull request should take care of it once he's done.
