### ISSUE TITLE
Vertical tabs

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2185]
Moving `<TabsToolbar>` inside of the `.mainContainer` in main.js makes it possible to get the vertical bar as follows (with some quite simple css tweaks). Here's a rough idea:

![](https://cloud.githubusercontent.com/assets/3362943/16044662/537c25a2-3280-11e6-9c84-edf41acd88bb.jpg)

Is there any chance to implement this as an option?

Spec should be:
- This feature should be added as an option
- The width of the tab bar should be changeable with a mouse
- The max number of the opened tabs should be unlimited (no tab pages should appear)
- Tabs should be set in a tree style (cf: https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/)
- The hamburger icon should be placed on the right of the browser (left/below of the lion icon)
- The new tab button should be placed at the bottom of the tab bar/the last opened tab

**Comment by bbondy** [comment]
cc @bradleyrichter I think adding an option makes sense. I think the hamburger button should probably go to the right of the bookmarks toolbar in that case though.  Not sure where the new tab button would go.

**Comment by bradleyrichter** [comment]
Needs some new UI thinking but it would be great to have the vertical option. 

Pinned tabs should be integrated into this side panel so we can hide the original tabs bar.

The Burger menu will need a new home. Perhaps 3 stacked dots to the right of the Brave button when the vertical tabs are enabled. (since the bookmarks bar can be hidden)

I won't have time for this for a bit. Maybe before 1.0 release. Certainly for 1.1.

**Comment by Lennium** [comment]
Side tabs are a great feature for power users. Would be even better to have tree styled tabs or also an option to have tabs at the very browser bottom for example like Yandex browser offers this lately.

Anyway, more tab bar location/styling options would be much appreciated from power users!

**Comment by dogancelik** [comment]
Hamburger menu and Brave icon should be next to each other on Vertical tabs mode
New tab icon should be centered with full width.

**Comment by luixxiul** [comment]
Setting a milestone just as a memo..

**Comment by diracdeltas** [comment]
This is awesome, thanks @luixxiul for trying this out! For me, the best feature of Firefox's tree-style tabs addons was that child tabs would show up nested under their opener tabs. Made it much easier to organize/prune.

**Comment by SJ-Diamond** [comment]
Tree-style-tabs... guys, add that and you get a big number of Firefox users who are frustrated with the browser :D

**Comment by bbondy** [comment]
For tree style, each opened tab/frame has a `key` and some have a `parentFrameKey`.  This allows for a recursive traversal.

**Comment by DeltaZone** [comment]
Tree-style tabs are crucial. We work so often on laptop screens where the screen estate space of the height is more critical than the width, so better to have them along the side, preferably also in a collapsible show/hide toggle panel. As it is now, I also miss an option to toggle hide/show of the horizontal tabs bar AND also the URL bar. This browser is wasting two whole lines that are not needed during the time we are working on or reading a web page. Even in so-called FullScreen mode, those do not go away, rendering the Fullscreen mode almost useless.

(Remember that easily available toggle functions are needed when implementing such features. It will be annoying if it is cumbersome to use an otherwise useful feature. Both a toggle button and a customizeable keyboard shortcut is needed.)

**Comment by DeltaZone** [comment]
FYI - The lack of this feature means I will not be using this browser for much. Only as a spare browser to open some special links/pages in that I do not want to risk disturbs anything in other browsers.

**Comment by luixxiul** [comment]
Though I have set the milestone to 1.1.0, the feature is so wanted that it will be enabled as soon as it is developed enough.

**Comment by clopez** [comment]
Please, check [tabkit2](https://github.com/tabkit/tabkit2) extension as an inspiration.

It is an improved three-style-tab extension that automatically assigns colors to each tab group and has a search box. See the [screenshot](http://ftp.neutrino.es/firefox_tabkit2_verticaltabs-treestyletabs.png)

**Comment by neomodern** [comment]
[Tab Center](https://testpilot.firefox.com/experiments/tab-center) has also done this rather well. 

There are ways to improve it further by incorporating both of the aforementioned [1] Tree Style Tabs  and [2] Tabkit 2 also.

When browsing it just displays the favicon ([1] which would make it **much** easier to incorporate tree-style tabs with as it takes up so little width space, which is the biggest limitation to tree-style tabs).
![](http://i.imgur.com/3XexhdE.png)

Rolling over with mouse opens it up...
![](http://i.imgur.com/ORKtNfk.png)

Until you get a full open preview of a tab
![](http://i.imgur.com/z3531j2.png)

[2] also the background of each tab could have a different colour to further highlight the "tab groups". 

Furthermore by having a defined set of tab groups in the codebase, it makes it easier to add similar tab-grouping styles such as [Tab Groups Helper](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-helper) and [Tab Outliner](https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl).

**Comment by dobriai** [comment]
I don't care so much if it is **tree-style** tabs, but I absolutely need **vertical tabs**, for sure. What Vivaldi has is good enough for me. Until such time, I'll stick to Firefox or Vivaldi. Lack of vertical tabs is a show-stopper for me.

**Comment by Darkless012** [comment]
I agree that what has Vivaldi (or to say also old Opera) is good enough, and also simple enough. Tree style tabs had quite a lot of bugs when I was using it. Although it would be nice to have "tree tabs", I think that just have simple "vertical tabs" would be sufficient for most cases. And then it could go from there.

**Comment by nk8020** [comment]
I think the code is almost directly available from the firefox 'tree-style tabs' xpi (certainly controlling the width/ tree view/ hide/auto-hide...) No real reason why it should not work with minimal changes in Brave.

**Comment by fabricedesre** [comment]
> I think the code is almost directly available from the firefox 'tree-style tabs' xpi (certainly controlling the width/ tree view/ hide/auto-hide...) No real reason why it should not work with minimal changes in Brave.

tree-style-tabs relies on Firefox internals so it's not really portable. In any case I think that with screens having a lot of horizontal real estate but comparatively less vertical, this should be part of the default UX options of a modern browser. For sure this can start simple with just a vertical list of tabs (and pinned ones at the top!), and evolve from here.

**Comment by luixxiul** [comment]
+1 from https://github.com/brave/browser-laptop/issues/10438

**Comment by Dalai-** [comment]
If Brave had vertical tabs I would definitely switch from Firefox to Brave! Horizontal tabs just aren't good when you have lots of tabs open. We've all seen Chrome when you have so many tabs they get so thin like tiny sawtooth spikes along the top of the window. A vertical layout lets you show more tabs, it doesn't eat into the web content (since most pages don't fill a full monitor width, or they adapt) and if you do have more tabs than fits on screen, you can naturally scroll up/down.

I'm considering figuring out how to apply the above hack. I guess I need a custom build of Brave.

**Comment by LaurenWags** [comment]
+1 from community (specifically tree-style tabs): https://community.brave.com/t/tree-style-tabs/6380

**Comment by mrowwy** [comment]
This is something I can't switch to Brave over. I use it sparingly now, but would like to use it more. It just becomes cumbersome once you have many tabs.

**Comment by LupinIII** [comment]
This will be a crucial feature for me as well. Tree style tabs is pretty much the main reason I am still sticking with Firefox (since version 1.5 over a decade ago). I tried other browers, but they were almost unuseable for me without that feature. I currently don't know what I'll do when Mozilla pretty much kills the possibility for a UI extension like this with the release of version 57.
The reason is the same as for most I guess. Horizontal space is plenty compared to vertical on every screen. I don't lose anything by having a 250px wide list shown to the side and I can read the titles of all tabs even if there's 40 or 50 of them open at once (rare, but does happen).
I also make alot of use of the collapsible hierarchical tree part of it, not just the vertical list, especially to organize results when I do research for something.

**Comment by eljuno** [comment]
+1 from community for vertical tabs with tree style https://community.brave.com/t/side-tabs-and-tree-tabs/8302?u=eljuno

**Comment by cherez** [comment]
I'll +1 that tree style vertical tabs are the main thing keeping Firefox as my primary browser.

@LupinIII A WebExtensions version of Tree Style Tab just came out: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

**Comment by NumDeP** [comment]
Is there a point where by '+1' should count anymore? It's also been up-voted here #1873

**Comment by mimoo** [comment]
Hey, I'm waiting for this extension to work to start using Brave, as it is unusable on Firefox at the moment :/

**Comment by JGJP** [comment]
If Brave had this I would use it, preferably it would work like tree-style tabs on FF, with folding/unfolding, and have an option to not show tab previews like tab-center

**Comment by diracdeltas** [comment]
+1 for prioritizing this for an upcoming release since Tree-Style Tabs are virtually useless in Firefox now

https://twitter.com/lyon01_david/status/933099035593818112

**Comment by luixxiul** [comment]
It just took me ~10 min. to create the vertical tabs bar on the 1st post, though the thing has changed and today it must take more time to implement that (at that time we did not have the tear off tabs function and pinned tabs IIRC).

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/tabs-in-a-sidebar-preferably-tree-style-tabs/15002?u=eljuno

**Comment by JGJP** [comment]
Firefox has a revamped Tree Tabs extension that's even better than the previous Tree-Style Tabs extension, many of the users of this feature are power users that care about privacy and the other perks that Brave offers. If Brave want increased market share, I suggest the team look at implementing this feature, as even a mildly workable alternative to horizontal tabs will lead to a sizeable increase in new users.

**Comment by jxpy** [comment]
Brave must be about cutting-edge innovation to have followers. Your early adopters are obviously power users and Brave must attract them, so be 'brave' and don't shy off from adding powerful features.

Tree tabs in general are the future for landscape monitors, they optimize space and organize content.
Vivaldi i.e. has native vertical tabs, but it can also support kroppy's excellent "Tree Tabs" extension.
 
Brave could implement a native vertical tab feature and give extensions devs enough api freedom to implement something like Tree Tabs as an extension.

Tree Tabs example on Vivaldi:

![vivaldi-tree-tabs](https://user-images.githubusercontent.com/17790517/35676125-ef1d0f12-074a-11e8-9eaa-abf56f57fa37.png)

**Comment by NumDeP** [comment]
I've only just noticed FF's built-in feature at the top right hand corner where you can view tabs in a list quite neatly actually, this was probably in relation to disabling Tab Center though it's still offered as Tab Center Redux in the Add-On store. 
Perhaps you can take a couple of notes from this as well so most of the window space isn't removed. 

![screenshot](https://user-images.githubusercontent.com/31957540/35782026-f72b6c0c-09e9-11e8-8813-1c1c02cca621.png)

**Comment by beimprovised** [comment]
Tree Style is just an entrance of knowledge management.
The style itself is nothing. What you need is a personal knowledge assistant, memory management, sharing management, etc.

**Comment by JGJP** [comment]
Even if that was true (which it's not, imo) Tree Tabs is still the best solution.

**Comment by beimprovised** [comment]
https://drive.google.com/file/d/1OlrHBccyxE0lDYmU_Uk2i_Emxiz_slRd/view?usp=sharing
Here is a demo I've made for a proof.
https://github.com/beimprovised/tute

**Comment by beimprovised** [comment]
A new browser window (a tabs group) for a new topic which links to a blog or a social media can be handled with limited tabs number showing up and with more tabs in a tree structure as a back-end data. And you just need several this kind of windows normally. I put them together because they share the same back-end tabs tree :)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/vertical-tabs-or-equivalent-request/22788?u=eljuno

> Like vertical tabs extension in Firefox.

**Comment by Jasperki** [comment]
+1 - this and support for KeePassXC new Browser Integration are what holds me back from using Brave.

**Comment by bsclifton** [comment]
I am fairly certain that we won't be able to make this feature happen with our current codebase (Muon). However, it's clear this is a great idea 😄 Since we're moving over to [Brave Core](https://github.com/brave/brave-browser/), I created an issue there to track this feature request. Please give it a +1 or leave feedback 😄 

https://github.com/brave/brave-browser/issues/464

**Comment by SirCaldude** [comment]
Still no Vertical tabs? Haven't used this browser since I installed it. Vertical Tabs in the sidebar is an absolute necessity. I can't believe anyone was stupid enough to create horizontal tabs in the first place.  Dumbest idea ever.....makes absolutely NO SENSE. The only software I ever paid for was the iRider browser back in 2000....they were the first to use Vertical tabs and I won't use ANY browser that doesn't have them.
