### ISSUE TITLE
Drop down list is not opened and links in menu don't work on bestbuy.ca

### ISSUE THREAD

**Issue by ElenaZhuk** [brave/browser-laptop#2206]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
On the site bestbuy.ca for Searching results page - Sort field drop-down list is empty. And links in left menu don't work.
**Expected behavior:**
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Win 10
- Brave Version:
  0.10.3
- Steps to reproduce:
  1. Open http://www.bestbuy.ca
  2. In Search field enter: Nexus 6 and Search
  3. On the page with results - try to open Sort drop-down - it is empty.
     Try to select any Categories from left side menu - it doesn't work too.
- Screenshot if needed:
  Video: http://screencast.com/t/a0sI8bDM
- Any related issues:

**Comment by neeklamy** [comment]
It’s because the ScoreCard research beacon is being prevented from loading ([ScoreCard info at Ghostery](https://apps.ghostery.com/en/apps/scorecard_research_beacon)) when adverts are blocked.

One easyish way to find what’s preventing a page from properly loading, is to use Ghostery (or NoScript) and then selectively toggle third-party scripts on and off till finding the culprit. Of course, Brave doesn’t support extensions yet, so that needs to be done in a different web browser.

**Comment by luixxiul** [comment]
Closing as the issue has been fixed.
