### ISSUE TITLE
block 3rd party document.referrer in subframes

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2213]
test case: https://jsfiddle.net/v0nL1so4/

**Comment by Sjors** [comment]
Above is Chrome, below is Brave:
<img width="875" alt="schermafbeelding 2017-02-01 om 12 26 54" src="https://cloud.githubusercontent.com/assets/10217/22505089/dd0a8dcc-e879-11e6-9b93-79688ab30fe0.png">

`document.referrer` is now incorrect, rather than blocked, when used inside an iframe on a different origin. Wouldn't it be better to throw an error, similar to what happens if you try to access the DOM?

This creates a problem with [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage): if the page inside the iframe does `window.parent.postMessage({hello: 'World'}, document.referrer)`. The child now either needs to hard code the parents domain, which means it can't be agnostic to that. Or it needs to broadcast the message to all origins, which could be unsafe.

**Comment by luixxiul** [comment]
I reopened it just in case. @diracdeltas

**Comment by diracdeltas** [comment]
@Sjors it was an intentional change to make `referrer` the origin of the embedded document, as setting it to empty was causing some issues. However, I think those issues were mostly with the referrer header, not document.referrer. I would consider changing it back to empty or throwing an error for document.referrer, but I'm a bit concerned about your `postMessage` use case. `window.parent.postMessage({hello: 'World'}, document.referrer)` would post a message to the parent document regardless of its origin, so it doesn't seem like a useful security check unless perhaps the embedded frame is using CSP `frame-ancestors` to limit the set of embedding origins. If it's using CSP frame-ancestors, it is already non-agnostic to the parent domains, so hard-coding the postMessage origin(s) doesn't seem impossible.

In any case, security best practice is to hard-code the postMessage origin, not use a runtime-determined origin like `document.referrer`. I'm curious about use cases where this wouldn't work.

**Comment by Sjors** [comment]
The use case I have in mind* uses `frame-ancestors` to constrain the parent of the iframe. The frame itself doesn't known which of the allowed ancestors it's in. The javascript inside the iframe is compiled before the application is deployed. 

Let's assume host domains A, B and C, and a child website X. 

The child X server sets `frame-ancestors: A B C;`.  If the parent domain is hardcode, the server needs to render different Javascript depending on if it's loaded inside A, B or C. Perhaps the server can figure out which one it is through an HTTP Request header. But if that's the case, you'd probably want to modify Brave to not send / modify that request header either.

A workaround could be to pass the parent domain in as part of the child frame URL. 

* = I'll be able to share it in a few weeks

**Comment by diracdeltas** [comment]
it appears this was fixed at some point
