### ISSUE TITLE
Sites with Flash content that don't redirect to Flash installer need click-to-play

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2279]
example: http://www.y8.com/games/superfighters

**Comment by diracdeltas** [comment]
not technically a bug, since click-to-play is not implemented yet, so Flash on sites that don't try to redirect you to the adobe installer are simply blocked. this is what that site looks like on the flash click-to-play branch though:
![screen shot 2016-06-23 at 9 27 08 am](https://cloud.githubusercontent.com/assets/549654/16314081/15770378-3931-11e6-8535-a29468b3354a.png)
