### ISSUE TITLE
Upon install, URL bar always shows but doesn't match preferences

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#2301]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
I tried out the RC today and noticed the URL bar was always showing. I went to about:preferences and then saw that the option for this was un-checked (which means it should NOT always be showing- it should auto-hide).  I toggled the setting and from that point on, it worked as expected.

**Expected behavior:**
URL bar should auto-hide by default like it did before until the user changes the preference
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 7
- Brave Version:
  0.10.4 RC3
- Steps to reproduce:
  1. Don't have Brave installed (clear the personal folder which has session, etc)
  2. Install Brave on Windows
  3. Open Brave and notice URL bar is always showing (even when mouse is not over that area) and that preferences have the "Always show URL bar" option unchecked.
- Screenshot if needed:
- Any related issues:

**Comment by cezaraugusto** [comment]
Working on it.

**Comment by bsclifton** [comment]
Reopened- I accidentally used closing keywords in another pull request

**Comment by gyandeeps** [comment]
I am not able reproduce this issue on 0.12.14 (If i understand the issue correctly).

**Comment by bsclifton** [comment]
@gyandeeps this is a weird one- you have to have a fresh install of Brave.  If you've already installed before, you'd have to clear your session folder (Windows - `%APPDATA%\brave`, Mac - `~/Library/Application Support/brave/`).  On first launch, URL bar will always be visible, but setting does not match

**Comment by bsclifton** [comment]
@gyandeeps this would be a pretty small scope bug; if you wanted to grab it, let me know :smile:

**Comment by gyandeeps** [comment]
@bsclifton after following the steps, what i saw was that the url bar was hiding when you had a webpage or something open. But url bar will not hide if ut was a new tab with no page open on that tab. Are you saying that it should still hide even if its a new tab without any rendered page on that tab?

**Comment by cezaraugusto** [comment]
@bsclifton is this still an issue on Windows? "Always show the URL bar" is only enabled by default on  Linux distros currently.

@gyandeeps under Preferences -> General, we have an option "Always show the URL bar", which is enabled by default on Windows/Mac, but disabled for Linux (using Linux you'll always see the URL bar).

The issue is: on a fresh start on Linux, the URL bar works as expected: it's visible. Our layer (called as titleMode) is hidden by default. But if you go to "Always show the URL bar" switch, it's disabled (opposite of what should be: enabled). So what's happening is that the feature works, but the switch button is not following.

For a better view, this is what makes this option enabled by default on Linux distros:
https://github.com/brave/browser-laptop/blob/master/js/constants/appConfig.js#L138

and this is the switch button (UI):
https://github.com/brave/browser-laptop/blob/master/js/about/preferences.js#L694

It was an issue when @bsclifton reported but I can't repro now if it also happens on Linux

**Comment by gyandeeps** [comment]
ah.... i did remove all the settings... it was default off for me on windows.... i never changed that setting....

**Comment by bsclifton** [comment]
@cezaraugusto it's has been an issue on all platforms actually; it just appears to be correct on Linux because of the default.  Let me clear my session real quick and verify is this is still open

**Comment by bsclifton** [comment]
@cezaraugusto well damn- looks like this issue has been fixed?  I tested multiple times on macOS and Windows with fresh session and was unable to reproduce.

@gyandeeps the behavior (which is correct) that you should see is:
- Launch branch with clean session (ex: move %AppData%\brave out of the way and re-launch Brave)
- When launching, new tab page is shown. URL bar always shows for new tab page.
- Visit github.com/brave
- Move mouse and notice URL bar gets hidden

I looked back at the commit history and I believe I see where the issue was fixed :smile: 
https://github.com/brave/browser-laptop/commit/10927580f0865cab2a7a6b7620d52417b185a071#diff-1f1754cabe685176d883eaf7f4763184

I'll close this out- thanks @cezaraugusto for retrying this and thank you @gyandeeps for taking the time to check it out also
