### ISSUE TITLE
Double clicking on titlebar should respect Dock preference on macOS

### ISSUE THREAD

**Issue by TognaBologna** [brave/browser-laptop#2364]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
In OS X there is the native full-screen option, using the green circle in the menu bar. However, many users prefer to hold shift while double clicking the title bar. What this does in most OS X programs is extend the window to the edges of the available desktop. This is different than the native full screen option in that other windows can still be placed on top of the expanded window, and the OS X title bar is not hidden. It is similar to how Windows handles full-screen applications (before Windows 8 apps...).

**Expected behavior:**
Holding shift while double clicking the title bar should expand the window to fill the available screen/desktop.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X 10.11.5 (15F34)
- Brave Version:
  Brave 0.10.4
- Steps to reproduce:
  1. Hold shift
  2. Double click on Brave's title bar
  3. Notice that nothing happens

**Comment by neeklamy** [comment]
Are you sure you didn’t change something in OS X’s System Preferences? I’ve always known double-clicking (or tapping) the title bar to minimise a window, and shift+double-clicking does that in slow motion…

But changing the preference, as you say, and double-clicking the “title” bar does nothing. I think this is down to and would need changing in Electron though (possibly this: [native_window_mac.mm](https://github.com/electron/electron/blob/6aef8f4fea5a019e8f9c4a6205c042b3fbc98dff/atom/browser/native_window_mac.mm#L548)), the change to Brave’s title bar was made with #1273.

**Comment by TognaBologna** [comment]
It works with any other program, including Google Chrome, which fully uses the title bar's real estate, like Brave.

**Comment by neeklamy** [comment]
Oh I’m not denying it – as it turns out I’d changed the application title bar bar behaviour:

![shpxvat-qhzo-qhzo](https://cloud.githubusercontent.com/assets/155358/16531604/344f6a48-3fc5-11e6-8aad-f569358319ff.png)

I’m not sure it’s necessary to hold the shift key while double-clicking either, just double-clicking a window title bar resizes or minimizes an application window.

But again, it really looks like it’s more of something for Electron to change (the framework which the Brave application is built on). Electron makes the title bar invisible, this, as far as I can tell, is to vertically align the “traffic lights”. A side-effect of making the title bar invisible is that it can’t receive any clicks, so the double-clicking doesn’t falls through.

**Comment by neeklamy** [comment]
Oh I’m not denying it – as it turns out I’d changed my OS X application title bar behaviour:

![shpxvat-qhzo-qhzo](https://cloud.githubusercontent.com/assets/155358/16531604/344f6a48-3fc5-11e6-8aad-f569358319ff.png)

I’m not sure it’s necessary to hold the shift key while double-clicking either, just double-clicking a window title bar resizes or minimizes an application window.

But again, it really looks like it’s more of something for Electron to change (the framework which the Brave application is built on). Electron makes the title bar invisible, this, as far as I can tell, is to vertically align the “traffic lights”. A side-effect of making the title bar invisible is that it can’t receive any clicks, so the double-clicking doesn’t falls through.

**Comment by wonderwarthog** [comment]
Brave 0.12.15 here on macOS Sierra 10.12.2 (16C67), same issue.

**Comment by wonderwarthog** [comment]
Still not fixed and it annoys the hell out of me. Never ever arbitrarily change features of the standard UI of the host OS, especially if there is a system wide preference where the behaviour can be set. The user has made a decision by setting this. Do not ignore it.

**Comment by bsclifton** [comment]
@wonderwarthog what is not being respected? Or rather, what behavior are you expecting to happen?  I'm trying to understand more about holding shift + clicking as I get the same behavior with/without.  I need help finding the setting

**Comment by wonderwarthog** [comment]
Currently my preferences are set to: **Double-click a window's title bar to [minimize]**

What happens actually is that if Brave's window isn't filling out the whole screen, it will simply maximize the window when I double-click on the title bar. Any consecutive double-click then will minimize the window.

That's not only wrong it's even not consistent in being wrong…

**Comment by Liunkae** [comment]
+1 from #9598 (https://community.brave.com/t/double-click-to-minimize-doesnt-work-in-osx/2274)

**Comment by paddor** [comment]
Same issue here with Brave 0.19.95 (cc0ebad). Double-click in title bar first zooms (instead of minimizing), and then another double-click minimizes the window. Very confusing.

**Comment by tedmcdo** [comment]
Can this issue get higher priority? My workflow involves heavy use of minimize my browser, and this issue keeps Brave from being my go to browser.
