### ISSUE TITLE
Tab discarding

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#2388]
Google Chrome/Chromium currently supports a feature called [tab discarding](https://developers.google.com/web/updates/2015/09/tab-discarding?hl=en).

Does Brave currently support similar functionality, or if not are their plans to do so?
#1796

**Comment by DivineOmega** [comment]
Thanks for your work on this! :smile: 

May I ask if this functions the same way as Chrome, and if there is a way to view a Brave equivalent of chrome://discards ?

**Comment by bbondy** [comment]
@DivineOmega pls post for chrome://discards if you don't mind in a new issue.

**Comment by luixxiul** [comment]
Is there any specific thing to test?

**Comment by bridiver** [comment]
@DivineOmega it uses the same memory-based tab discarding that Chrome does. We will be adding more features soon. @luixxiul there is a dev menu item that simulates a memory pressure event, but keep in mind that it will only discard non-active tabs and only if they are at least 10 min old.
Here is a test plan:
1. Open brave.com
2. Open a second tab with brave.com
3. Wait at least 10 min
4. Select "Simulate memory pressure event" from the dev menu
5. Switch to the original tab
6. Tab should reload because it was discarded

**Comment by alexwykoff** [comment]
Cannot reproduce with RC builds.

I attempted to use memory_pressure in bash, but to no avail.

**Comment by bridiver** [comment]
I don't think that's a reliable way to test. I have tested in dev builds using the dev menu item and it worked correctly.
