### ISSUE TITLE
Responsive ads of Adsense are not replaced

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2524]
**Describe the issue you encountered:**
Responsive ads of Adsense can be blocked, but not replaced with the Brave ad banner on https://braveinfo.net/, unless the size of ``<ins class="adsbygoogle">`` is styled explicitly.

**Expected behavior:** They should be replaced even if the height/width is not specified in CSS files for the ``<ins>`` element.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1dev

- Steps to reproduce: Go to http://braveinfo.net/

- Screenshot if needed:

- Any related issues:

**Comment by bridiver** [comment]
this falls under the general category of detecting ads dynamically in the browser. The current ad replacements come from a list generated by https://github.com/brave/vault-ad-info and I have no idea when that was updated last. This is definitely not a bug, but there should be a ticket in github or asana for better ways to detect potential ad replacements. What you're suggesting is not trivial because when the ad is blocked the element doesn't necessarily have the size that it would if the ad was injected. In many cases we would have to mock up the ad server calls to capture the placement size info.
