### ISSUE TITLE
Easier Enabling of Extensions

### ISSUE THREAD

**Issue by Krutonium** [brave/browser-laptop#253]
I ask because I have several addons that I would need to be able to truly move to this browser - LastPass for example for many people, would be a dealbreaker.

**Comment by diracdeltas** [comment]
Compatibility with Chrome extensions is a good post-1.0 goal. The main reason it's not coming earlier is that Electron doesn't want to support all the Chrome extension APIs; we'd have to convince them to do so or put them in our fork of Electron. https://github.com/atom/electron/issues/1498

**Comment by wrkerr** [comment]
This is a really important enhancement for me. I daily move between an Android phone, a linux home desktop, and a Windows work laptop. There are a handful of extensions that provide some important security and integration funcationality.

Like the OP, I too need integration from a cross platform password manager, though preferably not one that stores your password database on their servers like LastPass. [Enpass](https://enpass.io/) and [Keepass](http://keepass.info/) are primary examples, though there are others. These are particularly effective when combined with an extension like [Authy](https://www.authy.com/), which makes two-factor authentication much simpler.

Additionally, I would love to have support for some browser integration with a secure messenger that interfaces with android messaging. Signal Private Messenger by Open Whisper Systems is developing a Chrome web app [desktop interface](https://whispersystems.org/blog/signal-desktop/) that would be wonderful to have. [Telegram](https://telegram.org/) and others provide similar feature sets.

Lastly, there are several services which leverage browser extensions to provide a simple way to share text, links, and files between devices. [Join](http://joaoapps.com/join/) and [Pushbullet](https://www.pushbullet.com/) are two popular examples, and their browser extensions provide a great deal of multi-device integration and convenience. This would be a great addition.

All of these could be achieved if Brave gained support for Chrome extensions and web apps, rather than creating another ecosystem of exensions.

**Comment by weems** [comment]
@wrkerr definitely in plans, but we have to prioritize what will be in 1.0 so as to move as fast as possible and meet schedule on time :)

**Comment by wrkerr** [comment]
@weems, that makes sense to me. Thanks!

**Comment by diracdeltas** [comment]
Talked to @bridiver about this just now. We will probably implement all/most of https://wiki.mozilla.org/WebExtensions, which will cover the majority of functionality needed for chrome extensions.

**Comment by PFCKrutonium** [comment]
Wait, so Brave will support both Firefox AND Chrome extensions?

**Comment by bridiver** [comment]
@PFCKrutonium No, the webextensions are Mozilla's effort to support Chrome extensions, but we will not support FF only extensions

**Comment by PFCKrutonium** [comment]
Ah okay.

**Comment by SamHH** [comment]
Glad to see this is planned! +1

**Comment by x0x7** [comment]
I'm also looking to develop an online service that needs a plug-in and I would really like 100% coverage.  Chrome compatibility is a small plus because that's one less browser to support but it's more important to me at least that there is some way to target the browser.

I worry about Electron being able to support chrome extentions in a way that won't be buggy.  I feel bad for them being asked to support that and seeing as that's not even on their time table, much less on their time table but unrealistic, I'm a +1 for a rudementry add-on system.  Atom, which electron is coded for seemed to have no problem doing it at that layer.  That's another reason why Electron won't include chrom plugins.  It's not on Atom's radar so it won't be on Electon's.  Could you imagine how borked Atom could get if people injected extensions in there?

They forked Electron from aAom so people to could work on it to make it more stable for Atom.  They aren't going to accept features that could create pains for Atom even if by mistake.

**Comment by bridiver** [comment]
well, it's not really practical for Electron to have 100% coverage because a lot of API functionality depends on the specific app you have implemented. For instance: browser action popup windows can be triggered with generic functionality in Electron, but it's impossible to know how an app will actually want to display them. They are interested in pulling in some extension functionality and there is an open ticket for it, but I'm not sure how much of it we will be able to upstream. I'm doing my best to make the implementations as generic as possible, but there's no guarantee everything will make it to upstream. I'm also using the chromium code where possible (background pages, chrome.runtime and a few others).

**Comment by bridiver** [comment]
also, it's entirely up to the app whether or not they want to expose the ability to install extensions. I even left in checks that allow you to build electron with extensions disabled. So far we have not exposed the ability to install user extensions because the extension support is limited and we haven't implemented all the permission checks necessary to ensure the safety of unknown extensions

**Comment by nickschurch** [comment]
I'll add my voice to the need for some browser apps - keepass/lastpass is a must for me.

**Comment by blargity** [comment]
As a developer on [Toolkit for YNAB](https://github.com/toolkit-for-ynab/toolkit-for-ynab) I'd love to be able to support Brave as a platform.

**Comment by luixxiul** [comment]
FYI: LastPass has been integrated already.

**Comment by bridiver** [comment]
@nickschurch I was not able to find an "official" keepass extension for Chrome. There appear several extensions that support it to some degree, but I think it will likely have to wait until we have full extension support

**Comment by dogancelik** [comment]
You can use KeePass in Chrome and Firefox by using:

* Chrome extension: [Hostname in Title](https://chrome.google.com/webstore/detail/hostname-in-title/opcgicnmmbpnohinkbaonagehbhakjdl)
* Firefox extension: [KeePass Helper](https://addons.mozilla.org/addon/keepass-helper/)

Then enable "An entry matches if the host component of its URL is contained inthe target window title", hope this helps.

--

Also Chrome extensions are not really necessary right now but allowing users to customize their sites with Userscripts would be a good addition.

Userscript is a script that works on [Opera, Safari, Chrome](https://tampermonkey.net/) (6.6m users) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/) (1.2m users)

**Comment by ElijahLynn** [comment]
https://github.com/brave/browser-laptop/wiki/Brave-Development-Timeline

Says, 1Password, Dashlane and Lastpass are implemented.

**Comment by bridiver** [comment]
we have partial extension support right now and we're working towards full support. We won't have full support in 1.0, but we are hoping to add more extensions based on popularity. Without full chrome.* api support we really need to test each one right now

**Comment by ElijahLynn** [comment]
I am on .10 (Linux), I see support for 1Password and Dashlane in Preferences > Security. I am assuming .11 has the initial support for Lastpass?

**Comment by bridiver** [comment]
actually that's a bug, 1Password should be disabled on Linux because they don't have a linux client app. Lastpass should work, but it's currently missing a few options and is only accessible through the right-click context menu

**Comment by bridiver** [comment]
you don't see Lastpass?

**Comment by ElijahLynn** [comment]
Awesome, just updated and Lastpass is working flawlessly! I am now posting this from Brave! Sooo fast!!! MMMMMm..

**Comment by stri8ed** [comment]
I am very much interesting in using Brave to try out the Bitcoin integration, but until there is support for [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions), I cannot make the switch from Chrome.

**Comment by Kinnardian** [comment]
Is there a listing of extensions/add-ons that work already?

**Comment by Liunkae** [comment]
Related: #4600

**Comment by TristanWiley** [comment]
Is there any way I can port my Chrome extension to Brave?

**Comment by bridiver** [comment]
right now it really depends on which chrome apis you are using. We don't support all of them yet, but we are working on filling in the gaps. I believe @jonathansampson is working on a complete list of our current api support. Ideally you won't have to do anything to port it over

**Comment by TristanWiley** [comment]
Sounds good, second question is. How do I add extensions?

**Comment by jonathansampson** [comment]
@TristanWiley Testing extensions is fairly straight-forward. You can read about the process here: [Quickly test out an extension](https://github.com/brave/browser-laptop/wiki/Developer-Notes-on-Installing-or-Updating-Extensions#quickly-test-out-an-extension).

**Comment by Cassolotl** [comment]
+1 'cause Tumblr is a site I use a lot and it is a NIGHTMARE without X-Kit.

**Comment by luixxiul** [comment]
> +1 'cause Tumblr is a site I use a lot and it is a NIGHTMARE without X-Kit.

What do you +1 for?

**Comment by Cassolotl** [comment]
@luixxiul On Github project things I've been involved with in the past, +1 is the way you express support for an idea. Is that not a thing on this project?

I am not very techy and I don't really understand much of this conversation, but the lack of easy browser extension stuff on Brave means it can't be my main browser even though I love the idea of it in general. So I wanted to add my support for this idea.

**Comment by kmharper** [comment]
I'm like a lot of people who have largely switched to Brave, but can't entirely get away from Chrome yet.

One thing that helped me was to be able to use the Signal Private Messenger Chrome extension without actually opening Chrome (at least in Mac OS X).

1. Open Chrome and install the app:

[https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk?hl=en]

2. Go to Finder and search (with quotes) "Signal Private Messenger" to find the app in your file system. You can browse to Applications > Chrome Extensions if that folder isn't hidden, but if it is, and you don't want to unhide it, just do the search.

3. Drag it to your toolbar or make an alias of it. Now you can open it without going into Chrome.

**Comment by codeduph** [comment]
I would like to try Brave as I'm looking for an alternative to FF. However, one thing I really love about FF is their Bookmark. I've try some Chronium Browser and add Extension "Neater Bookmarks" or  "Popup my Bookmarks" and it works fine and I'm feeling soon to switch and leave FF.

I hope Brave would allowed user to use some unpopular 'Extension' soon.

**Comment by Zerophase** [comment]
The only plugins I think most people really care about are ones that change web page UI. I know personally, I couldn't get by without Stylish making all pages dark, and a couple of Chrome plugins that center Google search results. I'm pretty sure Stylish could be done through other means, and even use the altered css styles.

**Comment by droplab** [comment]
I think there is quite a large user base for developer extensions also, react-dev-tools, redux dev tools etc... Figuring out how to achieve chrome extension compatibility in Brave would elevate this project to be a serious contender with chrome or ANY other browser. Thanks for all the work on this Brave team!

**Comment by danshumaker** [comment]
i'm really enjoying the speed of brave, and while I don't like the slowdown that plugins and extensions have on browsers, I would really really like to have the 1Password (Agilebits) extension working for brave. If and when that happens then I will gladly click the "Make Brave my default browser" button.

**Comment by srirambv** [comment]
@danshumaker  1Password is available by default. You can enabled it from settings page under security

**Comment by qazip** [comment]
How is the support for chrome extensions going? I suppose one can not use chrome extensions on brave yet?

I'm looking for support to the following:

- ublock origin (I know you've support for blocking ads, but, for some reason, the invisible space is not being collapsed. I would also like to remove twitter, FB (etc) widgets. I can't seem to do that easily in Brave);
- Vimperator: I need vim-like behaviour;
- Dark background with white text: It blinds me having to read pages with white background;
- Pinboard extension;

**Comment by ElijahLynn** [comment]
+1 for Vim-like extension (or native support), scrolling, back/forward etc.

**Comment by c-u-b** [comment]
any advice on how to get kinjamprove on brave?

**Comment by jonathansampson** [comment]
@c-u-b Would you mind testing the extension? https://medium.com/@jonathansampson/testing-chrome-extensions-in-brave-8e25d1f7386d

**Comment by c-u-b** [comment]
@jonathansampson i have briefly glanced at the instrux on medium, and it appears i need to install chrome.  is there any other way?

**Comment by bsclifton** [comment]
@jonathansampson aren't there command line tools available via NPM that you can package / unpack chrome extensions?

**Comment by tbartlett0** [comment]
I would like to add my voice to the request for this. Perhaps if it was done similar to the way Firefox can temporarily load an extension through the "about:debug" page... this would make it a lot easier (and therefore more likely) that I would test extension that I'm interested in.

**Comment by nickytonline** [comment]
@bsclifton, it's chrome-ext-downloader, `npm install -g chrome-ext-downloader`. See https://brave.com/loading-chrome-extensions-in-brave for info on how to do the whole song and dance. ;)

**Comment by bsclifton** [comment]
@nickschurch thanks- I meant to give an update but totally forgot

I created an experimental extension branch which folks can try here (if you're up for running from source):
https://github.com/bsclifton/browser-laptop/tree/experimental-extensions

Here's the commit which does the magic (which includes testing steps):
https://github.com/bsclifton/browser-laptop/commit/ad3b95c18d1ec85fd802ba94a61e6f6f5d492ac1

I tested this out by downloading/installing about 20 extensions and they all seemed to work good (I'll admit, I didn't test in depth).  For folks wanting to try extensions, I'd highly recommend pulling down my fork (or just apply that patch on master)

**Comment by tbartlett0** [comment]
@bsclifton  I've had a go at building from your fork but no success yet - haven't had time to troubleshoot what went wrong. Also, that's in a dev VM so I won't be able to run extensions on my main Windows install unless I can get a build running on there too... I'm a bit scared to try!

I hope there is an option to enable this as a 'debug feature' in one of the official builds sooner or later...

**Comment by illegalnumbers** [comment]
So what troubleshooting and dev tasks are still required to get things enabled?

**Comment by bsclifton** [comment]
I'm going to close this as `wontfix`... because it will be addressed with [Brave Core](https://github.com/brave/brave-browser) - the upcoming version of Brave which uses a forked Chromium UI instead of Muon. We already have this installing extensions just fine and the build in `chrome://extensions/` page works great (you can load unpacked extensions, etc)

We should have a build of this new Brave available in a few months- hang tight 😄

**Comment by rdbox** [comment]
add this application Privacy Possum allows you to block and randomize the fingerprint

**Comment by Zerophase** [comment]
Doesn't the new version for release in October support all Chrome plugins?

**Comment by Liunkae** [comment]
@Zerophase Yes. A developer release of the new version is available already: https://brave.com/download-dev

**Comment by mmaura66** [comment]
i use Passman in brave following this tutorial: https://www.youtube.com/watch?v=B7dvJrhXIbc

**Comment by pkieltyka** [comment]
can we get an update on current status of a public/stable release for this? I need it before I can move over to Brave

**Comment by bsclifton** [comment]
@pkieltyka we launched brave-core on our Beta channel recently, which you can find here:
https://brave.com/download-beta

[Per our release schedule](https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule), we're targeting a stable release of brave-core just over a week from now

After the release channel ships, we'll (schedule undecided - but likely in the next few months) work on having this version of the browser update itself to brave-core
