### ISSUE TITLE
Add delete confirmation to downloads bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2604]
## Test Plan
- Download a file
- try to delete it from the `downloadsBar`
- notice new confirmation bar
  - click `ok` to remove the file
  - move the mouse outside the `downloadItem` panel to hide the confirmation bar.

## Original issue description
"Delete Download" on download bar should have a warning prompt.
- Any related issues: #1076 #1202

**Comment by stan-qaz** [comment]
An additional reason to add a confirmation here is because when downloading and you open the status-bar download box the "open in folder" is the last icon shown at the right. When the download completes the first icon on the left, "pause", is removed and a "delete" icon is added on the far right. This effectively replaces the "open in folder" icon with the "delete" icon in the same spot and nearly instantly when the remaining icons shift left to fill the hole left by the removal of the "pause" icon.

Maybe change the icon order so that the pause is replaced by the delete, in the far left location, until the confirmation option is available?

On the other hand it is nice to see that the delete icon can quickly remove a 4 GB ISO download that has just finished. :-(

**Comment by luixxiul** [comment]
> This effectively replaces the "open in folder" icon with the "delete" icon in the same spot

wdyt @bradleyrichter ? I noticed this too.

**Comment by willy-b** [comment]
+1, accidentally deleting downloads should be difficult imho

**Comment by bradleyrichter** [comment]
How about something like this?  (l10n friendly)

![image](https://cloud.githubusercontent.com/assets/13509546/20650985/cead0ba0-b490-11e6-8282-76bdda9ae46b.png)

**Comment by stan-qaz** [comment]
That would solve my problem completely and it looks pretty sharp too.

**Comment by Liunkae** [comment]
Solution: #5969

**Comment by bsclifton** [comment]
from #5969, here are the acceptance criteria per @bradleyrichter:

> Deleting files is destructive and can not be undone. Thus, it needs a minimal confirmation.
>
> Adding this to the delete bar UI keeps the confirmation focused at the point of interaction rather than opening a dialog. 
>
>To cancel, click outside of the popup box.
>
![image](https://cloud.githubusercontent.com/assets/13509546/20803042/c33828ee-b7a2-11e6-80a7-2ec61398c854.png)
