### ISSUE TITLE
CSP errors cause failure to auto update from the pre staging server at brave-laptop-updates-pre.brave.com

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2614]
<img width="538" alt="screen shot 2016-07-20 at 2 30 50 pm" src="https://cloud.githubusercontent.com/assets/210240/16998232/7f285334-4e86-11e6-93c4-b9053456b005.png">

**Comment by bbondy** [comment]
I think you looked at this before Yan but I think the fix didn't work or something.  Not a big deal but it leads to safer releases if we can test updates from the staging server.

**Comment by bbondy** [comment]
Can test with this or similar:
`BRAVE_UPDATE_HOST=https://laptop-updates-pre.brave.com  open -a /Applications/Brave.app/`

**Comment by diracdeltas** [comment]
last time it was fixed in https://github.com/brave/browser-laptop/commit/843e8b5ed194055407cc5c7e024940890b4848ba, but it looks like we're using `brave-laptop-updates-pre.brave.com` instead of `laptop-updates-pre.brave.com` now? it just needs to be updated in index.html and index-dev.html whenever the hostname changes.

**Comment by diracdeltas** [comment]
why is it trying to connect to an update server over HTTP instead of HTTPS?

**Comment by aekeus** [comment]
That may have been my mistake, let me try with HTTPS

**Comment by diracdeltas** [comment]
@aekeus i think it will fail anyway, let me push a fix right now

**Comment by diracdeltas** [comment]
fixed by https://github.com/brave/browser-laptop/commit/b3d38b0685066b6768c139301d48ebe4a30d5ba0
