### ISSUE TITLE
Allow/Deny/Ask Location Tracking options

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2616]
Allow/Deny/Ask Location Tracking options not available? Ideally when you visit whatsmyip.org and click on more info about you it tries to track the location.  Edge throws up error to enable location services. 

![edgeip](https://cloud.githubusercontent.com/assets/17010094/17001436/e49787b6-4ebe-11e6-9a08-74c427a37202.PNG)

All browsers also have the functionality

![location](https://cloud.githubusercontent.com/assets/17010094/17001446/ef442eda-4ebe-11e6-8c13-189b7f5ed0b1.PNG)

**Comment by diracdeltas** [comment]
http://www.whatsmyip.org/ doesn't show any notification in Chrome or Brave because it doesn't seem to use html5 geolocation. Any site can track you via IP address, but tracking via geolocation is not permitted by default in Brave.

**Comment by neeklamy** [comment]
As @diracdeltas says, Brave correctly asks for permission for access to the HTML5 geolocation API, and if a site is given permission and you have it remembered, it shows up in Brave Preferences → Security → Saved Site Permissions

![Brave geoloaction API request](https://cloud.githubusercontent.com/assets/155358/17054742/a2fd739a-5000-11e6-9c22-1990a8f9547f.png)

You can see this in action at [BrowserLeaks: HTML5 Geolocation API](https://www.browserleaks.com/geo).

**Comment by neeklamy** [comment]
As @diracdeltas says, Brave correctly asks for permission for access to the HTML5 geolocation API, and if a site is given permission and you have it remembered, it shows up in Brave Preferences → Security → Saved Site Permissions

You can see this in action at [BrowserLeaks: HTML5 Geolocation API](https://www.browserleaks.com/geo).

![Brave geoloaction API request](https://cloud.githubusercontent.com/assets/155358/17054742/a2fd739a-5000-11e6-9c22-1990a8f9547f.png)

The problem here is entirely with [WhatsMyIP](http://www.whatsmyip.org/), they’re trying to access the geolocation API over http. If you check out the dev tools console while you’re on [More Info About You](http://www.whatsmyip.org/more-info-about-you/), you’ll see this:

>getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

Safari 9.1.2, *with your permission*, still allows the geolocation API to be used, Safari Technology Preview doesn’t, and nor does the latest Google Chrome (51).

**Comment by diracdeltas** [comment]
Ah, that makes sense. non-HTTPS geolocation requests are simply denied in Chrome/Brave.
