### ISSUE TITLE
Notification bar for crashes does not dismiss

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2617]
If you get a renderer crash there is a notification bar at the top with an OK button.
Clicking on OK does nothing and keeps the bar.

No error in console.

cc @bridiver

**Comment by bridiver** [comment]
it appears that this worked previously because of a bug related to handling `NOTIFICATION_RESPONSE` in multiple places and calling `hideMessageBox(message)` for messages that actually shouldn't have been handled there. Seems like it would be better to handle them in one place and register callbacks. That would make it much easier to implement a default behavior and would prevent inadvertent closing of messages by other handlers.

**Comment by luixxiul** [comment]
Fixed ;-)

**Comment by bridiver** [comment]
tried to create an automated test for this, but webdriver doesn't like it when you crash the renderer process
