### ISSUE TITLE
Add a sandbox attribute to the inserted iframes

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#262]
Wladimir Palant on January 20, 2016 at 13:51:08 says:
Hm, safe ads... You know that an iframe with srcdoc attribute is considered first-party and the same-origin policy isn't stopping it from accessing its parent? So, unless you also add a sandbox attribute, the ad frames you are injecting are just as unsafe as the ones you blocked. Want to actually sandbox them?

For reference, I'm talking about this code: https://github.com/brave/browser-laptop/blob/e008a788c9d6256d04897bb5725a6018e68ea493/app/content/webviewPreload.js#L110

**Comment by bbondy** [comment]
cc @diracdeltas @bridiver pls take when you can

**Comment by bridiver** [comment]
The srcdoc is leftover from the OIP stuff when only an image and click url were going to be returned to browser. It will be removed before the release, but we can prioritize the change to alleviate any concerns that people have.

**Comment by diracdeltas** [comment]
nice to see Wladimir contributing!

@bridiver so there is no downside to adding the sandbox attribute anyway for now? i'll do it then

**Comment by bridiver** [comment]
this would apply to ios as well

**Comment by diracdeltas** [comment]
cc @garvankeeley, please fix when you get a chance

**Comment by bbondy** [comment]
cc @SergeyZhukovsky, please fix also when you get a chance in the Brave branch.

**Comment by SergeyZhukovsky** [comment]
@garvankeeley you should look on that commit 
https://github.com/brave/browser-laptop/commit/216f14120417ba54082d2e8f011d14904cd35ecb

**Comment by garvankeeley** [comment]
Added, thanks for the src link.
In future, please add issues to the respective githubs (no details needed, just slap it in there), as messaging volume increases, things are going to get missed.

**Comment by bridiver** [comment]
Sonobi has made the updates on their side to send through "clean" ads that are just html with no extra JS. This will allow us to simplify things on our end as well and a new URL will be coming next week which will replace the srcdoc with a src link. I believe it will just be a "switch" passed in the query string. The change from srcdoc to src will make the iframe 3rd-party by default, but we should keep the sandbox attribute and remove allow-scripts to make it even more secure

**Comment by diracdeltas** [comment]
+1, feel free to change the srcdoc to src with sandbox when the new URL comes @bridiver

**Comment by bridiver** [comment]
If we continue to use srcdoc as discussed on Slack we will have to go back to the method of loading the URL separately and inserting the response content vs the current method of just putting the url in the script src of the static html snippet. That's good long-term because we want to load them separately, but does it cause any short-term problems?

**Comment by bridiver** [comment]
@garvankeeley and @SergeyZhukovsky we discussed using a hidden webview or phantomjs-type process on the laptop browser to load the ad content and execute any JS that is used to build the DOM (ads commonly include document.write calls and I'm not sure if it will be practical to restrict that) and then pass the content to the iframe. Does that sound practical on ios and android or are we going to run into platform limitations?

**Comment by garvankeeley** [comment]
I would need a more detailed spec of what steps are being taken to say where the problems might be. I have only used that approach for JS that doesn't need a DOM. If it does need a DOM, then why not inject it into the current webview for execution?

**Comment by SergeyZhukovsky** [comment]
I think there shouldn't be any problems with that on Android, but need some investigation also.

**Comment by bridiver** [comment]
several reasons:
1. It may be helpful to have something that is not connected to ad blocking so we don't have to worry about conflicts between the ad block list and the replacement ads we deliver
2. We want to download the ads as far ahead of time as practical and maintain a small, short-lived cache. We often know what ad slots will be on the requested page so if we don't have any cached ads we can start loading them in parallel with the page (just the tag, not the creative. We don't want to interfere with bandwidth for page loading) We will also sometimes have to request more ads than we need to deal with user downvote preferences without exposing those to the network
3. We may want to remove parts of the rendered ad tag because we won't always be able to get curated tags with all extra JS removed.

Only the last one requires something that can generate html from the returned content and there are other ways we could do this if that turns out to be a  problem for the platform or for other reasons.

The process could potentially go something like this:
1. Request ad tag
2. Generated HTML from any returned JS without allowing any requests
3. Strip out remaining JS code
4. At display time download the creative and display from cache (to avoid blocking issues) in the iframe
But there are other ways to do it as well.

**Comment by garvankeeley** [comment]
Thanks, nothing jumps out as an issue

re: 1. iOS http filter is a catch-all, I think/hope I can distinguish non-actual-webview requests from others, but currently I don't have this.

re: Caching:
As for UIWebView disk caching, we have to consider the size of the disk cache, and how long a typical browsing session will take to flush that cache. Alternatively we install our own NSURLCache, but then all the code will likely be best written in swift/obj-c. I think the fact the cache can be short-term means that there shouldn't be a problem here, and that the build-in webview caching can be used.
