### ISSUE TITLE
Share Point

### ISSUE THREAD

**Issue by teagueamania** [brave/browser-laptop#2662]
**Did you search for similar issues before submitting this one?**
Yes.
**Describe the issue you encountered:**
�������X���:���4��լ�I�p�3"��Wh��2��A.b���u��
**Expected behavior:**
Rendering text on Share Point intranet site.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7
- Brave Version:
0.11.1
- Steps to reproduce: Sorry, forbidden from reproducing internal documents!
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by neeklamy** [comment]
How does the site appear using Google Chrome?

**Comment by teagueamania** [comment]
Chrome renders text and images as expected.

**Comment by neeklamy** [comment]
Could you confirm what character encoding the site is using? If you view a page’s source (right click on an empty part of the page → right click → View Page Source), then near the very top you will see something like:

```
<!DOCTYPE HTML >
<html dir="ltr" lang="en-US">
    <head><meta http-equiv="X-UA-Compatible" content="IE=10" /><meta charset="utf-8" /><meta […] content="text/html; charset=utf-8" />
```

In this example, the site is using UTF-8, notice that there’s two appearances of `charset=utf-8` inside that `head` element.

Another thing you could try, is to save out a page, then using a text editor*, strip out every sensitive thing, just leaving behind the bare minimum to see the problem in action. I’m guessing that you really wouldn’t need to leave much in there to reproduce the bug.

And if the bug is still present in a stripped down html document, it could be shared with the Brave developers.

\* Even the venerable Notepad would do it on Windows, *but they’re are better text editors*.

**Comment by teagueamania** [comment]
Here's the header. I will try your suggestion of stripping the text when
time allows.

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html dir="ltr" lang="en-US">
<head><meta name="GENERATOR" content="Microsoft SharePoint" /><meta
http-equiv="Content-type" content="text/html; charset=utf-8" /><meta
http-equiv="X-UA-Compatible" content="IE=10" /><meta http-equiv="Expires"
content="0" /><meta name="msapplication-TileImage" content="
/_layouts/15/images/SharePointMetroAppTile.png" /><meta name="
msapplication-TileColor" content="#0072C6" />

**Comment by teagueamania** [comment]
This appears to be resolved. Thank you!
