### ISSUE TITLE
Subtitles on TED doesn't show

### ISSUE THREAD

**Issue by dogancelik** [brave/browser-laptop#2695]
I can see subtitles of TED videos on Chrome and Firefox but not on Brave.
### Firefox

![firefox](https://cloud.githubusercontent.com/assets/486818/17084308/0656be1a-51c3-11e6-9395-01883a47bdc6.gif)
### Brave

![brave](https://cloud.githubusercontent.com/assets/486818/17084310/07b938b4-51c3-11e6-8777-c91636acfd4b.gif)

Video: https://www.ted.com/talks/suzanne_simard_how_trees_talk_to_each_other

Windows 8, Brave 0.11.1

No there is no subtitle button outside the player frame.

**Comment by dogancelik** [comment]
Anyone?

**Comment by luixxiul** [comment]
I actually cannot find the button to enable the subtitle.

**Comment by dogancelik** [comment]
@luixxiul Because the video frame doesn't exist in Brave, it's just a regular Video element, native video controls by Electron.

**Comment by neeklamy** [comment]
If you open up the help section on a TED video (hover over the video, where it lists the subtitle languages available, the question mark), it says this:

> **Desktop / laptop users:** please make sure you have the most updated versions of your browser and Flash player, and that Flash is enabled when you visit TED.com.

Even with PPAPI (“pepper”) Adobe Flash plugin installed, Brave hides this from the the website, and so the website sends us an H.264 video instead.

The solution here would be to have a per-site override (would the Brave devs be up for adding another check box though?). Sadly the TED Talk developers don’t seem to be in any hurry to add subtitles support to the HTML5 player, they first made the HTML5 player available [back in March 2010](http://blog.ted.com/tedcom_now_avai/):

> What it means for you: if you own an iPod Touch, iPhone, iPad — or any smartphone that supports the open HTML5 standard — you can watch TEDTalks right in your browser, and also make comments and rate the talks (though you won’t yet have access to our subtitles).

And they don’t appear to have said anything since.

**Comment by bsclifton** [comment]
Works great now 😄
