### ISSUE TITLE
Twitter pages not rendered properly (even with Shields Down)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2700]
Did you search for similar issues before submitting this one?
Yes

Describe the issue you encountered:
Twitter Profile header photo splits Global Navigation bar and Profile Navigation list while scrolling down tweets

Expected behavior:
Profile Navigation list should be displayed when scrolled. Only Global Navigation bar should be displayed.

Platform (Win7, 8, 10? macOS? Linux distro?): 
Windows 10

Brave Version:
0.11.1 64bits

Steps to reproduce:

```
1. Open any twitter profile
2. Scroll down to tweets
3. Header photo splits the global navigation bar and profile navigation list.
```

Screenshot if needed:
Chrome vs Brave
![twitter](https://cloud.githubusercontent.com/assets/17010094/17086458/7ffc7e90-51ea-11e6-9028-fc1a034f7cfa.PNG)

Any related issues:

**Comment by teagueamania** [comment]
Twitter is delivered with mobile interface, rather than appropriate desktop. Brave vs. Chrome:

![bravetwitterview](https://cloud.githubusercontent.com/assets/20600094/17813924/3dd32e86-65e2-11e6-8505-374bd029a686.png)
![chrometwitterview](https://cloud.githubusercontent.com/assets/20600094/17813926/4116af6e-65e2-11e6-8490-46052511f658.png)

**Comment by teagueamania** [comment]
Further: Shields completely off.

**Comment by luixxiul** [comment]
Closing as this is stale
