### ISSUE TITLE
"Save page as" should by default save with Webpage HTML/Complete file type

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2729]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Save page as doesn't save with Webpage HTML/Complete as default extension. Save as all file by default.

**Expected behavior:**
All pages being saved should have a default Webpage HTML/Complete file type when saved
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10.1
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Open any URL
  2. Press Ctrl+S or select Save Page as from File menu
  3. Save file doesn't offer to save the page as HTML/Web Complete page. Instead just give All Files. 
- Screenshot if needed:
  ![saveas](https://cloud.githubusercontent.com/assets/17010094/17152386/732289e0-536f-11e6-8ebc-f44eece1293a.PNG)
- Any related issues: #2231

**Comment by srirambv** [comment]
+1 from support 
> Firefox has a way to DOWNLOAD ALL embedded pictures at once. It also lets you File -> Save Page As - >Webpage Complete. Then I can drill down with my file editor and find the files I want. Brave only lets me right-click on the photos one at a time.

**Comment by JaneSmith** [comment]
I assume this issue is asking for webpages to be saved with an accompanying subfolder containing images, stylesheets, etc. That's the default way Firefox and Chrome work.

I would like to chime in with an additional feature request. I'm not sure if I should post this as a separate issue or not, but it seems quite related.

What I would really love would be support for the **.mhtml format**. This also saves all the accompanying images and such, except it bundles them all into one file together with the webpage, instead of creating tons of different files everywhere. I love the .mhtml format, but neither Firefox nor Brave support it - only Chrome does. For this reason, I'm forced to open up Chrome whenever I want to save a webpage nicely.
