### ISSUE TITLE
Detect/block tracking 1st party beacons

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2764]
**Describe the issue you encountered:** I would like to have an option in the bravery panel to block 1x1 pixel beacons. There are sites on which beacons are used as log-in credentials, so it should be able to detect which one is actually used for logging in and which one is for tracking.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version: 0.11.1 dev build
- Steps to reproduce:
  1. Go to http://chiebukuro.yahoo.co.jp/dir/list/d2080401655/solved
  2. View page source
  3. Look at L881
- Screenshot if needed:
  <img width="708" alt="screenshot 2016-07-29 11 18 17" src="https://cloud.githubusercontent.com/assets/3362943/17235711/3706e3c8-557e-11e6-80ec-d20f657e86ba.png">
- Any related issues:

cc: @diracdeltas

**Comment by luixxiul** [comment]
I'm not sure if my request is legit and how effective the countermeasure can be (1x1 pixel may be replaced with 1x2 pixel, 1x3 pixel, and so on).

**Comment by bsclifton** [comment]
@luixxiul usually these requests would be blocked because the image would be from a 3rd party domain. If it comes from the same parent domain, I don't think there's any way to easily detect/block the image... especially since some people use 1x1 images for spacing (yeah, it's an old technique)

Given the above, it looks like your request is:
Detect/block tracking 1st party beacons?  Do you have more information?

**Comment by luixxiul** [comment]
> Detect/block tracking 1st party beacons?

Yes, I think it should be this one 👍

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1054
