### ISSUE TITLE
Provide an option to clear data folder during uninstalling

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2848]
**Describe the issue you encountered:**
After uninstalling Brave its data still remain in `AppData\Roaming\brave` on Windows. I think some users (especially privacy-oriented users) do not welcome this.

**Expected behavior:**
There should be a dialog which asks users to select if data will be cleared or stored for reinstallation.
- Platform (Win7, 8, 10? macOS? Linux distro?): All platforms
- Brave Version: 0.11.1
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
Also folder inside ``AppData\Roaming\Microsoft\Windows\Start Menu\Programs``. The shortcut was removed but the folder remains.

**Comment by flamsmark** [comment]
Deleting profile info is not a typical uninstall behavior on any of the platforms. I don't think this should be the default because it'll surprise users. I think it makes sense to provide it as an option on two of the major platforms:
- on Windows, the uninstall wizard can offer a checkbox (default: unchecked) to remove all Brave user data
- on Linux `apt purge` (or equivalent) should remove profile info `apt remove` (/c.) should not

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/914
