### ISSUE TITLE
Lastpass input form icon doesn't always open lastpass menu

### ISSUE THREAD

**Issue by mikeyb** [brave/browser-laptop#2916]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Lastpass icon in form fields doesn't always open lastpass menu.  Cannot select a different login on some login forms

**Expected behavior:**
Lastpass menu will open and allow user to select other login credentials
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux Ubuntu 16.04
- Brave Version:
  Brave: 0.11.1
  Electron: 1.2.7
  libchromiumcontent: 51.0.2704.103
  V8: 5.1.281.65
  Node.js: 6.1.0
  Update Channel: dev
- Steps to reproduce:
  1. Visit https://cloud.digitalocean.com/login
  2. Try to click on username/password lastpass icon, nothing happens
  3. (requires more than one login saved in lastpass for specified site)

**Comment by akivatyler** [comment]
Having the same issue...Drop down with list of login credentials doesn't come up. Nothing happens when I click the Lastpass icon in the form field. 

Brave:0.11.4
Electron: 1.3.2
libchromiumcontent:52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev


<img width="368" alt="screen shot 2016-08-12 at 10 11 26 pm" src="https://cloud.githubusercontent.com/assets/21003683/17641553/ca9cfb20-60d9-11e6-8189-c6e3148d70f1.png">

**Comment by bbondy** [comment]
cc @bridiver

**Comment by BCSWowbagger** [comment]
Possibly related to #2936.
