### ISSUE TITLE
PDF rendering fails on Fidelity

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#2919]
**Describe the issue you encountered:**
Clicked the link to a PDF financial statement at Fidelity (https://statements.fidelity.com/). Got error message "invalid or corrupted PDF." More details shows this:

PDF.js v1.5.340 (build: bc86419)
Message: Invalid PDF structure

**Expected behavior:**
Views PDF in a new tab. Works in Chrome. When I downloaded the PDF, it opened fine in Adobe Acrobat. Sorry, obviously don't want to attach the file itself.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X 10.11.6 beta
- Brave Version:
  PDF.js v1.5.340 (build: bc86419)
  Message: Invalid PDF structure

**Comment by bbondy** [comment]
I think this is probably fixed in 0.11.2 already but CC @diracdeltas

**Comment by diracdeltas** [comment]
pretty sure this is fixed in 0.11.2

**Comment by bbondy** [comment]
Please re-open if it doesn't work in 0.11.2 thanks.

**Comment by stshank** [comment]
Sorry, just tried with 0.11.2 and got the same problem. 

Error message:
PDF.js v1.5.364 (build: 81cd66c)
Message: Invalid PDF structure

Brave version:
Brave: 0.11.2
Electron: 1.3.0
libchromiumcontent: 52.0.2743.82
V8: 5.2.361.43
Node.js: 6.3.0
Update Channel: dev

**Comment by bbondy** [comment]
could you attach a pdf here?

**Comment by stshank** [comment]
Sorry, it's a very personal financial statement, so no. If I find other PDFs that break I will, though.

**Comment by stshank** [comment]
I have a somewhat less private PDF that just failed to render. I'll email it to you.

**Comment by copiesofcopies** [comment]
I have this same problem regularly with PDFs accessed via federal courts' electronic court filing systems (essentially the other end of PACER). Today, I filed two PDF documents with the court, then attempted to access the filed versions from the court's system. Both of the documents were created the same way -- just exported to PDF from Word. Brave had no problem opening the first, but gave me this error for the second. This suggests to me that the problem may not be a problem with the structure of the PDF.

Unfortunately, because you need to be authenticated to access the documents, I can't post a link. I'm on v.0.11.4 on Windows 10.

**Comment by diracdeltas** [comment]
do any of the PDFs load if you refresh the page?

**Comment by bsclifton** [comment]
+1 from support; user is reporting issue with PDFs opened from [Xero](https://www.xero.com), an online accounting website

**Comment by jonathansampson** [comment]
I ran into a similar issue this evening after coming across [a Tweet](https://twitter.com/Landing_jobs/status/888226197708173313). I found that the PDF link itself directs the user to GitHub when opened in a new tab. When opened in a new window, however, Brave expects the format to be that of a PDF:

![image](https://user-images.githubusercontent.com/815158/28447717-471cdf00-6d98-11e7-9441-a70ff1dabc2e.png)

**Comment by rebron** [comment]
Closing. wontfix here but fixed in brave core. I have a Fidelity account and checked a couple of statements. The bigger issue is my statement balance is low, should be way larger ;-)

**Comment by ianjohnsa** [comment]
I'd like to reopen this since I am experiencing the same issue with a very similar situation. I am running Brave 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit). I have logged into my account with USAA and when trying to view my statement I get the same error message a the top of the PDF plugin for the new window which should open the embedded PDF of the statement: PDF.js v2.0.673 (build: 31012570)
Message: Invalid PDF structure.

**Comment by jonathansampson** [comment]
@ianjohnsa Does the same scenario work in Chrome?

**Comment by stshank** [comment]
I just tried again on the Fidelity site and also get the "invalid or
corrupted PDF file"
Version 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
I have no trouble using Chrome.

**Comment by bsclifton** [comment]
In the new version of Brave, this should have been fixed with https://github.com/brave/brave-core/pull/967

The issue in the brave-browser repo can be found here:
https://github.com/brave/brave-browser/issues/1033

The older version (Muon) won't be receiving the update
