### ISSUE TITLE
Portable Brave browser

### ISSUE THREAD

**Issue by msiyer** [brave/browser-laptop#2953]
I had been looking for **Firefox** and later **Chromium** binaries so that I could place them on a USB stick\hard drive and move my browser with me (portability). However, I never found them.

I was pleasantly surprised to see **brave** raw binaries available for Linux.   

I would like to suggest the following:
- Have binaries for all platforms available always - a USB stick\hard drive formatted using NTFS can store both Linux and Windows binaries and help the user achieve greater portability 
- Make the binaries collection\archive\compressed file self-sufficient. That is, either they have no external dependencies or the dependencies are well-documented
- If possible, make portable **brave** upgrade itself - [Tor browser (based on Firefox)](https://www.torproject.org/projects/torbrowser.html.en) already does this:

![result](https://cloud.githubusercontent.com/assets/2631325/17423059/2eaa2684-5ad5-11e6-8cd9-bd1a44396268.gif)

**Comment by bsclifton** [comment]
This would be a great thing to offer users :smile: 

cc: @bbondy @bradleyrichter - I'm not sure how this prioritizes but would love to talk more (especially w/ regards to Windows)

**Comment by msiyer** [comment]
@bsclifton I would be glad to help in whatever way possible.

**Comment by bsclifton** [comment]
@msiyer apologies for not responding sooner- Any effort you wanted to put towards this would be appreciated.  To get started, you should be able to get the project building locally and then you can generate the executable and other files by running `npm run build-package`.

Once you have that working, you can try different approaches at your own packaging.  For example: can you simply just take the executable, zip it up, and then use it on another PC?  Any findings regarding this would be appreciated :smile: I'm also curious how well the browser would work if launched from a portable drive, like a USB thumb drive (ex: does it save session properly, etc).

Windows may have an issue about the executable not being signed (where it asks if you're sure you want to run it); Solving that may prove more difficult (ex: we may have to sign it on our side; we maintain a cert at Brave Software for this purpose, but it's not public). Any info would be appreciated :smile:

**Comment by msiyer** [comment]
@bsclifton I tried building brave on Fedora 24, but had troubles with node.js version etc. Got busy after that. Will start building again on Arch this time. Will let you know my findings.

**Comment by msiyer** [comment]
@bsclifton I compiled brave successfully on Fedora 25. The following is my test report:

## Packaging and transport
1. Created an archive (zip) of the compilation output directory, **Brave-linux-x64.zip** 

2. Placed the zip in: 

    - an internal hard drive formatted **ext4**
    - a USB flash drive\pen drive formatted **NTFS**
    - an USB hard drive formatted **ext4**

3. Tested on various virtual machines (VM) and physical machines (PM) 

## Dependencies:
Arch Linux (VM and PM):

   - gconf
   - xss
   - nss
   - libgnome-keyring

Fedora 24 (PM):
    - none

Fedora 25 (VM):
    - none

Fedora Rawhide (VM):
    - none

Ubuntu 16.04 (PM):
    - none

## Saving the session
   - **brave** worked from all storage devices and was not bothered about the **filesystem**
   - the session information are stored in **/home/{USERNAME}/.config/brave**, which is machine specific
   - due to the above fact, the session information are ****not**** transported along with the storage media
   - however, the machine **remembers** session info
   - the session information stored in the machine works irrespective of the device plugged in and its filesystem. That is, a session saved by **brave** stored on a **ext4** formatted USB hard drive works fine with **brave** launched from an **NTFS** pen drive and vice versa.

**Comment by bsclifton** [comment]
@msiyer this is great info, thanks for capturing it! :smile: 

The same should be true for Windows, which stores the session information in the roaming profile folder (`%APPDATA%`)

Would your ideal solution be saving the session locally (and not contaminating the PC that you're logged into)?

**Comment by msiyer** [comment]
@bsclifton yes, the ideal solution will be self-contained in all respects and can update itself.
People can then use this portable system and safeguard their privacy, at least, as far as sessions etc. are concerned.

I would be happy to contribute.

**Comment by hieudang9** [comment]
@Msiyer Thanks for tip in Linux, it would be so great if you have a similar tip for Windows.
Thanks in advance.

**Comment by msiyer** [comment]
@hieudang9 I will try to compile on Windows and test just for the fun of it. However, the findings would be similar.

**Comment by bsclifton** [comment]
One issue with portable, at least on Windows (courtesy of @izzylaif), is that we can't set default browser for a portable instance (per https://github.com/brave/browser-laptop/issues/5246)

**Comment by crazy-max** [comment]
See issue #8691 if you are interested :)

**Comment by bsclifton** [comment]
Per @crazy-max, there is a project [brave-portable](https://github.com/crazy-max/brave-portable)

All instructions are available in the [README.md](https://github.com/crazy-max/brave-portable/blob/master/README.md) of [brave-portable](https://github.com/crazy-max/brave-portable) repository

**Comment by bsclifton** [comment]
Good news: the default browser resetting issue that Windows 10 users experience with portable executables will be fixed with Windows 10 Creators update 1703.  The RuntimeBroker process will not wipe out the default settings, which mean if you launch Brave from a memory stick, etc and configure as the default browser, it will be preserved

Thanks to @izzylaif for confirming (using Firefox portable)

**Comment by sapioit** [comment]
Hi!

It seems there's also [someone on the **PortableApps.com** website](https://portableapps.com/comment/232217#comment-232217) who is willing to make it trully portable. I tried the project from the `brave-portable` repo, but it wasn't fully portable. But since Brave is a Chromium-based browser, I figured it would be easier for someone who can make Chrome portable to make Brave portable.

Oh, and you'd get extra exposure, from their site. Well, you could always talk with the person in charge to have the download file on the official website, if you need it for metrics, and on `PortableApps.com` to have a link to that, so you get an accurate download count, for stats and whatever, but I still think that you can earn more by letting someone else do the extra work instead of you.

**Comment by Timovzl** [comment]
@bsclifton How have you managed to set Brave Portable as the default browser? For me, no portable browser shows under Web browser => Choose an app!

**Comment by sapioit** [comment]
I haven't even spent any more time on it, and haven't used for more than a few hours. 
The browser sounds good, but doesn't works well.

**Comment by luixxiul** [comment]
Please make sure that the `brave-portable` repo is unofficial and not managed by the team.

**Comment by bsclifton** [comment]
@Timovzl no I haven't been able to do that ☹️

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/portable-version/12824?u=eljuno

**Comment by NumDeP** [comment]
I agree with @sapioit - this will certainly bring great exposure and will arguably be the best browser they'll ([PortableApps](https://portableapps.com/)) have in their selection of browsers, truly, post v1 ofcourse. I don't think many users that utilize the portable version of the browsers from PortableApps make the type of modifications and changes as one usually would with a standard desktop browser but seeing as how Brave is quite radically different to most browsers with features such as ad&track blocking and the new Tor functionality given that they're built-in, it would be loved by the community of users. I think it will be seen as a 4-in-1 browser and the better/best choice with one unique feature, being the Tor feature which isn't currently available with greater ease, flexibility and with Brave's portable version, portability.

Not to come of across as rude but I don't think anyone would bother with it right now, as they mostly haven't in almost 2 years and I think that was a really good stance to maintain as least coherently because it would be much better to have this post v1 so other new users weren't and aren't annoyed by Moun/Electron so they can fully appreciate Brave working its best in the full Chromium environment and I wish a post v1 label is put on so it can immediately be advertised and implemented in PortableApps there after.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/694
