### ISSUE TITLE
Dropbox PDF files are not loaded when fingerprint protection enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2987]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Dropbox PDF files doesn't load when Fingerprinting protection is enabled.

**Expected behavior:**
Should load PDF files
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64 
- Brave Version:
  0.11.2 Dev RC2
- Steps to reproduce:
  1. Enable Fingerpritning protection
  2. Open [this file](https://www.dropbox.com/s/ug3m5cgw3m08r23/Sample.pdf?dl=0) 
  3. File is not displayed.
  4. Open [this file](https://www.dropbox.com/s/ab7vqvi09u49mzp/pdf.pdf?dl=0) 
  5. File is opened properly. 
- Screenshot if needed:
  File 1 error in Dev console
  ![image](https://cloud.githubusercontent.com/assets/17010094/17439632/eafe1e6c-5b20-11e6-88f4-0ee8e637e8e1.png)

File 2 error in Dev console 
![image](https://cloud.githubusercontent.com/assets/17010094/17439591/ba411bee-5b20-11e6-8229-5c4e572ec335.png)

cc: @diracdeltas

**Comment by bsclifton** [comment]
Somewhat similar to https://github.com/brave/browser-laptop/issues/2965

For sure, web sites visited may experience issues with fingerprint protection enabled (which we could communicate better).  The interesting thing about this issue is that you're simply loading a PDF, not processing HTML.

Should fingerprint protection stop when you download/open a file (which then executes PDF.js in this instance)? Maybe since PDF.js could be exploitable and the user did opt-in to having fingerprint protection enabled, we should not allow loading PDFs when feature is enabled (and communicate this via message box or icon, etc).

**Comment by srirambv** [comment]
Also File 1 only loads when FP protection is disabled but File2 open up even if FP protection is enabled. Checked with couple of other file it loads but the the file loading animation persist even after the page is loaded.

**Comment by srirambv** [comment]
Similar issue when opening files from MediaFire 

![image](https://cloud.githubusercontent.com/assets/17010094/17443580/44bd7e22-5b33-11e6-8ec0-7586b65f2a61.png)

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/dropbox-pdf-files-are-not-loaded-when-fingerprint-protection-is-disabled/10592
