### ISSUE TITLE
Spotify WebPlayer doesn't work even with flash installed.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3011]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Spotify WebPlayer doesn't work even with flash installed. 

**Expected behavior:**
Web Player should not throw install flash messag.

Works on Chrome and Opera

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, OpenSuse 42.1 x64, Windows 7 x32

- Brave Version:
0.11.3 

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

Chrome vs Brave
![image](https://cloud.githubusercontent.com/assets/17010094/17457071/3ce35eb8-5be4-11e6-90e4-dc61abd394e8.png)

Console Error 
![image](https://cloud.githubusercontent.com/assets/17010094/17457055/bf24225a-5be3-11e6-897f-829bbb427e83.png)

- Any related issues:
[3006](https://github.com/brave/browser-laptop/issues/3006#issuecomment-238023211)

**Comment by srirambv** [comment]
Verified on Windows machine. Working as expected for 0.11.4 RC1 build

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/47889847-f63a6f80-de43-11e8-9bb0-3d7cf99d1b53.png)

This leads to [this support article](https://support.spotify.com/uk/using_spotify/system_settings/enable-the-spotify-web-player/)

But the option it lists is already on.

**Comment by bsclifton** [comment]
@ChildishGiant @angezanetti I believe you're both using the new version of Brave (this repo is for the old Muon version)

I think the root cause may be that Widevine is not enabled. You might try visiting https://netflix.com or https://hulu.com and looking for a puzzle piece in the right side of the omnibar. You can then opt in to enabling Widevine.  We have an issue captured to make this more obvious, which you can track here:
https://github.com/brave/brave-browser/issues/1940
