### ISSUE TITLE
Titlebar on Windows has a lot of wasted space

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3036]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave on Windows has a lot of titlebar bloat. Here are some screenshot demonstrating that:

Windows 10
![screen shot 2016-08-08 at 8 04 52 am](https://cloud.githubusercontent.com/assets/4733304/17484476/e253f776-5d3e-11e6-8cbe-93193a8d6fe8.png)

Windows 7
![screen shot 2016-08-08 at 8 17 49 am](https://cloud.githubusercontent.com/assets/4733304/17484881/cb8951ba-5d40-11e6-828a-60427ab8680c.png)

In order to show the minimize/maximize/close buttons, Windows requires you to add the WS_CAPTION style to the window, which also adds the titlebar and the icon.

Electron has a [frameless mode](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md) but unfortunately that doesn't have the minimize/maximize/close buttons (and it doesn't support menus). While [working on a proof of concept](https://github.com/bsclifton/BrowserWindowStyles), I discovered the possibility exists to manually render these elements using Windows API, but there are complications.

The resolution for this issue needs to:

* Create the BrowserWindow object as frameless
* Manually render the caption buttons
* Manually render the menu
* Only update Windows; no changes are desired on Mac/Linux

**Expected behavior:**

Windows 10 (and 8) UI layout:

![image](https://cloud.githubusercontent.com/assets/13509546/18258104/40c3c1be-7384-11e6-9201-8a9b35b0b873.png)

Windows 7 UI layout:

![image](https://cloud.githubusercontent.com/assets/13509546/18258108/6a8ceb56-7384-11e6-9244-626000bb0fa9.png)

- Platform (Win7, 8, 10? macOS? Linux distro?):
All Windows platforms

- Any related issues:
https://github.com/brave/browser-laptop/issues/2386

**Comment by KillianKemps** [comment]
I would say the issue is not Windows-only. Here it is the same on Linux.

Screenshot on Arch Linux with Gnome: 
![screenshot from 2016-08-10 09-38-01](https://cloud.githubusercontent.com/assets/6884630/17545571/17ac7858-5ede-11e6-920d-bcfad62ef98c.png)

Screenshot on elementaryOS (based on Ubuntu):
![screenshot](https://cloud.githubusercontent.com/assets/6884630/17545838/4ade6712-5edf-11e6-9331-7e0cb0df656d.png)

**Comment by bbondy** [comment]
Linux should be posted separate since it is completely distinct work, and will be prioritized separately. Thanks!

**Comment by bsclifton** [comment]
What @bbondy said- it would be great if you can create a separate issue, @KillianKemps.  But definitely, thanks for reporting! I personally haven't used Brave on anything other than Ubuntu, so it's great to know it can be improved too

**Comment by KillianKemps** [comment]
Alright I understand, I've created a new issue for Linux: #3126

**Comment by Sh1d0w** [comment]
Hi guys. I've quickly implemented custom title bar, with minimize, maximaze and close actions. It also supports dragging and double click maximizing in the new title.

Tested on Linux. If someone can help with testing on Mac and Windows it will be very helpful. See my PR I have rised in order to run it locally and test.

Also I accept suggestion on styling, will upload a video shortly of the current look and feel :)

cc @bbondy @luixxiul @bradleyrichter @bsclifton

**Comment by bsclifton** [comment]
@Sh1d0w that's pretty interesting and it looks pretty good.  This functionality would only be needed on Windows and later on Linux (not needed on Mac).  The goal was to have pixel perfect versions of the native OSes buttons show in the top right.

@bradleyrichter @bbondy what do you think? Would having our own styling be an option, rather than using the OSes native window kit?

**Comment by bradleyrichter** [comment]
@Sh1d0w Your video above is showing this new toolbar on a Linux flavor which is running a macOS theme, correct?

If yes, then this is interesting. Can you show us how it looks with the default theme?

**Comment by bradleyrichter** [comment]
@bsclifton No, we need to conform to the OS standard window controls in the proper place for each OS, mainly for usability reasons.

**Comment by Sh1d0w** [comment]
@bradleyrichter Yes, this is Fedora 24 with macOS theme. Here is how it looks with v0.11.4 and without my changes

<img src="https://s10.postimg.org/wrqpds3eh/Screenshot_from_2016_08_12_05_42_43.png"/>

What about a setting just like chrome does it right now? Wich chrome you have the option to choose to use the syste theme border or the chrome theme, which removes and places custom buttons at the top? I think this way we will give the people the choice to have more compact view or to stick with the default one if they prefer it.

I will research however if it is possible to access the system current theme properties via electron in order to have the system theme's look and feel out of the box and willl get back if I find something.

cc @bbondy

**Comment by Sh1d0w** [comment]
PS: @bsclifton on macOS we have the following:

On macOS 10.10 Yosemite and newer, there’s an alternative way to specify a chromeless window. Instead of setting frame to false which disables both the titlebar and window controls, you may want to have the title bar hidden and your content extend to the full window size, yet still preserve the window controls (“traffic lights”) for standard window actions. You can do so by specifying the new titleBarStyle option:

Do you want me to implement this in my PR for macOS only? Please let me know and I willl do :)

**Comment by bsclifton** [comment]
@Sh1d0w the final call on whether or not we can use a non-OS styled theme lies with @bradleyrichter and @bbondy. When discussing with them earlier today, the consensus was a no-go for this PR- even though it looks pretty nice (and we definitely do appreciate it, trust me :smile:). It's a requirement for us to have the OS specific controls

The Mac version seems to be great as-is; it's basically frameless and the menu lives in the actual system menu on top. Here's a screenshot:
![screen shot 2016-08-11 at 9 11 14 pm](https://cloud.githubusercontent.com/assets/4733304/17612558/30f08f72-6008-11e6-8bd1-c9e93339c402.png)

You're absolutely right- the Linux and Windows versions use too much space :frowning: I opened the following issue in Electron which I encourage you to look at.
https://github.com/electron/electron/issues/6823

I need help understanding where to make the changes; maybe we can work together? :smile: I understand win32 very well but don't have much experience w/ X11 and Cocoa. The approach I am trying to take in electron would be using native API calls to get the bitmap and rendering it over the window contents, as if it were a non-client area. This could then be exposed on the BrowserWindow object so that other Electron users could benefit from it too

Let me know what you think and thanks again :smile:

**Comment by Sh1d0w** [comment]
@bsclifton Thanks for your comment. Unfortunately I am not that deep into the X11 stuff. What I know is that on Gnome desktop for example, as I suppose every other Linux desktop you can install different themes. Each of those themes are defined by CSS styles inside the themes.

In GTK you have `gtk_widget_get_style()` function, which fetches the current theme styles. Once we have them we can easily parse them and apply the styles to the buttons. Worth researchng also what should be the HTML structure for the buttons in Brave to be consistent with the styling.

This are only assumptions, as I said I haven't developed any GTK apps, despite I have read a lot how to.

Have you guys considered my suggestion to implement setting that turns my modification on/off? Since it is a common practise in Google Chrome for example? They have implemented the same thing - by default Chrome uses the system theme, but you have option to switch to completely custom Chrome theme with custom buttons at the top? This will keep as it is now, but will give the change to users like us who don't like the gap and the space waste :)

cc @bbondy @bradleyrichter

**Comment by bsclifton** [comment]
I understand the Google Chrome way- they allow you to customize the look and feel by offering themes.  We don't offer that yet...  but we do have several issues asking for functionality like this:
https://github.com/brave/browser-laptop/issues/1090
https://github.com/brave/browser-laptop/issues/473
https://github.com/brave/browser-laptop/issues/271

I think the only approach that would work is making the change at the electron level. We [maintain a fork of electron here](https://github.com/brave/electron) that I am looking at now. The [issue I shared above](https://github.com/electron/electron/issues/6823) is in the upstream repo- I'm hoping the maintainers can help me find a solution using the native controls.

For now, we can close the PR. But thank you for the thought and consideration that you put into it :smile:

**Comment by Sh1d0w** [comment]
@bsclifton No problems, thank you for your time. I will keep eye on this thread as I became very curious about the outcome :smile:

**Comment by bsclifton** [comment]
UPDATE: the electron route is a much longer term route. The great changes implemented by @Sh1d0w are being refined and will likely be accepted to close this issue :smile: 

For more info or to participate, check out his PR https://github.com/brave/browser-laptop/pull/3133

**Comment by bsclifton** [comment]
@Sh1d0w- I closed your PR after making progress with Windows API route. Shortly after, I ended up [getting stuck again](https://stackoverflow.com/questions/39319441/parts-drawn-with-drawthemebackground-on-windows-10-are-not-correct). After talking with the team, we'd like to manually render the content for Windows (and revisit the Windows API route).

I have your commits pulled into my branch and will use them as a starting point :smile: I'll be trying to match the above that @bradleyrichter created (may include small CSS tweaks) and will also be adding a menu (mockup TBD).

**Comment by Sh1d0w** [comment]
@bsclifton Cool I am glad I could help in some way. I hope you guys don't release this as windows only feature, as in my branch the component I've wrote can be reused for Linux build as well. Personally for each version of Brave I am building it from my branch so I can get a compact and polished look.

But it will be good to see it in the official build as well. Please don't leave Linux version behind and consider this for the 1.0.0 release :)

**Comment by bsclifton** [comment]
Definitely not perfect, but made some great progress matching the styles w/ CSS:

Windows 7 look
![windows7](https://cloud.githubusercontent.com/assets/4733304/18343079/b2378f54-7566-11e6-9526-048bc3d0eb00.png)

Windows 10 look (will be also be used for Windows 8/8.1)
![windows10](https://cloud.githubusercontent.com/assets/4733304/18343003/4bd34cb2-7566-11e6-92e4-4032befdc3e7.png)

cc: @bradleyrichter 

I'll get started on the menu control tomorrow :smile:

**Comment by bsclifton** [comment]
Here's how it looks with custom menus (still a work in progress- will wrap up soon!)
![screen shot 2016-09-09 at 7 54 33 am](https://cloud.githubusercontent.com/assets/4733304/18391447/ceb71fe4-7662-11e6-8bc6-9adfe3cd698f.png)

**Comment by bsclifton** [comment]
One concern I wanted to capture (before forgetting)- electron doesn't put a border around the window (we can fix this). Some small nitpicks regarding that:
* Windows 10 always puts a 1 pixel border with the users highlight color around each window... instead, a box shadow is drawn (which looks nice, but isn't consistent with OS)
* Windows 7 doesn't use any effects around the border and when you're on a white page, it can be really confusing- because there is no borders and the white will blend in (making it hard to tell what is in the browser and what isn't)

**Comment by bradleyrichter** [comment]
@bsclifton Let's add the border so that we achieve conformance with panache. :   )

**Comment by bbondy** [comment]
moving to 0.12.2

**Comment by bsclifton** [comment]
Heading towards the finish line on this one... here are some updated screenshots:
![screen shot 2016-09-12 at 2 57 31 pm](https://cloud.githubusercontent.com/assets/4733304/18454475/76231e34-78f9-11e6-90ed-80bcf760a99e.png)

![screen shot 2016-09-12 at 2 58 32 pm](https://cloud.githubusercontent.com/assets/4733304/18454480/7be2b0aa-78f9-11e6-85a1-56dbd8839f2a.png)

**Comment by bsclifton** [comment]
screen cap showing the menu being toggled and used
![windows-titlebar](https://cloud.githubusercontent.com/assets/4733304/18482947/0be32d36-7997-11e6-8f99-7f0d868c6145.gif)

**Comment by bsclifton** [comment]
@bradleyrichter here's a version that keeps the lion on the right
![windows-titlebar2](https://cloud.githubusercontent.com/assets/4733304/18496833/3b223d8e-79de-11e6-98ab-766ac46e5664.gif)

Thoughts?
