### ISSUE TITLE
Clear Browsing History better

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3065]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Clear Browsing Data now doesn't delete browsing history. Page history still visible when back/forward button is long pressed.

**Expected behavior:**
Should clear browsing history as expected.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64 
- Brave Version:
  0.11.4 Dev RC1
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
  ![ezgif-2505718510](https://cloud.githubusercontent.com/assets/17010094/17532920/a1cd71f4-5e7a-11e6-94d3-ec57f09b1feb.gif)
- Any related issues:

**Comment by bbondy** [comment]
ya this, nor the clear cache option we had before doesn't clear back-forward cache on webviews, only the history that we store. This is valid but not new.

**Comment by bbondy** [comment]
the browser history is still available in the history property on the frame. after i clear browser history, my session-store-1-dev file has entries like:

"frames":[{"canGoBack":false,"canGoForward":false,"computedThemeColor":"rgb(51, 51, 51)","endLoadTime":1470784542553,"findDetail":{"caseSensitivity":false,"searchString":""},"fingerprintingProtection":{},"history":["http://samy.pl/evercookie/","https://www.google.com/#q=abcdyahoo","https://www.google.com/#q=abcdyahoo","https://www.bing.com/"], ...


Also for closedFrames.

**Comment by NumDeP** [comment]
When members find the time to work on this further, could you have a look at the following suggestions because I think the term 'better' can be referenced to these.

- https://community.brave.com/t/secure-cleaning-of-browser-data/1734/9

- https://community.brave.com/t/secure-overwriting-of-deleted-data-deletion-of-browsing-history-and-such/5102

**Comment by NumDeP** [comment]
One other thing I'd like to point out as it may come across as a contradiction but related to the 'description encountered' is that in relation to closing a tab, I think 'clear' should not be regarded as 'immediate' as the function is currently set, meaning it's better to have it set to clear soon, like a 5 second rule because there's been numerous times where by I've accidentally closed a tab but reopened the tab immediately but could backspace; I can't be the only one who closes tabs and reopens them just to backspace, you're allowed to do so in other popular browsers so personally I think a rule of some kind should be implemented. Thanks.

**Comment by luixxiul** [comment]
> where I've accidentally closed a tab but reopened the tab immediately but couldn't backspace

that issue is actually tracked on https://github.com/brave/browser-laptop/issues/2702

**Comment by NumDeP** [comment]
@luixxiul I removed the comment about the backspace like an idiot, rather than confusing anyone who reads this further you should just remove the comment as well.

**Comment by kjozwiak** [comment]
This might be out of scope, but closing all currently opened tabs/windows when "Clearing All" could be super useful. I've been bitten a few times where I cleared the history, the browser was restarted and I accidentally hovered over a discarded tab which was then placed back onto `about:history`.
