### ISSUE TITLE
Add On/Off to the switches

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3108]
From support:

> As a new user to Brave, the Preferences settings are unclear. Does gray mean off and orange on or vice versa. Adding the words On and Off or giving me some very clear indication of the setting would be helpful. A summary of the settings to the right would also work.

**Comment by bradleyrichter** [comment]
I think we should track this but I don't expect it is a widespread issue. iOS has the ability to show similar labeling but they are off by default. 

The standard pattern in all OS switches is left=off, right=on (regardless of color)

Adding something like this ads too much visual noise to the UI in my opinion:

![image](https://cloud.githubusercontent.com/assets/13509546/17604729/e9003032-5fcb-11e6-91ee-770cbadb2356.png)


There will be some users who are confused by the orange color but it should also be minimal. Eventually we may add a pref to allow a user-definable theme color for those who prefer blue, green or purple for titles, switches and pref-tab colors.

**Comment by bbondy** [comment]
I'm surprised this is confusing for people, maybe just a title attribute that says on or off if you hover over the switch would be enough so we don't uglify it with the above?

**Comment by bradleyrichter** [comment]
I doubt it will confuse many. Let's keep an eye on it and not make any changes or new work unless it becomes a problem.

This user may be accustomed to the Windows approach but let't not go there yet.

![image](https://cloud.githubusercontent.com/assets/13509546/17636719/e383ec5c-6093-11e6-8c27-9774d6605e55.png)

**Comment by bsclifton** [comment]
Maybe there would be a better way to approach this- like from a high contrast mode perspective. It would be great to have a mode where everything is crystal clear (regardless of visual impairment)

One thing that could be interesting to consider (I say interesting because I am far from an expert; my experience is very limited)...

Since all of our about pages are HTML... we could consider the a11y of our pages via a screen reader. Maybe we can double check to ensure the proper attributes are tagged on our elements so that a screen reader finds them too

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-add-on-off-to-the-switches/10091

Let's reopen if we get some positive reactions there 😄
