### ISSUE TITLE
Question: Any plans to enable custom protocols in electron or via extensions?

### ISSUE THREAD

**Issue by joshuef** [brave/browser-laptop#3123]
When attempting to add a custom protocol to brave source (in `app/index.js` for example), I can access `electron.protocol`, and `protocol.registerStandardSchemes` exists, but there's no ability to register a handler. Errors are thrown on `npm start`: `TypeError: protocol.registerHttpProtocol is not a function`.  (`protocol.registerHttpProtocol` would normally allow for this, and exists in the [electron apis](http://electron.atom.io/docs/api/protocol/) ).

Doing this either throws the above error before `app` is 'ready', or `app.on( 'ready', ... )`, just kills brave altogether.

Are there any plans to open up this API in the browser source? Or perhaps enable it for extensions? (I didn't see a way to do that right now, extensions are based off chrome, no? Which also blocks custom protocol handling....)

Or am I missing the correct way of implementing this?

Thanks for any info!

**Comment by diracdeltas** [comment]
i think @bbondy added or is adding support for window.navigator protocol registration

**Comment by joshuef** [comment]
I saw the recent protocol [addition](https://github.com/brave/browser-laptop/issues/1583) for `:bitcoin` and `mailto:` handling, but I'd like to be able to register a protocol on the app level, utilising `electron. registerHttpProtocol`, which currently doesn't exist in the brave fork of electron.

Is there any chance of this being implemented?

**Comment by bbondy** [comment]
If you can convince upstream to add a dependency on KeyedService and to take in a PR then I'd be happy to help upstream. You should get buy in for that on that repo then cc me in there. 

We only had KeyedService which this needs now because we have extensions and upstream said they wouldn't take extensions support unfortunately.  We can do a PR that has KeyedService dep and this though without extensions.
