### ISSUE TITLE
Maximize / Fullscreen status is not saved

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3138]
From support:

> I am running Brave 0.11.3 on Windows 10, and I noticed that the browser window does not stay maximized after shutting down the program and re-opening it. I prefer all of my browser windows to be maximized (not full-screen) when I open them. Could you ensure that the browser window maintains its previous window setting when it is reopened?
> 
> I have upgraded to 0.11.4 and am still having the same issue.

IIRC the issue has been fixed with #2181

**Comment by Kirvx** [comment]
Same problem with the 0.11.6 version.
Windows 10 x64.

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6264

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6648

**Comment by bsclifton** [comment]
I suspect this is due to the user picking "Home Page" as "Brave starts with".

Issue was originally fixed with https://github.com/brave/browser-laptop/pull/2029, but unfortunately window state is not saved when you pick "Home Page" as your option (since it doesn't need to restore previous windows; it'll just open your home page)

The fix for this can be similar to what was done in https://github.com/brave/browser-laptop/pull/5102

**Comment by luixxiul** [comment]
Closing in favor of #8600
