### ISSUE TITLE
Monster Job portal breaks when Ad/Tracker is enabled.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3144]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Monster Job portal breaks when Ad/Tracker is enabled.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.4
- Steps to reproduce:
  1. Open https://monster.com
  2. Select United Kingdom - Page render fails as CSS and JS files are blocked
  3. Go back and select United States - Page is rendered properly
  4. Go back and select Austria-  Page render fails as CSS and JS files are blocked
  5. Go back and select Denmark - Page is rendered properly
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/17614210/55111e5e-605c-11e6-9cab-e4e8b40e450a.png)
- Any related issues:
  #2985 #2838

**Comment by lukemulks** [comment]
Hi @srirambv 

I've investigated this, and I'm unable to reproduce in the same way. 

I'm able to consistently reach the international Monster.com pages, with ad blocking and tracking enabled. 

When I reach those pages, I'm also seeing the same domains blocked by our shield settings: 

```
- https://securemedia.newjobs.com/global/img/icons/adchoices.gif
- https://oas.monster.com/Scripts/oas_analytics.js
- https://nexus.ensighten.com/monster/Bootstrap.js
- https://dpm.demdex.net/id?d_rtbd=json&d_ver=2&d_orgid=A86C525A548992260A4C98C6%40AdobeOrg&d_mid=02491370548177218446005561080690558054&d_cb=s_c_il%5B1%5D._setAudienceManagerFields
- https://secure.jdn.monster.com/render/adimage.aspx/can.js
- https://newjobs.d1.sc.omtrdc.net/b/ss/newjobsprodseekeruk/1/H.27.5T/s39703883031088?AQB=1&ndh=1&t=17%2F2%2F2017%2016%3A22%3A48%205%20420&sdid=2A786AE443FB4816-0AD644D47A0A3F3E&mid=02491370548177218446005561080690558054&ce=UTF-8&ns=newjobs&pageName=desktop%7Cuken%7Clpf%7C%2Flpf-medley&g=https%3A%2F%2Fwww.monster.co.uk%2Fjobs%2F&r=https%3A%2F%2Fwww.monster.co.uk&cc=GBP&ch=200&c1=D%3Dg&v1=D%3Dg&v2=unrecognized&v4=0&v44=COMP%3ANone_CAT%3ANone_KW%3ANone_LOC%3ANone_JSE%3AMEDLEY-medley&v69=CardView&c75=m1&l3=ViewSplit_CardView%2CRecentSearchSplit_Default&s=1920x1080&c=24&j=1.6&v=N&k=N&bw=1918&bh=984&AQE=1
```

Monster: Canada: Shields Up
![brave-monster com-webcompat-can-03172017](https://cloud.githubusercontent.com/assets/8979240/24066376/54ae2ab4-0b2f-11e7-8567-8531b3c50060.PNG)

Monster: France: Shields Up
![brave-monster com-webcompat-fr-03172017](https://cloud.githubusercontent.com/assets/8979240/24066378/58aecc90-0b2f-11e7-836f-13e13216ac91.PNG)

Monster: Germany: Shields Up
![brave-monster com-webcompat-ger-03172017](https://cloud.githubusercontent.com/assets/8979240/24066396/7924d0fa-0b2f-11e7-977c-75ecf6908d43.PNG)

Monster: Netherlands
![brave-monster com-webcompat-netherlands-03172017](https://cloud.githubusercontent.com/assets/8979240/24066409/98ce909e-0b2f-11e7-92a5-2423a9c7a2f0.PNG)

That said, I did run into a few cases where the US Monster.com page failed to load, which appeared like this in Brave: 
![brave-monster com-webcompat-us-error-03172017](https://cloud.githubusercontent.com/assets/8979240/24066418/ae9a5a0c-0b2f-11e7-9731-8742ffcd7c16.PNG)

When I started inspecting the console when this happened (twice out of ~12 page loads), I started noticing these document.write violations that Chromium is now flagging in the Console: 

```
Violation] Parser was blocked due to document.write(<script>)
(anonymous) @ (index):79
www.monsterboard.nl/:79 A Parser-blocking, cross-origin script, https://securemedia.newjobs.com/js/sc/targetsitecatalystLL.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.

(anonymous) @ (index):79
www.monsterboard.nl/:79 [Violation] Parser was blocked due to document.write(<script>)
(anonymous) @ (index):79
www.monsterboard.nl/:79 A Parser-blocking, cross-origin script, https://securemedia.newjobs.com/js/sc/targetsitecatalystLL.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.

(anonymous) @ (index):79
targetsitecatalystLL.js:75 [Violation] Parser was blocked due to document.write(<script>)
Nf @ targetsitecatalystLL.js:75
(anonymous) @ targetsitecatalystLL.js:75
targetsitecatalystLL.js:75 A Parser-blocking, cross-origin script, https://cdn.tt.omtrdc.net/cdn/target.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.

Nf @ targetsitecatalystLL.js:75
(anonymous) @ targetsitecatalystLL.js:75
targetsitecatalystLL.js:75 [Violation] Parser was blocked due to document.write(<script>)

Nf @ targetsitecatalystLL.js:75
(anonymous) @ targetsitecatalystLL.js:75
targetsitecatalystLL.js:75 A Parser-blocking, cross-origin script, https://cdn.tt.omtrdc.net/cdn/target.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
```

IIRC, Brave blocks `document.write` with shields enabled, as there are security risks and perf issues around `document.write` invocations. 

Chromium also has an experimental flag that can be enabled to disable `document.write` invocations within the browser, which is an indicator that the browser is likely going to be sunsetting support. 

Additionally, the violations provide another indicator that document.write is on the way out. 

All the above leads me toward this being more of an issue with large-scale compatibility with `document.write`, as opposed to specific shield blocking settings. 

**I've found a workaround when I was investigating this:** 

- If the user gets stuck at the error page, they can manually key the URL into the URL field, and the user should be able to access the monster.com URL. 

Given the amount of time that has passed between when this issue was created and now, it could be that this was happening more frequently then, and that it's less reproducible as the site may have taken steps to replace calls that use document.write. 

This is probably a safe one to close at this point. I'm going to close it, but if you're able to consistently repro on your side, feel free to open it again and let me know. Totally down to team up on getting this resolved if what you're seeing is more regional than what I'm experiencing.
