### ISSUE TITLE
Can't view images on prntscr.com

### ISSUE THREAD

**Issue by Rollerdl** [brave/browser-laptop#3176]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Images will not show on prntscr.com
**Expected behavior:**
Should be able to view images.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS/OS X  10.11.6
- Brave Version:
0.11.4
- Steps to reproduce:
    1. click on a link to prntscr.com
    2. wait for page to load
    3. once page loads the image doesn't display

- Screenshot if needed:
![d21a69a8e5dd4c05bd4734ef53d62296](https://cloud.githubusercontent.com/assets/21024630/17650461/c05606b8-621c-11e6-8cc2-55f4d5383de2.png)

- Any related issues:

**Comment by neeklamy** [comment]
The issue here is caused by a combination of HTTPS Everywhere and some peculiar website design.

- Visiting the site using Brave’s default settings, we’re directed to https://prnt.sc.
- Individual screenshot pages use an `iframe` pointing to another domain, `http://printscr.com`.
- Because the enclosing document is over the `HTTPS` protocol, the child iframe isn’t loaded, the error from Brave’s dev tools:

  > **Mixed Content:** The page at 'https://prnt.sc/1iais' was loaded over HTTPS, but requested an insecure resource 'http://prntscr.com/image.html'. This request has been blocked; the content must be served over HTTPS.

Steps to reproduce:

- Try viewing this page: https://prnt.sc/8wazka – where the image should appear, it’s broken,
- Click on the Bravery menu → disable **HTTPS Everywhere**,
- Hack the URL to remove the `s`, hit <kbd>Enter</kbd>,
- It works!

It looks like the only way this could be fixed right now is to have a special exception for this site, the images are served up on yet another domain which can’t even be accessed over HTTPS.

From that URL above, the image is kinda here*, http://img.prntscr.com/img?url=http://i.imgur.com/xpTaj0C.jpg. Try hacking the URL, you’ll get redirected to the HTTP protocol.

\* Hosted by Imgur, oh my head…

**Comment by Rollerdl** [comment]
Thank you very much. All I had to do was disable **HTTPS Everywhere** for that site and it excepts and displays any screenshot on there without needing to hack the URL to remove the "s". I assume this a resolved issue so I will close this issue.
