### ISSUE TITLE
popyard.org pictures does not display properly

### ISSUE THREAD

**Issue by xiaohanzhu** [brave/browser-laptop#3181]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
when visiting popyard.org, the pictures on the site do not display properly unless to bring down the brave shield.
**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.4
- Steps to reproduce:
  1. go to www.popyard.org
     2.
     3.
- Screenshot if needed:
- Any related issues:

**Comment by xiaohanzhu** [comment]
Chome with ADB display the pictures on the website properly.  It must be a fixable bug.

**Comment by SergeyZhukovsky** [comment]
There is a screenshot
<img width="1254" alt="screen shot 2017-02-27 at 9 18 54 am" src="https://cloud.githubusercontent.com/assets/12011303/23365856/a58ade66-fcd2-11e6-8b07-bf4960c4e066.png">

**Comment by jonathansampson** [comment]
The problem here appears to be with the `Referer` header being sent when images from moremorewin.net are requested. When the _referer_ is http://www.moremorewin.net, the long-page image is returned. When the _referer_ is http://www.popyard.org, the proper image is returned.

When _Block 3rd Party Cookies_ is enabled, the Brave sets the referer to moremorewin.net. When _Allow all cookies_ is selected, Brave sets the referer to popyard.org for these image requests.
