### ISSUE TITLE
Add a bookmarks bar

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#319]
<img width="818" alt="screenshot 2016-01-25 07 26 01" src="https://cloud.githubusercontent.com/assets/831718/12550939/e7237ef6-c334-11e5-881e-9675bbca6cad.png">

There's an early spec.  The UI has changed since then obviously. 
You should be able to show/hide the bookmarks bar via a context menu in the navigation area.
The Bookmarks menu can also change to have a Show Bookmarks option since bookmark's management will come a lot later.

Also domain alone will not work as the screenshot does because many people bookmark for example 2 wikipedia pages, so we should do page title I think and probably favicon.

**Comment by SJ-Diamond** [comment]
Since we are speaking about bars, what would be too nice would be a full status bar, a side bar and add-on bar.

That is anyway a large problem of Chromium - Chromium devs do not understand that an optional side bar can be of great use, same like an optional bar for add-on icons, more place for them ;)

**Comment by bbondy** [comment]
Would be best to propose those ideas in different issues so they can be discussed independent of this task. Thanks!

**Comment by adamcweitzman** [comment]
I can't seem to add the bar, just downloaded latest prod. version yesterday

**Comment by weems** [comment]
@adamcweitzman still a WIP I think.

**Comment by bbondy** [comment]
This was implemented a while ago, closing.
