### ISSUE TITLE
Different color app logos by release channel

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3233]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

It would be nice if each release channel had a different color app icon so when you had say a build version and a prod version open you can differentiate. It might also be nice if we can rename the app so it said something like Brave (dev) when tabbing through open apps.

**Expected behavior:**

It might be nice if the dev build was grey and the prod build stayed orange.
- Platform (Win7, 8, 10? macOS? Linux distro?):

All
- Brave Version:

All
- Steps to reproduce:
  1. Open production brave
  2. npm start dev brave
  3. No visual way to tell the difference.
- Screenshot if needed:

![img_3993](https://cloud.githubusercontent.com/assets/490294/17750525/c0bf4198-6477-11e6-8768-93685234142e.JPG)
- Any related issues:

**Comment by bsclifton** [comment]
Would be a super easy one for anyone looking to get their feet wet :smile: 

@bradleyrichter can help provide guidance for alternative colors. The resources are located at https://github.com/brave/browser-laptop/tree/master/res; we'd just need new colorized icon for the DEV channel (gray won't work because that is the shields down color)

Mildly related, updating the icon for the installer on Windows- https://github.com/brave/browser-laptop/issues/2763

**Comment by bradleyrichter** [comment]
I have a task to update the app icons for 1.0 so I will try to create a variation to solve this need as well.

**Comment by Liunkae** [comment]
The icons have been posted at #4120.

**Comment by Liunkae** [comment]
I think this has been implemented. I see the dev icon on the latest master.

**Comment by Liunkae** [comment]
I'm not sure how/when this was implemented, but I'll close this issue.
