### ISSUE TITLE
Restoring from a state with 0 windows on macOS should remember position of last window

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3247]
We do have code for remembering window placement for new windows but it doesn't seem to be used with the following steps:

- Launch Brave.
- Open one window. Move it to the left side of the screen.
- Close the one window.
- Quit Brave.

Actual results:
Launch Brave. A new blank window should open in the center of the screen. 

Expected results:
It should be on the left side, where you last window was.

**Comment by bbondy** [comment]
cc @bsclifton

**Comment by bsclifton** [comment]
This makes sense- the position is part of the WindowState, which gets discarded when closed.  When it's time to quit, an event is fired and Brave will save the WindowState for any open BrowserWindows (which there are none anymore).

Doesn't happen on Windows/Linux because closing the last window will close the app

We could save this as part of the AppState?

**Comment by bbondy** [comment]
We already store defaultWindowWidth and defaultWindowHeight in app storage, so it should just be updating that I think.
