### ISSUE TITLE
Make pressing Esc in address-bar return focus to viewport (Enhancement)

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3248]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If the address-bar has focus, there is no way to switch focus to the viewport by using the keyboard.

**Expected behavior:**
In Firefox, pressing Esc eventually returns focus to the viewport.

This is also the case in Opera.

In Chrome, there is a workaround using Cmd+P to open the Print dialog and then pressing Esc to close it, but that doesn't work in Brave.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.11.5
- Steps to reproduce:
  1. Open a page
  2. Switch focus to the address bar by pressing Cmd+L
  3. Try to return focus to the viewport by pressing Esc several times
  4. Try to return focus to the viewport by pressing Tab

Expected: Focus is returned to the viewport after 1-3 presses of Esc or Tab

Actual: Focus remains in address-bar

**Possibly related issues:**
#2920, #2914, #3057

**Comment by Liunkae** [comment]
QA steps:
1. Open a new tab and navigate to any site (e.g. github.com).
2. Click the URLbar.
3. Press <kbd>Esc</kbd>.
4. The web content should now be focused. You should be able to scroll up and down with arrow keys.

**Comment by Liunkae** [comment]
Rejected in #7039.

**Comment by bbondy** [comment]
The use case this would break is something a lot of users do often:
i) type in a url or some input
ii) realize you want a different url
iii) press esc to clear
iv) start typing a diff url


Also about if you are on a page and you decide you want to see what the url is you are on, you press esc.  But with our title mode that would make matters even worse because we'd hide the url.
