### ISSUE TITLE
Brave then closed continues to show what was typed in the previous session

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#3269]
**Did you search for similar issues before submitting this one?** No

**Describe the issue you encountered:** When I open pages will name one as an example (Google Translate) happens if I close the tab or close the browser completely to reopen and access the page continues with the contents entered later.

- Platform (Win7, 8, 10? macOS? Linux distro?): Win 10

- Brave Version: 0.11.5

**Comment by darkdh** [comment]
I think this is expected because google translate will put the thing you want to translate into url.
For example, if you want to translate `brave` then the url will be `https://translate.google.com/#auto/en/brave`. 
And Chrome, Firefox and Safari do the same thing because url will be saved and restored as all tab locations are.

**Comment by EuNlope** [comment]
I understand.
