### ISSUE TITLE
Search fails for terms with "." (ex: "json.parse" or "location.href")

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#3317]
**Did you search for similar issues before submitting this one?**
Yes - this seems to be the opposite of https://github.com/brave/browser-laptop/issues/3020

**Describe the issue you encountered:**
If I type in `location.href` into the url/search bar and press enter, Brave attempts to go to `https://location.href` instead of searching DDG or Google for the text "location.href".

**Expected behavior:**
I expect a search to be performed, since this isn't a valid URL.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X 10.11.6
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. In a Brave tab, type "location.href" into the URL/search bar and press enter.

**Comment by gulkily** [comment]
This is consistent with Vivaldi and Firefox behavior.

Chromium somehow knows that it's not a valid domain, probably with a list of currently allowed TLDs. The full list is available here: http://stats.research.icann.org/dns/tld_report/

However, using this list means that trying to navigate to a local network URL will take the user to a search instead, so I'm not sure if it's a good idea.

**Comment by echosa** [comment]
> This is consistent with Vivaldi and Firefox behavior.

So it is. Alas, I suppose this is par for the course. I'll close this ticket, and if this ever comes up again, a new one can be made. 👍

**Comment by mikeyb** [comment]
Par for the course or following horrendous trends?

Seriously, I consider this to be about as broken as a search/url combo bar goes.  If you are going to strip away a search bar, make the url/search bar function like one.

I don't want to use chrome.  I just want to type a string into the bar and have search results come up as I would expect them to.

This is insanely frustrating, and to leave as is because some super rare edge case where I use a local network name that isnt a valid tld might cause issues is even more insane.  I would bet my life that the majority of Brave usage is on the internet, not a local network.

How about we make the search bar usable, and if you are actually trying to hit a local network name, lets make **those users** type in something like a `/` at the end.  I am guessing this would be an issue about .000000000001% of the time compared to actual users needing actual search results.

Let's say I want to search for a javascript function.  Something like `JSON.parse`.  Well I get the failed dns resolution page.  DUH! not even a valid TLD, why the hell would it try and resolve it as one?

Okay...fine...I will compensate for bad software design.  So instead I will search for `JSON.parse()` which is **obviously not a tld** and if your network server name is `json.parse()` you deserve to diaf.  But guess what, we are still trying to resolve `parse()` as a tld..WTF! **http://json.parse%28%29/** cool story bro

so now i have to type `gofuckaduck json.parse`, let a bad search page load, edit my search and resubmit it so I can get the search results I need.  **OR** I can just type duckduckgo.com in my browser then search for the term I want because that is probably faster.

I run into this issue daily.  It is frustrating.  If I wanted to use Vivaldi or Firefox I would and constrain myself to horribly designed software.  Brave is not horribly designed software right?  So let's make it not act like it.

I consider this to be the biggest design flaw in Brave and it should be highest priority in the queue for usability fixes.  Or just give me a search bar I can hotkey into.  Those guys and gals at google sure do think about usability a lot, too bad they are scum sucking advertisers.

If someone could point me where in the code base this is handled I will try and formulate a working software design fix, or at least fork this awesome browser and put in the changes I need.

I can't be the only one who searches for dotted function names...

**Comment by luixxiul** [comment]
`:d json.parse()` lets you display the search result on duckduckgo

**Comment by mikeyb** [comment]
@luixxiul so you are telling me, if you type **json.parse()* in to your brave browser url/search bar you can get it to load search results on duckduckgo?

![image](https://user-images.githubusercontent.com/36461/28493498-fed91b4c-6ecc-11e7-9dbf-816625ead63d.png)

weird, cause I cant get it to work.

**Comment by luixxiul** [comment]
Please add `:d` in front of the strings. See `about:preferences#search` for other shortcut keys available currently.

**Comment by luixxiul** [comment]
> I can't be the only one who searches for dotted function names...

Yes: https://github.com/brave/browser-laptop/issues/5627

**Comment by mikeyb** [comment]
Got it.  So the expectation is every time I want to search I prefix my search with `:d ` so local network users dont have to type `/` once in a great while.  And that having a tld list will require too much computational resources to be deployed.  Correct?

Do you happen to know where in the code base this functionality is stored so I can tune the browser into a working state as I see needed?  I have all this empty space on my url bar that adding a search field and hotkeying it to F7 would still leave about 6 inches of empty space on my url bar.

![image](https://user-images.githubusercontent.com/36461/28493660-456ac6f8-6ecf-11e7-9bb5-124d9bf0ac94.png)

Cool, we made all this extra room to take out much needed functionality. 2 extra keystrokes might not seem like a lot, but it adds up over time.

(I know you didnt design this, im just baffled that someone actually thought this functionality was good...or maybe there was no thought put into handling periods because obviously any string with a period is a url)

**Comment by luixxiul** [comment]
> And that having a tld list will require too much computational resources to be deployed. Correct?

Sorry I'm not sure.

> I know you didnt design this

Well, I have fixed that: https://github.com/brave/browser-laptop/pull/8714

Open `about:preferences#advanced` and enable `Use wide URL bar`.

**Comment by echosa** [comment]
I closed this almost a year ago, though I don't recall doing so. Still, I agree that this is broken, and having to specify `:d` or anything like that is a workaround, and definitely not a good solution, especially for the average user. 

I can either reopen this ticket, or maybe this can move to one of the other, still open tickets? Not sure what we want to do here, but having multiple tickets for the same things is not desirable.

**Comment by mikeyb** [comment]
Oh thanks @luixxiul that is surely a nice touch!  Activated.  My OCD is already thanking you.

@echosa I am okay using any ticket that is currently open.  This was the first one I found and didn't want to issue hop with comments, flood an active ticket or open another.  I will let you decide the best place to track.

My thoughts on possible solution, in order, would be to:

-  Have the default use a list of tld's and only attempt resolution on those.  Possibly having an editable configuration to add local network host suffix for auto-resolution attempts, or by adding `/` to the end of the hostname specifying directory structure

-  Have an actual search bar that can hotkey'd into that does purely searching.  Possibly having a setting toggle to enable/disable.  Disabled by default to follow standard layout as it is now.  I think google killed this idea off years ago, Firefox still clings to it.  But both browsers are ultimately last resort for browsing use.

-  Have a button of sorts on the error with `Back` and `Try Again` that says something like `Search Instead?`

Again if there is a link to some code that could point me in the direction I could start looking at more concrete solutions.  I would love to spend my day reading through this source code fully sometime, but my current priorities do not allow for this freedom.  I am willing to help formulate and implement these fixes to the extent my knowledge allows.  Brave is by far my default goto browser and would like to see it dominate the likes of billion dollar companies who want to eat my info to sell me out.  Today was the day that broke the camels back and I simply can't work around this search limitation anymore, this bug hits me constantly.

Thanks for the responses today.  Please ping this issue with whatever ticket you go with for tracking and I will see what I can do to alleviate any workload from your plates.

**Comment by bsclifton** [comment]
Re-opened and updated the title to make it a little easier to understand 😄
