### ISSUE TITLE
Cannot share screen in Google hangouts

### ISSUE THREAD

**Issue by tschf** [brave/browser-laptop#3392]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

If I try and share my screen in a Google hangout, I can not. When I click "Share Screen" nothing happens (aside from the context menu disappearing). 

**Expected behavior:**

Dialog to present, allowing me to nominate which part of my screen to share.
- Platform (Win7, 8, 10? macOS? Linux distro?):

Linux, Ubuntu 16.04, x64
- Brave Version:

Brave: 0.11.5
- Steps to reproduce:
  1. Go to https://hangouts.google.com/
  2. Select video call (new window pops up)
  3. Click the 3 cogs in top right and select Share Screen
  4. Nothing happens
- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/1747643/17953179/94c61024-6ab4-11e6-9e90-4f34115ddd0a.png)

Dialog that appears in other browsers (Chrome), but not in Brave.

![screenshot from 2016-08-25 11-11-43](https://cloud.githubusercontent.com/assets/1747643/17953226/f7e38cf4-6ab4-11e6-9930-dbb3f70ef58a.png)

No errors on the console either.
- Any related issues:

**Comment by bridiver** [comment]
this is likely another case of google thinking that we're chrome and looking for something chrome-specific. I'll take a look

**Comment by alexwykoff** [comment]
+1 from everyone in the company ;)

**Comment by srirambv** [comment]
+1 from community
https://community.brave.com/t/google-hangouts-screenshare-not-working/1031

**Comment by iamhenry** [comment]
+1  Would really appreciate if this was fixed. I use GH for all my company meeting and I have to switch to Chrome just for this task multiple times a day to share what I'm working on.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/google-hangouts-screenshare/14176?u=eljuno

**Comment by gerbsen** [comment]
the problem still exists

**Comment by aweis89** [comment]
+1

**Comment by grallc** [comment]
+1

**Comment by julpro** [comment]
+1

**Comment by centiqchris** [comment]
+1

**Comment by jolbax** [comment]
+1

**Comment by lformiga** [comment]
+1

**Comment by bsclifton** [comment]
Looks like this also doesn't work in [Brave Core](https://github.com/brave/brave-browser)
cc: @bbondy

**Comment by annienar** [comment]
This is still happening, anyone knows a way to make it work?

**Comment by nextlovell** [comment]
Still an issue. Here's where it breaks for me: in Google Meet / Hangout video chat, click 'Present Now', select either 'Your entire screen' or 'A window', and nothing happens. Expected: 'Your entire screen' starts screen sharing and 'A window' opens a modal to select which window to share. Trying to join the meeting by clicking 'Present to meeting' also does not work.

Shield settings: I get the same behavior with shields up or down. With shields up, I have tried toggling ad control, cookie control, and block scripts (nothing on the page works with scripts blocked).

With shields down, I sometimes get an error message "sorry, an error has occurred while screensharing." This seems to appear not the first try but on subsequent tries to share my screen.

Impact: this is my one daily activity where I have to switch out of Brave. It embarrassed me more than once in front of customers and colleagues before I gave up on using Google Meet screensharing with Brave. I now take all my remote meetings with another browser because I might have to share my screen and cannot with Brave.

**Comment by bsclifton** [comment]
@annienar @nextlovell can you please try the newer version of Brave? You'll have to import your data, but it should fix a lot of issues. This issue may be fixed there
https://brave.com/download-beta

**Comment by bsclifton** [comment]
Closing issue since we're moving to the new brave-core code-base. Please let me know if this functionality doesn't work in brave-core and I'll open an issue to track it there 😄

**Comment by tschf** [comment]
My read of the above comments is that it should work in the beta. I just tested this on a fresh install on Ubuntu and experiencing slightly different behaviour than OP. When I click Share Screen, I just get no option to select which window/display to share.

> Version 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)

**Comment by aleksod** [comment]
> My read of the above comments is that it should work in the beta. I just tested this on a fresh install on Ubuntu and experiencing slightly different behaviour than OP. When I click Share Screen, I just get no option to select which window/display to share.
> 
> > Version 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)

Same here. Version 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)

**Comment by csalvato** [comment]
The Beta download does not fix it.  Still get an error.

**Comment by bsclifton** [comment]
@csalvato can you please subscribe to https://github.com/brave/brave-browser/issues/1982? That issue is tracking this problem

Thanks!
