### ISSUE TITLE
Form autofill suggestions are misaligned

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3400]
**Describe the issue you encountered:**
When you start typing in an imput you have previously filled, you are given a suggestions from the autofill. This suggestions are misaligned, often not under the input you are typing in, they are displayed often on the far left, right or bottom of the input.

**Expected behavior:**

The autofill suggestions should be displayed right below the currenty focused input, adn their width must match the input width.

Also when the autocomplete appears it is not possible to use the arrows to choose a suggestion, you have to click it.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, Fedora 24

- Brave Version:
0.11.6-beta3

- Steps to reproduce:
    1. Try to autofill any form you previously filled

- Screenshot if needed:

<img src="https://s3.postimg.org/piphobwsz/Screenshot_from_2016_08_25_10_33_37.png"/>

- Any related issues:

cc @bbondy @bradleyrichter

**Comment by bsclifton** [comment]
Thanks for the report, @Sh1d0w. This issue was just recently resolved (it was originally captured with https://github.com/brave/browser-laptop/issues/3359). I'm going to go ahead and close this issue as a duplicate

The resolution was merged to master and a fresh install of electron should fix the issue (unless the electron-prebuilt has not been updated yet):
https://github.com/brave/browser-laptop/commit/ceb48ceb2516a7c808bb8501f1e6ff450de312b6
