### ISSUE TITLE
Adjust layout and polish - Ledger Add Funds Dialog

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3437]
current:

![image](https://cloud.githubusercontent.com/assets/13509546/17993533/5bee5b7a-6b05-11e6-8b72-f41127e2e937.png)

revised:

![image](https://cloud.githubusercontent.com/assets/13509546/17993563/9f9cebe8-6b05-11e6-9fe9-e60be8cb316a.png)

cc @jkup

**Comment by diracdeltas** [comment]
one thing to note is that the current layout has two states, depending on whether the `bitcoin:` URL handler has been registered. if it hasn't, it looks like the screenshot Brad posted above.  if it has, it looks like this:
![screen shot 2016-08-23 at 8 39 25 pm](https://cloud.githubusercontent.com/assets/549654/18023286/413a07b4-6bac-11e6-8570-fe52dd5702ca.png)

because you can just click `transfer funds` and your browser's registered bitcoin handler will automatically do the transfer. 

if you don't have a registered bitcoin handler, you either have to scan the QR code or copy-paste the payment URL into an app that can handle transfers. hence why the first screenshot shows the full payment URL, not just the wallet address.

**Comment by diracdeltas** [comment]
@jkup to test this out, you can use https://jsfiddle.net/LnwtLckc/5/ to register/unregister the bitcoin: URL handler. you should see the component state change as soon as it's registered/unregistered.

**Comment by bradleyrichter** [comment]
@diracdeltas would this work for both? Then we can just drop the "Transfer bitcoin" button when the URI is not configured.

![image](https://cloud.githubusercontent.com/assets/13509546/18023476/59354d36-6bae-11e6-9544-cd57fda6022b.png)

**Comment by diracdeltas** [comment]
@bradleyrichter that would probably work for the vast majority of cases. the one it doesn't cover is if you use a desktop app to handle bitcoin: URLs, so you can't scan the QR code. the point of showing the payment URL is so that you can copy it into your bitcoin app in this situation. but OTOH you could copy the wallet address and manually enter the other payment info.

i'm not sure how often this case comes up; i think most people have bitcoin apps with QR code scanners.

**Comment by bradleyrichter** [comment]
we can link the full URL under the wallet address for this case?

**Comment by diracdeltas** [comment]
@bradleyrichter sure

**Comment by mrose17** [comment]
sorry to be chiming in late. here is what we had prior to rc 1:

<img width="704" alt="1" src="https://cloud.githubusercontent.com/assets/400552/18136280/9155effa-6f59-11e6-8901-9d0d3b350e2c.png">

and here is what we have in rc 1:

![pasted image at 2016_08_31 12_03 am](https://cloud.githubusercontent.com/assets/400552/18136293/a3654b82-6f59-11e6-875e-e9cf4da74a56.png)

my view is that what we have in rc 1 is less helpful to the new user (and not that helpful to an existing BTC user).

my suggestion is that we stick with the first image above with one change: if the browser does not have a bitcoin URI set, then replaces the "Transfer BTC" button with this text "Scan the QR code above or transfer $X to your Brave wallet." below that, keep the usual "Your Brave wallet address is..."

**Comment by bradleyrichter** [comment]
closing this since it has been replaced by a new version:

#3677
