### ISSUE TITLE
If a site does not have a title, the bookmark should default to the url instead.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3442]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When attempting to bookmark http://alexwykoff.com/2/demo/ the url did populate the appropriate entry in the modal, however the Save button was not enabled. 

**Expected behavior:**
If the modal contains sufficient data, the Save button should be enabled. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta4

- Steps to reproduce:
    1. Open the latest build
    2. Visit a site with no title, like http://alexwykoff.com/2/demo/
    3. Attempt to bookmark the page, observe the modal.
    4. Click on the Save button.

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/3344

**Comment by alexwykoff** [comment]
I noticed the tests added to confirm the fix in #3344 . (https://github.com/brave/browser-laptop/commit/fd60bac1fa0d3282a964f02471e199d8d62e8c10) I would suggest using .waitForEnabled instead of .waitForVisible.

**Comment by Sh1d0w** [comment]
The root cause of this is 

https://github.com/brave/browser-laptop/commit/fd60bac1fa0d3282a964f02471e199d8d62e8c10#diff-92301445f9beebf63f7a7ea1cc1a541fR106

The check if the bookmarkNameIsValid does not include the url check. This commit also introduced a new bug, now you can never have empty title input, it will be always be prepopulated with the URL if you try to delete everything and just type your custom title.

cc @bridiver
