### ISSUE TITLE
location.reload() reopens closed tabs

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3468]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If you close a tab, open a dev console, then execute location.reload(), the closed tab reopens.

**Expected behavior:**
The current tab should reload.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta4

- Steps to reproduce:
    1. Open multiple tabs
    2. Close a tab
    3. Open the dev console (fn + shift + f8 on OS X)
    4. Execute 'location.reload()' on the console

- Screenshot if needed:
![location_reload](https://cloud.githubusercontent.com/assets/1434040/18024742/533f0952-6bd7-11e6-8407-85acf15f5280.gif)

- Any related issues:

**Comment by bbondy** [comment]
This is just because you're running it with the browser devtools and not the webpage dev tools.
So you are reloading the window without saving the state first, so it goes to the last saved state.
Normal users don't know about these dev tools so have no reason to do this. So I think I'm going to mark this as wontfix. Lmk if you disagree or if I'm misdiagnosing.
