### ISSUE TITLE
Preferences : Payments : Text clipping for localized strings.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3539]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While testing https://github.com/brave/browser-laptop/pull/3414 it was discovered that 'Brave Payments Beta' was being clipped for non-English languages. 

**Expected behavior:**
The translated string for 'Brave Payments Beta' should be visible for  Bengali (Bangladesh), German, Spanish, French, Hindi, Indonesian, Japanese, Dutch, Portuguese, Tamil, Telegu, Turkish, and Ukranian.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta6

- Steps to reproduce:
    1. With the latest build, change your language to one of the affected languages above.
    2. Navigate to Preferences -> Payments, observe the top of the page.

- Screenshot if needed:
<img width="1072" alt="screen shot 2016-08-29 at 3 52 21 pm" src="https://cloud.githubusercontent.com/assets/1434040/18067634/3d96fadc-6e03-11e6-9399-947891c104de.png">

- Any related issues:

**Comment by jkup** [comment]
This is fixed (for now) as the strings have been updated to just say Brave Software. Although as translations come in they might break the design.

@bradleyrichter the problem here is just that in order to get the text "Brave Payments" to stick to the bottom I (think I) need to use position absolute which means that it can't have a flexible width.

Tonight I don't think it's a blocker for 11.6 because there are currently no translations for that string so we're back to them all saying "Brave Payments" which fits just fine.

Happy to work on a more long-term solution ASAP.

+ @bbondy

**Comment by luixxiul** [comment]
Please be careful when you use pixels, from a perspective of localization. Text overflow happens easily. cf: #2096

**Comment by bradleyrichter** [comment]
oops. This shouldn't be localized. It's a brand name. The fix is to remove it from transflex or make a logo file.

**Comment by bradleyrichter** [comment]
@jkup Please remove the translflex tag from the Top Logo-title so this instance skips the translation. Leave the rest as is so they are translated.
