### ISSUE TITLE
Can't enable "Web notifications" on twitter

### ISSUE THREAD

**Issue by joneschrisg** [brave/browser-laptop#3579]
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**

Can't enable "Web notifications" on twitter.

**Expected behavior:**

Web notifications are enabled after tapping "Turn on" button; see STR below.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X 10.11.6
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. Navigate to Twitter Settings, then "Web notifications" subsection.
  2. Tap "Turn on" button
- Screenshot if needed:
- Any related issues:

**Comment by cgjones** [comment]
Same behavior in 0.11.6.

**Comment by luixxiul** [comment]
The config page says "web notifications settings are currently disabled" for me.

**Comment by diracdeltas** [comment]
@luixxiul do you see any permission for Twitter domains in about:preferences#security?

**Comment by alexwykoff** [comment]
Confirmed this is not working:
![web_notifications](https://cloud.githubusercontent.com/assets/1434040/18447898/312038cc-78ee-11e6-9105-f599599eae3b.gif)

No special permissions existed for Twitter domains in about:preferences#security

I believe this also caused : https://github.com/brave/browser-laptop/issues/3877

**Comment by diracdeltas** [comment]
#3877 is definitely unrelated to 08e6191, but web notifications won't work anyway because of it

**Comment by bridiver** [comment]
this is going to require some larger changes. Electron's somewhat odd permission handling doesn't cover this case and we really should migrate to `HostContentSettingsMap`

**Comment by bbondy** [comment]
moving to 0.12.2

**Comment by bridiver** [comment]
The issue is caused by the way electron handles permissions. Everything is initially granted and the actual allow/deny decision is made in the cancel callback. This causes problems for setting detection both in twitter and in https://www.browserleaks.com/geo
As mentioned above, I think the best solution is to move away from the default electron handling and use `HostContentSettingsMap` and implement `GetPushMessagingService` in `BraveBrowserContext` so we can still return permissions synchronously and only trigger the permission callback when `CheckPermissionOnIOThread` returns `ASK`

**Comment by diracdeltas** [comment]
This seems to be fixed now? On OS X web notifications are appearing for me in 0.12.3

**Comment by luixxiul** [comment]
Closing as fixed. Let's reopen if we see the issue again 👍
