### ISSUE TITLE
Get rid of magic numbers associated with downloads bar

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3604]
The code in Brave is using 50 pixels as the height in several places:
- https://github.com/brave/browser-laptop/blob/a4aca7ed0da1d98fad54340a25729f2cd48d86ac/js/components/frame.js#L583 (#1712, #1947)
- https://github.com/darkdh/browser-laptop/blob/9e02263ed5c5c0646429ccf885560f319c14f17e/js/contextMenus.js#L1086
- there may be more occurrences

This code needs to be updated to fetch the value via CSS variable. Here is a great example of that:
https://github.com/brave/browser-laptop/blob/master/js/components/bookmarksToolbar.js#L287

**Comment by maaz93** [comment]
Hi @bsclifton,

I would like to take this up. I have gone through the [contribution guide](https://github.com/brave/browser-laptop/blob/master/.github/CONTRIBUTING.md). Could you guide me about the further course the action?

**Comment by bsclifton** [comment]
Hi @maaz93 

I'd love to help get you started with this change :smile: 

Have you got the project working from source? That would be the first step (what OS are you using?).  Next up, you'll want to create a variable in `less/variables.less` to hold this value.  You should be able to then reference the value similar to the example linked above in `js/components/bookmarksToolbar.js`

Let me know if you have any specific questions or if any of the above is unclear :smile:

**Comment by maaz93** [comment]
Hi @bsclifto,

These instructions are sufficient for me to get started. I'm using a Mac. I'll get the project running from source and start working. I'll contact you on this thread, if need be! Thanks 😄

**Comment by bsclifton** [comment]
@maaz93 how's it going? Hope all is well- let me know if you have any questions :smile:

**Comment by maaz93** [comment]
@bsclifton I was able to get the project running from source. I'm new to the react ecosystem, so I was just looking around in the code base. But, I realized that this bug doesn't seem to require any react knowledge. Right?

I went through files to find any hardcoded 50 pixels usage. I believe this exists only in the 2 files mentioned in the bug description. In order to test my change, I tried to hit the breakpoints in these functions. I was able to hit this one

https://github.com/darkdh/browser-laptop/blob/9e02263ed5c5c0646429ccf885560f319c14f17e/js/contextMenus.js#L1095

I was unable hit the other two

https://github.com/brave/browser-laptop/blob/a4aca7ed0da1d98fad54340a25729f2cd48d86ac/js/components/frame.js#L583
https://github.com/darkdh/browser-laptop/blob/9e02263ed5c5c0646429ccf885560f319c14f17e/js/contextMenus.js#L1083

Could you guide me on this ?

**Comment by bsclifton** [comment]
Hi @maaz93 

You can breakpoint debug any of the code running in the render process from inside the browser. In order to breakpoint debug the browser process, you can try Visual Studio Code. We have some documentation that I hope is useful here:
https://github.com/brave/browser-laptop/blob/master/docs/debugging.md

Another good way to debug that I use is to just drop some console.log statements in the code.  You'll see the output in two places:
- system console (where you ran `npm start`) for the browser process
- the electron devtools (Shift + F8, go to console) for the renderer process

If you're working on an about: page (like about:history), then you'll have to go to the console devtools (F12 or cmd+opt+i)
