### ISSUE TITLE
Extra separator under bookmark menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3666]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Extra separator under bookmark menu

**Expected behavior:**
Extra separator should not be there under bookmark menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev

- Steps to reproduce:
    1. 
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18213362/bb8de114-713f-11e6-9827-83c2566cfcbd.png)

- Any related issues:

#3444

**Comment by charbelrami** [comment]
When there are bookmarks, they're shown under the extra separator.
To reproduce: delete all bookmarks
This issue happens whenever a submenu is hidden. Another example:
![extra_separator](https://cloud.githubusercontent.com/assets/5647344/18214842/2120889e-7125-11e6-9ac8-cf955e75358e.png)
The "Paste" option is hidden because the clipboard is clean.
