### ISSUE TITLE
Random: ledger balance error: "Error: HTTP response 401 for GET /api/balance"

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#3736]
No idea what triggers it, but happens when I open about:preferences#payments. Everything appears to be working on the page, but I get the console error “ledger balance error: "Error: HTTP response 401 for GET /api/balance"” every few hours or so.

**Comment by mrose17** [comment]
i am fairly confident you can ignore this! here's what's going on:

the [ledger-balance](https://github.com/brave/ledger-balance) package polls numerous blockchain reporters to get the unconfirmed balance of your brave wallet in order to report information in the right-hand corner. (the actual balance is reported via a round-trip to the actual wallet provider, but on a slower interval).

the 401 is from one of the blockchain reporters that does more aggressive load limiting than the others (not sure why it's not a 429). the way that ledger-balance works is that it round-robins between the blockchain providers and keeps track of response time, errors, etc, so when you see that 401, it's very likely that a new request is sent to another blockchain provider.

if you have some time, take a look at the README and the `index.js` file starting [here](https://github.com/brave/ledger-balance/blob/master/index.js#L21) to see the list.

thanks!

**Comment by mrose17** [comment]
@Aeyoun - does the explanation above make sense? should i close this issue or ... ? thanks!

**Comment by Aeyoun** [comment]
I’ve not noticed any negative effects from this, but it’s reported as an error not a warning….

**Comment by mrose17** [comment]
fair point, thanks!
