### ISSUE TITLE
Autofill suggestion overlaps the field on which the suggestion is shown

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3758]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Autofill suggestion overlaps the field on which the suggestion is shown

**Expected behavior:**
Suggestions should be prompted below the input field.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 RC2 (Clean Install)
- Steps to reproduce:
  1. Add Autofill entries
  2. Visit [Roboform](https://www.roboform.com/filling-test-all-fields)
  3. Click on input field to load suggestion
  4. Suggestion overlaps the input field

Issue happens on the first clean install of the build. 
Uninstalling and removing residual folders from %appdata% and reinstalling the same build, autofill suggestion doesn't overlap on the field.
- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/17010094/18266033/8730fce8-7410-11e6-9ce2-92bbd7229305.png)

![image](https://cloud.githubusercontent.com/assets/17010094/18266045/9ac6ca76-7410-11e6-9344-678e4e8c1267.png)
- Any related issues:

cc: @darkdh , @bsclifton

**Comment by bsclifton** [comment]
I can't reproduce... I upgraded and tried my existing install, then I moved my %appdata%/brave folder out of the way (so that it creates a new session). Still can't reproduce

@srirambv can you reliably reproduce? I'm curious if the actual issue is something like the page accidentally being zoomed while the popup comes up (like using middle scrollwheel). Zooming and resizing the page while autofill is displaying definitely has position issues

**Comment by srirambv** [comment]
@bsclifton. I am unable to repro the issue again. There was no page zoom because with page zoom the location of the autofill changes but doesn't overlap the field.

![image](https://cloud.githubusercontent.com/assets/17010094/18283095/9c85556c-745b-11e6-9ce6-1ddc48db2de7.png)
