### ISSUE TITLE
Check page status code before running ledger timer

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#3759]
Status code should be in the HTTP 2xx Success range. Anything from 3xx (redirects), 4xx (client error), or 5xx (server error) shouldn’t count against the ledger.

Should cover sites out of bandwidth, crashed sites, CloudFlare stuff, dead links, etc.

...and while we're at it, let's ensure that the page is text/html

**Comment by mrose17** [comment]
@bridiver - this looks like a one-liner! care to point me where to add that line (or add the line yourself)? thanks!

**Comment by bridiver** [comment]
We already cover most of these. Redirects last less than 8 seconds and 5xx errors go to about:error which are already excluded. 304 is a valid and common response that shouldn't be ignored. We can exclude 4xx pages, but it's definitely not a one-liner because we normally don't get the http status code. We either get a load success or load failure, but 4xx pages are not considered load failures by chromium. Electron has a `did-get-response-details` that we could possibly use in the place of the webview load, but we don't currently use it and I need to look at it more closely. With the focus/idle changes this seems like a minor issue at the moment. How long are you going to keep a 404 page focused and active? Also fyi - the milestone is set to 0.12.1dev
