### ISSUE TITLE
Increase pinned tab size 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3769]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Increase pinned tab size. The pinned tabs keeps resizing when audio/video is playing. Looks a little distracting.

**Expected behavior:**
Increase the size of pinned tabs so that tabs don't resize when audio/video is playing. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All platform
- Brave Version:
  All releases till date
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

cc: @bradleyrichter

**Comment by bbondy** [comment]
ya that is annoying, @bradleyrichter what do you suggest? It resizes because of the audio icon you can click to mute the tab.

**Comment by bbondy** [comment]
one option is just to have the options in the context menu and don't show them for pinned tabs with the icon on the tab.

**Comment by bsclifton** [comment]
The mute icon being on there (and being accidentally clicked when trying to switch to the pinned tab) has bitten me a bunch of times. Especially when doing a Google Hangout and switching tabs while talking. I'm curious how the experience could be better, but there are legit reasons you'd want to mute/unmute

**Comment by bbondy** [comment]
I think we can get rid of the button since the functionality in the context menu, but we need some visual queue to identify it if we do.

**Comment by bradleyrichter** [comment]
I could envision a double-wide tab to reveal the mute button only when needed. 

Any other indication large enough to be visible may created click-expectation.

**Comment by bbondy** [comment]
double wide is kind of what we do now.

**Comment by bradleyrichter** [comment]
I like it how it is. But if we feel it is causing problems, I would first try reducing the mute button by 25% so it's takes up less space on the pinned tab. @bsclifton Would that help your issue?

If we hide it and leave it up to the context menu, I think this could be more frustrating when it's blaring in your face after a reload. (assuming you did the right things to wake it up or otherwise cause it to continue playing.)

I think the inconsistent nature of pins is a bigger problem:

(these were 3 open brave windows that I aligned for the snap shot)
![image](https://cloud.githubusercontent.com/assets/13509546/18324454/70881bf2-74f1-11e6-98b3-b11987e6a602.png)

**Comment by bbondy** [comment]
pins are prime for a refactor, I'm sure we can fix that inconsistent ordering and also the sometimes duplicating pins that way.

**Comment by paJFJ** [comment]
i implemented a redesign for pinned tabs. will upload a demo video for discussion tomorrow.

**Comment by lucidNTR** [comment]
https://dl.dropboxusercontent.com/u/11806822/private%20tab%20interaction%20redesign.mov

**Comment by cezaraugusto** [comment]
we now have an alternative audio indicator for pinned tabs so closing this
