### ISSUE TITLE
Reduce actual RAM usage

### ISSUE THREAD

**Issue by Bushido1** [brave/browser-laptop#3836]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Brave takes about 170-210 Mb RAM (+Lastpass enabled) . For example, I use Opera with 2 extensions enabled and it takes about 130 Mb RAM,

**Expected behavior:**
Brave should take half less RAM as it takes now. In most positive outcome, Brave should take less than 130 Mb RAM.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 Pro x64
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. Code Brave to use about 130 Mb or less RAM
#415

**Comment by bbondy** [comment]
Would you be able to compare the same use case on Chrome? Is it more similar to Opera?

**Comment by Bushido1** [comment]
Chrome takes with the same 2 extensions about 141 Mb RAM.

**Comment by bbondy** [comment]
please stay 0.12.1 for now but just an fyi /cc @bridiver

**Comment by Sh1d0w** [comment]
I think there is memory leak somewhere. With continious usage for more than 16 hours after I closed most of the tabs opened and left only two of them, Brave takes more than 700 MB RAM which is crazy:

<img src="https://s17.postimg.org/mmeb6h3i7/Screenshot_from_2016_09_09_22_02_27.png"/>

**Comment by Bushido1** [comment]
Now, if I opened Brave, then Task Manager showed that Brave takes on initial launch 291 Mb of RAM (Lastpass enabled).

**Comment by bridiver** [comment]
There is a known memory leak in the main process. It was mostly fixed and then accidentally re-introduced and now mostly fixed again in 0.12.1. The remaining leak is very small, happens less frequently and will be fixed soon. There were some renderer process memory leaks, but I believe those have all been addressed. @Bushido1, both Brave and Chrome run many different processes, which one(s) are you looking at? There is the main process (Brave) and the renderer processes (Brave Helper). There will typically be one renderer process for each main window and one renderer process per tab (just like Chrome), but in some cases multiple tabs will share a renderer process. There is also a renderer process for each extension that uses a background page (LastPass, Brave and PDFJS). Brave 0.12.1 and earlier also have an extra set of background page processes for each session tab. This was due to the fact that they are roughly the equivalent of having multiple accounts on Chrome, but in the next release they will be linked and share a single background process.

**Comment by Bushido1** [comment]
I was summarizing all Brave processes that Task Manager showed me.

**Comment by bridiver** [comment]
I'm not sure about Opera, but in both Brave and Chrome the memory used by the main process is dwarfed by the memory used in the renderer processes. We are concerned about memory usage and want to keep it as low as possible, comparing the main process for Brave and Chrome is a bit like comparing apples and oranges. The renderer processes share most of the same code and should be roughly the same, but the main processes share basically nothing.

**Comment by bridiver** [comment]
you were only seeing 130MB total usage for Chrome for all processes? How many windows/tabs did you have open?

**Comment by Bushido1** [comment]
![5](https://cloud.githubusercontent.com/assets/11409601/18400404/6a369e1a-76de-11e6-824d-c72f9eb2e9bf.jpg)

**Comment by Bushido1** [comment]
This is latest Opera Developer version's RAM usage:
![6](https://cloud.githubusercontent.com/assets/11409601/18400465/b1dcb5e2-76de-11e6-9b79-1c1dfec48558.jpg)

**Comment by Bushido1** [comment]
This is latest Google Chrome stabel version's RAM usage: 
![7](https://cloud.githubusercontent.com/assets/11409601/18400513/eedc42e6-76de-11e6-819c-79f872d79ad2.jpg)

**Comment by Bushido1** [comment]
This is latest VIvaldi stabel version's RAM usage: 
![8](https://cloud.githubusercontent.com/assets/11409601/18400591/3e8717e4-76df-11e6-88b9-65c48c64c900.jpg)

**Comment by bridiver** [comment]
Can you try this?
1. Clear all tabs from Brave and Chrome so they start with a single empty tab
2. Open cnn.com in one tab and facebook.com in a second tab
I see roughly equivalent RAM usage on win7 between Brave and Chrome. Brave is still using slightly more, but the RAM usage for Chrome jumps quite a bit once I actually start using it.

**Comment by Bushido1** [comment]
This is latest Mozilla Firefox stabel version's RAM usage: 
![9](https://cloud.githubusercontent.com/assets/11409601/18400718/c96839b0-76df-11e6-81a0-e4d519cfc7c1.jpg)
This is latest Tor Browser stabel version's RAM usage: 
![10](https://cloud.githubusercontent.com/assets/11409601/18400770/046552b4-76e0-11e6-8f4f-dbcad9a5e048.jpg)

**Comment by Bushido1** [comment]
@bridiver Do you mean that browser should start with a single empty tab during initial start or after I have opened browser?

**Comment by bridiver** [comment]
when I tested each browser opened with a single empty tab. Another thing I just noticed is that you are using the 32-bit version of the other browsers. 64-bit apps will always consume more memory than the same app compiled for 32-bit because the pointers are twice as big (4 vs 8 bytes). It won't cause a doubling in the size because obviously not all memory is consumed by pointers, but it will make a noticeable difference. Try downloading https://www.google.com/intl/en/chrome/browser/desktop/index.html?platform=win64 and compare again

**Comment by Bushido1** [comment]
Hopefully all my settings and bookmarks will be untouched after installing 64bit of Chrome to 32-bi.
Is Brave 64-bit?

**Comment by bridiver** [comment]
Brave is 64-bit. We have a 32-bit version, but you have the 64-bit version installed. You shouldn't lose any settings, but if you are concerned you can backup your chrome profile http://hellboundbloggers.com/2012/11/backup-restore-google-chrome-profile-50609/

**Comment by Bushido1** [comment]
Chrome 64-bit:
![5](https://cloud.githubusercontent.com/assets/11409601/18401703/781b5088-76e4-11e6-8951-5667d0af0729.jpg)
Brave 64-bit: 
![6](https://cloud.githubusercontent.com/assets/11409601/18401710/7f53bc0a-76e4-11e6-80fe-66a45a87ac2c.jpg)

**Comment by bridiver** [comment]
The difference between the two is still more than than I'm seeing, but I'm testing on win7 so maybe that's why. I also have a fresh, blank profile for both Brave and Chrome. A difference of less than 200MB is not really a major cause for concern and the Brave main process is running node and has not been optimized for memory usage yet. I think this is likely just the result of loading unnecessary libs into the main process and will be easy to sort out either before 1.0 or shortly after it. The main process memory leak is a much bigger issue, but that should be mostly fixed in 0.12.1 and will definitely be fixed by 1.0. Thanks for the feedback @Bushido1 and we'll leave this ticket open to track the main process memory usage

**Comment by Bushido1** [comment]
> A difference of less than 200MB is not really a major cause for concern
For laptop users because of battery lasting, it is :)

**Comment by bridiver** [comment]
Applications use pointers to address locations in memory where data is stored. 64-bit apps can directly address a larger memory space, but that also means that the pointers to that space have to be larger to accommodate the extra addresses. It would be like the difference between a 5-digit telephone number and an 10-digit telephone number. A 5-digit telephone number would only allow 99,999 people to have their own phone numbers, but a 10-digit telephone number allows 9,999,999,999 to have their own numbers. However, the telephone numbers are now twice as long and therefore take twice as much space to store. The number of pointers in an application like Chrome or Brave is very large and therefore the total memory usage is higher.

**Comment by Bushido1** [comment]
Thanks for explaining. So, sticking to 32-bit version is in nowadays technology clever idea if the main criterium is RAM usage.

**Comment by bridiver** [comment]
In terms of battery life, the amount of memory used by an application is normally not a real factor. CPU/GPU, display backlight and disk activity are typically have the biggest impact on battery life. Your laptop has a fixed amount of RAM, but the OS allows you to use open more applications than your physical ram would allow by temporarily writing some of it to disk. The OS tries not to write frequently used memory to disk, but in some cases it is unavoidable and this can result in excessive disk activity and very poor performance. The OS will even actively kill some applications to restore performance when memory pressure is too high. In normal usage with a lot of tabs and windows open both Brave and Chrome will use significantly more than 200MB of RAM and since most of the extra RAM in Brave is likely going unused it will be written to disk once and become a non-issue.

**Comment by bridiver** [comment]
I'm not suggesting that we won't improve the memory usage, but if  battery life is your real concern it should be a big issue.

**Comment by Bushido1** [comment]
I use f.lux and Windows own screen brightness adjustament tool to keep the display backlight as light as low as possible.
My RAM has not over exceeded during web browsing but I have noticed that Opera browser gets slower in certain forum pages if those pages are opened as a tab for a long time (about 1-2 hours). But if I open a new tab with and surf in a new website, then browsing in it is faster. I have not restarted browser or closed tabs with a slow browsing activity during that time.

**Comment by bridiver** [comment]
we want to have equal or better memory usage compared to Chrome regardless of extensions, but to be a completely fair comparison you should install Chrome extensions for ad blocking and https everywhere. I doubt that will bridge the memory gap completely, but they are baked into Brave.

**Comment by Bushido1** [comment]
Well, I use for ad blocking a separate program (Adguard for Windows with no browser extension). It uses about 40 Mb of RAM.

**Comment by bridiver** [comment]
@Bushido1 sometimes the page itself can cause issues that the browser can't really do anything about. This is a contrived example, but a web page could create an empty list in javascript and add a unique string to it every second and then search the list for a random entry. Over time the memory usage will grow and the time to search the string will grow to the point where it will have a noticeably impact on the page performance.

**Comment by srirambv** [comment]
@bridiver There is still high memory usage on Brave with just one tab running. Below is the comparison between Chrome/Opera/Firefox/Vivaldi/Brave with just one tab running and no extensions installed. still Brave is high on memory 

![image](https://cloud.githubusercontent.com/assets/17010094/21983130/83ab7bc2-dbe7-11e6-87a0-1c7f06e0f510.png)

**Comment by bridiver** [comment]
@srirambv I'm not terribly concerned about 135MB of ram, but it would be a better comparison if all the browsers were on the same page because that can have a big effect on the memory usage for the renderer

**Comment by bbondy** [comment]
when doing side by side comparisons, best to ensure it's the same number of tabs, same sites loaded, no extensions unless the check is related to that, fresh profile better unless the check is related to that.

**Comment by Stryder24** [comment]
I am having what I consider a lot of 
![brave](https://cloud.githubusercontent.com/assets/23262338/25493241/821987f8-2b43-11e7-961c-8fc78c99d472.jpg)
memory used.

**Comment by Jacalz** [comment]
Here is the detailed example that @bbondy was talking about:
![image](https://user-images.githubusercontent.com/25466657/30657796-05d4e3cc-9e39-11e7-811d-4baf0136008f.png)
<strong>This is Brave and Chrome running without any extensions, same pages and both are running fresh profiles!!!</strong> The difference is huge and this really needs to be improved :-1:

**Comment by luixxiul** [comment]
I don't think it's fair to compare Brave with adblocker, fingerprinting method protection, etc. with the clean Chrome :-D How much RAM will Chrome take after Adblock, ublock Origin and NoScript are enabled?

**Comment by Jacalz** [comment]
Here is a comparison with Ublock0, Disconnect, HTTPSe and Privacy Badger on chrome vs Brave:
![image](https://user-images.githubusercontent.com/25466657/30662235-ae22f5fc-9e46-11e7-87ef-95f03d7f4b2f.png)
Still the very same story :-1:

**Comment by bridiver** [comment]
The 77.8MB you are seeing is only the Chrome browser process and that is a drop in the bucket of the total RAM usage. You will find multiple process for both Chrome and Brave under "Background Processes" and it's not uncommon to have a single tab take up 400+MB of RAM. If you are doing anything more than a trivial test with a few tabs, the non-renderer processes will be completely lost in the noise of the RAM usage by the renderer processes.

**Comment by ntolman** [comment]
Here's the RAM usage on my system compared with Firefox.
![2017-09-21](https://user-images.githubusercontent.com/5316602/30698333-9dc57d6a-9eaf-11e7-9c78-bfef95acdc41.png)

Here are all the extensions Firefox is using
![2017-09-21 1](https://user-images.githubusercontent.com/5316602/30698432-f135d986-9eaf-11e7-8ec4-06789a60e267.png)

**Comment by luixxiul** [comment]
> You will find multiple process for both Chrome and Brave under "Background Processes" and it's not uncommon to have a single tab take up 400+MB of RAM. If you are doing anything more than a trivial test with a few tabs, the non-renderer processes will be completely lost in the noise of the RAM usage by the renderer processes.

It seems to me to be worth blogging or tweeting about that, telling users pointless to do the simple math on Task Manager.

**Comment by bsclifton** [comment]
++ on a blog post or at least a wiki entry; would be great to know more information 😄  Would this be something you could consider doing, @bridiver?

**Comment by NumDeP** [comment]
Hi @bridiver I think this issue requires an investigation label before the wiki entry is made. 
I'm certainly not as experienced as you are but I have to disagree with that notion that it's not a huge concern because the above reports were mostly trivial tests to provide evidence and not necessarily normal usage and as you suggest 400+MB is not really uncommon but the following report certainly has to be.

I think this issue and the other issue pertaining to excessive energy drain/consumption in MacOS and recently Android platform are sort of linked and the below stats are quite possibly a plausible reason as to where the great energy drain is going which are being reported in the community and Github.

I realize the comparison to FF could be regarded as a caveat, due to Mozilla's recent introduction of Quantum which has surprisingly made it more efficient memory wise but not by this much.
~~~
FF Version 58.0.2 (64-bit)

Brave: 0.21.18
OS Architecture: x64
OS Platform: Linux
~~~
Same number of tabs and same sites loaded in each finding, no apps/extensions with the exception of uBo in FF.
~~~
FF with fresh start                      - Around 519  MiB

Brave with fresh start                   - Around 444  MiB


FF with 15 sites                         - Around 1232 Mib

Brave without Strict Site Isolation      - Around 2857 Mib

Brave with Strict Site Isolation         - Around 2949 MiB


Brave starts with 75 MB less memory but uses 1625 MiB more memory than FF 
~~~
FF with fresh start  
![ff fresh start](https://user-images.githubusercontent.com/31957540/37558926-e2a46352-2a13-11e8-9bf1-83ee8bce562b.png)
Brave with fresh start
![brave fresh start](https://user-images.githubusercontent.com/31957540/37558917-cda15bfe-2a13-11e8-8b43-2ec187a5f58f.png)
FF with 15 sites
![ff with 15 sites](https://user-images.githubusercontent.com/31957540/37558932-fc1bf44e-2a13-11e8-8ff5-448873e4e578.png)
Brave without Strict Site Isolation 
![brave without strict site isolation 15 sites](https://user-images.githubusercontent.com/31957540/37558949-5ab688d4-2a14-11e8-9563-183650abb4cc.png)
Brave with Strict Site Isolation 
![brave with strict site isolation 15 sites](https://user-images.githubusercontent.com/31957540/37558942-2d871fb8-2a14-11e8-9393-b8075dbd146a.png)

**Comment by bsclifton** [comment]
Closing as we won't be able to make a meaningful impact with this code-base (Muon). Let's open an issue in the brave-core issue log if this occurs there

The latest developer channel release for brave-core can be downloaded here:
https://brave.com/download-dev
