### ISSUE TITLE
Users need a more obvious clue that Flash has indeed been installed and is available

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3858]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
https://linkbubble.zendesk.com/agent/tickets/5035 
https://linkbubble.zendesk.com/agent/tickets/5205
https://linkbubble.zendesk.com/agent/tickets/5214
https://linkbubble.zendesk.com/agent/tickets/5147
all revolve around Flash, its install and use being less than obvious to the user and causing frustration. 

**Expected behavior:**
Users should have a good sense of whether or not they have installed Flash and how to use it.
Especially for sites which require flash, but do not use the view. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
> 0.12.0 

- Steps to reproduce:
    1. 
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
cc @bradleyrichter

**Comment by diracdeltas** [comment]
i suspect a large part of the pain is because we are trying to deprecate Flash by pretending it doesn't exist to trigger HTML5 fallback (see https://github.com/brave/browser-laptop/wiki/Flash-Support-Deprecation-Proposal), so sites without fallback will try to tell the user to install Flash. i know this seems like a usability nightmare right now, but it's actually going pretty well in the sense that many sites will "just work" with html5 in Brave, whereas they require Flash in Chrome (as @srirambv has noticed). 

but we can probably do a better job of detecting if the user already has Flash installed in the right place and prevent them from trying to re-install

**Comment by diracdeltas** [comment]
it turns out there was a regression where the Flash-already-installed notification wasn't being shown. fixing now.

**Comment by diracdeltas** [comment]
@alexwykoff to make this easier for support, i wrote a short guide on troubleshooting Flash which you can link people to in Zendesk. https://github.com/brave/browser-laptop/wiki/Flash-Support-Deprecation-Proposal#troubleshooting-flash-issues
