### ISSUE TITLE
Localization of Payments FAQ text on about:payments

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4102]
**Describe the issue you encountered:**
These lines on about:payments should be localizable in languages whose grammar is different from English.

```
<span data-l10n-id='paymentsWelcomeText6' />&nbsp;
    <a href='https://brave.com/Payments_FAQ.html' target='_blank' data-l10n-id='paymentsWelcomeLink' />&nbsp;
<span data-l10n-id='paymentsWelcomeText7' />
```

https://github.com/brave/browser-laptop/blob/238938ef5d04e27840bcb03744d6266d62eaafc3/js/about/preferences.js#L915-L917

In Japanese, based on the current status, they need to be sorted reversely. Also no whitespaces should exist there because it is gramatically wrong to have ones in a sentence.

**Expected behavior:**
Make `paymentsWelcomeText6` and `paymentsWelcomeText7` concatenated and include the URL in it as a variable like this: https://github.com/luixxiul/browser-laptop/commit/ef284caa8be29a62ea18f68cc38f8f7c4d0244fa. Also whitespaces should not be hardcorded, and let translators handle them.
- Brave Version: 0.12.1
- Screenshot if needed:

Currently you get this:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18620854/8e0e2410-7e55-11e6-8740-15aa17eda17e.png)

It could be improved like this, which is grammartically correct:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18620931/a635a882-7e56-11e6-9227-ad34073c412c.png)
- Any related issues:

**Comment by bsclifton** [comment]
@luixxiul if you think about the spans that are in place as tokens (instead of a block of text that must be translated as-is), you can already solve this without code changes:
```html
<span data-l10n-id='paymentsWelcomeText6' />&nbsp;
  <a href='https://brave.com/Payments_FAQ.html' target='_blank' data-l10n-id='paymentsWelcomeLink' />&nbsp;
<span data-l10n-id='paymentsWelcomeText7' />
```
(I can't copy/paste your text above, since it's in an image, but I'll try to simulate)

```yaml
paymentsWelcomeText6=Words before link
paymentsWelcomeLink=link text goes here
paymentsWelcomeText7=words after link
```

The variable strategy like you suggest is great- but in this case, it would be generating an HTML element (which I believe is out of scope for a translation).  In this case, the folks doing the translation would need to be aware of how the strings are used in the UI, which I think is acceptable (instead of them blindly translating the strings)

Thoughts? cc: @aekeus @alexwykoff @bbondy

**Comment by bsclifton** [comment]
Removing ledger tag since this is really a content / i18n issue and not something that impacts Brave Payments functionality

**Comment by Liunkae** [comment]
See https://github.com/brave/browser-laptop/issues/8162#issuecomment-295369760
