### ISSUE TITLE
How to add existing Bitcoin Wallet?

### ISSUE THREAD

**Issue by decode-dev** [brave/browser-laptop#4111]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
I want to add my existing Bitcoin Wallet rather creating it by Brave.
**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 8.1 Pro x64
- Brave Version:
0.12.1
- Steps to reproduce:
    1.Go to Brave Payments. You need to create the Bitcoin W
    2.No option to add the existing Bitcoin Address

**Comment by willy-b** [comment]
What wallet are you using @decode-dev? Is your wallet P2PKH or P2SH?
What private key export formats would you want supported?

IMHO, this approach is much harder, even as a user, than just transferring BTC to the Brave wallet (which is multisig with BitGo). Moving BTC is easy -- this is one of the reasons we love it, right :-)?

That said, there is a Wallet Recovery/import page already on the roadmap (#3350) which could possibly be extended to support some other private key formats (P2PKH):
https://github.com/brave/browser-laptop/issues/3350#issuecomment-241897227

This page from @bradleyrichter's mockup would probably be the spot:
![ledger-wallet-recovery-import](https://cloud.githubusercontent.com/assets/6969859/18679789/f9285cfa-7f15-11e6-82b1-18e9a9733389.png)

Perhaps without even advertising it in UI, Brave could allow import of a single key for P2PKH wallets.
But it would make sense for Brave to then move the BTC to a new wallet anyway so that the format could be standardized (otherwise maintenance would be very difficult!).

**Comment by decode-dev** [comment]
I already have a Blockchain Wallet which has Bitcoins instead of creating the new one by Brave I think it will be better if we can add the existing wallet.
And I need not transfer the bitcoins from one to another.
I understand that it would be easier to Brave to maintain but we can have an option to add the Wallet from others also.

**Comment by bradleyrichter** [comment]
@mrose17 can explain why we are not able to allow users to add existing wallets partially for anonymity reasons.

**Comment by mrose17** [comment]
@decode-dev - at some point, the brave ledger server has to be able to "know" that a browser is authorized to perform a given amount of statistical voting. brave software doesn't want to credit publishers incorrectly (that's the authorization part), and users want to be anonymous (that's the statistical voting part).

while your could send coin from your private wallet to the brave settlement wallet, brave software would still need to have a way of correlating that transaction to your browser, to know that your browser is authorized to do statistical voting. i couldn't figure out a way of doing that transparently.

when the browser creates a brave wallet for the user, it can be done automatically, and that has to be a good thing... the downside, of course, is the extra trip through the blockchain. nothing's perfect, i guess.

does that make sense?

**Comment by mrose17** [comment]
Closed due to inactivity.
