### ISSUE TITLE
bookmarks toolbar still not fully filling up on some resolutions

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4116]
I think it depends on the DPI setting, my wife's laptop doesn't fill up the whole toolbar though.

#9939

**Comment by jonathansampson** [comment]
@bbondy Does this still repro on your wife's laptop? If so, can you share its specs here?

**Comment by bbondy** [comment]
This issue is very old, we still have problems but now with it being too full. I think nejc's changes should solve it finally hopefully.

**Comment by cezaraugusto** [comment]
I think Nejc's PR just moves the current calculation to the state and is more perf-related. This issue was duplicated at least two times and was supposed to be fixed in #9664 but still needs improvements. 

Calculation is still not at its best ATM but will be eventually after checking for element intersection in bm toolbar which is a method I'm still introducing.

I'm tracking it in a similar issue: #9939
