### ISSUE TITLE
undo right-click deletion of synopsis site does nothing

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4133]
1. right click to delete a site in about:preferences#payments
2. go to about:preferences#shields and remove the site exception that was just added
3. the site does not show up again in about:preferences#payments synopsis, even after restart

@mrose17 what is the expected behavior? i would expect the site to show up again in the synopsis table.

to listen for the undo-deletion, put something here: https://github.com/brave/browser-laptop/blob/master/app/ledger.js#L132

**Comment by mrose17** [comment]
it will show up again, *after* you visit the site again. the issue is that when you delete it, you delete the history -- it goes away. if you then go to shields and click the "X", new visits will show up as you'd expect (i tested this last night quite a bit...)

so, i'd close this issue as "after clarification, closed due to design intent"

**Comment by diracdeltas** [comment]
sgtm
