### ISSUE TITLE
mailto: notifications display "null" rather than the domain when opening in new tabs

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4198]
## Test plan

https://github.com/brave/browser-laptop/pull/10668#issue-253030755

----

**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

Clicking mailto link produces the following message:

`Allow ⁨null⁩ to ⁨open an external application⁩?`

<img src="http://s22.postimg.org/ole8lmbep/mailto_support_brave_com_014.png"/>
- Brave Version:
  0.12.1
- Steps to reproduce:
  1. Open brave.com
  2. Go to footer section
  3. Click Support link in the footer
- Screenshot if needed:
- Any related issues: #4003

**Comment by bbondy** [comment]
@Sh1d0w could you re-verify this with master tip? I can't reproduce? If you can still reproduce please let me know the page and link that you can reproduce from. Thanks!

**Comment by Sh1d0w** [comment]
@bbondy Hey Brian. Yes it happens on the latest master. I think it can be Linux issue only, currently don't have Mac or Win PC to confirm that, but it happens under Linux.

**Comment by Sh1d0w** [comment]
@bbondy Since update to version 0.12.4 now this message appears even if I try to open a magnet torrent link:

`Allow ⁨null⁩ to ⁨open an external application⁩?`

**Comment by kjozwiak** [comment]
I ran into this issue while helping a community memeber. I noticed that rather than the correct domain appearing under the notification, "Null" was being displayed. This happens when a website uses `target="_blank"` for their mailto: links or the user opens the mailto: link in a new tab.

STR:

* Open the latest version of Brave
* Visit https://brave.com/ and scroll to the bottom
* Under Contact Us, right click on an email and select "Open Link in New Tab"

<img width="1473" alt="screen shot 2017-08-25 at 12 16 55 pm" src="https://user-images.githubusercontent.com/2602313/29722827-32ddb9b0-8990-11e7-8433-217b71714f3e.png">

Reproduced with the latest build of Brave:

> Brave 0.18.23 | rev 36ae2ec06efed0057ae16351108bf4d4c10a7ab4
> Muon 4.3.10
> libchromiumcontent 60.0.3112.90
> V8 6.0.286.52

Reproducible on the following platforms:

* macOS 10.12.6 x64 - Reproduced
* Win 10 x64 Build Build 15063 - Reproduced

**Comment by bbondy** [comment]
Pulled this into 0.19.x to another merge easier.

0.19.x: 00ccec41b4a238e7eb7e9690fae1f4c3c420fda1
0.20.x: ef9374f8a1b6368c9857c3d53c0e70913a773e6b
master: 3383ff667594c1c3f3d7a3185d7ed0dee7968ab3

**Comment by srirambv** [comment]
No notification on Windows 
![4198](https://user-images.githubusercontent.com/17010094/30681365-cbd1992e-9ec2-11e7-8500-951799775bc9.gif)

**Comment by LaurenWags** [comment]
I see the same as @srirambv on MacOS.

**Comment by diracdeltas** [comment]
The notification not appearing at all seems to be a separate issue. This change only changes the name of the domain in the notification.

**Comment by diracdeltas** [comment]
^ opened https://github.com/brave/browser-laptop/issues/11075
