### ISSUE TITLE
Hidden history entries appear by deleting the latest entry

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4224]
**Describe the issue you encountered:** Hidden history entries appear by deleting the latest entry.

![history](https://cloud.githubusercontent.com/assets/3362943/18780254/9a9c1a9c-81b7-11e6-8c91-8305723acf15.gif)

5:50:14 PM -> 5:50:22 PM -> 5:51:04 PM -> 5:51:06 PM

I am not sure of steps to reproduce the issue.

**Expected behavior:** No history entries should be hidden.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.1
- Any related issues:

**Comment by luixxiul** [comment]
Sometimes these hidden entries appear at one time after browsing some pages.

**Comment by aekeus** [comment]
I cannot reproduce this bug. Are there any other steps required for the STR?

**Comment by bsclifton** [comment]
Closing. Please do reopen if there are some clear STR.  Thanks :smile:

**Comment by luixxiul** [comment]
Though not sure of STR I still experience the bug both on macOS and WIndows.

**Comment by luixxiul** [comment]
I would close the issue if I confirmed the issue has been fixed in some way.

**Comment by bsclifton** [comment]
@luixxiul would you be able to back up your session file so we don't lose it and then remove entries one at a time until there is no sensitive info? If you're open to sharing privately, hit me up on Slack with the file :smile:

**Comment by bsclifton** [comment]
I'm going to close this issue; the root cause is likely solved with https://github.com/brave/browser-laptop/pull/5559 and there are not clear steps to repro / no example session file.

Please reopen after https://github.com/brave/browser-laptop/pull/5559 is accepted and in master (or a preview/release candidate) and it can be confirmed that it's not fixed.  Thanks :smile:

**Comment by luixxiul** [comment]
@bsclifton Is this fixed with #5600?

**Comment by bsclifton** [comment]
Hi @luixxiul, it's not fixed with that PR, thanks for the follow up

I suspect I have an idea of what the root cause might be- maybe you can help me try to reproduce? 😄 

Basically, history and bookmarks are combined. When you delete a history entry, there is still a bookmark for it. Also, if you remove the bookmark, there is still a history entry for it.

Would you try some combinations of visiting a site, making sure it shows in history, bookmarking it, making sure bookmark shows in bookmark manager.. then deleting the history entry?

I'll reopen issue in the meantime

**Comment by NejcZdovc** [comment]
This should be fixed with #9978
