### ISSUE TITLE
Two windows on xdg-open

### ISSUE THREAD

**Issue by hmrodrigues** [brave/browser-laptop#4247]
When I use xdg-open to open a URL, brave opens two windows, one with the previous tabs a another with the site that I open from the console
It only happens when the browser is closed

Expected behavior: Open a tab a long side with the others instead of a seperate window

- Platform: Arch Linux (from AUR brave-bin)

- Brave Version: 0.12.1

- Steps to reproduce:
    1. Close the browser
    2. Open a link using xdg-open

**Comment by Sh1d0w** [comment]
Further instructions how to reproduce:

This only happens if you have set Brave to start with previous tabs/session. If you already have Brave opened with multiple tabs, xdg-open will correctly open the new url in a new tab.

@luixxiul can you please test the following scenario under Windows and Mac:

1. Set Brave to start with Tabs from previous session
2. Close Brave (make sure no Brave processes are running)
3. Click on external link to be opened in the browser (for example from your e-mail cleint)
4. Observe if it will correcly start with one window or with two

**Comment by bridiver** [comment]
duplicate #4197
