### ISSUE TITLE
try to open a website that has an script that detects an adblocker

### ISSUE THREAD

**Issue by mohit94614** [brave/browser-laptop#4288]
when i tried to open a website that detects that your browser has an adblocker then relevant website doesn't show their data,until we disable the blocker

We should create an similar script to adblocker or integrate the feature that checks the following that either there is an script that checks the adblocker on the browser 
- Platform (Win7, 8, 10? macOS? Linux distro?):Most Probably on each one of that I personally faced it on Win 10 
- Brave Version:0.12
- Steps to reproduce:
  1. create an similar script to block that particular script
  2. More filters need to be there for adblocker
- Screenshot if needed:
  ![time](https://cloud.githubusercontent.com/assets/17672906/18814099/8ddd4db8-832d-11e6-89a1-1cc461ced51c.png)

**Comment by luixxiul** [comment]
For now I'm going to close this issue since this is stale for a long time.

If you are still around here, would you please join https://community.brave.com to discuss about this issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
