### ISSUE TITLE
Brave Payments: Total time spent online is not shown

### ISSUE THREAD

**Issue by dimitri-xyz** [brave/browser-laptop#4331]
This is an enhancement request.

When viewing the Preferences>Payments tab I can see a ranking of the sites I used most with the number of views, time spent and percentage, but I do not know how much time I spent online overall during that "month".

It would be very useful to see how much time I spent online overall on top of the individual site listing.
- Brave on OSX 0.12.1

<img width="839" alt="lixo" src="https://cloud.githubusercontent.com/assets/6128090/18886348/c7c55d38-84ac-11e6-9651-d67c589e4806.png">

**Comment by mrose17** [comment]
@dimitri-xyz - interesting idea. just so i'm on the same page: the browser keeps track of (at most) the last 30 days of activity, so that's the best we could get.

the other thing to note is that the sites shown are the ones that you haven't marked as "never be included" (right click on the publisher to get a menu with that choice, among others), so even if we were to total the views and timespent, it wouldn't reflect your total viewing, just the viewing that you've allowed the browser to account for.

would that still be of interest?

**Comment by dimitri-xyz** [comment]
@mrose17  Good points. I had two uses for this. I want to find out:

1. how much web browsing I'm doing on average each day
2. how much to pay this month by comparing usage to last month's

If we don't include youtube and other high engagement user-content sites, then a "total usage" doesn't really help me find (1). I wanted to use this "total usage" like I use the total GB data in my phone bill. I look at it from time to time just to make sure I'm using the right plan for the amount of data I'm consuming. That's what I'm doing with (2).

Given your comments,  I think a "total usage" is still interesting (I don't want to contribute as much during the months I go on vacation), but not as much as I thought.

**Comment by mrose17** [comment]
ok, thanks! this issue has the amazing 'suggestion' label, so it remains open until we do our post 1.0 review!
