### ISSUE TITLE
Small adjustments to Payment History modal and CSV files

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#4332]
Items to improve:

1 - in "Your Payment History", each link points to "download.csv regardless of the link name in the list ...The save-as file name should match the link name in the list.

2 - CSV file should be sorted by the "Publisher" value

3 - a final record should be present called "TOTAL" which sums the values in each column

Assigned to @diracdeltas - as the implementor of https://github.com/brave/browser-laptop/issues/3477

cc: @bradleyrichter

**Comment by mrose17** [comment]
![1](https://cloud.githubusercontent.com/assets/400552/18887878/ec6f56ae-84aa-11e6-8311-c24aef29c680.png)
![2](https://cloud.githubusercontent.com/assets/400552/18887881/ef0b9102-84aa-11e6-9d17-2cc2045ded5e.png)

**Comment by willy-b** [comment]
Will you have to modify WebContents#downloadURL in brave/electron's `atom/browser/api/atom_api_web_contents.cc` in order to support a suggested filename?

**Comment by diracdeltas** [comment]
@willy-b that's one way to do it; the other is to send the transaction info to the front-end so you can just use an `<a>` element with a filename

**Comment by willy-b** [comment]
Nice. The transaction info is even already present in front-end, so only the transaction->CSV logic needs to be made accessible to `js/about/preferences.js`.(Then `<a href={dataURL} download={csvFilename}>{csvFilename}</a>` will work.)

We could either expose the CSV methods as "static" functions in ledger-client so that `preferences.js` can use them without creating a ledger-client instance, or move the logic to `preferences.js`. (I'm happy to do either today if you haven't done this.)

Independently of this issue, it would be nice for WebContents#downloadURL to have the option to specify a filename.

**Comment by diracdeltas** [comment]
@willy-b feel free to start on this issue; i think moving the CSV logic to preferences.js or to a `js/lib/` util makes the most sense

**Comment by willy-b** [comment]
@diracdeltas, I opened a PR (#4346) switching to an `<a>` w/ data URL and `download` attribute as you suggested, and the name issue is fixed.

I did move the CSV export stuff out, but to `ledger-client/util.js` instead of into `browser-laptop`.
But it is being `require`-ed all by itself as`require('ledger-client/util')`, **without** pulling in rest of ledger-client or its dependencies / messing up webpack. 

(If you don't like that, we can just move `util.js` to `browser-laptop/js/lib/util.js`, as there are no ledger-client deps.)

**Comment by bbondy** [comment]
will not be in 0.12.3rc3

**Comment by alexwykoff** [comment]
what about the edge case of multiple transactions on the same day (as seen in the screenshot)? should there be a differentiator for the file name? otherwise the user is likely to overwrite their own file on export.

**Comment by mrose17** [comment]
that is possible for developers and others who want to mess with `ledger-state.json` ... i wouldn't consider getting the overwrite file warning, the expected behavior...

**Comment by willy-b** [comment]
@alexwykoff, @mrose17 that makes sense.
What do you think about putting the edge case in a new issue so as not to confuse with the changes here which also fix a crash?
I created #4605 to track that edge case, lmk if you prefer not to do it that way
