### ISSUE TITLE
Make bookmark and history management look nicer

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#441]
As Chromium has truly ugly bookmark management and history, i would appreciate it if you would make both parts look more nicer and add more functionality so that it is not that bare bone style.

**Comment by luixxiul** [comment]
Being worked on. The detail is on the issue, whose number I cannot remember. Maybe @bradleyrichter could.

**Comment by SJ-Diamond** [comment]
Good to see that some of my suggestions are considered as useful :D As power user i care of course for tons of customization features and a bit for design too :D

**Comment by bsclifton** [comment]
Happy to report that this issue is being worked on right now :smile: 

Here's what's currently in master- a bare bones history screen:
![screen shot 2016-08-18 at 11 06 26 pm](https://cloud.githubusercontent.com/assets/4733304/17800484/7dee0f30-6598-11e6-8c5b-2d1ecf37fe31.png)

You can right click to delete entries or open them in a new tab. You can also double click entries to open them.

I'm currently adding search and then I'm also trying to organize the entries by date (along with some style updates).  Suggestions or mockups are extremely welcome :smile:

**Comment by bsclifton** [comment]
and here's where we're at now:
![screen shot 2016-08-19 at 1 41 10 am](https://cloud.githubusercontent.com/assets/4733304/17803938/33a17000-65ae-11e6-8ca1-f1506ceeda6d.png)

@bradleyrichter let me know what you think :smile: I grabbed styles from Preferences because I wanted it to look "Brave-esque", rather than the mild black text on white background. I put some sample buttons there, wiring them up wouldn't be too hard (including checkboxes for deleting individual items)

**Comment by srirambv** [comment]
@bsclifton Looks really good. Making urls align would make it look even more polished. More like a tabular items something similar to this 
![image](https://cloud.githubusercontent.com/assets/17010094/17806778/7ae5fc88-65fe-11e6-8ccb-c2fee8448dbf.png)

**Comment by bbondy** [comment]
The grouping should be pretty easily accomplished by using something like:
http://underscorejs.org/#groupBy

I think ledger introduced the dependency so you can use it.  Or else just copy the impl and modify slightly.

**Comment by bsclifton** [comment]
@bbondy is underscore more efficient than just using reduce? Here's a link to the code I put together, it's fairly clean:
https://github.com/bsclifton/browser-laptop/blob/history-page/js/about/history.js#L88

**Comment by bbondy** [comment]
ah sorry I didn't realize you had it done already, your way is fine.

**Comment by bsclifton** [comment]
Here's a screencap of the proposed look, courtesy of @bradleyrichter! Going to start molding the screen to look more like this...
![image](https://cloud.githubusercontent.com/assets/4733304/17838314/88aba926-677f-11e6-9110-28dd7bdcbbd8.png)

**Comment by bsclifton** [comment]
Starting to get there... here's where I'm at currently:
![pasted image at 2016_08_20 03_32 pm](https://cloud.githubusercontent.com/assets/4733304/17839369/4b0a8126-679a-11e6-90f7-5365eeb05da9.png)
