### ISSUE TITLE
Suggestion : Detect filetype and adjust 'Save as...' dialog as needed. 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4417]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When saving a file (ex: http://alexwykoff.com/2/demo/bg.mp3) the dialog says 'Save Page as...' but since this is not a web page, but rather a file, it is confusing. 

**Expected behavior:**
The browser should be able to detect the file type being provided and adjust the UI accordingly.
*It's worth noting that Chrome says 'Save Page as...' as well, however they have a context menu item to 'Save as...' which I would imagine the majority of users prefer.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on Win7 x64 and OS X
- Brave Version:
  0.12.3 RC5
- Steps to reproduce:
  1. Visit a resource online like http://alexwykoff.com/2/demo/bg.mp3
  2. Attempt to save the resource
  3. Observe the UI provided to the user
- Screenshot if needed:
  <img width="830" alt="screen shot 2016-10-01 at 10 11 42 am" src="https://cloud.githubusercontent.com/assets/1434040/19011127/1906c770-87c0-11e6-8833-d8016cba095f.png">

Chrome context menu for mp3:
<img width="444" alt="screen shot 2016-10-01 at 10 13 36 am" src="https://cloud.githubusercontent.com/assets/1434040/19011135/559fe7c0-87c0-11e6-85f0-75112784f59e.png">

Brave context menu for mp3:
<img width="611" alt="screen shot 2016-10-01 at 10 17 22 am" src="https://cloud.githubusercontent.com/assets/1434040/19011137/60530ada-87c0-11e6-9de1-3edd39facaee.png">
- Any related issues:

**Comment by srirambv** [comment]
+1 from community for webpages 
https://community.brave.com/t/save-page-as-not-working/7042/3

**Comment by WausauBill** [comment]
This issue has either been fixed in later versions of Brave or is a Windows specific issue.
Here is what I am using currently:
 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.8.0-53-generic 
OS Architecture: x64

I am running Linux Mint 18.3 with a KDE Plasma desktop.

When I go to the mp3 file referenced above, I do get "Save Page as..." entry in the right click menu.  When I save the page, it is correctly saved as an mp3 file, not as a webpage.
If I go to an image file, the context menu correctly identifies it as an image and shows "Save Image as..." and correctly saves the image.

I can understand that it might be confusing to have the context menu say "Save Page as..." rather than "Save File as..." but other than that the function works correctly in the latest version of Brave on Linux.

**Comment by WausauBill** [comment]
I am a little confused by this as it seems to be both a bug report and feature request.  I was unable to reproduce the bug part of this issue.  Here is my system status:
 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.8.0-53-generic 
OS Architecture: x64

I am running LinuxMint 18.3 with the KDE desktop.

When I go to a media file (.mp3 or .wav for example) the context menu correctly shows a "Save Page as..." menu item and it does save the file as an .mp3, not as a webpage.  Image files do have a "Save Image as..." context menu entry and this works correctly as well.  So the not saving error has either been fixed in later versions or works correctly in Linux.

It would seem to me that having the context menu simply say "Save as..." would be simpler than detecting all the different media types and would not be confusing to the user.
