### ISSUE TITLE
Brave crash when I try to open csv from payment history

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#4433]
- Platform (Win7, 8, 10? macOS? Linux distro?): 

Ubuntu

- Brave Version:

Dev Channel Beta 0.12.3dev-RC5

**Comment by willy-b** [comment]
Thanks for report, I'm looking into this now

**Comment by willy-b** [comment]
Hey @bitcoinuser, on 0.12.3dev-RC5 the whole Preferences->Payments tab is broken.
If I start without any data (~/.config/brave-test), then it hangs creating a wallet:
![stuckcreatingwallet](https://cloud.githubusercontent.com/assets/6969859/19019255/4b1dd3d6-8836-11e6-890b-b43ba80a9a62.png)

If I import data from a previous session (manually, by copying `~/.config/brave-test`, the Wallet balance still fails to be loaded (browsing history, time spent per publisher, is all loaded fine):
![paymentson0 12 3_rc5_existingdata](https://cloud.githubusercontent.com/assets/6969859/19019296/8098059e-8837-11e6-8f2b-91f4a6ba5bbc.png)


@alexwykoff is the Payments tab working for you on 0.12.3dev-RC5 or later?

**Comment by alexwykoff** [comment]
Brave 0.12.3 RC5 on Ubuntu 16.04 latest pass. All systems appear to be functioning properly for wallet creation and ledger.

![ubuntu_brave_wallet](https://cloud.githubusercontent.com/assets/1434040/19020886/7a5784b0-88e7-11e6-9431-ff80885a1745.gif)

Testing the CSV will mean forcing a reconciliation IIRC. To do so, edit ~/.config/brave/ledger-state.json and change the  "reconcileStamp" value to a very small number (like 0).

This does mean MONEY WILL LEAVE YOUR WALLET. 

@diracdeltas might have another suggestion for a means of mocking the creation of payment data so that you can check the frontend without it costing real money.

**Comment by willy-b** [comment]
Thanks @alexwykoff. As long as wallet creation is working, you can also point your client at testnet to test CSV, which is what I have been doing: https://github.com/brave/browser-laptop/issues/4286#issuecomment-250875786

**Comment by willy-b** [comment]
Hey @bitcoinuser, I unfortunately can't reproduce this. I was able to test the full Payment History flow on the latest build, but didn't get any crash or error.

Would you feel comfortable sharing any of your ledger data files? E.g.` ~/.config/brave-test/ledger*.json`.
You can email to willy@entropi.info if you like or post somewhere public and link. WARNING: if you have any remaining bitcoin balance you should OMIT `persona.wallet.keychain` from `ledger-state.json`

**Comment by bitcoinuser** [comment]
Hi,

Strange. I'm not reproducing the problem anymore.

2016-10-02 19:49 GMT-03:00 Willy Bruns <notifications@github.com>:

**Comment by willy-b** [comment]
Now I'm really looking forward to writing automated tests for this stuff :-)

**Comment by lucaszanella** [comment]
Same here, Debian 8

**Comment by willy-b** [comment]
Hey @lucaszanella! 
Can you provide more details please? 

Does the Payments History panel load, but opening a CSV crashes Brave?

**The CSV link is just a `<a>` element with a data URL in the `href`** so if the Payments Panel loads but that crashes it there may be a general problem with data URL handling.

**Comment by willy-b** [comment]
@alexwykoff (or anyone from Brave) have you been able to reproduce this crash?

**Comment by willy-b** [comment]
@lucaszanella, If you could right click the CSV link, click "Copy Link Address" and paste it here, that would be extremely helpful. (NOTE: this will share the contents of the CSV)

**Comment by willy-b** [comment]
OK, figured this out after talking with Alex from BitGo who had this problem.

The pre-packaged download / version of Brave pushed by update does not have #4332 in it (specifically https://github.com/brave/browser-laptop/commit/87ad861714d5f56f3988293c26b9febcfdaa81d3 ).
Whereas it IS in the latest tags from Git, e.g. https://github.com/brave/browser-laptop/releases/tag/v0.12.3dev . The pre-#4332 CSV export (which used an Electron call to download rather than a data URL) appears to cause this crash. 

Question for @bbondy or any other Brave-r:
how does one figure out which Git hash a packaged release (on Downloads page or pushed via update) is built from?

**Comment by diracdeltas** [comment]
@willy-b i think releases are built from the tip of the dev-channel branch but @bbondy can correct me if not

**Comment by willy-b** [comment]
Ok, cool. Is there a build timestamp then to figure out what the stte of the dev-channel branch was at the time the release was packaged? 

----
Here's why I'm asking.
The Dev-channel was updated early this morning, at ~5:30a w/ v0.12.3dev at commit 9117f09:
![0 12 3dev_released_530a](https://cloud.githubusercontent.com/assets/6969859/19061174/47b84f82-89a3-11e6-8a65-0832337ab9ee.png)

That hash includes the data URL for export fix (https://github.com/brave/browser-laptop/commit/87ad861714d5f56f3988293c26b9febcfdaa81d3).

However, the 64-bit linux .deb downloaded from the Brave downloads page at 1:40p pst (`brave_0.12.3_amd64.deb`, sha256sum starting w/ `2394f`) doesn't have the data URL change:
![bravepayments0 12 3_prepackaged_build_no_data_url](https://cloud.githubusercontent.com/assets/6969859/19061237/e39ca074-89a3-11e6-8996-380a1b634a08.png)

So the `brave_0.12.3_amd64.deb` I downloaded must have been prepared earlier than 5:30a and it would be cool to be able to tell that easily :-)

**Comment by mrose17** [comment]
@willy-b - are you of the opinon that builds with #4332 will not have the problem seen by @lucaszanella & @bitcoinuser ?

**Comment by willy-b** [comment]
Yes, @mrose17 , as it is just a standard data URL link, e.g. `<a href="data:text/csv;base64,[...]">` instead of a link with an onClick handler which tiggers an IPC message and an Electron call to downloadURL. 

See diff:
https://github.com/brave/browser-laptop/commit/87ad861714d5f56f3988293c26b9febcfdaa81d3#diff-e3eeb751016b2ce9f8278efce585a461L543

**Comment by mrose17** [comment]
@willy-b - many thanks!
