### ISSUE TITLE
Implement history and Ctrl +Y to bring it up

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#444]
Ctrl +Y does not bring up history in windows version of Brave, it literaly does nothing.

**Comment by hasanhuseyincakir** [comment]
Ctrl + H doesn't work either.

**Comment by Tombsmen** [comment]
hasanhuseyincakir Ctrl + Y is the key set for Brave Ctrl + H is for other browsers.

**Comment by opyh** [comment]
Is there an ETA for that? That's really the biggest thing that prevents me from being able to try Brave as my main browser…

**Comment by dunn** [comment]
Based on the forward- and back-button context menus, it looks like each BrowserWindow has its own history.  Does this mean that Electron has no concept of global history and it'll have to be implemented from scratch in Brave?

**Comment by Duranis** [comment]
this seems like a downer.  Received a Brave - UPDATE message.  Went ahead with it thinking either 1) would reopen with the tabs I currently had open...no it did not (yes I did have that preference turned off - but when the browser prompts you to perform an update and that it needs to restart perhaps either bypass the preference and restore pages on restart or give the option to override your preference at that time) that did kinda irritate me because I had forgotten I had that option off.
But 2) History : I should be able to see my history and restore the tabs that A) I had opened last (...Firefox - "Restore Previous Session") or B) at least see the history of pages I have opened over the course of today, yesterday, etc...  Sadly I cannot see any history, no history log at all and the "Reopen Last Closed Window" does squat.
Windows 7 Ultimate
Brave 0.11.4
