### ISSUE TITLE
Brave ad blocker affecting legitimate images

### ISSUE THREAD

**Issue by parkumcp** [brave/browser-laptop#4442]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The ad blocker feature is blocking legitimate images on websites like cnet.com and costco.com

**Expected behavior:**
Legit, non-ad related images should be visible

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
v0.12.1

- Steps to reproduce:
    1. Select "Block Ads" within Ad Control preferences and visit cnet.com or costco.com to see legit images being blocked in Brave.
    2. Or select "Allow Ads and Tracking" to allow images to be visible. 

- Screenshot if needed:
Not needed

- Any related issues:
None

**Comment by stshank** [comment]
I have this issue a lot on CNET. Often the top image loads, but subsequent images in a story show only alt text. Screenshot attached of one example.
<img width="992" alt="screenshot 2016-10-18 11 46 11" src="https://cloud.githubusercontent.com/assets/16833251/19491653/96ef329c-9528-11e6-8deb-04a82a84d1b4.png">

**Comment by privatzee** [comment]
An example of an image URL blocked at Costco by _Ad Control/Block Ads_ is:
`http://richmedia.channeladvisor.com/ImageDelivery/imageService?profileId=12026540&amp;imageId=1103544-847__1&amp;recipeName=350`

For this purpose, ChannelAdvisor is the equivalent of a CDN.

**Comment by privatzee** [comment]
One approach would be to have an intermediate blocking level, wherein a user allows a known list (provided by Brave) of CDNs and CDN-like sites. The CDN sites are still spying, of course, but they are not exclusively spying. The whitelist probably won't be very large, because it'll be made up mostly of a few large companies. 

This is like IE's security slider, which I never liked, but the approach fits better here.

Otherwise, having a user individually select what sites to block likely leads to the decision fatigue spoken of elsewhere by @BrendanEich. (Though he was talking there about payments, it's still the same thing). After all, anybody can already use any browser and install adblockers and script blockers and https rewriters and cookie blockers - but only a few hardy souls will actually do all of that. For Brave to thrive, you need to provide one-click solutions for the masses. After that, it would of course be good to have more complexity available for the aficionados who want it (and will not recommend Brave to others without it). The complexity should be unobtrusive, so as not to clutter the UI and drive away the masses.

**Comment by bbondy** [comment]
Fixed by:
https://github.com/bbondy/abp-filter-parser-cpp/commit/78f61117f52e9e52f1b3782027ee4a65b7abc678

https://github.com/SergeyZhukovsky/tracking-protection/commit/904dd09e42b0fc65107574ceb405fd3b14cbe414

This isn't ideal but for now it's better for webcompat. 

We were able to get the images unbroken but not the video by doing this w/ no filtering rule changes within cnet.com for future reference:
```
$('img[data-original]').each(function (img) {
  $(this).attr('src', $(this).data('original'))
})
```

**Comment by srirambv** [comment]
Not working reopening the issue. 

Related issues: #5151

**Comment by privatzee** [comment]
similar: Facebook CDN for images #5153

**Comment by bridiver** [comment]
@privatzee I'm seeing the FB problem in Brave ios, but seems to work on desktop. You're seeing it on Desktop as well?

**Comment by privatzee** [comment]
@bridiver yep, eg. at https://developers.facebook.com/?ref=pf
Win7 x64 
Brave 0.12.6

But I don't have a FB acct, so I don't know about users' pages.

**Comment by bridiver** [comment]
I believe @bbondy has pushed updates to fix both issue

**Comment by bridiver** [comment]
but I want to revisit the cnet issue because this could be a start of a new trend to bypass ad blockers. Mixing ad/tracking content with legitimate content will require more sophisticated blocking techniques

**Comment by privatzee** [comment]
> Mixing ad/tracking content with legitimate content will require more sophisticated blocking techniques

@bridiver How about allowing only images and videos from certain origins, but blocking scripts from that origin? 

Btw, the problem still exists for me, please see #5153 again, bottom comment.

> Mixing ad/tracking content with legitimate content...

Made me think of google's _helpful and free_ fonts to grab users' IPs :)

**Comment by bridiver** [comment]
it's not quite that simple unfortunately. We found an easy workaround for the images, but the videos won't play unless you load one of the scripts. We can still block the other scripts that are loaded from the first script and we still block 3rd-party cookies, but they will likely become more sophisticated and start delivering site and ad/tracking content mixed together

**Comment by bridiver** [comment]
@privatzee I think the tracking list only updates on browser restart and it runs in the background so you may not see it right away. @bbondy can confirm or provide better info

**Comment by privatzee** [comment]
@bridiver Okay, thanks for the insight, Bryan.

I had just restarted, but the problem remains the same.

**Comment by bridiver** [comment]
I never saw the problem on browser-laptop, but it's working for me now on ios

**Comment by bbondy** [comment]
List updates happen once per day at most, and it'll apply to even old versions. So I think you just have to test this again @srirambv maybe by tomorrow.

**Comment by privatzee** [comment]
FWIW: still

**Comment by luixxiul** [comment]
It seems that it works fine on https://www.facebook.com. Images are no longer blocked.

@bbondy still I'm a little bit worried, because this time no ads/trackers are blocked. Is it fine?

**Comment by bbondy** [comment]
I think they are served 1p rom there, was it the case we used to have some blocked there?

**Comment by jmmartinez300** [comment]
I like Brave. I also would like to block all images, but cannot find the way to do it... Thanks. JMM

**Comment by Liunkae** [comment]
@jmmartinez300 That feature is being tracked in issue #4065.
