### ISSUE TITLE
Offer the user a way to opt-out of crash reporting

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4479]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
We use electron's crash reporting code to collect data about crashes that occur (which do not contain personally identifiable information (PII)). Not all users are OK with this and would like a way to opt-out.

This could be offered during installation and/or as a preference

**Expected behavior:**
When a crash occurs, no information is transmitted.

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version:
all (current version is 0.12.3)

**Comment by bbondy** [comment]
@aekeus would you mind taking this one? We need to have it for 1.0.  The switch control can go into preferences in advanced section under Enable smooth scrolling.


smooth scrolling is one of those things in `app/index.js` that you have to set early on or it has no effect. I think you can init `crash-herald` alongside it, just search for `disable-smooth-scrolling` in `app/index.js`. 

I'd like you to take this because you can best make sure we are still getting crash reports still.

**Comment by aekeus** [comment]
Fixed with pull request https://github.com/brave/browser-laptop/pull/4606
