### ISSUE TITLE
Right click on a window when it doesn't have focus causes error

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#448]
> Cannot read property 'webContents' of null

**Comment by inian** [comment]
This happens to me only when I have focus on the dev-tools and right-click on the window I am debugging. 

This is because `BrowserWindow.getFocusedWindow()` can return null if no window is being focussed ([doc](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindowgetfocusedwindow)). I don't think the focus actually shifts to the window even though you right click on the window from another window. 
 
We should have a check [here](https://github.com/brave/browser-laptop/blob/master/app/index.js#L132) if the value returned from the function is null

**Comment by luixxiul** [comment]
Does this still persist?

**Comment by luixxiul** [comment]
Closing as stale.
