### ISSUE TITLE
Brave cannot load PDFs with JS PDF reader in session tabs

### ISSUE THREAD

**Issue by pureooze** [brave/browser-laptop#4651]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
PDF files do not load using the JS pdf reader when using a session tab. I just get a blank tab when I attempt to load a PDF in a session tab.

**It works fine in non-session and private tabs.**

**Expected behavior:**
PDF should load.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux, OpenSUSE 42.1
- Brave Version:
  0.12.4
- Steps to reproduce:
  1. Open a new session tab
  2. Visit any link that should load a PDF
- Screenshot if needed:
  Session tab (PDF does not load):
  ![image](https://cloud.githubusercontent.com/assets/2337524/19244283/9e62e4a0-8ee9-11e6-8f3b-5ec3171ba8a1.png)

Regular tab (PDF loads):
![image](https://cloud.githubusercontent.com/assets/2337524/19244295/aa16152e-8ee9-11e6-97a7-160e664a54fd.png)

**Comment by diracdeltas** [comment]
confirmed on mac that pdfjs works in private and regular tabs but not session tabs

**Comment by kjozwiak** [comment]
This issue is reproducible in Windows as well. When loading PDF's via session tabs, you'll get the following error within the tab:

> Your file was not found
> 
> It may have been moved or deleted.
> ERR_FILE_NOT_FOUND

* Platform: Win 10 x64 Build: 10.0.15063
* Brave version: 0.18.14, 0.18.20

STR:

- open a new `regular tab` and load https://bitcoin.org/bitcoin.pdf (no issue)
- open a new `private tab` and load https://bitcoin.org/bitcoin.pdf (no issue)
- open a new `session tab` and load https://bitcoin.org/bitcoin.pdf (ERR_FILE_NOT_FOUND)

**Example:**

![pdfsession](https://user-images.githubusercontent.com/2602313/29151082-d1bd787c-7d4c-11e7-92b2-8e680d9160a4.gif)
