### ISSUE TITLE
Create new preference for controlling telemetry

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4691]
The user should be able to control whether Brave is allowed to collect and send anonymous information regarding performance, memory usage, or other collected statistics.  

If disabled, Brave will respect the user's settings and not collect or transmit info.

- Screenshot if needed:
cc: @bradleyrichter for screenshot

- Any related issues:

**Comment by bradleyrichter** [comment]
Are we OK with merging both of these settings like Chrome does?

![image](https://cloud.githubusercontent.com/assets/13509546/19291565/de59fb3e-8fca-11e6-9d17-78c87f80d897.png)

**Comment by privatzee** [comment]
@bsclifton Bravo, Brian. Having telemetry sent while having no ability to turn that off is really very out of place on a privacy oriented browser. You absolutely need the off switch before 1.0 and would take flack without it. 

Ideally, things should be set up to _opt-in_ to telemetry anyway. Otherwise the off switch should be **prominently** revealed somehow. It was only yesterday that I stumbled across the word _telemetry_ within Brave or on the website somewhere - I was taken aback by that. I would have been ticked off if I was currently using Brave for anything other than here at github, and related activities.

**Comment by bradleyrichter** [comment]
@privatzee For mobile, we will have an opt-out screen at the beginning. See below:

![image](https://cloud.githubusercontent.com/assets/13509546/19292749/45ed1cba-8fd3-11e6-9fd1-c6038a915153.png)

I was planning to use a similar approach for desktop. Any thoughts?

Typically, if the switch is off by default, the amount of useful information we will receive will be quite low. Since we are a privacy browser, everything we do is anonymized. And learning about crashes is very valuable.

**Comment by privatzee** [comment]
@bradleyrichter That screen seems like the right way to me, Bradley. No one can say they didn't know. 

I would separate out crash reports, maybe have that pre-checked. For telemetry, that would be pre-unchecked but I would add extra _begging_, so to speak. Say it's for the common good and the user can always go back to no-telemetry later. I think your biggest user base should come from people who want privacy but do not want to spend hours in research becoming acquainted with what is necessary. They won't even want to to spend more than a few minutes. So they have to trust you and once broken you can't get that back. Give them the choice but beg more.

I just had an image in my mind of using a graphic of a somewhat comical looking angel with hands in a begging gesture :)  I might then even check that box myself.

Oh, and I'd also I'd include the word 'anonymized' on that screen. (Though I would personally say there is no such thing because IP is always there.  Hmmm... in some other more verbose place I'd say that IP is never stored, which I hope it isn't.)

Keep up the good work, Bradley. You and Brian and the heroes of the day.

**Comment by privatzee** [comment]
How about this: if the telemetry choice is unchecked when the screen is presented, then a lot of people will just brush past that and click to Accept without changing it. So then what if instead there are two boxes, allow or not-allow, and the Accept button is not clickable until a choice is made. Just thinking out loud here.

-----

I'll mention that today is Windows Update day, wherein users have to not only think about protecting themselves from criminals but also from Microsoft itself. Their opt-out of telemetry was always sneakily buried, and 'recommended' updates try to re-enable telemetry all the time.  

The Atom editor sends spy data to google via analytics. That's the first I know of application software being so infected. But at least they told us when first starting it up, so that's fair even if misguided.

**Comment by Liunkae** [comment]
IMO, Brave should try to be much better than Chrome when it comes to privacy. 😉 

FYI, Firefox separates telemetry and crash reporting:
![image](https://cloud.githubusercontent.com/assets/19424103/19296440/1909bfe0-9001-11e6-8de8-238f96422128.png)
In Firefox, I think crash reporting is on by default but telemetry is not.

Regardless, I think an opt-in/out screen on launch and options in settings are essential for Brave.

**Comment by privatzee** [comment]
Speak of the devil, the latest update for Atom (a few days ago) presents the user with a choice page. The options for crash/telemetry are split. There is also some _extra text_, which I've colloquially described as _begging_, which asks at a little length to allow both - rather than the cut-and-dried short boilerplate which is usual. 

Sorry, I should have taken a screen shot but didn't.

**Comment by gw0** [comment]
I am unable to find this preference in Brave on Android and telemetry is being sent without my consent.

**Comment by bsclifton** [comment]
Hi @gw0 - this repository is for an outdated (no longer supported) version of the Desktop browser

You might check here - feel free to open an issue:
https://github.com/brave/browser-android-tabs
