### ISSUE TITLE
Characters fall off if URL is autocompleted on the URL bar 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4731]
**Describe the issue you encountered:** On the latest master, if history entries are found and autocompleted, some characters on URL bar fall off if you type them fast, like “github” -> “gihub".

**Expected behavior:** They should not fall off.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: https://github.com/brave/browser-laptop/tree/f9f9bffc6465d28d3dbfc7e4869482ff0d9c72ba

- Steps to reproduce:
    1. Go to https://github.com/brave/ and https://github.com/brave/browser-laptop
    2. Open a new tab
    3. Type "github" fast

- Any related issues:

Please set a milestone if necessary.

**Comment by bbondy** [comment]
cc @diracdeltas

**Comment by luixxiul** [comment]
Also the autocomplete pulldown flickers if another github page is bookmarked

**Comment by diracdeltas** [comment]
@luixxiul did you test this after pulling f9f9bffc6465d28d3dbfc7e4869482ff0d9c72ba?

**Comment by diracdeltas** [comment]
@luixxiul never mind comment above, i just saw you included the version in the issue

**Comment by Sh1d0w** [comment]
This is still happening from time to time for me on 0.12.5-RC1. I am not sure how to reproduce 100% but it happened several times with the following pattern:

1. I have opened new tab as ususal
2. Started typing url of a website I often visit (I was not typing fast, just with a normal speed
3. After I wrote the domain name before the `.` and started typing `.com` the characters start to ersa and I had to type them twice. Even after I typed the whole address before I hit enter I deleted the .`.com` part and started typing it again again characters were dissapearing so it was 100% reproducible.
4. I closed that tab without navigating to the address and opened new tab again. After that the issue was not reproducible

I thought it was something not worth to mention but happened twice more times this morning.

Brave version: 0.12.5-RC1

**Comment by Sh1d0w** [comment]
Here is a video. I typed random chars, that even do noe autocomlete and still lossing chars.

Typed `waywwad`, result in the url bar was `waywwd` - http://webm.land/media/cZYK.webm

cc @diracdeltas

**Comment by bbondy** [comment]
would like to get this in 0.12.6 if possible

**Comment by bbondy** [comment]
Moving to 0.12.6

**Comment by diracdeltas** [comment]
please try out the fix in 2c5a369. it seems that characters are only lost when the in-place autocomplete happens as a key is being pressed, so i just changed it so that autocomplete never happens while a key is pressed.

**Comment by Sh1d0w** [comment]
@diracdeltas Just builded it and installed. Good job, seems it is working correctly now :+1:
