### ISSUE TITLE
Correction in Linux install instructions

### ISSUE THREAD

**Issue by Kasmetski** [brave/browser-laptop#4740]
I'm using Fedora 24 64bit. At first I have follow your guide:

```
sudo dnf install lsb
wget -O brave.rpm https://laptop-updates.brave.com/latest/fedora64
sudo dnf install ./brave.rpm
```

but it gives me error with `dnf install brave.rpm` , so I did it with `rpm -i brave.rpm`
Add this to the manual, because someone new to Linux and Fedora could have the same problem and maybe he wouldn't know how to solve it.

**Comment by pureooze** [comment]
I'm not familiar with dnf but are you sure the issue wasn't with dependencies rather than command syntax errors? I know zypper attempts to resolve dependencies when you use `zypper install file.rpm`. If that's the case it might be better to just host a repo that has the needed dependencies rather than forcing users to do manual RPM updates.

I'm familiar with RPM packaging and OBS so maybe it could be setup to allow builds for various distros. I know it has support for Fedora, OpenSUSE, Ubuntu and RHEL/CentOS.

**Comment by luixxiul** [comment]
I'm going to close this issue for now, as the document has been changed significantly and updated. Let's reopen if the latest instruction does not work 👍
