### ISSUE TITLE
Bookmark folder disappears after drag and drop in about:bookmarks

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4751]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I was drag and dropping in the new about:bookmarks screen and one of my folder disappeared. No matter what I did, I could not find the folder. The bookmarks are still there; you can search and find them.  I opened the session file up and saw the the folder in question had it's parentFolderId set to the same number as the folderId (which should be impossible)

JSON from the session:
```javascript
{
  "lastAccessedTime": 1475044276843,
  "tags": [
    "bookmark-folder"
  ],
  "folderId": 1,
  "customTitle": "favorites",
  "parentFolderId": 1
},
```

**Expected behavior:**
You should never be able to move a folder onto itself

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac, but @alexwykoff had it occur on Windows

- Brave Version:
HEAD of master

- Steps to reproduce:
  I cannot reliably reproduce, but @alexwykoff had encountered the issue too

- Screenshot if needed:
![windows_folder_drag_poof](https://cloud.githubusercontent.com/assets/4733304/19367730/38337bc6-9151-11e6-93fe-6a7bdeb9cb4d.gif)

- Any related issues:

**Comment by ajohnsen** [comment]
I just had this same bug happen to me in the bookmark toolbar.
I checked in the session-store1 file and when i look at my missing folder i can see it, but its referencing itself as the parentId. 

Could it be possible that this bug is back or maybe not fixed in the bookmark toolbar?

Is there any way to get the bookmark folder back? I tried editing the json file, but that didn't change anything.
