### ISSUE TITLE
contents of ledger recovery key text file should be set to the spec 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4807]
**Describe the issue you encountered:**
According to https://github.com/brave/browser-laptop/issues/3350#issuecomment-241897227 the contents of ledger recovery key text file should be like this: 

```
Brave Wallet Recovery Keys
Date created: 08/12/16

Recovery Key 1: e0c455d3-8b8a-40da-9358-2c38ce380b80
Recovery Key 2: 73de0bee-31f3-40e9-9a01-0f27958d925a

Note: These keys are not stored on Brave servers. These keys are your only method of recovering your Brave wallet. Save these keys in a safe place, separate from your Brave browser.
```

For now the key file lacks the date created and the note. Also the keys should be labelled.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.5 RC1
- Any related issues:

**Comment by bbondy** [comment]
cc @jkup please handle for 0.12.6

**Comment by jkup** [comment]
@bbondy happy to, this must have gotten lost in the shuffle but I did have a question about how best to handle this. Right now the text that gets printed or saved is just a string in one of our properties files (https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/locales/en-US/app.properties#L129) 

In order to make this to spec I'll need to add new line breaks. What's my best approach here? A bunch of strings (one for each line)?

Thanks!

**Comment by bradleyrichter** [comment]
this is nice to have as the current implementation is lacking the friendly factor...

**Comment by bbondy** [comment]
I think the string would just be an HTML string instead.  Should be able to just use template strings to hack that together.

**Comment by mrose17** [comment]
when we do get around to addressing this issue, perhaps we can also deal with the line-wrap issue!

![2](https://cloud.githubusercontent.com/assets/400552/19693263/bf7765b0-9a8f-11e6-82b2-c47861050e83.png)

**Comment by jkup** [comment]
@mrose17 definitely. I think the line wrap should be an easy fix as there is only so long a key can be.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5862#issue-191893476
