### ISSUE TITLE
Implement an upgrade details tab with fixes and new features for each upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4853]
It would be nice to show a new tab with the new features and fixes for that release when a user completes the upgrade. This upgrade details tab should be shown only once when browser relaunches after update. This way users will get to know what's new and what has been fixed.

**Comment by Sh1d0w** [comment]
I'd rather wish Changelog page implemented, rather than force opening new tab after update. For technical users it may be cool, but regular users won't understand much of it not they will be interested.

Implementing changelog page will allow geeks to see fixes not ony for the current build, but for previous ones as well.
