### ISSUE TITLE
Add support for PGP email encryption

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#4914]
From support: https://linkbubble.zendesk.com/agent/tickets/5626

> Hello
> 
> I have started to use your brave browser. It is ok for me, but I would like you to add PGP email encryption add on possibility. I am using Mailvelope for Chrome now I cant read my encrypted Gmail emails in Brave.
> 
> Regards
> 
> Blaž

**Comment by NumDeP** [comment]
I will never be able to create anything remotely as good as Mailvelope, so it's quite rich for me to say this but that extension as well as many other PGP / GPG based extensions when requested will only be taxing not just for team but also on the browser because users would essentially be requesting a solution which is exactly the same with the exception ui/ux differing and possible one or two features. 

So I think a better solution needs to be engineered as opposed to simply forking every single request that is made because personally I don't want to always turn on and off an extension which I'm not always going to be using like a VPN. 

We see it all too often specifically in Firefox and Chrome when extensions and applications of the sort are unnecessarily running in the background and there's a whole row of extensions not being used at all and stressing the CPU/Memory. Even though if users have at least 8, 16GB or greater DDR4/LPDDR4 I hope you understand this is not my point, it just makes it less efficient.

Take the 'Don't manage my passwords' in Password Manager for example, is it any different from having it set to 'Brave Built-in' - This is how I think it should work, I think if you have it like this it would also further encourage non-users of such solutions to play about with it whilst educating themselves why it is a necessity in this day an age as similar solutions and services become ubiquitous. 

+1 - https://community.brave.com/t/built-in-encryption-solution-for-secure-emailing-functionality-without-addons-for-all-email-services/1754

**Comment by bsclifton** [comment]
Mailvelope should work great in [brave-core](https://github.com/brave/brave-browser) 😄 👌
