### ISSUE TITLE
Folders in about:bookmarks should be collapsable

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#5077]
I have several dozen bookmark folders organised in a hierarchy. The folders list in about:bookmarks should be collapsable as per Chromium (and other browsers).

Related to: #5076

Ubuntu 16.10
Brave: 0.12.5
Electron: 1.4.14
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/9241

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmark-page-add-alphabetical-sort-option-add-collapse-and-expand-option-for-nested-folders/26679?u=eljuno

**Comment by bsclifton** [comment]
We won't be fixing with the Muon codebase, but this is already fixed with [Brave Core](https://github.com/brave/brave-browser) (coming soon). Here's a screenshot of the fixed UI in action:
![screen shot 2018-07-01 at 10 07 56 pm](https://user-images.githubusercontent.com/4733304/42146237-69c0912a-7d7b-11e8-9591-ff4257d86a90.png)
