### ISSUE TITLE
Adjust widevine flow for ease of use

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5131]
The initial implementation required 2 separate alert bars and a trip to Brave preferences.

This approach allows the first-time  Brave "streamer" to complete the task in a single alert bar plus a dialog but retains the same legalese.

step one. User visits netflix.com (example) and receives alert bar.

![image](https://cloud.githubusercontent.com/assets/13509546/19706584/9a6198a8-9ae0-11e6-93bf-0936f2a6c37f.png)

Step two. User clicks "allow" and a modal dialog opens:

![image](https://cloud.githubusercontent.com/assets/13509546/19706608/ca1aba20-9ae0-11e6-9a0d-02ae79c6125d.png)

(checkbox from bar is translated and made available on bottom of dialog)

If a new site requires "allow" after this initial installation dialog, only the bar will be shown.

If a user wishes to uninstall the plugin (effecting all sites that require it) they may disable it from the Brave Prefs panel:

![image](https://cloud.githubusercontent.com/assets/13509546/19706666/1b479918-9ae1-11e6-9ffd-f6f5b9a69cb8.png)

**Comment by EuNlope** [comment]
**Initially visited the site (netflix.com) and tried to install the component but the dialog box does not appear, uninstalled the Brave and installed it again, I entered the same site but the dialog box does not appear persists ... Ai goes a print ->**

![dialog](https://cloud.githubusercontent.com/assets/20443574/19709865/bc905c52-9b08-11e6-9ce1-934eee275e4c.png)

**Comment by bbondy** [comment]
@EuNlope this is only available in 0.12.7 which hasn't shipped yet

**Comment by EuNlope** [comment]
Ok I'm sorry.

**Comment by bbondy** [comment]
Didn't make it as pretty but it's consistent with the rest of the app, this is what I ended up with since this is short notice task / spec change to begin with:
<img width="997" alt="screenshot 2016-10-27 00 43 48" src="https://cloud.githubusercontent.com/assets/831718/19754764/70b35308-9bde-11e6-99ad-72e9e648c645.png">


New flow:
1. Go to netflix.com
2. Click Install and Allow

It reloads when installed (which is almost instant, then enjoy netflix).

**Other use cases:**

If you cancel instead of install, it just doesn't show anything until the next page load on netflix where it will show the dialog again.

You can still go and install via preferences which looks slightly different now too and install that way:

<img width="1405" alt="screenshot 2016-10-27 00 46 01" src="https://cloud.githubusercontent.com/assets/831718/19754795/bde84b06-9bde-11e6-816b-655e6d837002.png">
 

If you do that, or if you unclick the remember always from the first dialog & visit in a diff tab later, you get a normal permissions hanger:

<img width="1436" alt="screenshot 2016-10-27 00 48 32" src="https://cloud.githubusercontent.com/assets/831718/19754838/18f47b46-9bdf-11e6-9177-5743f09ff124.png">
