### ISSUE TITLE
Adjustable Brave UI

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5143]
A user requested that Brave's UI be adjustable, making it easier to read text in menus, tabs, and more.

**Comment by bradleyrichter** [comment]
We will get to this in 1.2 timeframe. It will take some refactoring so that all of the text related containers can grow to fit the font sizes without falling apart.

**Comment by jaredbeck** [comment]
As someone with bad eyesight, I've used browser plugins like https://addons.mozilla.org/en-us/firefox/addon/theme-font-size-changer/ for this, with mediocre results. What a joy it would be to have this built into the browser UI!

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/make-the-different-tabs-have-larger-fonts/699

**Comment by jonathansampson** [comment]
This is now supported from preferences.

**Comment by bradleyrichter** [comment]
hey @jaredbeck - if you get a chance to try the UI zoom feature, please let us know how you like it.

**Comment by jaredbeck** [comment]
> hey @jaredbeck - if you get a chance to try the UI zoom feature, please let us know how you like it.

I just updated to 0.17.13 and Preferences -> General -> Default zoom level worked like a charm. This is really great for me. I've wanted a browser with a legible address bar for so long. Ever since Navigator UI text has just 
gotten smaller and smaller, and/or my eyes have gotten worse! Thanks to everyone who worked on this.
