### ISSUE TITLE
Websites blocked by Net-Nanny opens in Brave

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5149]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
From [Support ](https://linkbubble.zendesk.com/agent/tickets/6346)

> I was still able to go to sites that I blocked without a password when using Brave as my browser. 

**Expected behavior:**
Sites blocked by website blocker should be respected by Brave
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  0.12.6 
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by privatzee** [comment]
I took a quick look at their website. They talk about filtering by page content, so that possibly means that they install themselves as system proxy. I tried Fiddler as a test and that works with Brave. So why not Net Nanny? If that user isn't using mobile, then it's a mystery and they likely need to contact Net Nanny's support.
