### ISSUE TITLE
Images not loaded on Facebook.com when block ads is selected in shields

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5151]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Images not loaded on Facebook.com when block ads is selected in shields

**Expected behavior:**
Should show pics when Adblock is enabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.7 Preview 1 (clean install)

- Steps to reproduce:
    1. Enable block ads in Shields
    2. Visit Facebook.com, all images are blocked
    3. Disable block ads, all images are loaded

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19725507/b3f6f608-9b7d-11e6-9ed3-f91ffe0c9487.png)

- Any related issues:
#4442

**Comment by privatzee** [comment]
likely because of blocking Facebook CDN at fbcdn.net: #5153
which is technically CORS

**Comment by privatzee** [comment]
@srirambv Since this is FB, wouldn't this qualify as ultra-top priority? Times 1,000?  :)

Btw, I see that you are not identified as 'Brave Software Member' 

![image](https://cloud.githubusercontent.com/assets/22591438/19730156/48100fd0-9b67-11e6-90f9-ce6431da18f7.png)
versus, e.g.:
![image](https://cloud.githubusercontent.com/assets/22591438/19730030/e7d29354-9b66-11e6-8e01-a656cd53edcf.png)

Just letting you know, I don't mean to be intruding.


Also, one day I was looking around on the website issues, and IIRC it was mentioned that you should be on the website's about page... Okay, here it is:  [needs Sriram](https://github.com/brave/brave-website/issues/126)

**Comment by bbondy** [comment]
This was fixed a couple hours ago and due to a Tracking Protection list update that was overly aggressive.
