### ISSUE TITLE
Add Pocket Integration 

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#516]
Seen some requests in support for Pocket integration.
Would be nice to maintain common features like this.

**Comment by Pitasa** [comment]
It would be great to have Pocket available, but it would be even better to have it 'integrated' in function rather than doing what Mozilla did, disabling the addon and replacing it with a crippled version. Just  saying you integrated it but with all the functionality destroyed  isn't really integrating it.
In Firefox, the old addon version worked much better than the integrated version. If you can integrate it and restore the functionality from before it was integrated it would be really nice.
For example, when you visit a page that you have already bookmarked, the old version would light up the Pocket button so that you know you have already marked it. The button acted as a toggle, so you could mark and unmark by clicking the same button on and off. 
The old version had a drop down so that you could, in a single click view a list of last 10 or so pages added, you could then click on a page in the list and view the original, full webpage.
The Firefox integrated version of Pocket hides the pocket list away in bookmarks, which is pointless, as it's easier to use bookmarks instead. Worse, it only allows wiewing a crippled version of the page, meaning another click to view the full original page - another reason to use bookmarks instead.
All this means that in Firefox, the integrated version of Pocket is useless compared to the pre-integration version.
Please do integrate Pocket, but please make it work at least as well as the old Firefox pre-integrated addon version.

**Comment by luixxiul** [comment]
> In Firefox, the old addon version worked much better than the integrated version.

I couldn't agree more.

**Comment by bbondy** [comment]
If we integrated it'd be the same as the Chrome extension.  It would use that unchanged.

**Comment by sebastianmacias** [comment]
+1, this is so far the only thing keeping me from switching entirely to brave. I even tried the bookmarklet but didn't work.

**Comment by Kinnardian** [comment]
Any updates on this?

**Comment by bsclifton** [comment]
I know we're wanting to add this for sure-
cc: @bradleyrichter

**Comment by bbondy** [comment]
It's in the works, we're hoping by 1.0.

**Comment by HLFH** [comment]
[wallabag](https://github.com/wallabag/wallabag) is the open source alternative to Pocket. =D cc @nicosomb
It would be greater to integrate wallabag! 
If Pocket is added to Brave, I hove that we will be able to remove it!
The [Chrome extension for wallabag v2](https://github.com/Rurik19/wallabagger) does not seem to be entirely ready btw.

**Comment by borisrorsvort** [comment]
@HLFH  It's quite dangerous to integrate a new tech that has no adoption yet. Think about if it goes unmaintained… Then brave would have to pick it up to keep his users happy. Pocket is not open source but is well maintained and probably still for a while. Also, most non tech people will never install wallabag themselves.

**Comment by nicosomb** [comment]
> has no adoption yet

It's like the 1st required experience for a job :) 

> Pocket is not open source but is well maintained and probably still for a while.

Think about if they don't find any business model.

> Also, most non tech people will never install wallabag themselves.

That's why we also have SaaS.

**Comment by luixxiul** [comment]
I assume that's why we are going to add it as extension instead of integrating it as a core service. You'll be able to install wallabag too, if it is configured following the documentation (https://github.com/brave/browser-laptop/wiki/Developer-Notes-on-Installing-or-Updating-Extensions). Sorry if I am wrong.

**Comment by bbondy** [comment]
This is landed, installable in advanced -> extensions. There are some sub-things being tracked separately so I'll close this.
