### ISSUE TITLE
browser restart clears dropdown history

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#5167]
**Did you search for similar issues before submitting this one?**
yes

Win7 x64 
Brave 0.12.6
- Steps to reproduce:
  1. visit some sites
  2. ensure that about:preferences#security is not set to clear history when Brave closes
  3. restart
  4. observe that history dropdown has been cleared
- Screenshot if needed:  **AFTER RESTART**

![image](https://cloud.githubusercontent.com/assets/22591438/19738319/f1deca16-9b84-11e6-95f0-476a71dabf75.png)
---
---
---

![image](https://cloud.githubusercontent.com/assets/22591438/19738458/8430d530-9b85-11e6-980a-1dcb334cc2bf.png)
- Any related issues:
  After some time, the dropdown history starts to get repopulated, but not with recently visited sites -- instead with sites that had been visited an hour or so previously. There's another issue about delayed appearance of history entries. #5072

**Comment by Sh1d0w** [comment]
This is probably related https://github.com/brave/browser-laptop/issues/4794

**Comment by luixxiul** [comment]
Doesn't it work as it should? @bsclifton

**Comment by bsclifton** [comment]
At the moment, this is expected.  History menu will only show what was recently closed:
![screen shot 2016-11-01 at 4 21 09 pm](https://cloud.githubusercontent.com/assets/4733304/19911832/4e18531a-a053-11e6-89ff-49af7d1768ea.png)

Since the browser was closed, this data is lost.  We do have an issue tracking the restoration of frame history when Brave is launched:
https://github.com/brave/browser-laptop/issues/963

For now, I'll close this as a duplicate- since it would be fixed by https://github.com/brave/browser-laptop/issues/963
