### ISSUE TITLE
Block Phishing / Malware toggle in Brave shield is nonfunctional in 0.12.7 Preview 1

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5169]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While visiting http://excellentmovies.net/ as part of the regression pass, it was noticed that the toggle for Block Phishing / Malware did not work, nor did turning shields down.

**Expected behavior:**
Either the toggle or shields down should allow the user to see the site.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.7 Preview 1

- Steps to reproduce:
    1. Visit http://excellentmovies.net/
    2. Turn off the Block Phishing / Malware toggle

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Should be working with newest dat file.  You might need to clear your .dat files in user dir to get it to go if testing within a day.

**Comment by alexwykoff** [comment]
I moved my /brave folder and tried again, but still could not view the site after changing shield settings.

I then turned off malware check at the global level and went back, turned off the site-specific malware toggle, and then I could view the site.

**Comment by luixxiul** [comment]
Confirmed on Win10 32 bit

**Comment by bbondy** [comment]
I decided to keep it the way it is and I updated the test cases to use omomovie.com instead of excellentmovies.net. It works the same as it used to.

The problem that happened is excellentmovies.net was updated to redirect top level to web.mad.excellentmovies.net, so even know you allow excellentmovies.net, it then redirects to web.mad.excellentmovies.net  which is blocked.  

Changing code to allow it based on the parent domain isn't ideal either because it would show the page but on a new domain now, and then you could re-block it but it would re-block the subdomain and not the parent one, and it doesn't work as you'd expect.

**Comment by srirambv** [comment]
Works on  downloadme.org

**Comment by bbondy** [comment]
test cases and wiki was updated to downloadme.org
