### ISSUE TITLE
Feature Request : Keyboard shortcuts for bookmarks in bookmarks toolbar

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5212]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has requested keyboard shortcuts for quick navigation of bookmarks in the bookmarks toolbar like Safari. 

**Expected behavior:**
Users should be able to quickly navigate their favorite sites via keyboard accelerators.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/6313

**Comment by hugobuddel** [comment]
Why is this closed? It would still be nice to have keyboard shortcuts for bookmarks

**Comment by bsclifton** [comment]
@hugobuddel as we wind down development on `browser-laptop` (and ramp up work on [brave-core](https://github.com/brave/brave-browser/)), I've been closing issues which:
- don't have steps to reproduce / description is not very clear
- haven't gotten any +1s or comments
- won't be fixed (until after switch to brave-core is made)
- are fixed in the process of moving to brave-core

The original description for this issue leaves a lot to be desired (ex: I'm not familiar with how Safari does it, so saying "like Safari" doesn't mean anything to me). I would encourage if you wanted this functionality, let's open an issue in the brave-core backlog:
https://github.com/brave/brave-browser/

**Comment by hugobuddel** [comment]
Thanks for the explanation @bsclifton.

I'll try to remember it once brave-browser is released. If I'll forget, then it apparently isn't that important :-)
