### ISSUE TITLE
multibyte characters should be encoded

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5220]
**Describe the issue you encountered:** multibyte characters should be encoded on the URL bar and the status bar, as well as in the site listed on ``about:preferences#payments``.

<img width="435" alt="screenshot 2016-10-28 15 45 50" src="https://cloud.githubusercontent.com/assets/3362943/19797382/bb5fb0c0-9d25-11e6-9767-ef44a7b1677b.png">

the above is Brave, the below is Chrome.

<img width="272" alt="screenshot 2016-10-28 15 54 52" src="https://cloud.githubusercontent.com/assets/3362943/19797568/e72b640a-9d26-11e6-8e37-756691ef3f6e.png">

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: master branch

- Steps to reproduce:
    1. Hover the link [http://はじめよう.みんな/](http://はじめよう.みんな/) 
    2. Open the link [http://はじめよう.みんな/](http://はじめよう.みんな/)

- Any related issues:

**Comment by luixxiul** [comment]
You cannot input Japanese characters in "Home Page" setting on ``about:preferences`` as well

**Comment by luixxiul** [comment]
On URL bar (macOS) multibyte characters are encoded well.

<img width="292" alt="screenshot 2017-06-19 2 14 20" src="https://user-images.githubusercontent.com/3362943/27262589-0a859594-5495-11e7-9e2a-7bac89ad96f1.png">

Maybe thanks to bloodhound update? https://github.com/brave/browser-laptop/pull/8824

CC @darkdh for confirmation with Chinese characters.

**Comment by darkdh** [comment]
<img width="213" alt="screen shot 2017-06-18 at 2 25 54 pm" src="https://user-images.githubusercontent.com/11330831/27264389-16b0bece-5432-11e7-9064-df8c863d9f68.png">
<img width="96" alt="screen shot 2017-06-18 at 2 26 21 pm" src="https://user-images.githubusercontent.com/11330831/27264392-1fa05dfa-5432-11e7-9844-14d285b12204.png">
and your example will give me
<img width="365" alt="screen shot 2017-06-18 at 2 27 15 pm" src="https://user-images.githubusercontent.com/11330831/27264399-475ad3c0-5432-11e7-9c9e-08fd43d23743.png">

I'm on 0.17.3 MacOS
cc @diracdeltas for opinions

**Comment by bsclifton** [comment]
Good call on cc'ing @diracdeltas; because unicode characters can be used to spoof popular sites, it's probably better that we show the raw ASCII name (ex: the punycode encoded domain name).

It would be nice though to either have an option (opt-in) to enable punycode decoding of the domain names (showing in the native unicode) OR for us to consider what type of UX would be needed to ensure users don't get spoofed (do we check against a list? etc)

**Comment by diracdeltas** [comment]
We display punycode-only to prevent homograph attacks, see for instance https://thehackernews.com/2017/04/unicode-Punycode-phishing-attack.html. Google has some standards for what unicode characters should be displayed as punycode. https://www.chromium.org/developers/design-documents/idn-in-google-chrome

**Comment by luixxiul** [comment]
As long as we stick to the Chromium way, it looks good to me.

`http://xn--p8j9a0d9c9a.xn--q9jyb4c/index.html` looks just simply corrupted, and I think we should avoid that.

**Comment by diracdeltas** [comment]
chromium doesn't necessarily filter out all characters that can be used for phishing (which is why the recent IDN attacks affected Chrome but not Brave)

**Comment by kenorb** [comment]
Same for this URL:

- https://puzzling.stackexchange.com/questions/37444/%E1%9A%AB%E1%9B%84-%E1%9B%9F%E1%9B%8B%E1%9A%B1-%E1%9B%97%E1%9A%A3%E1%9B%9A%E1%9A%A9%E1%9A%BB-%E1%9A%A9%E1%9A%AB-%E1%9A%B3%E1%9A%A6%E1%9A%B7%E1%9A%B9-%E1%9A%B9%E1%9B%9A%E1%9A%AB-%E1%9B%89

- Actual result:

I see %E1%9A%AB... instead of the Unicode characters.

- Expected result:

I could see the URL similar as in Chrome or Firefox, e.g.

<img width="635" alt="screen shot 2017-08-25 at 23 52 34" src="https://user-images.githubusercontent.com/266306/29735411-a2a9e4f2-89f0-11e7-885d-d5af2d8061b2.png">

**Comment by bsclifton** [comment]
@diracdeltas this bug is fixed with [brave-core](https://github.com/brave/brave-browser)- but you make a good case for showing the punycode encoded domain. Should we open an issue to also do this in brave-core?

**Comment by bsclifton** [comment]
@diracdeltas created https://github.com/brave/brave-browser/issues/1004 👍
