### ISSUE TITLE
Default browser setting gets reset after upgrade

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5246]
https://twitter.com/konacommuter/status/792107397900673024

@jonathansampson can you audit our defaults registry code to see why Microsoft is resetting us sometimes?  I think only on win10.

Related code:
https://github.com/brave/browser-laptop/blob/master/res/braveDefaults.nsi
https://github.com/brave/electron/commit/7ab83251f3c1c25cdb71a6cd87f19e04793e767d

But maybe inspecting using regedit is easier.

**Comment by srirambv** [comment]
Looks like a Windows issue after the recent update. I am not able to even set Edge as default browser. 
![defaultbrowser](https://cloud.githubusercontent.com/assets/17010094/19827542/97107b7a-9da5-11e6-84f5-2d34ce39a020.gif)

The Only way to set is now by Control Panel>Programs>Default Programs>Set Default Programs and then Brave shows up in System settings. Setting Brave this way also sets it as default client for Email.
![image](https://cloud.githubusercontent.com/assets/17010094/19827545/b6f4658c-9da5-11e6-9de6-f2b16daba5d3.png)

**Comment by bsclifton** [comment]
I believe this has been an issue for as long as I've used Brave :frowning_face:

Original issue here:
https://github.com/brave/browser-laptop/issues/2054

**Comment by lukemulks** [comment]
FWIW - after Windows 10 reset my default browser from Brave to Edge happened again today (for the ~6th time now), I decided to dig in a little more. Admittedly, I'm not as versed in how these updates are detected or configured within the OS to recommend a direct course of action to fix, but I'm going to add some additional info about the issue here in case it helps (as it's a pesky bugger or an annoyance).

I've done some digging around the Windows forums, and there appear to be other variations of the issue as well with Chrome, but I'm only going to include cases I've directly observed below for reference.

I've encountered _**three**_ different variations of this issue over the past 4 months, _**one**_ of which appears to be remedied. 

**Variations of Issue**

1. Windows resets default browser from Brave to Edge immediately following some Windows 10 updates. (still appears to be occurring, have experienced 2x)

2. Windows resets default browser from Brave to Edge randomly. (occurred today, and in one other instance)

3. Windows resets default browser from Brave to Edge, immediately after a Brave version update. (from what I can tell, this has been corrected - I observed this 2x). I have not experienced this variation of the issue for at least 3 Brave browser updates. 

**What _may_ be potentially causing the issue**
After resetting the default browser back to Brave within **_Windows 10 Settings > Default Apps,_** I went a step further into the system settings. 

Steps on how to repro are going to be included below, but basically it appears that although the Default Browser is set to Brave, certain web extensions are not being associated to Brave, but instead are being associated with other browsers (IE and Chrome). 

What I suspect is happening, is that Windows 10 has some security or update check that it runs using both **xht | xhtml** **_and_** **http | https**, but due to the "default browser" not associating all the extensions under the same browser, this mismatch might be flagged by Windows, resulting in the default browser being reset to Edge.

It might be an extension + protocol handling item, but am currently unsure.

I've updated (including in screencaps below) to assign those extensions to Brave, but have not assigned the protocol options as I expect they are probably unrelated (but am testing that out for the next windows update - will include protocols under Brave that aren't if I end up seeing Windows switch the default back to Edge again) 

**Steps to Reproduce**

If Windows 10 resets the default browser from Brave to Edge:

From the **_Settings > Default Apps_** screen, click **_Set defaults by app_** at the bottom of the screen.

The **_Set defaults by app_** link opens: 
Control Panel\Programs\Default Programs\Set Default Programs

Select **_Brave_** from the list of programs in the left column
![windows10_browseralternatedefault_10302016](https://cloud.githubusercontent.com/assets/8979240/19842716/d5e0a5f8-9ed8-11e6-9ca7-8bbf4e60fa42.PNG)

Select **_Choose Defaults for this Program_**

The **_Choose Defaults for this Program_** link opens: 
Control Panel\Programs\Default Programs\Set Default Programs\Set Program Associations

**_With Brave set as the default browser in Windows 10_**, Brave _only appears to be associated with_ **_2/6 extension types_**, and 2/4 protocol types. 
![windows10_browseralternatedefault_associations_10302016](https://cloud.githubusercontent.com/assets/8979240/19842734/f91f9664-9ed8-11e6-893e-9964b12f4ef4.PNG)

**EXTENSIONS**

Brave was set as associated to: 
.htm 
.html

Chrome was set as associated to: 
.shtml
.webp

Microsoft IE was set as associated to: 
.xht
.xhtml


I'm able to select the other extension types and associate them to Brave manually. I suspect this will likely prevent reoccurrences of the issue
![windows10_browseralternatedefault_associations_update_10302016](https://cloud.githubusercontent.com/assets/8979240/19842817/cce46c4a-9ed9-11e6-88cc-04c90df04910.PNG)

I'm not sure if there is a way for Brave to include the extensions above when the user opts to use Brave as the default within the Brave app, but that might do the trick if possible. 

I'll be sure to update here if I run into the issue again after making these manual adjustments. I hope the info helps with resolving (if it's possible to fix independent of MSFT).

**Comment by bbondy** [comment]
Great info thanks, worth noting if the problem goes away after 0.1.28 since I fixed a crash with url handling for the default handler, maybe windows detected such a crash and reset it at that point.
https://github.com/brave/browser-laptop/commit/c73844c961af91bc7e4ce2ea01d50f5b8ffbee79

**Comment by lukemulks** [comment]
Confirming that I have just experienced the issue again (within ~60min of updating to 0.1.28).

What's strange about this particular instance is that I did not receive *_any_* notification from Windows that the default browser was reset from Brave to Edge. 

No notification record displaying in the Win 10 Action Center notification history this time either. 

Typically the notification would be visible, with the record temporarily saved in the Action Center history. 

Within Brave (Gen Settings), Brave is still indicating that it is set as the default browser, despite Windows resetting the default to Edge. 

This is the first instance I have experienced where this has taken place without any type of visible notification from Windows.

**Comment by lukemulks** [comment]
![windows10_browser_update_issue_protocol_11072016](https://cloud.githubusercontent.com/assets/8979240/20087544/4c5bb604-a52e-11e6-8804-19f0bcd4cf5c.PNG)

^^^ - it appears that after the update to v0.1.28, all of the default extension types that were associated by default to Brave remained that way, but the HTTP & HTTPS _protocol associations_ were updated from Brave to Microsoft Edge. 

I haven't updated any settings since this browser reset occurred today, so if there are any other areas you'd like me to check before updating the default back to Brave within the OS, let me know and I'll be happy to reference anything from this end.

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7361)

**Comment by Liunkae** [comment]
+1 from #6987 ("Default Browser" setting lost upon update).

**Comment by lukemulks** [comment]
Confirming the default browser reset happened to me as well from 0.13.0->0.13.1. 

Windows 10, 64bit OS.

Note that last week, the default browser was changed again, but it was changed by Windows, and didn't take place following a Brave update. 

Vivaldi users have also been complaining about Windows 10 switching their default browser selection as of last week, so it appears that while the 0.13.0->0.13.1 update did cause a default browser change, that there are still enough instances of Windows 10 changing the default browser to warrant Vivaldi releasing articles about Windows being anti-competitive by changing the default browser (article was released last week about this).

One noticeable difference between when Windows 10 changes the browser setting, and when a Brave update causes the change (that I have directly observed):

When Windows 10 changes the default browser, the default browser goes from Brave to Edge.

When a Brave update changes the default browser, the default browser is a blank gray tile within the OS default browser settings.

**Comment by izzylaif** [comment]
OK, I'm sick and tired of this. For over 10 years now, I've been using portable version of Mozilla Firefox as my main browser ever since Windows XP, for privacy concerns. I have both Firefox Portable and its TEMP folders on an encrypted container (TrueCrypt/VeraCrypt, BitLocker), which I mount manually as a K: drive after each Windows logon. The perks of this is no one can access your browser (where passwords, browsing history and lots of other sensible stuff is stored nowadays), even if they gain access to my desktop PC or laptop, because you need a password to decrypt the drive. Even if the laptop is stolen, the only thing I lose is a bit of money, and not my passwords and privacy. I also do not use non-portable software at all, which keeps my Windows uncluttered, and when I need to reinstall Windows, I just backup the folder where all portable software is and the cryptocontainer to an external drive, format local drive, do a fresh install, and copy back the folders to get all the apps with all the settings. The only thing left is to set up default programs and file associations to make the pc open files with correct portable apps. This also serves another purpose: I use 3 PCs daily, and to sync all programs and settings between them, I just copy over the said folder and crypted drive container, and I'm good.

This long preface is to avoid the stupid argument "lol your portable apps are not designed to be used as desktop apps, do a proper install of the programs". I have good reasons to do it the way I do it.

The issues started with Win8, which showed empty icons (a blank paper sheet), if you put the shortcut into start menu, taskbar or desktop. Probably because of the drive not being mounted at logon, when these icons are populated. This also rarely, but happened in Win7. To get the icons back, I had to clear and rebuild thumbnail cache and restart explorer.exe. I finally fixed it in idiotic way, by putting the icons on the C: drive and linking them to the desktop shortcuts. Not pretty, but it works.

But ever since updating to Windows 10, I'm having an issue with Default Programs which is driving me nuts. 
![image](https://cloud.githubusercontent.com/assets/9394529/22779580/6e4acf2e-eecc-11e6-9d74-169086d2c3ec.png)

For some reason, Firefox Portable is gone from metro Default programs interface. It is present in the old school Default programs, however the HTTP and HTTPs default actions are unchecked.
![image](https://cloud.githubusercontent.com/assets/9394529/22779598/811a16fa-eecc-11e6-8017-b900665dc02f.png)

 Because of this, every time I click a link in a program, like email client or just About section of any other program, an Open with menu appears to select the browser. 
![image](https://cloud.githubusercontent.com/assets/9394529/22779621/95fc8364-eecc-11e6-95fe-f0ad26f6f086.png)

 If I recheck those two settings after I boot and mount the crypto container where Firefox is, everything opens fine. Until next reboot. How can I fix it? I tried putting shortcuts on c: drive and pointing default programs there, also I tried symlinks and other stuff to no avail. I don't like the idea of having the set default program batch run every time I mount the crypto drive, even though it's possible. This behaviour was not present up until Win10. How to prevent windows from unchecking that? Can I change ownership of that registry tree? Which tree?

Any help much appreciated.

PS: These are clean installs of Windows 10 Home, PRO and LTSB with all updates upto Jan 2017.

**Comment by lukemulks** [comment]
Hi @izzylaif,

No worries about any portability lol-zy responses to your question. :-)

I echo your frustration over the default behavior updating on it's own. It
sounds like from your set of requirements that you're experiencing this
more frequently than I personally have. That said, I can only imagine the
frustration, as it is extremely frustrating when I intermittently encounter
the issue myself.

I don't have a definitive answer for this one, but I may be able to help
point you in a direction.

What has happened in my case with Windows 10, and from what I know from
early adopting the OS, is that Windows is handling a lot more with this OS
than in past versions.

3rd party driver management, update methods, ads within the OS, etc. are
all different than earlier versions. I've upgraded over 5 machines to
Windows 10, and have experienced major driver issues on 2 of them,
completely bricked 1 of them and had the other 2 go fairly smoothly.

Long story short, earlier versions of Windows 10 would update the default
browser to either blank or Edge, but would flag the issue as a "detected
security problem" via push notification. This no longer happens in my case
(the notification).

What I suspect happens, is that Windows 10's security checkups phone home
on restart, and if a default browser is set that isn't on a whitelist
(guessing it's a primary set of common browsers) then Windows flags and
changes the default. The conditions you're operating within could be
causing the checkups to take place more frequently than typical users.

It may be worth experimenting with some of the Windows security callbacks
to see if disabling one of those processes resolves the issue. I am not
sure exactly which one, but the processes should have ID codes which should
be searchable.

I personally have reported the default browser change to Windows over 6
times, without a response. I know our devs have repeatedly put measures in
place to limit this as much as possible, but often the OS is performing the
switching. Vivaldi users have also been reporting similar behavior.

The next time that I experience this behavior, I will check the system logs
(Windows / Administrative Tools / Event Viewer:
http://www.howtogeek.com/school/using-windows-admin-tools-like-a-pro/lesson3/
) to try and see if I can spot any specific events that have taken place
that may be the culprit.

If you're able to determine which process it is the next time you encounter
it, please let me know which one you suspect it is and I'd be happy to help
dig in further.

p.s. bonus points if you give Brave a shot, if that works w/in your model.
;-)

On Feb 9, 2017 2:35 AM, "izzylaif" <notifications@github.com> wrote:

OK, I'm sick and tired of this. For over 10 years now, I've been using
portable version of Mozilla Firefox as my main browser ever since Windows
XP, for privacy concerns. I have both Firefox Portable and its TEMP folders
on an encrypted container (TrueCrypt/VeraCrypt, BitLocker), which I mount
manually as a K: drive after each Windows logon. The perks of this is no
one can access your browser (where passwords, browsing history and lots of
other sensible stuff is stored nowadays), even if they gain access to my
desktop PC or laptop, because you need a password to decrypt the drive.
Even if the laptop is stolen, the only thing I lose is a bit of money, and
not my passwords and privacy. I also do not use non-portable software at
all, which keeps my Windows uncluttered, and when I need to reinstall
Windows, I just backup the folder where all portable software is and the
cryptocontainer to an external drive, format local drive, do a fresh
install, and copy back the folders to get all the apps with all the
settings. The only thing left is to set up default programs and file
associations to make the pc open files with correct portable apps. This
also serves another purpose: I use 3 PCs daily, and to sync all programs
and settings between them, I just copy over the said folder and crypted
drive container, and I'm good.

This long preface is to avoid the stupid argument "lol your portable apps
are not designed to be used as desktop apps, do a proper install of the
programs". I have good reasons to do it the way I do it.

The issues started with Win8, which showed empty icons (a blank paper
sheet), if you put the shortcut into start menu, taskbar or desktop.
Probably because of the drive not being mounted at logon, when these icons
are populated. This also rarely, but happened in Win7. To get the icons
back, I had to clear and rebuild thumbnail cache and restart explorer.exe.
I finally fixed it in idiotic way, by putting the icons on the C: drive and
linking them to the desktop shortcuts. Not pretty, but it works.

But ever since updating to Windows 10, I'm having an issue with Default
Programs which is driving me nuts.
[image: image]
<https://cloud.githubusercontent.com/assets/9394529/22779580/6e4acf2e-eecc-11e6-9d74-169086d2c3ec.png>

For some reason, Firefox Portable is gone from metro Default programs
interface. It is present in the old school Default programs, however the
HTTP and HTTPs default actions are unchecked.
[image: image]
<https://cloud.githubusercontent.com/assets/9394529/22779598/811a16fa-eecc-11e6-8017-b900665dc02f.png>

Because of this, every time I click a link in a program, like email client
or just About section of any other program, an Open with menu appears to
select the browser.
[image: image]
<https://cloud.githubusercontent.com/assets/9394529/22779621/95fc8364-eecc-11e6-95fe-f0ad26f6f086.png>

If I recheck those two settings after I boot and mount the crypto container
where Firefox is, everything opens fine. Until next reboot. How can I fix
it? I tried putting shortcuts on c: drive and pointing default programs
there, also I tried symlinks and other stuff to no avail. I don't like the
idea of having the set default program batch run every time I mount the
crypto drive, even though it's possible. This behaviour was not present up
until Win10. How to prevent windows from unchecking that? Can I change
ownership of that registry tree? Which tree?

Any help much appreciated.

PS: These are clean installs of Windows 10 Home, PRO and LTSB with all
updates upto Jan 2017.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/brave/browser-laptop/issues/5246#issuecomment-278605168>,
or mute the thread

**Comment by bsclifton** [comment]
I've been looking into this and it's definitely an interesting issue.  I'd like to document one use-case completely (will revisit others later)

## Brave is default and Auto upgrade happens
1. Manually install an older version of Brave (0.13.4).
2. Use the default programs UI to set everything to use Brave as the default program.
  - hit Windows key, type `default programs`, and push enter
  - click `Set defaults by app`
![screen shot 2017-03-27 at 5 24 09 pm](https://cloud.githubusercontent.com/assets/4733304/24383581/a729d64a-1312-11e7-8415-cd10b82eabc1.png)
  - Click Brave on left and pick "Choose defaults for this program"
  - use the UI to pick all available options
    ![screen shot 2017-03-27 at 5 22 03 pm](https://cloud.githubusercontent.com/assets/4733304/24383493/01f7bd36-1312-11e7-86fc-f179551523bf.png)
4. After setting the defaults, close the UI completely
5. Launch Brave and use `Help` > `Check for Updates`
6. An update will appear; accept it / install / relaunch
7. Quit Brave

At this point, the default programs still seem to be set. This can be verified in regedit by checking the following keys:
```
HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice\Progid
HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice\Progid
HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\ftp\UserChoice\Progid
```

In each of these cases, you'll see the value set to `BraveHTML`.  If you open the default programs UI again, this will reset ONLY the `HTTP` and `HTTPS` protocol handlers, changing them to `Microsoft Edge`.
![screen shot 2017-03-27 at 5 19 24 pm](https://cloud.githubusercontent.com/assets/4733304/24383764/e400d4be-1313-11e7-90da-530cc1ad4023.png)

**Comment by bsclifton** [comment]
I've done registry dumps of the following registry branches BEFORE and AFTER upgrading:
- `HKEY_CURRENT_USER > Software > Clients > StartMenuInternet > Brave`
- `HKEY_CURRENT_USER > Software > Microsoft > Windows > Shell > Associations > UrlAssociations`

In both cases, the keys are identical before and after the upgrade. However, if I open the default programs UI (seen above) OR if I just wait long enough, the keys for ONLY HTTP and HTTPS get reset back to Microsoft Edge

There are three use-cases which can cause the default browser to be reset:
- Brave is default and is Auto upgraded (captured in post directly above this)
- Brave is default and Windows is updated (reported by @lukemulks in one of the posts above)
- Brave is default and is re-installed

I'll continue digging in... it seems that something suspicious is going on here.

**Comment by bsclifton** [comment]
Based on some posts I've read, I tried putting this registry hack in place:
```registry
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\AppXq0fevzme2pys62n3e0fbqa7peapykr8v]
"NoOpenWith"=""
"NoStaticDefaultVerb"=""

[HKEY_CURRENT_USER\SOFTWARE\Classes\AppX90nv6nhay5n6a98fnetv7tpk64pp35es]
"NoOpenWith"=""
"NoStaticDefaultVerb"=""
```

This does prevent Microsoft Edge from being assigned as the default program for HTTP and HTTPS.  **However**, it wipes that entry completely... leaving HTTP and HTTPS unhandled.
![screen shot 2017-03-27 at 11 18 20 pm](https://cloud.githubusercontent.com/assets/4733304/24391397/bfe239ee-1343-11e7-806b-ff0b6378d7bc.png)


Link to posts I used as reference when creating the above:
- [Fix for “An App Default was Reset” Windows 10 Resetting File Associations (Registry Fixes)](http://www.winhelponline.com/blog/windows-10-resetting-file-associations/)
- [Prevent Windows 10 from resetting your default apps](http://winaero.com/blog/prevent-windows-10-from-resetting-your-default-apps/)

**Comment by bsclifton** [comment]
After the upgrade is complete, `RuntimeBroker.exe` will come around and wipe out `BraveHTML` values for HTTP / HTTPS and replace with the default (Microsoft Edge).  Here's a screen cap of it happening using ProcessMonitor.exe
![screen shot 2017-03-27 at 11 43 32 pm](https://cloud.githubusercontent.com/assets/4733304/24392099/4b855690-1347-11e7-8589-3d31ad710076.png)

During the upgrade itself, there are some registry operations happening (which may be triggering RuntimeBroker.exe to run- it seems this is a delicate process).
![screen shot 2017-03-27 at 11 47 42 pm](https://cloud.githubusercontent.com/assets/4733304/24392300/17497126-1348-11e7-8d1c-f5cc0436b873.png)

**Comment by izzylaif** [comment]
>  However, it wipes that entry completely... leaving HTTP and HTTPS unhandled.

on a -LGBT- LTSB version on Windows, this is also left empty as there is no Edge packaged.

**Comment by bsclifton** [comment]
I performed a manual upgrade and believe I found the problem. I replaced the binaries for Brave and it'll continue to work fine.  The RuntimeBroker.exe process wasn't triggered until this value is updated: `HKEY_CURRENT_USER\SOFTWARE\Classes\BraveHTML\shell\open\command`

During my demo, I manually changed the value from:
`"C:\Users\brian\AppData\Local\brave\app-0.13.4\Brave.exe" -- "%1"`
to
`"C:\Users\brian\AppData\Local\brave\app-0.13.5\Brave.exe" -- "%1"`

This triggered RuntimeBroker.exe which reset the value.

Windows must be watching the class name `BraveHTML` (since it was registered as a protocol handler for HTTP / HTTPS) and then resetting if any values under here change.

**Comment by izzylaif** [comment]
Try putting brave.exe on a drive not available at boot, i.e a thumbrive/networkdrive/unmounted bicrypt volume. it will reset.

**Comment by lukemulks** [comment]
clifton = hero. ❤️

**Comment by luixxiul** [comment]
Comment left: https://github.com/brave/browser-laptop/pull/8060#issuecomment-292782940

**Comment by izzylaif** [comment]
Windows 10 build 1703 (creator's) doesn't have this issue anymore. I've been using 1703 build for over a week, and the HTTP/HTTPS strings do not get reset. 1703 fixed this for me.

**Comment by Jacalz** [comment]
But it was fixed in 0.15.0

**Comment by izzylaif** [comment]
I don't give a shit about brave browser, sorry. my problem was with firefox portable, see my post above.

**Comment by bsclifton** [comment]
@izzylaif are you saying the Creators update doesn't reset default http/https for browsers? (for any app, like for example, Firefox portable?)

This is great news actually- we would like to have a portable version too.  Sorry to hear that you don't enjoy the browser

**Comment by izzylaif** [comment]
I don't see the need for any other browser, since we have firefox for like 15 years already
Yes, seems that Creator's update 1703 changed the behavior of RuntimeBroker and it doesn't wipe out/default to Edge the HTTP and HTTPS default program line anymore. At least not within the first 5 minutes after boot, while I moun the container as a drive with Firefox anyway.

**Comment by bsclifton** [comment]
@izzylaif great- thanks for the update 😄
