### ISSUE TITLE
Changing bookmark folder in the add bookmark modal changes it to bookmark added

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5314]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Changing bookmark folder in the add bookmark modal changes it to bookmark added

**Expected behavior:**
Should just change the folder location and not change modal to bookmark added

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
Verified from 0.12.6 onwards

- Steps to reproduce:
    1. Open about:bookmarks and create a new bookmark folder
    2. Click on the start+ icon to add a new bookmark
    3. Change the bookmark folder from toolbar to the folder created in step 1/ or vice versa
    4. Modal changes to bookmark added instead of retaining the add new bookmark modal

- Screenshot if needed:
![bkmrkadded](https://cloud.githubusercontent.com/assets/17010094/19892770/7ecac778-a03e-11e6-8bb0-f27ca6c84d8b.gif)

- Any related issues:

 cc: @bsclifton 
 Setting milestone to 0.12.9

**Comment by bsclifton** [comment]
Removed milestone-  Let's discuss if you feel strongly / want to re-add

**Comment by gyandeeps** [comment]
I started working on this and found we use showLocation state value to determine the title of the modal. That is not correct because the title and location show are not directly linked to each other.
Example: you can have a location filled out bu that doesn't mean bookmark has been added.

**Plan:** Come up with a another state attribute called `phase` which will have values from `new`, `edit`, `done` so that we can accurately determine the title without interfering with location.

**Issue:** Also fix when the location field is shown because if you look at the visual inside issue, even if you dont have the location set but changing the folder will hide the location option.

**Plan:** To always show when you are editing bookmarks from bookmark manager. Will not show location if you are interacting with it by clicking the start inside the url bar because at that time you already have the location in context.

**Comment by bsclifton** [comment]
@gyandeeps that would definitely work :smile: If you are interested in grabbing this, you could take a look at the action and identify the callers that would have to change. If you need any help or have any questions, let me know :smile:

**Comment by kumarrishav** [comment]
@srirambv It's happening on MacOS Brave	0.15.2 rev	af7ef42 too. Also 'location' input box getting disappeared while changing the folder like as @gyandeeps said.
Also, can we add platform label too to the issue? It's easy to filter by platform label and easy to pick the issue as everyone won't have all platform laptop. 
Any thoughts on this @bsclifton

**Comment by NejcZdovc** [comment]
This should be fixed with #9710
