### ISSUE TITLE
URL bar duplicates the title bar

### ISSUE THREAD

**Issue by bkjohnson** [brave/browser-laptop#5416]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** When hidden (which is anytime except on mouseover or active), the URL bar displays the page title which is already displayed directly above it.

**Expected behavior:** A clean interface that displays information appropriately.

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux Mint

- Brave Version: 0.12.8

- Steps to reproduce:

    1. Open any tab in Brave.
    2. Look at the title bar and see redundant information

I understand that there is an option to always show the URL bar, but I don't see why hiding the URL bar is considered a feature.  At the very least the URL bar should be **enabled** by default in accordance with [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) because users are used to seeing the URL.

![screenshot from 2016-11-04 22-05-37](https://cloud.githubusercontent.com/assets/2008881/20027248/d02ad5d6-a2dc-11e6-8aac-e3483e5dc8bf.png)

- Any related issues:
#3712 was about making the URL bar active for new tabs, not by default.

**Comment by bsclifton** [comment]
With Windows and Mac, this is a useful feature since the titlebar is not there:
![screen shot 2016-11-05 at 12 40 57 am](https://cloud.githubusercontent.com/assets/4733304/20028492/911157ee-a2f0-11e6-9d33-b6760ed154f6.png)

![screen shot 2016-11-05 at 12 35 41 am](https://cloud.githubusercontent.com/assets/4733304/20028487/65e8ddbc-a2f0-11e6-96b0-24429fb09f50.png)

I know many Linux users would like this feature too, which is tracked with https://github.com/brave/browser-laptop/issues/3126.  If the titlebar was hidden like it is on Windows/Mac, would that solve the issue for you?

**Comment by bkjohnson** [comment]
Oops, I didn't even think about this being an OS issue.  Yes, if the titlebar behaved like it does on Windows/Mac then that would solve the issue, as long as there was still an option to enable the URL bar.

**Comment by Sh1d0w** [comment]
Unfortunately unless there is a theming engine implemented in the browser, allowing the user to select a custom theme for the layout/window this won't be effective on Linux. Because there are too many distors with too many skins/themes and currently I don't think it is possible to fetch and mimic the theme layout in the browser itself (like it is hardcoded for windows), unless this is implemented on electon side.

Until then unfortunately the only solution I found for myself is to maintain a custom fork of the browser, with tweaked window styles to match my Fedora theme and to hide the title bar.

**Comment by luixxiul** [comment]
There are relevant issues: #1698 #1903. Both on Ubuntu Unity.

**Comment by bsclifton** [comment]
@Sh1d0w good call- unless we wanted to override the look and feel of the window manager, there is no solution currently.

@bradleyrichter should we consider defaulting the magic titlebar to OFF on Linux (since the titlebar always shows?)

**Comment by bradleyrichter** [comment]
Yes. Pointless redundancy is bad. 

Please set title mode off by default on Linux. (all versions)

![image](https://cloud.githubusercontent.com/assets/13509546/20040039/e6978aac-a404-11e6-8d53-14738eb433cd.png)
