### ISSUE TITLE
extend blue outline in URL bar to include bookmark button

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5439]
old: 

![image](https://cloud.githubusercontent.com/assets/13509546/20040325/e1827950-a409-11e6-91c4-69e7f8937bae.png)

new:
![image](https://cloud.githubusercontent.com/assets/13509546/20040329/eea76672-a409-11e6-95a0-e4f72913fffe.png)

**Comment by pmkary** [comment]
@bradleyrichter  thanks a lot! This is way much better.

**Comment by bbondy** [comment]
I had to revert this because of a couple of big UI bugs that were introduced.

Reverted here:
https://github.com/brave/browser-laptop/commit/9aedf588300741d65bb06de4f7fb8d5c7842126a

Screenshot of UI bugs:

<img width="362" alt="screenshot 2016-11-23 18 17 01" src="https://cloud.githubusercontent.com/assets/831718/20581910/2067ae26-b1aa-11e6-8407-8d623dbf3cdb.png">

<img width="324" alt="screenshot 2016-11-23 18 24 39" src="https://cloud.githubusercontent.com/assets/831718/20581912/2421f0a8-b1aa-11e6-8eaa-2c616f6bc666.png">

**Comment by bradleyrichter** [comment]
@jkup I was trying to fix a few things in it but ran into the search-favicon problem and thought it was too risky for the next freeze..

**Comment by jkup** [comment]
@bradleyrichter @bbondy what is the bug in the first image? what is the search-favicon problem?

**Comment by luixxiul** [comment]
See #5816

**Comment by bsclifton** [comment]
Bumped to 0.13.1

**Comment by jkup** [comment]
Closed my PR against this and going to wait until @bsclifton merges in the new PNG sprite version of the icons!

**Comment by bradleyrichter** [comment]
@cezaraugusto @jamesmudgett this has been sitting but what do you 2 think? Still looks better than current? (see above)

**Comment by cezaraugusto** [comment]
changes looks better than current imo

**Comment by luixxiul** [comment]
the current has changed thanks to @NejcZdovc fyi
