### ISSUE TITLE
coinbase widget doesn't allow changing credit card

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#5552]
recently my old credit card was canceled due to fraud. in the process of changing to a new card with coinbase, i noticed some bugs:

1. if you try to buy BTC through the coinbase widget, it will display as successful even though the card isn't valid and the transaction never goes through.
2. there is no way to change your credit card in the widget
3. if you go to coinbase.com settings to add a new payment method, it won't be usable by the coinbase widget until you get someone at coinbase to manually delete your old card.

as such, the only practical way to change credit cards is to make a new account in the coinbase widget.

cc @mrose17

**Comment by mrose17** [comment]
@diracdeltas - was there any resolution on this? is there anything at brave software that we can do to mitigate this?

**Comment by diracdeltas** [comment]
@mrose17 other than warning users that they need to make a new account in order to change  cc cards, no

**Comment by mrose17** [comment]
@bradleyrichter - i'm punting this to you... where should we put this information? in an FAQ?

**Comment by bradleyrichter** [comment]
Yes. Catherine will add it to the BP FAQ.

**Comment by mrose17** [comment]
thanks. once that happens, could you or @CCBrave close this issue?

**Comment by mrose17** [comment]
now in the [FAQ](https://brave.com/Payments_FAQ.html): 4. How do I change my credit card information in the Coinbase widget?
If you wish to use a different credit card with the Coinbase widget, you will need to create a new account in the Coinbase widget. It is currently not possible to update old credit card information due to some limitations in the Coinbase widget.
