### ISSUE TITLE
support dragging a tab to another tab set

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#557]
To facilitate moving a tab between tab sets, let me drag a tab over to the tabstrip's scroll arrow have that advance through tab sets.

Additionally or alternatively, you could support dragging a tab onto a set in the tab set indicator/switcher thing.  I suspect this would interfere with easy reordering within a set.

**Comment by bbondy** [comment]
This is in the design spec, we just haven't implemented it yet. Thanks for posting the smaller more consumable mini task.

**Comment by bradleyrichter** [comment]
looking forward to this as well as a list of tab-set related features in the future.
- reordering sets
- bookmarking sets
- moving sets to a new window
- closing sets via context menu
- set previews

**Comment by bbondy** [comment]
Dropping tabs onto sets is implemented, leaving this open for the other subtasks.

**Comment by TognaBologna** [comment]
If "Dropping tabs onto sets" means dragging a tab from one Brave window to another Brave window, that is not working on OS X 10.11.5 (15F34) with Brave 0.10.4. When I drag a tab from one Brave window to another, it either replaces the tab I am trying to place it next to or it will duplicate the tab onto the new window, while still keeping it in the old window.

**Comment by bradleyrichter** [comment]
@TognaBologna You are right that moving tabs from one window to another is not fully implemented.

Dragging a tab to a tab set indicator does work but it needs refinement, especially in the hover states.

Dragging to the tab set navigation arrow does not work yet.

**Comment by sirkitree** [comment]
This is my only pet peeve with Brave so far. I love everything else. With multiple monitors it's pretty important to me.

**Comment by NumDeP** [comment]
Hi @petemill , in relation to @sirkitree 's pet peeve, as well as for other users that utilize multiple monitors using Brave as it matures, what do you think of having the tab-set chain follow the mouse area instead of moving a tab towards one of the tab-set? 
I realize this may cause frustration for many users as it may resemble ping-pong every time a tab is dragged off for whatever reason but perhaps motioning a tab in a particular way brings the tab-set chain closer to the cursor, for example, a rainbow motion above the tab area which has to at least touch the top part of the browser frame.

**Comment by petemill** [comment]
Not sure I follow what you mean by `tab-set chain follow the mouse area` @NumDeP. Tab dragging has been fully re-implemented with #11720 (which hasn't yet been merged to a release, but is targeted, for the time being, at 0.23) and the methodology in this for moving between pages is to drag to the prev / next page arrow indicators, with a pause built-in to ensure intention.

**Comment by NumDeP** [comment]
I mistakenly read the title to 'support dragging a tab INTO another tab set', however I think my proposal still has some merit @petemill . Say if I have 20 tabs set for each tab-set and I have 80 tabs open, assuming I'm in the first of the the four tab-sets that would be available and I wanted to drag a tab into the fourth tab-set, it would be killer dragging it past 69 tabs like the capture implementation shows in #11720 wouldn't it? 

I probably shouldn't have called it chain but sticking to calling multiple tab-sets a chain, don't you think it would be brilliant if multiple monitor users and even users in general that have many tabs and tab-sets open to drag a tab directly into a tab-set?

**Comment by petemill** [comment]
@NumDeP you can already drag a tab directly to any page by dragging to any tab page indicator and letting go. In #11720, you don't have to drag it physically past all the tabs, you just hold on at the next/prev indicator and it will keep progressing the tab to each tab page until you let go. Not perfect, no.

**Comment by NumDeP** [comment]
I'm sorry I was viewing #11720 and I assumed from the gif 'Tab sorting between tab-pages' that, that was the only option of dragging a tab into another tab-set.

**Comment by petemill** [comment]
@NumDeP sure, but I mean right now in the current release you can drag to any tab page indicator

**Comment by bradleyrichter** [comment]
@NumDeP I'm not quite able to visualize what you have in your vision but I do think we could utilize some of the currently implemented features to enhance dragging tabs into specific locations within a tab set. 

The tab set indicator currently works as a jump button and a hover preview button. If you hover on it, it shows you the tabs that lie within. 

We could potentially extend this so that while dragging a tab, if you pause over a tab page indicator, it could temporarily switch the set and allow you to then drop the tab into position in that set. The tab would then become selected and also the set.

If you aborted, the set would return to previously displayed set.

Does this make sense?

(cc @petemill )

**Comment by NumDeP** [comment]
Exactly what I meant @bradleyrichter but in addition to this wouldn't it be a neat feature to have the page indicators move to the sides of the cursor i.e left and and right, when the intention is made to move a specific tab to a different page indicator. 
So imagine there are 20 tabs open and a users has '10' selected for 'Number of tabs per tab set:', there would practically be 2 tab page indicators with 1 highlighted orange just below the url bar in the center, correct? If I'm in the first highlighted tab of the two tab page indicators and I wanted to move tab number 1 and tab number 10 into the second tab page indicator, rather than dragging those tabs towards the un-highlighted tab page indicator, it would be quite different and set it apart form the other browsers if the un-highlighted tab page indicator were to move left and right as soon as the intention is made, don't you think? 
As mentioned above in regards to the intention and that it may cause frustration for some users bringing resemblance to ping-pong every time a tab is dragged off for whatever reason but perhaps motioning a tab in a particular way could indicated the function for bringing one of tab page indicators or all the un-highlighted tab page indicators closer to the side of the cursor, for example, a rainbow motion exactly where the tab lies which has to at least touch the top part of the browser frame so the tab page indicators don't move will-nilly.

I seriously hope I made myself clear this time round, otherwise I'm going to start to think there's something wrong with me. Maybe it's because we're not utilizing large screens to ascertain the benefit of this or perhaps you are and I'm terrible at descriptions but I think it would be rather unique and probably later construed as essential feature for those that have close to a 100 and over a 100 tabs open.

**Comment by bsclifton** [comment]
Closing as `wontfix`- we won't be able to address before moving to [Brave Core](https://github.com/brave/brave-browser), which doesn't have tab sets (yet)
