### ISSUE TITLE
How to use Brave for online shopping

### ISSUE THREAD

**Issue by ktd99** [brave/browser-laptop#5572]
**Did you search for similar issues before submitting this one?**  yes.

**Describe the issue you encountered:**  When I shop online and the web site has a "cart" or a "bag", I cannot add items to the cart/bag.  It's as if there is a need to allow a script or a cookie or to disable some sort of blocker.  I've tried to change the Brave setting for the site, to no avail.

**Expected behavior:**  Allow normal interaction with the site...be able to update cart/bag.

- Platform (Win7, 8, 10? macOS? Linux distro?):  Win 7.

- Brave Version:  the latest release as of 11/11/2016.

- Steps to reproduce:  It's behaving pretty consistently.
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by privatzee** [comment]
Can you say which site? There are some that won't work, even if you click the lion in the upper right and turn off all shields. In that case, you'd next try to _Allow all cookies_ in about:preferences#shields as a temporary workaround.

**Comment by ktd99** [comment]
Landsend.com  And I did Allow all cookies, as well as Ads and tracking.  Made myself as open as I knew to do...!

**Comment by privatzee** [comment]
Good morning, ktd. A quick workaround is to disable all shields, like so:

![image](https://cloud.githubusercontent.com/assets/22591438/20246145/bd1941b4-a97e-11e6-8eee-7db73e0e3f62.png)

---

The following also works, because for this site you also need to disable HTTPS Everywhere and protections from fingerprinting:

![image](https://cloud.githubusercontent.com/assets/22591438/20246175/3aa9aec0-a97f-11e6-9116-fd82943614bd.png)

---

It turns out that this site has some particular problem with httpse . If you go there with Chrome and httpse installed, the site also fails. 

Notice that when httpse is enabled, you can start out as expected at https://www.landsend.com, but when you click any link, you wrongly end up back on plain http.

**Comment by luixxiul** [comment]
> It turns out that this site has some particular problem with httpse .

The bug should be submitted on https://github.com/EFForg/https-everywhere and fixed by them.

**Comment by ktd99** [comment]
Privatzee, wow...I had already disabled the ads and 3rd party cookies.  Also disabling HTTPS E made the site work....thank you!

Luixxiul, can you please elaborate?  What sort of bug..??

**Comment by luixxiul** [comment]
Brave browser integrates HTTPS Everywhere and uses the rulesets to switch http to https (or https to http), which are maintained manually on https://github.com/EFForg/https-everywhere. Because server configurations can be changed by server owners any time, there is a chance that the ruleset would lead to wrong domains. I think this is one of the cases.
