### ISSUE TITLE
Issues with brave rpm installation on openSUSE machine

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#5580]
From support: https://linkbubble.zendesk.com/agent/tickets/5606

> I tried to install the latest brace.rpm for openSuse x86_64 . 
Usiually on this platform the maintenance is done via yast and/or zypper . 
> 1. Using zypper I got the following messages 
sudo zypper in -D ./brave.rpm 
No provider of '_tmpRPMcache_:brave=0:0.12.1-1' found.
>
> Nothing to do.
>
> 2. Installing via rpm -i brave.rpm is ok 
BUT 
When I start/using yast [ the standard/recommended for opemSUSE ] I got a message that 
Brave.rpm is not installable .

**Comment by bbondy** [comment]
+1 from support: https://github.com/brave/browser-laptop/issues/5580

**Comment by posix4e** [comment]
@cezaraugusto Howdy! if you use zypper with -D nothing will happen. It means dry run. You need to exclude the -D. You will also need to install gconf2-devel and libgnome-keyring-devel

**Comment by NumDeP** [comment]
+ 1

**Comment by posix4e** [comment]
@NumDeP keep in mind we have our own mechanism for shipping browser updates. I am happy to help

**Comment by NumDeP** [comment]
Thanks for your help so far :) Just out of curiosity what's your preferred way of installing Brave in Suse because I imagine you're not able to retrieve the latest stable updates if you did it via Yarn or as mentioned above sudo zypper in ./brave.rpm for it to essentially show up in the Update Manager.

**Comment by posix4e** [comment]
@NumDeP Just installed using the instructions for opensuse. 

From: https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md
```
OpenSUSE AMD64:
To install Brave using zypper:

sudo rpmkeys --import https://s3-us-west-2.amazonaws.com/brave-rpm-release/keys.asc
sudo zypper install lsb
sudo zypper addrepo --type yast2 https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/ brave-rpm-release
sudo zypper ref
sudo zypper install brave
```
I also ran
sudo zypper install libxss1 libatk-bridge-2_0-0 libgtk-3-0

**Comment by NumDeP** [comment]
Thanks for taking time out of your most likely busy day. 
It didn't work for me last time (last year) for some reason and I couldn't be bothered to debug. 
One final thing, how come unlike your above suggestion to install gconf2-devel and libgnome-keyring-devel you didn't mention it in the last comment and is there another reason this issue is left open?

**Comment by posix4e** [comment]
@NumDeP it's left open due to my incompetence. Sorry about that. I am actually working with dev to upgrade our packages to the next level of awesome

**Comment by NumDeP** [comment]
HI @posix4e did you receive the latest update as soon as it was pushed because I didn't?

So I uninstalled Brave (sudo zypper remove brave) and it seemed to have removed it from the PC only when I tried to re-install for the latest version the message below appeared and I ended up having to install the older version strangely with the same preferences and other data still intact.

errors:

~> sudo zypper addrepo --type yast2 https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/ brave-rpm-release
Warning: Legacy commandline option --type detected. This option is ignored.
Adding repository 'brave-rpm-release' ...........................................[error]
Repository named 'brave-rpm-release' already exists. Please use another alias.


:~> sudo zypper update brave
[sudo] password for root: 
Loading repository data...
Reading installed packages...
No update candidate for 'brave-0.22.810-1.x86_64'. The highest available version is already installed.
Resolving package dependencies...

Nothing to do.

**Comment by NumDeP** [comment]
Update: I ran update last time when the newer version was released but it didn't work, if I remember clearly it was related with amazonaws. I tried 'sudo zypper update brave' again and the latest version showed with the GConf2 problem as described in #12609 as well. I naturally forced 2 and it downloaded.
