### ISSUE TITLE
Remove Open in new private tab from context menu while in a private browsing tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5610]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While in Private tabs right click context menu shows Open in a New Tab and Open in a Private tab. Open a in a new tab by default opens in a new private tab. 

**Expected behavior:**
Should only have Open in a New Tab as it opens a private tab by default from a Private tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.9 RC1

- Steps to reproduce:
    1. Open any link in Private tab
    2. Right click on any link to show context menu
    3. Shows open new tab and open in a private tab

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20274885/36555012-aa8e-11e6-9248-4460c835b4da.png)

- Any related issues:

**Comment by davewallace** [comment]
@srirambv I started looking into this, but then my common sense bells started tingling, is this not by design? I understand your comment about opening a new tab in private, from private, by default, however for better usability I'd say that having both options present would clarify that both options are still available. Without the private option, the assumption is that clicking the link rather than the context menu alt-link option will open a new tab - but will this always be the case?

For example, what about the User who is currently in private mode, who wishes to open a given link in a new tab in non-private mode? This would then rely on the link itself having "_blank" or equivalent JS function so the browser behave as it does by default on links of this type.

**Comment by srirambv** [comment]
@davewallace  As far as I can see the only option to open a link in a non private tab is by selecting a new sessions tab. And since open in a new tab defaults to a new private tab(by design), having an explicit option to open in a private tab doesn't make sense. 

@bbondy your thoughts on this

**Comment by bbondy** [comment]
> For example, what about the User who is currently in private mode, who wishes to open a given link in a new tab in non-private mode?

I don't think we need to handle that use case but will CC @bradleyrichter for his thoughts.
I think the chance of misuse and private data leaking is greater than the need for that use case.
