### ISSUE TITLE
about:preferences icon is 2px too high (on mac)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5694]
![image](https://cloud.githubusercontent.com/assets/13509546/20366926/29b20b8c-ac02-11e6-8d40-e2b0a866f445.png)

**Comment by bbondy** [comment]
@bradleyrichter we're trying to avoid pixel tweaking icons so we can make the UI more consistent. Could we maybe replace both of these icons with SVGs which are better aligned?

**Comment by bsclifton** [comment]
@bradleyrichter can we have sprites for the URL bar icons? I think this would be better because we'd have more control (PNG is fine- can be a sprite sheet with http/https/etc).  Moving to backlog for now, but please re-assign it a milestone once there are assets :smile:   We can solve this by doing a proper image button control 

cc: @jkup

**Comment by bsclifton** [comment]
This issue is now a dupe :smile: Closing in favor of https://github.com/brave/browser-laptop/issues/5891
