### ISSUE TITLE
Social Buttons on Vice.com aren't working

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5740]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I am unable to use the social buttons on motherboard.vice.com

**Expected behavior:**
Social buttons work.

**Platform:** Windows 10

**Brave Version:** 0.12.9

**Steps to reproduce:**
1. Navigate to https://motherboard.vice.com/read/irs-demands-identities-of-all-coinbase-traders-over-two-year-period#
2. Click Twitter logo to left of article (responsive layout, browser window should be full-screen)
3. Note that nothing occurs (no errors are raised either)

**Observations:**
The [script responsible](https://motherboard.vice.com/assets/js/motherboard/shared/shared_plugins.js?v20161020110750) for the behavior is _on the same domain_. This page is using Backbone, which uses event-delegation to bind handlers for these buttons. When I have "Block Ads" selected, the handlers aren't bound. Permitting _Ads and Tracking_ resolves the issue.

**Comment by jonathansampson** [comment]
Due to Brave's _script-blocking_ functionality, the page has more than one Reference Errors. For instance, Brave blocks a third-party script from Google, which is supposed to stand-up a `window.googletag` object, having a `cmd` method. We can provide our own:

```js
window.googletag = { cmd: {} }
```

You'll find that `window.googletag.cmd` is expected to have a `shift` method too, but that isn't crucial to the sharing functionality.

Next is a Reference Error for `nol_t`. Here is the code from vice.com:

```js
var trac = nol_t(pvar);
trac.record().post();
```

We can see that `nol_t` is expected to return an object, and that this object is expected to have a `record` method that returns another object. This last object is expected to have a `post` method.

Here is our stub:

```js
var nol_t = function () {
  return {
    record: function () {
      return {
        post: function () {}
      }
    }
  }
}
```

I added the above object stubs via an _Auto Responder_ in Fiddler. I was able to confirm that this resolves the issue, restoring sharability to the account.

**Comment by lukemulks** [comment]
I've revisited this issue with v0.14.0 released, and can confirm that this issue is no longer observed in Brave. 

I've also run a comparison check in Chrome, just to make sure, and we're matching Chrome in social sharing functionality. 

Screencap from Brave after testing the social buttons: 
![brave-social-buttons-03312017-vice](https://cloud.githubusercontent.com/assets/8979240/24572071/93765022-162a-11e7-8c84-2f5fc9c3bbf1.PNG)

I'm going to close the issue at this point, but if the behavior is observed again for this domain we can open an issue and reference this one.
