### ISSUE TITLE
Prevent overflow for stats on about:newtab

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5747]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Stats being shown to the user show the raw numbers.  When high enough, they will run out of space and will have formatting issues.

Time saved already does a better job at abbreviating itself, since it goes from seconds => minutes => hours.

**Expected behavior:**
We should consider abbreviating the stats (ex: 36792 => 36k) or allowing the stats divs to resize properly.  Ideally, this should be something we can write an automated test for (which checks the size of a given div)

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version:
0.12.9+

- Steps to reproduce:
    1. Have a large number for any of the stats shown. [Edit the code](https://github.com/brave/browser-laptop/blob/master/js/components/frame.js#L130) to return a much larger number than you actually have.
    2. Launch Brave and open a new tab
    3. See the overflow

- Screenshot if needed:
![screen shot 2016-11-20 at 6 45 34 am](https://cloud.githubusercontent.com/assets/4733304/20463275/fde8e230-aeec-11e6-9b8e-6432efcafdfa.png)

- Any related issues:

**Comment by luixxiul** [comment]
I'd place them with display: flex, flex-flow: row wrap, justify-content:flex-start, setting max-width to the container. I think it is also l10n-friendly because the labels under the counters can be longer.

<img width="569" alt="screenshot 2016-11-20 23 02 54" src="https://cloud.githubusercontent.com/assets/3362943/20463408/7fac43ba-af75-11e6-91c3-3a39645e53a1.png">

**Comment by bsclifton** [comment]
closing as a dupe of https://github.com/brave/browser-laptop/issues/5889
