### ISSUE TITLE
wusoup.com main site functionality broken

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#5751]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Attempting to login to the site, or use the site in anyway beyond initial registration results in the site issuing the message 'Loading failed, sorry! Try reload this page?'.

Based on console errors, and a brief look at the minified JS on the site, the issue appears to be related to the 'Sente' real time communication library (https://github.com/ptaoussanis/sente). Note the CSRF token console warning shown in the screenshot.

This issue occurs regardless of the Brave shield status.

The website works correctly in Google Chrome.

**Expected behavior:** Site functions correctly, as in Google Chrome.

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux

- Brave Version: 0.12.9

- Steps to reproduce:
    1. Register on wusoup.com, or attempt to login if you already have an account
    2. Note the error message presented by the website and the CSRF token related warning in the developer tools console.

- Screenshot if needed: Dev. tools screenshot showing CSRF token warning - https://imgur.com/a/qeTb1

**Comment by privatzee** [comment]
**Suspected cause:**  Brave is not sending cookie with _WebSocket Secure_ (wss) request.

Auth is missing:

![image](https://cloud.githubusercontent.com/assets/22591438/20493758/19f002b4-afe8-11e6-8bea-5136f4f400e9.png)
---

Brave is not returning the _percival_ cookie with the wss request. (The string 'enss' is associated with Sente, and both Sente and wusoup sites share the same TLS cert.)

Maybe Sente needs the value of the percival cookie in order to accomplish the handshake.

![image](https://cloud.githubusercontent.com/assets/22591438/20498492/6557186a-affb-11e6-8126-60fc518fb86a.png)

Note: no request cookie header from Brave, but Chrome does send it:

![image](https://cloud.githubusercontent.com/assets/22591438/20498605/ce6146e6-affb-11e6-8768-f689e663f7d5.png)

---
---
P.S> Maybe this is also related to the wss issue with Asana.com.

**Comment by DivineOmega** [comment]
@privatzee Thanks for looking into this in even more detail. That's awesome.

I've just testing this again with the newly released Brave 0.12.10 and the issue still occurs.

**Comment by privatzee** [comment]
Thanks, @DivineOmega

But after the update yesterday, passwordManager.js is now putting my password as my email address for login there, so I can't get in anymore. You ever had any problems like that?

**Comment by DivineOmega** [comment]
@privatzee I'm not having the password autofill related issue. I'm currently using LastPass in case that is related.

**Comment by DivineOmega** [comment]
This seems to be fixed in Brave v0.13.1. :smile:

**Comment by luixxiul** [comment]
Thanks for reporting. Closing this.
