### ISSUE TITLE
Updated to 0.13.0 and payment doesn't process

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#5974]
Hi,

I updated to Brave 0.13.0 some hours before  Brave process the payment.
Now look what happens: (your next payment contribuition is 20 hours ago)

![captura de tela de 2016-12-01 19-11-34](https://cloud.githubusercontent.com/assets/1178856/20812851/4fff8d92-b7fa-11e6-9ec1-1f9dc818502a.png)

![captura de tela de 2016-12-01 19-11-42](https://cloud.githubusercontent.com/assets/1178856/20812857/55f88b18-b7fa-11e6-9210-69d0e43dc5f0.png)

**Comment by bitcoinuser** [comment]
I don't know is the payment was processed. And the PDF file was not generated too.

**Comment by willy-b** [comment]
Uh oh, I see spaces in the PDF filenames in your screenshot too. Looking.

**Comment by willy-b** [comment]
OK, I can reproduce this on Linux with the packaged brave_0.13.0_amd64.deb , but could not reproduce from latest master in development mode.

**Comment by bitcoinuser** [comment]
What problem exatly did you reproduce?

**Comment by willy-b** [comment]
Not sure about payment failing to go through, but the Payment Receipt PDF generation error, I can reproduce, and in my case comes from there being spaces in the PDF filename as in your screenshot (see below).

-- prepackaged build 0.13.0, spaces in filenames:
![brave_prepackaged_build_pdf_filenames](https://cloud.githubusercontent.com/assets/6969859/20815701/ce1b620e-b7d3-11e6-86e4-9592a225bdd6.png)

-- vs master, no spaces in filenames:
![brave_master_pdf_filenames](https://cloud.githubusercontent.com/assets/6969859/20815720/e08c19d8-b7d3-11e6-8586-c39e69096b13.png)

The code around the filename generation should not be locale sensitive, but it happens here because of different behavior of Date.toLocaleDateString (even when locale is forced to be same) in the prepackaged vs. master (Electron difference?), see below.

-- prepackaged build, Date.toLocaleDateString behavior in console:
![brave_js_date_behavior_prepackaged_build](https://cloud.githubusercontent.com/assets/6969859/20815776/268f32ee-b7d4-11e6-85fe-ea0aa2718e8d.png)
**(note that specifying options, e.g. "month" as numeric makes no difference here)**

-- vs. master, Date.toLocaleDateString behavior in console:
![brave_js_date_behavior_master](https://cloud.githubusercontent.com/assets/6969859/20815791/34204362-b7d4-11e6-8b7d-af7778445e3b.png)
**(note that specifying options, e.g. changing "month" to numeric changes output here)**

**Comment by willy-b** [comment]
@bbondy , do you know any reason why the prepackaged and dev-mode behavior of Date.toLocaleDateString might be different?

**Comment by bsclifton** [comment]
@willy-b we are getting ready for a Chromium 54 upgrade; I wonder if you got a new version locally? you can check about:brave and look at the Muon version for both)

That aside, this could probably be hardened :smile: 

I personally would vote for choosing the formatting, instead of using toLocaleDateString() (for the file name). I would go with a format like `BravePayments_YYYY-MM-DD.pdf`

You could try to go the route of replacing spaces with underscore or trimming whitespace on beginning/end of string... but some folks will have their locale setup to use / as the delimiter, which is not valid for Windows. I think making the filename respect the locale is a nice enhancement (which we could create another issue for), but for now, we go with something that works

**Comment by posix4e** [comment]
I believe 0.13.0 is the one based off of chromium 54. We need to rebase it badly

**Comment by willy-b** [comment]
Sounds good @bsclifton. I changed to the format you suggested, basing my changes on the 0.13.0 commit, which is in conflict with master. The change has been pushed to a branch (see https://github.com/willy-b/browser-laptop/commit/e74670f8f5c1affc2e16383fba40b9004369f858).

But what branch should I open a PR against to get it into 0.13.0?
This is important because the feature will be broken for everyone, regardless of locale, due to the change in Date#toLocaleDateString behavior that has popped up in the 0.13.0 branch.

Thanks

**Comment by bsclifton** [comment]
@willy-b you can rebase it against master and PR it against master too

The chromium54 branch will need to be rebased against master also (but that'll happen before we build a next release)

**Comment by luixxiul** [comment]
Would anyone please add QA steps for this issue? 0.13.0 will be the largest release ever and the QA team needs clear and simple steps! Please see #6668 for more info. Thanks in advance :pray:
