### ISSUE TITLE
Panopticlick reports Brave as susceptible to Fingerprinting

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5975]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Panopticlick reports Brave as being susceptible to fingerprinting, even if fingerprinting protection turned on.

**Expected behavior:**
Brave is not fingerprintable (or not fingerprinting to a meaningful degree)

**Platform (Win7, 8, 10? macOS? Linux distro?):** All

**Brave Version:** 0.12.10

![image](https://cloud.githubusercontent.com/assets/815158/20813420/26efe812-b7db-11e6-931c-4ea12c4a1628.png)

![image](https://cloud.githubusercontent.com/assets/815158/20813453/4253202e-b7db-11e6-8000-5ff0a03a50e6.png)

#242 #1354 #2229 #2259

**Comment by luixxiul** [comment]
CC @diracdeltas

**Comment by privatzee** [comment]
I believe that everybody using Brave has the same spoofed hash, so that's a kind of herd anonymity. Here is me, tested just now:

![image](https://cloud.githubusercontent.com/assets/22591438/20839082/2e88913e-b879-11e6-97b2-6c88f1aab40e.png)

It would also be nice if reported screen size was set to browser window size. Hopefully that will be available once we can add browser extensions.

**Comment by diracdeltas** [comment]
everyone should have the same canvas hash

panopticlick is based on the number of users who visit EFF's site, so it's definitely skewed. if you visit the site over and over again in new incognito tabs, it no longer says you're fingerprintable.

**Comment by pmo** [comment]
I just noticed the canvas fingerprinting and wondered why mine was that unique, kinda solved when I saw this post, we all have the same fingerprint hehe.
