### ISSUE TITLE
[Request] Add setting to turn off modal darkening effect

### ISSUE THREAD

**Issue by Gelo3D** [brave/browser-laptop#5992]
**Did you search for similar issues before submitting this one?**

yes

**Describe the issue you encountered:**

Please do options to turn off/on darker effect -
![screenshot_2](https://cloud.githubusercontent.com/assets/15075411/20848083/e057090c-b8d0-11e6-8ae8-a6202cc7aa35.png)

Its really cool and important to bad / slow pcs/laptops.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
Renamed to be more general. Other actions, such as the Clear Browsing Data panel, also darken the current window.

**Comment by bradleyrichter** [comment]
I agree with @Gelo3D on this one. There really is no point in having the darkening effect with most of our dialogs. Darkening should only be used on modal dialogs. 

cc @bsclifton

**Comment by bsclifton** [comment]
This is an interesting one... 

The purpose of the dark is to show that there is an overlay.  For example (using the screenshot above), the dark colored area is where you need to click in order to hide the bravery menu

If we didn't show an overlay, users may expect that they could click on any UI elements and it would work as expected.  If that is the desired behavior, this would become a larger change.  Also, we'd need to define what happens in this scenario:
- You click lion head, open Bravery. Let's say there is no overlay anymore
- You can click refresh button, even with Bravery Menu up
- The click refreshes the page

At this point, do we hide the Bravery menu? or do we keep it open, since the user never chose to close it?

The overlay forces you to close the modal before using the browser again

**Comment by bradleyrichter** [comment]
I call hogwash based on other dropdown panels. ;   )

![image](https://cloud.githubusercontent.com/assets/13509546/20854315/adffdca0-b8a7-11e6-9b57-26faa35427fd.png)

![image](https://cloud.githubusercontent.com/assets/13509546/20854319/b5ac8de0-b8a7-11e6-9f5e-345b19c07fe8.png)

![image](https://cloud.githubusercontent.com/assets/13509546/20854372/1d9713e4-b8a8-11e6-9dd3-67257276216a.png)

**Comment by Liunkae** [comment]
Related: #3653

**Comment by lucidNTR** [comment]
+1

**Comment by luixxiul** [comment]
Fixed with https://github.com/brave/browser-laptop/issues/3653
