### ISSUE TITLE
Significant lag in loading newtab image

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6063]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Significant lag in loading newtab image

**Expected behavior:**
Should load quickly, there should not be a noticeable lag in loading the image

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.13 RC2

- Steps to reproduce:
    1. On  a clean install of 0.12.13 RC2 open a new tab 
    2. Significant lag in loading the image

- Screenshot if needed:
![ntab](https://cloud.githubusercontent.com/assets/17010094/20964006/ae55f716-bc67-11e6-85ac-9003442b9438.gif)

- Any related issues:
cc: @cezaraugusto

**Comment by bsclifton** [comment]
Closing this issue as it's similar to https://github.com/brave/browser-laptop/issues/5309 (and I believe would have the same root cause fix)

Definitely not related to Windows; would likely be slowness between our EC2 host and your machine (since the images do load remotely). They are cached however after a successful load; loading the same image again should be quick
