### ISSUE TITLE
New 126% zoom increment.

### ISSUE THREAD

**Issue by stephenkru** [brave/browser-laptop#6089]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
There is now a 126% zoom increment. Press zoom + or ctrl+mouse scroll up. The increments of browser zoom are now 100%, 110%, 125%, and 126% (and so on). 

Click 3 dot settings menu, go to zoom + and click it till it hits 126%.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:
0.12.13
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
@stephenkru What operating system are you using? I am not having the issue with Brave 0.12.13 on macOS 10.12.x.

**Comment by stephenkru** [comment]
Win 10

**Comment by Liunkae** [comment]
@srirambv: Can you reproduce on Windows 10?

**Comment by srirambv** [comment]
@Liunkae Nope can't repro on Windows 10. Jumps to 150% right after 125%

**Comment by bertrandrustle** [comment]
This is also present on Ubuntu, both in builds from git and the recent .deb packages.

The bug seems to be triggered when `Default zoom level` is set to something other than `100%` under General Settings.

Set `Default zoom level` to `125%`, open a new tab, then pop open the Brave menu. You should see the new tab's zoom level set to `126%`. Next, click _once_ on the minus button to decrease the zoom level one step. You should see the zoom level indicator drop to `125%` and the tab's page content scale down ever so slightly as well. From there if you click on the plus button _twice_ to increase the zoom level one step above `126%` you should see the indicator increase to `150%`, as would normally occur absent the buggy behavior.

Behavior similar to the above is triggered when `Default zoom level` is set to `110%`: a new zoom level between `110%` and `125%` is created. However, in this case the zoom level indicator still reads `110%` at one step above the normal `110%` preset, but you can confirm its existence via the scaling of the page content itself. So it acts as if this new zoom level is something between `110.0` and `110.5` and is being rounded to the nearest integer for display in the menu, which results in a repeated value of `110%`.

**Comment by Liunkae** [comment]
Thanks @bertrandrustle! That reproduces for me with Brave 0.13.4 on macOS 10.12.x.

Steps to reproduce:
1. Set the default zoom level to 125% in Preferenecs.
2. Open a new tab.
3. Open the kabob menu.
4. Notice that the zoom percentage is 126%.

Pinging @bsclifton

**Comment by Liunkae** [comment]
Still exists with Brave 0.18.x.

**Comment by Liunkae** [comment]
Still reproducible with Brave 0.20.30 on macOS 10.13.x.

**Comment by Liunkae** [comment]
@jonathansampson Still reproduces on the latest release build, 0.21.24. Are you using one of the pre-release builds?

**Comment by stephenkru** [comment]
The 126% is gone for me now, but I am getting an extra 110% increment. I click + zoom at 110% and it doesn't change from 110%. You can see a slight size increase to text when it happens tho. Other increments appear to be fine.
