### ISSUE TITLE
Some UI elements are too small and are not usable on touch screen devices (or by drunk people)

### ISSUE THREAD

**Issue by speaGIT** [brave/browser-laptop#6125]
**Did you search for similar issues before submitting this one?**
No alcohol related posts found.

**Describe the issue you encountered:**
Alcohol inhibits fine motor controls, resulting in small icons becoming impossible to click.

**Expected behavior:**
Sober precision.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All platforms.

- Brave Version:
All versions.

- Steps to reproduce:
    1. Consume excessive amounts of alcohol.
    2. ???
    3. Attempt clicking "Add new tab" (+) icon.

- Screenshot if needed:
It looks like this --->    +

- Any related issues:
Possible alcoholism.

**Comment by bsclifton** [comment]
Hi there! I did have a similar problem; it was super hard (although I wasn't drunk at the time)

We fixed this with https://github.com/brave/browser-laptop/issues/5925 which will be in our next major release (0.13.0).  I'll mark this issue as a duplicate, but I'm curious for more details

The fix we had brings it up to this size.  What do you think? Does it need to be bigger?
![screen shot 2016-12-09 at 5 22 07 pm](https://cloud.githubusercontent.com/assets/4733304/21069114/1d9e249a-be34-11e6-99ca-514149ec0231.png)

**Comment by gabriel1313** [comment]
I've found that the text in the Tabs / Bookmarks Bar / URL Bar look smaller or more cluttered on Brave than on Chrome. A visual check shows that the combined space for Tabs / Bookmarks Bar / URL Bar is about the same on both. Chrome uses its vertical space more efficiently though - check (1) Chrome has less vertical space between the text in URL Bar and the text in the Bookmarks Bar, but still manages to look less cluttered and (2) Chrome has no space above the tabs (in Maximised mode) whereas Brave does. 

The extra vertical space can perhaps be reclaimed to make the design appear less cluttered or allow for bigger text?

**Comment by stephenkru** [comment]
Yeah, I use my computer as a media device so I have a wireless touchpad/keyboard I use from the couch. It's like performing surgery trying to click buttons in Brave, where it's easier on all other browsers.

Same issues on my surface pro using touch screen. It's impossible to hit certain buttons in brave on these setups. I was forced to switch back to chrome on the surface because of it. Please make the buttons bigger and spaced out a little more. the close tab x and + on the last tab are way to close and easy to hit the wrong one when using touch screen. This applies to the vertical dots settings menu as well. Make it bigger. The most frustrating thing was opening brave on the surface. Hitting on a folder in the bookmarks bar accidentally hitting the close tab x and the whole browser would close. This is the main reason I had to switch browsers as it happens constantly. 

There is weird behavior with clicking in the bookmarks bar, too. Have a folder structure like //Animals/Dogs in the bookmarks bar. Click the animals folder, click the dogs folder and the bookmark menu closes... why would I ever want that behavior. Keep them open.

This weird behavior applies to the settings menu. Click the settings menu, click bookmarks, shields, or help. Nothing happens, the menu stays open, as it should. Now try press and hold mouse button 1 down on any of those 3 (bookmarks, shields, help), hover your mouse over anything in the sub menu and let go of mouse button 1. Nothing happens. It should open up whatever you let go of mouse 1 over.

Also, as someone using two monitors (actually a TV and 1 monitor) drag and drop of tabs to new monitors/windows would be a great feature.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6474#issue-198175776
