### ISSUE TITLE
Clicking the button linked to Cubits opens a blank tab without loading the page

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6152]
**Describe the issue you encountered:** Clicking the button linked to Cubits opens a blank tab without loading the page

**Expected behavior:** It should load Cubits page

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: b824ae6

- Steps to reproduce:
    1. Disable Coinbase via VPN and enable Cubits
    2. Open about:preferences#payments
    3. Click "Add funds"
    4. Click "Cubits" -> `about:blank` is opened

This does not occur by clicking another link on the preferences page like #security to Adobe for example

- Any related issues:

**Comment by luixxiul** [comment]
Also `https://cubits.com` remains on the status bar after closing the modal dialog until previewing another anchor link.

**Comment by cezaraugusto** [comment]
I could repro status bar link persisting after closing modal (which is maybe a different issue?)

As a note: 

A likely fix is replacing default `<a target='_blank' href={url}>` [here](https://github.com/brave/browser-laptop/blob/master/js/about/preferences.js#L415) with `aboutActions.newFrame`, but since it doesn't seem to open adjacent tabs, the fix would undercover other issue (see #5913, which relied on the action to open a new tab, fixed [here](https://github.com/brave/browser-laptop/pull/6060/files#diff-e3eeb751016b2ce9f8278efce585a461R329)).

**Comment by luixxiul** [comment]
Another case is clicking the link box on facebook timeline does not open the link.

**Comment by bsclifton** [comment]
The fix done to close #5880 should have resolved this https://github.com/brave/electron/commit/bd3e9a225bf087998c4ffe85b22e36489b9f4a3f

We need to retest. Since cubits won't show for US folks automatically, you will need to edit the conditions in the code so that it shows. The notes in https://github.com/brave/browser-laptop/pull/6051 may be useful :smile:

**Comment by luixxiul** [comment]
Test plan:

Disable Coinbase via VPN and enable Cubits
Open about:preferences#payments
Click "Add funds"
Click "Cubits"
