### ISSUE TITLE
Regression : Alignment off for about:about

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6183]
Only reproducible with the PR from:
https://github.com/brave/browser-laptop/issues/5790#issuecomment-265839135

**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
Visiting about:about 'List of about pages' is flush left with no margin.

**Expected behavior:**
'List of about pages' should left-align under 'About pages' header.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on os x

- Brave Version:
0.12.15 RC2

- Steps to reproduce:
    1. Visit about:about

- Screenshot if needed:
<img width="367" alt="screen shot 2016-12-13 at 11 24 29 am" src="https://cloud.githubusercontent.com/assets/1434040/21151177/23707062-c127-11e6-83cd-266bf2ec74a5.png">

- Any related issues:

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/commit/15976325924431b5fdbac96df72af5ef9ad16027#diff-1fcd5f7d89a2a38953d711aeb2e1dfeaL84 causes a regression.

Because `siteDetails.less` is used globally, actually the changes in the file with the commit should be reverted to set up a special file which is to be loaded only in about:brave.

https://github.com/brave/browser-laptop/commit/15976325924431b5fdbac96df72af5ef9ad16027#diff-1fcd5f7d89a2a38953d711aeb2e1dfeaR81 would therefore cause a regression too.

**Comment by bbondy** [comment]
resetting milestone since the PR that introduced it was reverted:
https://github.com/brave/browser-laptop/pull/6107/files

**Comment by luixxiul** [comment]
Also make sure every change in `history.less` would cause a regression because about:brave is based on that file.

**Comment by luixxiul** [comment]
Test plan:

Open about:about
