### ISSUE TITLE
about:extension doesn't contain Favicons of any of the installed extensions

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6257]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
about:extension doesn't contain Favicons of any of the installed extensions

**Expected behavior:**
Should show the favicons for installed extensions

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Enable all extensions on 0.13.0
    2. Open about:extensions, none of them have the favicons

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21268564/42ccd7a2-c3a7-11e6-8047-40c0091d62f1.png)

- Any related issues:

**Comment by cezaraugusto** [comment]
This is related to how we collect icon files, which ideally we should collect via `chrome-extension://` instead of `file://`. #6290 didn't address the issue the right way.

Stepping back in favor of @bbondy [comment](https://github.com/brave/browser-laptop/pull/6290#issuecomment-267997311). Will happily assist anything needed.

**Comment by bbondy** [comment]
So I tried a lot of different things, Chrome encodes to data:// urls, which we could calculate on extension load.  We might possibly be able to get to it via chrome extension management api once we implement as well.  For now I ended up just going to simply adding file://* without removing the others.

**Comment by luixxiul** [comment]
Test plan:

Open about:extensions
Make sure that extensions have their icons
