### ISSUE TITLE
about:newtab top sites do not delete in the order you would expect

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6282]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When deleting top sites, I found that they often deleted other top sites tiles and not the one I selected.

**Expected behavior:**
The top site tile I chose to delete should disappear, any tiles to the right should shift left by one space.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Remove /brave
    2. Open 0.13.0 Preview 4
    3. Attempt to delete the top site tiles in random order

- Screenshot if needed:

- Any related issues:

**Comment by cezaraugusto** [comment]
Couldn't repro this one.

Anyway, my guess is that it's related to the way we're doing "frecency" on newtab. Somehow the index of each item is being altered by number of visits for each site. After several visits on Medium.com, I had to remove it several times in order to make it disappear.

@bsclifton what's your thoughts about this one?

**Comment by bsclifton** [comment]
From master, I can't repro this either (I didn't try the preview release 4 yet)

Steps I did:
1. Delete my session folder completely (since I'm running in dev mode, it's the `~/Library/Application\ Support/brave-development` folder
2. Launch Brave, it opens to new tab screen
3. I can delete any tiles; it works as expected. I can then pick "Restore All" and try deleting them in a different order. Always seems correct

**Comment by bbondy** [comment]
Seems like we need better STR here but also that this was probably present in 0.12.* as well, I think this should be removed from this milestone if so pls.

**Comment by bsclifton** [comment]
Closing as we can't repro the issue; however, let's reopen if the next preview or release candidate has the issue :smile:
