### ISSUE TITLE
AdBlocker-Blocker on v3.co.uk

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6393]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Users are unable to read content from http://www.v3.co.uk/v3-uk/feature/3001670/ten-desktop-browsers-to-try. While scrolling, the user encounters an adblocker-blocker message requesting they turn off any adblockers that may be running.

Blocking scripts preserves the content.

**Expected behavior:**
The user should be able to read online content uninterrupted.

**Platform (Win7, 8, 10? macOS? Linux distro?):** Windows 10

**Brave Version (revision SHA):** 0.12.15

**Screenshot if needed:**

![image](https://cloud.githubusercontent.com/assets/815158/21437905/15afdbda-c84c-11e6-810e-8bb049e13cbb.png)

- Any related issues:

**Comment by lukemulks** [comment]
It appears they're using an anti-ad blocker, but instead of having the AAB replace the ads, the AAB blocks content instead. 

I took a look at this script, which appears to run some detection by baiting the client with some white/blank ads: 

http://assets.v3.co.uk/javascript/live/v3/javascript-v3.head.min.js

The script above contains: 
```
22: [function(require, module, exports) {
		var utility = require("./utility.js"),
			DetectAdBlock = function(options) {
				this._options = {
					checkOnLoad: !1,
					resetOnEnd: !1,
					loopCheckTime: 50,
					loopMaxNumber: 5,
					baitClass: "pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links",
					baitStyle: "width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;",
					debug: !1
				}, this._var = {
					version: "3.2.1",
					bait: null,
					checking: !1,
					loop: null,
					loopNumber: 0,
					event: {
						detected: [],
						notDetected: []
					}

```

The bait call and the content masking appear to be made using opentag and cloudfront: 

728x90 "bait" ad call
`https://d3vuqzsqy1r5zj.cloudfront.net/Pub/AAB/www.v3.co.uk/ad.js`

Opentag script that initiates the content blocking: 
`https://d3c3cq33003psk.cloudfront.net/opentag-53775-238465.js`

within the above script, there is this custom tag function which calls out Rezonance
```
function() {
	var C = qubit.opentag.CustomTag;
	var b = new C({
		"dedupe": false,
		"locationPlaceHolder": "END",
		"needsConsent": false,
		"active": true,
		"url": "",
		"timeout": 5E3,
		"async": true,
		"usesDocumentWrite": false,
		"name": "Unlocking script - Rezonanace",
		"disabled": true,
		"id": 57903982,
		"locked": false,
		"locationObject": "BODY"
```

There's also this call that takes place which appears to respond once the content has been blocked: 

`http://assets.incisivemedia.com/rezonance_fonts/kill_switch/v3/TestKillSwitch.json`

```
{
	"blockContent": "true"
}
```

Blocking recommendation: 
I'd suggest attempting to blocking these requests: 

`https://d3vuqzsqy1r5zj.cloudfront.net/Pub/AAB/www.v3.co.uk/ad.js`

`https://d3c3cq33003psk.cloudfront.net/opentag-53775-238465.js`

I suspect the assets.incisivemedia.com domain may be more of a confirmation event than an execution, but I am not 100% sure.

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3

**Comment by alexwykoff** [comment]
Hey @lukemulks if you could dig into this a bit more when you have time, that'd be rad.

**Comment by lukemulks** [comment]
Will do @alexwykoff 

I am going to do a big sweep through the backlog this week. :-)
