### ISSUE TITLE
Brave is not passing the Acid 3 test.

### ISSUE THREAD

**Issue by pmkary** [brave/browser-laptop#6509]
**Did you search for similar issues before submitting this one?** yup

So while Chromium passes Acid 3 test perfectly:
<img width="676" alt="screen shot 2017-01-03 at 11 21 31 am" src="https://cloud.githubusercontent.com/assets/2157285/21602233/24e91b2a-d1a7-11e6-91e4-58297df96d59.png">

Brave can't:
<img width="680" alt="screen shot 2017-01-03 at 11 21 07 am" src="https://cloud.githubusercontent.com/assets/2157285/21602239/34c780fe-d1a7-11e6-8958-5fdabdecea2e.png">

I don't know what is that for, Even with the shields down it happens.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS sierra (latest and greatest)

- Brave Version (revision SHA):
Latest and greatest?
<img width="477" alt="screen shot 2017-01-03 at 11 22 55 am" src="https://cloud.githubusercontent.com/assets/2157285/21602260/5d9cb92c-d1a7-11e6-8df7-7eedef608204.png">

- Steps to reproduce:
   Runnig http://acid3.acidtests.org/

**Comment by josiah-keller** [comment]
The red text there is a link (selector `a#linktest`).  You can see that test 48, from lines 1885 to 1898 of the page source, adds the link to the DOM, sets its href, and navigates an iframe to the same URL.  The CSS rules for that link are supposed to make it colored white when the link is visited, so you can't see it.  So the problem is that Brave does not respect the visited color.  This is (I'm assuming) done for privacy reasons so that a site can't read the color of a link to see whether you've visited it or not.  I thought all browsers had something like this, so I'm not sure why Brave fails the test and Chrome doesn't.

**Comment by pmkary** [comment]
Yeah as you mentioned [all browsers have this rule to protect the privacy](https://stackoverflow.com/questions/21871515/javascript-find-the-colour-of-link) but why Brave fails this is something very strange to me because they both share one core and this is very strange to get multiple results

**Comment by luixxiul** [comment]
So this should be duping to #512

**Comment by pmkary** [comment]
@josiah-keller so judging by the issue number of #512 it's one old problem with visited links.
