### ISSUE TITLE
Brave does not remember vertical (y axis) amount

### ISSUE THREAD

**Issue by 2disbetter** [brave/browser-laptop#6602]
## Test plan
1. Open Brave on Windows
2. Position your window, taking note of the Y position
3. Close Brave and reopen
4. Position should be exactly the same as before

## Original issue description
**Did you search for similar issues before submitting this one?**
Yes 
**Describe the issue you encountered:**
When restarting Brave on Windows 10 brave will be positioned correctly in the last place it was before being closed but the vertical size is wrong and looks to be set by default to the max y axis resolution of the monitor. 
**Expected behavior:**
Brave remembers both position and size of previous window. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version (revision SHA):

- Steps to reproduce:
    1. Close brave
    2. Open brave
    3. Note maximized y-axis 

- Screenshot if needed:

- Any related issues:

**Comment by draeron** [comment]
i have this issue too, been there for a while now.

Version Info : 
Brave: 0.13.5 
rev: 1db81cb18b6919535792bb7e198ab87276bd67ea 
Muon: 2.56.8 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64

**Comment by JaneSmith** [comment]
Not sure if this is the correct place to post or not, but Brave never remembers the horizontal position of my window between restarts. It always appears centered on screen, instead of on the left side where I always position it manually.

I've also noticed that sometimes it doesn't remember the window size either, but usually it does.

I'm running version 0.18.23 (36ae2ec) on Windows 10 Pro.
