### ISSUE TITLE
Make tab pane manager more visible

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#6603]
I noticed this new/closed thread in the Brave Community:
https://community.brave.com/t/closed-max-number-of-tabs-per-set-first-window-vanishes/632

I think there's a case to be made for having a more visible tab pane manager. Here are some possibilities I came up with:

Use alignment:
1. align the TPM bars to the left since the user's gaze is (possibly) more likely to scan that area.
2. or align centered immediately above the currently active tab for a similar reason.

Use colour:
1. Set active TPM bar to something more noticeable (e.g. the same orange as the Brave Shield).
2. Use colour in combination with either of the alignment tweaks mentioned above.

Any thoughts? I'll message the thread OP who might have other suggestions/comments.

**Comment by srirambv** [comment]
>Use colour:
>1. Set active TPM bar to something more noticeable (e.g. the same orange as the Brave Shield).

+1 for colors, to visibly highlight the tab sets when created something like 

![image](https://cloud.githubusercontent.com/assets/17010094/21847503/1fa5103a-d7f4-11e6-966b-07e3572bd808.png)


cc: @bradleyrichter

**Comment by bsclifton** [comment]
I really like the color option :) Matching the lion orange (and perhaps even allowing customization) would be awesome

**Comment by bradleyrichter** [comment]
I think this Brave-orange treatment is great for discovery but I can already hear the user feedback about the bright orange headlights in the center of my browser chrome. :  )

I would prefer to add more contrast if more is needed.

Also - I plan to accentuate the audio-feedback which is really one of the great advantges to this UX feature. (subtle animation to represent where the noise tab lives.) (currently it is a subtle blue outline)

**Comment by CliqueBait** [comment]
@srirambv Actually, I wasn't thinking of all pane bars being brave-orange. In my mind's eye, I was thinking of only the currently active pane bar doing that. The others could remain subtle in order not to offend the user in the way @bradleyrichter expects it might. (correctly I think).

**Comment by ClemencyFane** [comment]
Hi, I was the OP for the original question. CliqueBait asked me to comment on the options discussed here. FYI, I've been using Brave exclusively on Macbooks, all with OS 10.12.2, but I have a Win10 notebook as well if you want me to test anything on it - I'd be happy to.

I vote for the pane bars in the center, for two reasons. When desktop notifications from various apps show up, they're usually in a corner. If I have them set to Alerts so they remain until I dismiss, they could cover the pane bars if located in the corner.

Also, just personal preference, but when my eyes scan up to the URL bar, it's more toward the center of my screen, so that placement seems more natural. I do adjust my settings so the URL bar is visible all the time.

For the color scheme, I really like CliqueBait's idea of the active pane bar being orange, and the others more subtle. I think that would stand out best on various screens. I have a range of Macbooks from 2012 up to the retina display, so colors look drastically different on these machines. A lot of people to whom I've been recommending Brave are on older machines (mostly Windows, one Linux, all at least 3 years old).

Thank you for requesting my input - it's really cool that you take community members' feedback into consideration! 😊

**Comment by bradleyrichter** [comment]
Hi All - here is a quick mockup via GIF movie. LMK what you think about orange.

BTW - we will add a subtle audio-animation to these to help you notice more easily which tab set has the noise tab.



![orange_tabset_indicators](https://cloud.githubusercontent.com/assets/13509546/22261129/9e1b6118-e220-11e6-989a-cafa699da249.gif)

**Comment by ClemencyFane** [comment]
I like it. It shows up well on my lowest resolution screen.

**Comment by ClemencyFane** [comment]
Also, I got pulled away and forgot to come back, but the additional animation for the tab having the sound is a good idea too. I often have more than one browser and a lot of windows/tabs open, and a video somewhere will start playing and it can be heck to find the tab.

**Comment by luixxiul** [comment]
> the additional animation for the tab having the sound is a good idea too

Is this not enough?

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22274493/2bf53ba2-e2ea-11e6-8a6f-f780de681b03.png)

**Comment by ClemencyFane** [comment]
My apologies, I was using Safari earlier today and I was thinking Brave also had grey audio icons. I should have double checked that before commenting. That looks really good; I just tried it with three browsers open and it's much easier to find the tab. Thanks, and sorry for the confusion.

**Comment by luixxiul** [comment]
np!

**Comment by luixxiul** [comment]
the milestone was moved to 0.13.3

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/35
