### ISSUE TITLE
'Inspect Element' should refocus developer tools

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#6605]
**Did you search for similar issues before submitting this one?**
Similar to #45, but not the same

**Describe the issue you encountered:**
If you have developer tools already opened and you right click on page and select `Inspect Element`, you can see that developer tools is activated, but it's not focused. 

**Expected behavior:**
Developer tools should be focused every time that you click on `Inspect Element`.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.12.15 as well as 0.13.0 b466a44

- Steps to reproduce:
    1. Right click on any site and select `Inspect Element`
    2. Right click on the same site and again select `Inspect Element`

**Comment by n8udd** [comment]
Agreed. This is the default behaviour with Chrome, Firefox, Safari and Edge. 

Right clicking the page and selecting "inspect element" should bring the developer tools to the foreground of the window (What ever the equivalent is of a Z-Index for the OS)

**Comment by bsclifton** [comment]
Officially closing the issue as `wontfix` since this issue is addressed in our upcoming releases (our fork of the Chromium UI, which is called [Brave Core](https://github.com/brave/brave-browser)). Stay tuned! This new code-base will not only resolve this issue, but will address many of the concerns with extensions and more
