### ISSUE TITLE
Don't prompt for restart when clearing cookies / history / images and files

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6611]
Starting with https://github.com/brave/browser-laptop/issues/4157, a restart is required when choosing to clear cookies / history / images and files

User @Kanichiro recently brought this up with https://github.com/brave/browser-laptop/issues/4082#issuecomment-271930259.

Is there anything we can do to improve the experience?
- is it possible to fix without restarting?
- if not (or fix isn't easy), can we check if any WebRTC device IDs exist? if not, then don't prompt

cc: @diracdeltas @bbondy @bradleyrichter

**Comment by diracdeltas** [comment]
It seemed like a lot of work to reset the WebRTC deviceId in muon without restarting, but someone should look into it again. IIRC the webrtc device ID always exists since it is set when the session is created.

This is a good starting point - https://chromium.googlesource.com/chromium/src/+/4db1329e005388540eb07429ac97827ca9bc422b.
