### ISSUE TITLE
Opening a new session tab launches Pocket login page as well (Intermittent Issue)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6630]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opening a new session tab launches Pocket login page as well(Intermittent Issue)

**Expected behavior:**
Should not launch the pocket login page when a new session tab is created

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	0c7a64d
Never seen this happen on 0.12.15

- Steps to reproduce:
    1. Enable Pocket from Advance settings
    2. Wait for the Pocket login page to be launched in a new tab
    3. Do not Login to pocket, close the tab opened on step 2
    4. Open a new session tab by pressing `Ctrl+Shift+S`
    5. Pocket login page also opens in a normal tab along with a new session tab 

- Screenshot if needed:

- Any related issues:
Somewhat similar to #6586

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/keyboard-shortcut-duplication/1381. User reports this happens on opening a private tab

**Comment by willclarktech** [comment]
Since the community poster never responded, I can provide feedback on the private tab issue. Here's what I experience:

1. I'm logged into Pocket
2. I hit Cmd + Shift + P to open a new private tab
3. The private tab opens, and I interact with it like normal
4. When I switch back to the previous tab, the Pocket toast saying something like "Page saved to Pocket" is visible, and I have to delete the page from my Pocket list.

Mac OSX - 10.12.4
Brave - 0.14.1 - 3de60d5

**Comment by mbirkegaard** [comment]
Same issue. Whether I want to open a private or save to pocket, this makes doing either cumbersome. Maybe just make it possible to remap shortcut keys?

Mac OSX - 10.12.5
Brave - 0.16.9 - fba98fc
Save to Pocket - 2.1.32

**Comment by supercr7** [comment]
Any updates or workarounds to this? It is annoying to clean up my pocket list every week due to this and I could not find a way to edit the hotkeys as well.
