### ISSUE TITLE
Extension suggestions

### ISSUE THREAD

**Issue by martinchodev** [brave/browser-laptop#6645]
I would like to suggest these extensions (sorry if there's a duplicate, I didn't see these in the project page):

- Privacy Badger
- Mailtrack
- Boomerang
- High contrast by google (inverts the colors for better readability)

Thanks!

**Comment by stan-qaz** [comment]
I'd add Vanilla Cookie Manager, https://github.com/laktak/vanilla-chrome might be worth making a native part of Brave too.

It is the simplest and most effective I've found. Sync between different browsers or machines is weak but everything else is great. The "allow cookie for XX minutes" option saves a lot of time and tweaking.

**Comment by drfunkencluck** [comment]
what about these extensions
https://chrome.google.com/webstore/detail/remove-google-redirection/dnhjklgpiifbofihffldllbcopkinlod?utm_source=chrome-app-launcher-info-dialog
https://chrome.google.com/webstore/detail/briticism/jcjnkkhmhbmfbidbebnkbihddnfldplp?utm_source=chrome-app-launcher-info-dialog
https://chrome.google.com/webstore/detail/chrome-currency-converter/anbfhidldjknonaihbalghlebaijealk?utm_source=chrome-app-launcher-info-dialog
https://chrome.google.com/webstore/detail/poper-blocker/bkkbcggnhapdmkeljlodobbkopceiche?utm_source=chrome-app-launcher-info-dialog
unless these features are built in then ok build them in otherwise these could be used

**Comment by bsclifton** [comment]
cc: @jonathansampson 

We're tracking all our extensions here 😄 
https://github.com/brave/browser-laptop/projects/1
