### ISSUE TITLE
fading effect b/w tabs feels like flickering

### ISSUE THREAD

**Issue by bobinson** [brave/browser-laptop#6716]
**Describe the issue you encountered:** 
This is a minor UX aspect. While moving the mouse pointer from an active tab to a another one, the transition from active tab to inactive background tab is not smooth. Its like a flickering. The screen is re-drawn way too fast.

**Expected behavior:**

A smooth transition will be great.

- Platform : macOS 10.12.2, all softwares and development tools updated.

- Brave Version (revision SHA):
Brave	0.13.0
rev	d7a324a
Muon	2.0.11
libchromiumcontent	54.0.2840.100
V8	5.4.500.41
Node.js	7.0.0
Update Channel	dev
os.platform	darwin
os.release	16.3.0
os.arch	x64

 // minor refinement request.

#6665

**Comment by aakashysharma** [comment]
Instead of creating a new issue, I'd like to give my feedback here.

The hover/preview effect is maybe nice but at the same time confusing.
1. If I hover over other tab, the preview of other tab is displayed in full size.
2. This makes user want to click on the preview content he sees.
3. However, the user would have to click first on the tab head first and then on the content. 
4. Since brave doesn't implement this, it ends up as accidental clicks on random areas on other page.

The preview being in full size implies that you should be able to click on the previewed tab content to switch focus. The current/longer way doesn't seem to be a good UX design. I think, it can be made better.

**Comment by lucidNTR** [comment]
@bobinson could you clarify? is this flicker maybe just the grey-out overlay animation or do you think it is the actual page-preview, that flickers?

**Comment by luixxiul** [comment]
@cezaraugusto I feel you fixed the issue recently, don't you?

**Comment by cezaraugusto** [comment]
yes but not in master and needs @bradleyrichter approval first. Work is done in `brad-preview-bundle` if anyone is interested. Feedback welcome
