### ISSUE TITLE
Make Brave base on truly trustless free micropayments - cooperation with Bitshares

### ISSUE THREAD

**Issue by noisy** [brave/browser-laptop#682]
Daniel Larimer (@bytemaster) - lead developer of cryptonomex lately proposed an idea of new way of charging fees in the bitshares network. Briefly... bitshares can be a fee-less blockchain, allowing for truly micropayments.

In first poll [91,5% of bitshares community](https://bitsharestalk.org/index.php/topic,21359.0.html) support this idea, what means that probably in near future this will be implemented.

I believe that cooperation of brave and bitshares can introduce a lot of new possibilities. People could not only send fractions of bitcoins, but actually fractions of stable bitAssets like bitUSD or bitCNY. 

Moreover, sites could giveaway custom tokens (which are very easy to create on bitshares) to their readers/users, which can act like shares of blog/site/service. In that way, owner of the website can not only offer a ads free service for tiny price, but also a revenue from profits of website/blog.

It would be great deal in the future, to trade "RedditSupporter" asset for a discount buying a airplane ticket on Hipmunk.com (both services were created by A. Ohanian). Possibilities are endless :)

**Comment by beyondbitcoin** [comment]
this is all true, but it is important to cover the benefits and downsides to working with bitshares.

bitshares is easily the fastesr and most scalable blockchain in existence, but it requires more development time than most other cryptos.  I personally like the idea though if done right because.. well lets face it, if the other cryptos dont change, they are going to face terrible problems with scalability.  Id say it is probably worth it if brave is interested in the same type of philosophy bm brings to the table.

**Comment by noisy** [comment]
http://bytemaster.github.io/article/2016/02/10/How-to-build-a-decentralized-application-without-fees/

**Comment by luixxiul** [comment]
Let @BrendanEich decide..

**Comment by luixxiul** [comment]
Closing as stale.
