### ISSUE TITLE
SUGGESTION: clicking a tab's playback icon should Pause instead of Mute

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#6830]
Audio playback icons show whenever a tab is playing. When being drowned by multiple noisy tabs it's possible to mute those not currently of interest. Shouldn't it Pause instead of Mute?

e.g. I open several lectures. I don't want to hear all lectures at the same time but I do want to hear each lecture eventually so Pause makes more sense than Mute.

Gotchas:
1. Chrome does Mute meaning a divergence. But I'd argue that Chrome gets it wrong.
2. If we do this then it should still be possible/easy to Mute when that is what is required.

**Comment by NumDeP** [comment]
I think it should Pause (& mute) because if it's just muting content which you want to see later on, it would simultaneously play and use unnecessary resources for tabs that probably won't been seen for 15mins or more, which in turn would have to be replayed when you're done with other tabs, again using a excessive amount of bandwidth.
