### ISSUE TITLE
Clicking on a link first loads about:blank then the page

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#685]
I noticed this when clicking on a link, it does flash about:blank in the titlebar before actually loading the page. This is with links that produce a new page, I think with target="_blank"

**Comment by bridiver** [comment]
This happens because we send intentionally send about:blank on new tab creation for anything that has an opener (window.open, target="_blank", etc..). If we send the actual url then we get a conflict between the app setting the src and the opener setting the src (crashes on Windows). I briefly see "untitled" on Chrome as well and I think this will largely disappear when we fix the slow about:blank loading time.
