### ISSUE TITLE
GA & waffle.io breaks with default settings + Japanese blocklist

### ISSUE THREAD

**Issue by dignifiedquire** [brave/browser-laptop#6924]
- Describe the issue you encountered: Visiting https://waffle.io/ipfs/jenkins (and other waffle.io projects) results in a blank screen
- Platform (Win7, 8, 10? macOS? Linux distro?): `macOS 10.12.3`
- Brave Version (revision SHA): `719b6f89fc81ae65c4162cfcb4daba17423897ef` (`master`)
- Steps to reproduce:
    1. Visit https://waffle.io/ipfs/jenkins
    2. See blank screen
- Actual result: waffle.io is blank
- Expected result: waffle.io loads and works
- Will the steps above reproduce in a fresh profile? Yes
- Is this an issue in the currently released version? 
- Can this issue be consistently reproduced? Yes
- Screenshot if needed: 
<img width="1061" alt="screen shot 2017-01-30 at 17 05 26" src="https://cloud.githubusercontent.com/assets/790842/22430496/c0132b5a-e70e-11e6-81f5-91eb5924ee75.png">

**Comment by Liunkae** [comment]
Works fine for me with Brave 0.13.0 on macOS 10.12.3 with the default shield settings. Screenshot:
![image](https://cloud.githubusercontent.com/assets/19424103/22434077/3999cfe4-e6e0-11e6-910c-e98d48093e8c.png)

**Comment by dignifiedquire** [comment]
Might be something in `master` that breaks it

**Comment by dignifiedquire** [comment]
Updated description to include the commit hash I'm running

**Comment by Liunkae** [comment]
Works fine for me with a14fcdf.

**Comment by luixxiul** [comment]
Duping to #6883 ?

**Comment by dignifiedquire** [comment]
I figured out where the issue is coming from. I had enabled `JPN: ABP Japanese filters (日本用フィルタ)`and disabling fixes things.

**Comment by luixxiul** [comment]
@lukemulks the brekage of GA platform is also caused when that filter is enabled. Here's the list: https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt

By enabling the list and visiting https://analytics.google.com, nothing is displayed because these resources are blocked.

````
https://ssl.gstatic.com/analytics/20170314/app/js/js__ja.js
https://ssl.gstatic.com/analytics/20170314/web/education-content-ltr.css
https://ssl.google-analytics.com/u/ga.js
https://ssl.gstatic.com/analytics/20170314/web/analytics-ltr_1.css
https://ssl.gstatic.com/analytics/20170314/web/analytics-ltr_2.css
https://ssl.gstatic.com/analytics/20170314/web/analytics-ltr_3.css
https://www.google-analytics.com/analytics.js
https://ssl.gstatic.com/analytics/20170314/web/analytics__ja.js
https://ssl.gstatic.com/analytics/20170314/app/css/css.css
````

https://www.google-analytics.com/analytics.js and https://ssl.google-analytics.com/u/ga.js are obviously safe to be blocked, but the other resources seem to me to be requred to display the platform.

Yet I am not sure if this was caused by false rules as ``ssl.gstatic.com`` is not mentioned in that list.

Also please have a look at this: https://github.com/brave/browser-laptop/issues/6883. It is known that custom filters block the resouces more than as they are expected.

**Comment by luixxiul** [comment]
@lukemulks Also please feel free to rename this issue if necessary and add it to the project.

**Comment by lukemulks** [comment]
thanks @luixxiul will investigate

ssl.gstatic.com is used for advertising, but is also used for non-advertising. In the US, the filters don't block ssl.gstatic.com, but I will check and see if the other blocklist does. 

will also look into #6883
