### ISSUE TITLE
Pinning a tab while it is loading crashes Brave

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6968]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When a tab is loading, any attempt to pin it will crash Brave.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows

- Brave Version (revision SHA): 0.13.0

- Steps to reproduce:
    1. Navigate to github.com
    2. While tab is loading, right-click tab and select "Pin"
    3. Note crash
    
- Actual result:
Brave crashes

- Expected result:
The tab is pinned, and the user proceeds uninterrupted

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

- Any related issues: #6844, #3760

**Comment by bbondy** [comment]
I'm not able to reproduce on both Windows and macOS with the steps provided, I think there's more to it.  I'm going to push this out because I think it's the same as https://github.com/brave/browser-laptop/issues/3760 and pinned tabs code is changing completely soon where we'll share guest views across windows.

**Comment by bbondy** [comment]
Duping to #3760
