### ISSUE TITLE
[data-attribute="name"] not visible in styles element

### ISSUE THREAD

**Issue by alokpant** [brave/browser-laptop#7020]
styling with data-attribute is not visible in console when one inspects a element. However I am not able to reproduce the issue in codepen.io

https://codepen.io/gorkhali/pen/vgjxRv

So closing it now.

It is however not available in the project I am working on. Tested on chrome, it shows up there.

**Comment by luixxiul** [comment]
Let's leave this open until it is confirmed it is fixed

**Comment by bsclifton** [comment]
@alokpant can you please provide steps to reproduce? I'm going to close this as there is no action we can possibly take.

I inspected your codepen and I'm seeing `data-label`.  Are you mistakenly looking for `data-attribute` instead of `data-label`?

Another thing to consider: in your project, please try it on raw HTML.  Any attributes starting with `data-` should be OK for react, but you didn't specify which (if any) framework you're using.

**Comment by alokpant** [comment]
@bsclifton I wasn't able to reproduce it on codepen. I am using Foundation and DataTable. This is why I closed it. Because I know it is hard to test without valid proof. If this reoccurs, then I will try to recreate it again (and if I get successful) will add it there. Thank you for the great product. 👍

**Comment by bsclifton** [comment]
@alokpant sounds good! 😄  please feel free to re-open this issue at any time.  Also glad to hear that you enjoy Brave! 🦁
