### ISSUE TITLE
Is there an About:Flags or chrome://settings equivalent for brave? Is there a way to manually purge cookies per-page ?

### ISSUE THREAD

**Issue by tonsimple** [brave/browser-laptop#7117]
Basically, just looking for a way to 
1) disable webgl completely and 
2) delete cookies per site

Is there a Brave browser way to do that ?

**Comment by luixxiul** [comment]
> disable webgl completely

You can disable fingerprinting methods including WebGL with Fingerprinting Protection Mode. Please click the top right lion icon and enable the option. You would like to take a look at this: https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode

> delete cookies per site

The function is tracked here: https://github.com/brave/browser-laptop/issues/1268

Thanks!

**Comment by bsclifton** [comment]
@tonsimple Like @luixxiul said, we have an issue tracking the per-site cookies.

Regarding your question about `chrome://flags`:  any of the chromium/chrome command line flags that you're used to should work fine with Brave.  Instead of a `/` you'd use a `--` prefix.  For example, to disable WebGL, you can edit your shortcut and append `--disable-webgl`

We don't have an issue tracking an equivalent of `chrome://flags` if you wanted to create one.  The closest thing we have (which you're welcome to give a ++ to) would be https://github.com/brave/browser-laptop/issues/545 (implementing an about:config screen)

**Comment by jnm2** [comment]
> > delete cookies per site
> 
> The function is tracked here: #1268 

I want the option to actually delete cookies one time for one site, not block cookies. Is that tracked anywhere?

**Comment by luixxiul** [comment]
it's tracked here https://github.com/brave/browser-laptop/issues/6677
