### ISSUE TITLE
Create setting option to make the menu bar always visible on macOS

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7200]
**Describe the issue you encountered:**

https://community.brave.com/t/mac-os-10-command-h-not-working-and-fullscreen-default/1180?u=suguru

> my menu bar at top of screen and dock at bottom of screen vanish when I open Brave, and I have to hover to get them to show up (screenshot attached). I prefer having them visible at all times

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This is happening because the green button is fullscreen on macOS.  Every other app behaves the same way

In order to have the menu visible at all times, the preferred way would be to make the window the size you'd like.  As a shortcut, I believe you can double click any draggable area.  If not, you can at least double click the corners (after the cursor changes)

I'm going to mark this as a `won't fix`, but it might be good to document this
