### ISSUE TITLE
Export bookmarks option should be available in kabob menu 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7218]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Export bookmarks option is not available under kabob menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.13.3
rev	40d9979

- Steps to reproduce:
    1. Install 0.13.3 RC2 build
    2. Click on kabob menu 
    3. No export bookmarks option under the bookmarks menu
    
- Actual result:
No bookmark export option under kabob menu

- Expected result:
Provide export bookmark option under kabob menu

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment]
@srirambv I tried out Chrome, FF and Opera and none of them have export in main menu. If you think that we should have I can easily add it.

**Comment by srirambv** [comment]
@NejcZdovc Its not a standard behavior but just a suggestion to provide easy option in kabob menu rather than opening menu option. 

@bbondy @bradleyrichter  thoughts on adding this option in kabob menu.

**Comment by bradleyrichter** [comment]
We should be careful adding items to the kabob because it will grow out of control over time and it is always harder to remove a menu item than to add one after a measure of requests to support it.

Since Chrome on Windows has NO app menus at all, they "should be" making careful decisions about the kabob menu so I like to use this as a reference point. 

@srirambv My suggestion is to wait for enough requests. A minimum of 3 but this depends on the feature.

**Comment by bbondy** [comment]
We already have a Bookmarks submenu in that menu with Bookmarks Manager..., Bookmarks Toolbar, and Import Browser Data..., I think adding a 4th there would be good and I don't expect that submenu to grow a lot.
