### ISSUE TITLE
Show bookmarked status when urlBar is on titleMode

### ISSUE THREAD

**Issue by obvio171** [brave/browser-laptop#724]
Currently the reload button (`startButtons`) is hidden together with the star button (`endButtons`) when on titleMode. If you just unhide `endButtons`, the star is partly occluded by the title text/ellipsis.

This is bad because:
* When visiting a bookmarked page, user can't tell that it's bookmarked.
* User bookmarks a page with Ctrl+D, sees no feedback that it worked.

**Comment by psimyn** [comment]
do you think the bookmark icon should move in titlemode? If window width is much more than title width there will be an arbitray gap between them in title mode
![screen shot 2016-02-14 at 01 32 37](https://cloud.githubusercontent.com/assets/1731922/13028176/11540642-d2bb-11e5-9e8c-f6ed0ccc2fb7.png)

due to the fixed-width of the input field (in edit mode)

![screen shot 2016-02-14 at 01 32 27](https://cloud.githubusercontent.com/assets/1731922/13028175/114e64e4-d2bb-11e5-9eb4-6f56211f8e0b.png)

Could move the bookmark icon so it is at the right of title text, but it jumping around is probably stranger
