### ISSUE TITLE
Windows not allowing  Brave as a default browser 

### ISSUE THREAD

**Issue by teagueamania** [brave/browser-laptop#7287]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Windows no longer presents Brave as a default browser option in the start menu options, as in the past. I was able to set associations for file extensions as directed by Windows help, but it will not allow me to change associations for protocols, meaning other programs referring to HTML, etc. will not open Brave by default.

- Platform (Win7, 8, 10? macOS? Linux distro?): 
Windows 7 (Enterprise, SP1, 64-bit) 

- Brave Version (revision SHA): 0.13.4

- Steps to reproduce:
    1. Chose "Make Brave my default browser" on update
    2. Confirm that Brave is default browser in preferences
    3. 
    
- Actual result:
Old browser continues to open default when called
- Expected result:
Brave opens all web-related files and protocols
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![2017-02-16 06_30_48-](https://cloud.githubusercontent.com/assets/20600094/23025245/1f152a8a-f412-11e6-9ce6-676511d77741.png)

- Any related issues:

**Comment by Liunkae** [comment]
Maybe related issue: #5246.

**Comment by jhaney5930** [comment]
I don't know if I'm having the same issue, but I just downloaded the windows.exe file for Brave, and Windows 10 is not even recognizing it as an installed app, much less allowing me to set it as my default browser. I eventually figured out where it was installed so that I could create a desktop shortcut to launch it, but it would be nice to have it as a default browser instead of Microsoft Edge.

I've spent a couple hours searching to see if this issue has already been raised, and I'm tired of trying to figure out the magic keywords for my problem. If you want me to create a new issue, I'm happy to do so. Or if you think it belongs as part of this issue, that's fine, too.

**Comment by bsclifton** [comment]
Moving to 0.13.7

**Comment by bsclifton** [comment]
@teagueamania If you're a more technical user and are comfortable with regedit, I'm curious if you have entries under `HKEY_CURRENT_USER\SOFTWARE\Classes\BraveHTML`

If you don't have values OR you aren't familiar with regedit (or don't feel comfortable trying that out), let's try this:
- right click the installer for Brave
- pick "run as administrator" and grant permission
![screen shot 2017-03-28 at 1 08 14 am](https://cloud.githubusercontent.com/assets/4733304/24395103/4b3eccbe-1353-11e7-8f25-a0ab1058efa8.png)

**Comment by srirambv** [comment]
@bsclifton This might help. No reg entries under `HKEY_CURRENT_USER\SOFTWARE\Classes\BraveHTML`
![image](https://cloud.githubusercontent.com/assets/17010094/24395247/e9ef7afa-1396-11e7-8fed-f679e4cf766b.png)

**Comment by bsclifton** [comment]
@srirambv sorry- I had some bad wording there.  I can see from your screenshot that you have subkeys... specifically the `shell > open > command` one 😄

**Comment by bsclifton** [comment]
Marked as `needs investigation` and removed milestone. If you are experiencing this issue, please let me know and I'd love to help debug. Thanks 😄

**Comment by lukemulks** [comment]
I've just reinstalled Windows10 (last night) - and set my default browser to Brave. 

My default browser was just changed from Brave to Edge by Windows (after installing 0.14.2, rprvw3

However, there are other things going on in Windows that are having me suspect that this is more of a **Windows OS behavior** than something we may be able to resolve in Brave. 

We need to see if other browsers are doing this same thing when they are set as the default browser, because there are some additional points where the OS is trying really hard to get the user to stick with Edge. 

Here are some examples that have me leaning this direction. Note: Some of these used to happen intermittently, but I'm now seeing them come up more often (right after re-installing the OS). 

Also, I'm really starting to wonder if Microsoft has setup Windows to heavily prompt the *new* user, or *fresh OS install* more frequently immediately after they begin using the OS, and then back off later on. Just a suspicion, but seems to be fitting a pattern as this is the 4th time I've done a Windows 10 install on various machines, and these prompts seem to happen more often right after I update. 

After Edge was made the default browser by Windows (after I had made brave the default)
![win10-default-browser-change-04122017](https://cloud.githubusercontent.com/assets/8979240/24969544/fbd1bbfe-1f65-11e7-9bf3-254a73ccd21d.PNG)

Windows is asking me if I'm really sure if I want to do this, then presents a "try it out" button larger than the "switch anyway" link to make the decision I actually want to make. 

Also, this behavior is occurring, even when I have Brave set as my default, if I click a web URL from Slack, Windows 10 asks me if I really want to use my default browser, instead of Edge (ridiculous!): 

![win10-double-sure-default-browser-04122017](https://cloud.githubusercontent.com/assets/8979240/24969634/40603bf6-1f66-11e7-93db-d72820d758f1.PNG)

Note that my default browser is clearly set to Brave in the background of that image. 

Just adding here because we're going above and beyond to try and get a user's default browser choice to be respected by the OS, and these moves by Windows are really counter to letting the user be the operator of the Operating System.

**Comment by bsclifton** [comment]
@lukemulks thanks for the report- those nag screens are incredibly annoying and unprofessional of Microsoft

The good news is: the fix for this issue is only in 0.14.2.  Since you went from 0.14.1 to 0.14.2 (knowing what I know), it makes sense why the browser was reset.  Basically the value under `HKCU > Classes > BraveHTML` was modified. This shouldn't happen going forward 👍

**Comment by lukemulks** [comment]
Updating to include the chronological order of operations for the issue noted above. 

1. Reinstalled Windows 10 (last night)
2. Install Brave 0.14.1, prod release. (last night)
3. (This morning) Clicked a URL from the Windows 10 Slack Desktop app, expecting to open in Brave, since it is my default browser. Instead,  I got the: "are you sure you want to open with your default browser selection, try Edge" prompt - where I have my Brave default visible in the bg.
4. Install Brave 0.14.2 prvw3
5. Test awesome things like tab tear off.
6. About 10min later, Windows resets to Edge.
7. I go to set default to Brave, get the switch anyway prompt.

**Comment by bsclifton** [comment]
There isn't enough information here to investigate

If anybody experiences the problem where Brave is not shown as an option for default browser (after it's installed), please re-open this issue and include information that may help narrow down the issue (what does show up? screenshot might be helpful. Did you try re-installing by right clicking installer, picking install as administrator?)

**Comment by lukemulks** [comment]
Confirming that after the latest windows 10 cumulative update, Brave has remained my default browser (has not been switched to Edge) for 24hrs. 

This is a really good sign. Expectation, given the past history, was for Windows to switch to Edge. 
cc: @bsclifton @luixxiul for visibility.
