### ISSUE TITLE
Refactor SwitchControl with Aphrodite

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7321]
## Test plan

https://github.com/brave/browser-laptop/pull/11954#issue-273803005

----

Refactor SwitchControl with Aphrodite

- Any related issues: #7320

**Comment by petemill** [comment]
I'm happy to attempt this one since the SwitchControl and all its uses are fresh in my mind.

However, there are a couple of issues that I think also require a refactor for switchControl that would make this task easier and cleaner:

- Style overrides of switchControl's elements in other consuming components. Should consider converting to true/false props on switchControl (i.e. `compact` or `primary` mode, etc) and let the component contain all the css variations itself in order to avoid fragmented css definition and future regressions.

- Poor accessibility support. The component cannot be 'tabbed' to and the keyboard cannot be used to toggle the checked state. One way I have fixed this in the past is by using an underlying, but hidden, `<input type='checkbox' />` and the pseudo `:checked` css selector.

In your experience in this codebase migrating from less -> aphrodite for the shared components, is it acceptable to do a combined overall refactor, or just to do the css conversion, and then more of a functional one after, separately?

**Comment by luixxiul** [comment]
Hi @petemill, 

> In your experience in this codebase migrating from less -> aphrodite for the shared components, is it acceptable to do a combined overall refactor, or just to do the css conversion, and then more of a functional one after, separately?

Converting to the props along with a11y support, migrating to Aphrodite, within one PR will make it quite huge and increase chance of regressions, so separating the tasks (ideally each task should have its own issue) is a better way, obviously.

Because visual regressions cannot be detected by webdriver tests and therefore it has to take some time for the PRs to be audited and merged (especially if changes and manual test plans are not well commented), I think the migration should be conducted step by step. It will also help the QA team to confirm the expected result can be reproduced on each platform.

To get started, I would recommend you to have a look at this document: https://github.com/brave/browser-laptop/blob/master/docs/style.md.

**Comment by petemill** [comment]
I'm preparing a PR based on your partial refactoring @luixxiul (thanks for that!) and including the following changes:
- migrate to aphrodite
- semantic props instead of css overrides
- accessibility / keyboard support

It makes sense to me to do it like this since the test plan is exactly the same check for regressions as just doing a small part of it, so saves having to do that multiple times and therefore reduces the risk of missing something.

Here's the new control before I replace the usages, with a preview of most unique uses: https://codepen.io/petemill/pen/YxrMEO?editors=0010

**Comment by luixxiul** [comment]
> having to do that multiple times

I am pretty sure that you would not have to worry about that. Please remember the QA team including me has usually more than 100 issues (often around 200 issues) to test within one release. Who cares adding another couple of issues to that? :-D It would be appreciated if you would avoid creating one gigantic commit with a bunch of diff lines. 

Thanks for your contributions and I'm looking forward to the next PRs! 👍

**Comment by luixxiul** [comment]
Also: I like the snippet and most of the controls there can be imported to `about:styles` ;-)

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
