### ISSUE TITLE
preferences don't work on linux

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#743]
#666 is still happening on linux

**Comment by bbondy** [comment]
CC @bridiver because it's probably contentScript not loading related.

Do ad insertions happen?

**Comment by diracdeltas** [comment]
yep, ad insertions work

**Comment by bbondy** [comment]
I think you must have had an old build of electron or something because I verified and content scripts aren't loaded.  So ad insertions not working with latest either.   This is also causing theme colors not to work on linux.  Path of the content script seems to be passed correctly 

> /home/bbondy/projects/brave/browser-laptop/node_modules/electron-prebuilt/dist/brave --type=renderer --no-sandbox --lang=en-US --node-integration=false --guest-instance-id=1 --enable-blink-features --content-scripts=file:///home/bbondy/projects/brave/browser-laptop/app/content/webviewPreload.js

@bridiver ca you take a look?
