### ISSUE TITLE
Linux: Keyboard Shortcuts Conflict With Gnome 'Workspace Grid' Defaults

### ISSUE THREAD

**Issue by inlandsee** [brave/browser-laptop#7446]
On Linux, Brave tab left and right keyboard shortcuts (Ctrl-Alt-L/R) conflict with Gnome 'Workspace Grid' defaults. The Gnome values can easily be remapped but this causes them to deviate from expectations.  

While this is not default Gnome behavior, Workspace Grid is a commonly used extension. I am not aware of any other conflicts than Brave. It would be nice to be able to remap Brave shortcuts to compensate.

Notes: 
1. Chrome uses Ctrl+(Shift)+Tab, Ctrl+PgUp/PgDn for this function

Expected result:
1. Ctrl-Alt-L/R switches workspace left, right

Actual result:
1. Brave tabs switch left-right when Brave is active

To reproduce:
1. Install Gnome Workspace Grid extension
2. Configure multiple Workspace rows
3. Launch Brave
4. Attempt to Navigate WS left/right using Ctrl-Alt-L/R
5. Workspace will not change, Brave will tab L/R

Notes: 
1. Chrome uses Ctrl+(Shift)+Tab, Ctrl+PgUp/PgDn for this function

Environment:
Fedora 25 / Gnome
Brave	0.13.4
rev	71d8ffc
Muon	2.56.4
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	linux
os.release	4.8.12-300.fc25.x86_64
os.arch	x64

**Comment by jpcima** [comment]
The shortcut Ctrl-Alt-Left/Right is present in many of Linux desktops which have workspace switching.
I've tried only on MATE desktop and I can say this problem is also present there, as the browser and desktop fight for taking control of this keyboard shortcuts.
It's a strong annoyance with running Brave browser, that it ruins the keyboard workflow and is so uncomfortable for programming.

Can it have a special exception to disable this shortcut pair in Linux OS?
https://github.com/brave/browser-laptop/blob/fdfb0b55d7f6399e71441f884f23a22ea64d84d0/app/localShortcuts.js#L22-L23

**Comment by kbsali** [comment]
@bsclifton won't fix? This is a blocker as far as i'm concerned! I won't be able to switch to Brave until this is fixed! :)

**Comment by bsclifton** [comment]
@kbsali it's `wontfix` with our current code-base, but it may already be fixed with `brave-core` (our new code-base for Desktop).  You can download and give it a try here:
https://brave.com/download-beta

For Linux, the link should go to install instructions. Once you have it installed, you can import your existing settings from Brave. Let us know if it works and I'll add a `fixed-with-brave-core` tag on this issue 😄

**Comment by kbsali** [comment]
Hi @bsclifton ,

sorry for the late update! I've tested brave-beta and it works perfectly well! :) Thanks a lot, I've been working with it for a few days already and so far so good! :+1:
