### ISSUE TITLE
Publishers are auto included even when auto-include sites is turned off

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7451]
## Test Plan
- Enable payments in settings
- Disable auto-include switch
- Visit brianbondy.com in a new tab, site is added in the list and is not included

## Automated test plan
- `npm run test -- --grep="auto include"`

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Publishers are auto included even when auto-include sites is turned off

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	0e68342

- Steps to reproduce:
    1. Enable payments in settings
    2. Disable `auto-include` switch 
    3. Visit brianbondy.com in a new tab, site is added in the list and is auto included
    
- Actual result:
Publishers are auto included even when auto-include sites is turned off

- Expected result:
If auto-suggest is `off` then it should be set as disabled

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/23514069/0d3e8872-ff5e-11e6-8e81-32059b05fff3.png)

- Any related issues:
#7429
cc: @mrose17 @cezaraugusto

**Comment by cezaraugusto** [comment]
Stepping back and assigning @mrose17

**Comment by mrose17** [comment]
@cezaraugusto - i think i understand what's going on here in `enabledForSite` at https://github.com/brave/browser-laptop/blob/master/app/renderer/components/preferences/ledgerTable.js#L51 the default `return true` should return the value of  `! settings.advanced.hide-excluded-sites` (not the exact syntax).

does that make sense to you?

**Comment by NejcZdovc** [comment]
@cezaraugusto also we need to change it here https://github.com/brave/browser-laptop/blob/master/app/renderer/components/preferences/ledgerTable.js#L101, we are sending `true` as default value

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/auto-include-button-for-brave-payments-not-functioning-correctly/1674

**Comment by NejcZdovc** [comment]
@mrose17 I fixed this auto include problem, but I think that we have other problem as well. We don't set `ledgerPayments` to `false`, when we have auto include `off`. Which it the root cause for this "problem":
![7](https://cloud.githubusercontent.com/assets/9574457/23848409/75679944-07d7-11e7-8c33-f03b5acf6feb.gif)

We don't set a value for the `ledgerPayments`, but we set default value based on auto include setting. This means that when you toggle auto include sites include changes based on that. 

I would expect that if you have an auto include off, this should be saved into the store and can't be effected with a later change of auto include checkbox.

What do you think?

**Comment by mrose17** [comment]
@NejcZdovc - i agree!

cc: @bsclifton

**Comment by bsclifton** [comment]
Sounds good to me! I'll hold off on the merge until this is ready 😄
