### ISSUE TITLE
When maximized, hitboxes seem off for buttons and address bar

### ISSUE THREAD

**Issue by acvanzant** [brave/browser-laptop#7641]
covering both:
- Back/Forward Buttons clickable area does not extend to the edges of the button.
- Unable to focus on address bar properly

______

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Clicking the back or forward buttons didn't seem to work consistently.  I discovered that clicking near the edge was not working. I had to click in the very center of the button. It seems that the clickable area of the button is not the whole button.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7 64

- Brave Version (revision SHA):
1db81cb

- Steps to reproduce:
    1. Browse to two pages.
    2. Attempt to go back by clicking the back button but click as close to the edge of the button as possible.
    3. Notice nothing happens.
    4. Click in the center of the button to confirm the button is working.
    
- Actual result:
Clicking the button works if you click nearer to the center.

- Expected result:
The button should work if you click it anywhere in the graphical button.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I believe so. I've just installed Brave.

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

#5679

**Comment by acvanzant** [comment]
I believe this issue also affects the 'Add Tab' button on the tab-bar.

**Comment by acvanzant** [comment]
It seems the refresh button also does this.

**Comment by SethClydesdale** [comment]
I have the same issue, it appears to occur on every button ( back, forward, refresh, home, shields.. ), save for the window options ( min, max, close.. ). I created an image that shows the clickable area on the forward button. Note that this clickable area seems to vary for each button, perhaps based on the icon ? Although, clicking near the very bottom of all the buttons doesn't work, that's one thing they all have in common.
![](https://i58.servimg.com/u/f58/18/21/41/30/brave-11.png)
red : non-clickable
green : clickable

You can tell if you're within the clickable area, because the tooltip pops up, if the tooltip doesn't pop up, then you're not within that area. I can't tell you how many times I've click these buttons, only to realize there was no response, because I didn't click the right area.

OH one more thing : If you double click or hold down and drag your mouse within the non-clickable area, you can resize and drag the window. I suppose because you're clicking the title bar area and not the button.

Extra note : I'm running Win10, same rev of Brave

**Comment by SethClydesdale** [comment]
I just noticed that it might be related to the window state. When I have Brave maximized this occurs, but if I leave Brave windowed I can click the buttons without the aforementioned problem.

**Comment by luixxiul** [comment]
I can reproduce the issue with the window maximized. @bsclifton would you please check it out?

**Comment by luixxiul** [comment]
@jonathansampson reported that not all of the URL bar area is clickable. I think these issues are related.

> Mouse needs to be nearly 50% up the URL bar in order to click-select the contents.

**Comment by SethClydesdale** [comment]
@luixxiul It's definitely related to this issue, because I've also had trouble clicking the address bar while Brave is maximized. I forgot to mention that in my last reply, but it's good someone else caught it.

**Comment by SethClydesdale** [comment]
I just noticed that the little lock for HTTPS is nigh impossible to click while the window is maximized. I'm assuming this is related to the current issue, so I thought I'd mention it.

**Comment by bsclifton** [comment]
+1 from users @ChubbyNinja and @hexigen via https://github.com/brave/browser-laptop/issues/8176

**Comment by bsclifton** [comment]
My hunch is that this problem is in the Electron/Muon code. The client rect is likely wrong because of border calculations. The fixes I have in mind should also fix https://github.com/brave/browser-laptop/issues/5159

My first step would be to pull in https://github.com/electron/electron/pull/9140 from upstream electron into Muon

**Comment by bsclifton** [comment]
possibly related: https://github.com/brave/browser-laptop/issues/7215 and https://github.com/brave/browser-laptop/issues/7770

**Comment by ChubbyNinja** [comment]
@bsclifton according to http://dpi.lv/ it's 190 DPI scaling would be 100% as i have not altered anything like that, hope this is helpful and goodluck!

**Comment by bsclifton** [comment]
+1 from earlier report by @Zuzu-Typ https://github.com/brave/browser-laptop/issues/6445

**Comment by TheJare** [comment]
FYI I have noticed the wrong non-clickable areas behave like the title frame, i.e. a double click on what should have been a UI element (like the url bar) instead restores the window to non-maximized state.

The same happens with the timing information (little blue text) embedded inside the right side of the address bar, but this may be intended (wrong choice IMHO) and unrelated to this bug since it happens in both maximized and restored window states.

This drives me crazy. :)

**Comment by bsclifton** [comment]
Also happens with tab sets: https://github.com/brave/browser-laptop/issues/8292

**Comment by Jacalz** [comment]
Comfirmed fixed in latest master :+1:
