### ISSUE TITLE
Brave closes in seconds on Windows

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7677]
**Describe the issue you encountered:**

https://community.brave.com/t/brave-remains-open-for-only-a-second/1032?u=suguru

> Brave is installed on my PC, and I love it. Today we had to shut off the PC in order to do some minor electrical work. We shut off everything at the surge protector bar. After the work was done, I turned everything on with a flip of the switch on the surge protector. Now when I go to the PC and click on the Brave icon, it opens for a second (perhaps less) and closes again. Chrome is working fine, though.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
I can't reply to the post on Community, but I'll reply here

@luixxiul when users are experiencing this, can we please have them try to open the Brave.exe manually?  This would involve:
1. Windows key + R to open start/run box
2. Type `%userprofile%\AppData\Local\brave` and hit enter
3. Double click the folder for the current version
4. Double click the Brave.exe

At this point, it should work (the previous problem being something wrong with squirrel auto-updater, which uses a stub EXE)

The root cause for this may be a bad shortcut path.  Before, it would have "Update.exe" with a "--" param, but then this was switched to the stub "brave.exe" executable

cc: @aekeus

**Comment by luixxiul** [comment]
I replied on that topic, waiting for their reply

**Comment by luixxiul** [comment]
Closing as stale.
