### ISSUE TITLE
1Password has different behavior for context menu than extension button

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7787]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you visit a site which has a login prompt and right click the username textbox and choose "1Password", it'll show results like this:
<img width="480" alt="screen shot 2017-03-19 at 10 41 22 pm" src="https://cloud.githubusercontent.com/assets/4733304/24089569/46458fc2-0cf5-11e7-983e-1dd4435757b0.png">

Notice that no sites are shown.  If you instead click the extension button in the top right (next to the lion), you'll get a filtered set of results which are relevant
<img width="387" alt="screen shot 2017-03-19 at 10 42 53 pm" src="https://cloud.githubusercontent.com/assets/4733304/24089584/6efd61e2-0cf5-11e7-9180-cfee53e1a346.png">

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 

- Brave Version (revision SHA):
0.14.0 preview 3

- Steps to reproduce:
    1. Launch Brave and set default password manager as 1Password
    2. Visit GitHub.com in a new session tab
    3. Click the extension button in the top right
    4. Notice the behavior. Dismiss the context menu
    5. Right click the username field on the page and pick "1Password" from the context menu
    6. Notice you get a generic empty result set. You can drill down and find a login, but none are suggested.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @bradleyrichter

**Comment by vkuznet** [comment]
Hi, I can partially confirm this behavior since I have different initial setup. I don't see 1password extension, but I learnt from https://discussions.agilebits.com/discussion/61396/1password-support-in-brave-browser-see-agilebits-reply-on-april-9-for-details that Brave has build in 1password and people suggested that it can be activated via Option-Command-\ shortkey (on OSX). Indeed, I can do that and I can see 1password menu similar to first posted screenshot. So I do see 1password, but I don't see suggestion for site I'm in. Also, I found that if I search for the login in 1password and click on it, it does not actually fill in the user/login into required field on a web page, instead it opens up new window and append my login info as parameters to the URL. Therefore I would add to this issue that it 1password extension does not work properly to fill out and login automatically into the site.

**Comment by bsclifton** [comment]
Closing as `wontfix`. This version of the browser is deprecated. If this is still happening with the new version of Brave (Brave Core), we can open an issue there:
https://github.com/brave/brave-browser/
