### ISSUE TITLE
In order for LastPass to fill into basic authentication dialogs, you need to install the binary version of LastPass for Chrome.

### ISSUE THREAD

**Issue by deXterbed** [brave/browser-laptop#7789]
Probably a typo in error message, it should say Brave!

![image](https://cloud.githubusercontent.com/assets/1491315/24095058/62cea322-0d81-11e7-9791-770822c31eff.png)

**Comment by jabowery** [comment]
I clicked on the prompt to download the binary version, executed it, apparently installed it because it prompted for master password and accepted it, opening the vault under Brave.

However, reentering the site that triggered the demand for basic authentication resulted in the same prompt to download and install the binary version.  This, even after quitting brave and restarting.

**Comment by dinks** [comment]
Not related to this (may be a bit). I was trying to create a Secure Note on LastPass with an attachment and it asked me to download and install the binary version. I installed it and then it restarted Chrome and Firefox (not Brave). I still cannot add attachments anyway.

**Comment by bsclifton** [comment]
Should be fixed with our developer channel release
https://brave.com/download-dev
