### ISSUE TITLE
When re-launching after maximized, window cannot be maximized again once restored down

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7825]
**Describe the issue you encountered:** When re-launching after maximized, window cannot be maximized again once restored down

- Brave Version (revision SHA): 64b381a

- Steps to reproduce:
  1. Launch Brave and maximize the window.
  2. Quit and relaunch Brave again
  3. Click "Restore down" of the caption button
  4. Click the button again
    
- Actual result: nothing happens
  ![offset](https://cloud.githubusercontent.com/assets/3362943/24180880/d1b87e32-0efa-11e7-8387-e2654e56ed7f.gif)

- Expected result: the window should be maximized again

- Any related issues: #7664

**Comment by bsclifton** [comment]
I believe this was caused by https://github.com/brave/browser-laptop/commit/494b94410df2bf5c20291fc693ccd963788d8827#diff-05d099af3c7a156e5d741630c31670d0. It didn't present an issue though because another regression prevented the state from being saved:
https://github.com/brave/browser-laptop/commit/6d722101025835ee4c92403901ee6d2cfe2fedde

**Comment by luixxiul** [comment]
It also disables the grabbing the top edge of the window, after maximizing, restarting and restoring down.

**Comment by bsclifton** [comment]
@luixxiul I confirmed this has been a bug since 0.13.0 😄 Adding release notes include tag
