### ISSUE TITLE
bitwarden: chrome.windows.onFocusChanged not supported

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7830]
bitwarden: Autofill from context menu doesn't fill the login credentials

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	64b381a

- Steps to reproduce:
    1. Enable bitwarden password manager from settings
    2. Visit the site for which credentials is stored
    3. Right click->autofill->select stored credentials, doesn't autofill
    
- Actual result:
Autofill from context menu doesn't fill the login credentials

- Expected result:
Should autofill the credentials

- Screenshot if needed:
![bitwarden](https://cloud.githubusercontent.com/assets/17010094/24194388/d01d8994-0eed-11e7-9d7e-06dd32e73951.gif)

- Any related issues:
https://github.com/brave/browser-laptop/issues/4776#issuecomment-288292824
cc: @kspearrin

**Comment by kspearrin** [comment]
Related code for this function: https://github.com/bitwarden/browser/blob/master/src/background.js#L305

**Comment by bsclifton** [comment]
If we're not able to resolve this, we'll have to hide this in our UI for now (and create a follow up task to re-enable in the future).  I'm not sure about next steps for debugging ☹️  Help needed

**Comment by kspearrin** [comment]
@bsclifton If there was a reliable way for me to detect brave I could add some conditionals around this feature.

Additionally, what is the method for debugging the background page for a web extension in brave? I could try to take a look at what is happening. This works fine in all of our other browsers.

**Comment by bsclifton** [comment]
@kspearrin we have a new preview release which you can check out:
https://github.com/brave/browser-laptop/releases/tag/v0.14.0dev-Preview7

Here's the PR where the functionality was added https://github.com/brave/browser-laptop/pull/7895. There are steps shown on how to navigate to the background page. This *should* pop open the dev tools

cc: @jonathansampson, @bridiver

**Comment by kspearrin** [comment]
@bsclifton The issue is that an unrelated JS error is happening higher up in the background page and therefore is not allowing code further down to execute/initialize (in this case, the context menu code on lines 305). This will cause a lot of functions in bitwarden not to work since they are not initialized as well.

![image](https://cloud.githubusercontent.com/assets/1190944/24366658/c11aad52-12e7-11e7-9304-9b6b783d6edc.png)

> Uncaught TypeError: Cannot read property 'addListener' of undefined

Is this API not available in brave? https://developer.chrome.com/extensions/windows#event-onFocusChanged

**Comment by bsclifton** [comment]
@kspearrin thanks for digging in! We indeed do not have support for that... yet. For reference, we currently have two other extensions which need that supported:
https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20chrome.windows.onFocusChanged%20

Since there is additional work needed on our side, I'll hide this for now and create an issue for re-enabling it once this issue is resolved

**Comment by kspearrin** [comment]
@bsclifton I think this is supported now? https://github.com/brave/browser-laptop/issues/4760

**Comment by jonathansampson** [comment]
@kspearrin Indeed it is :)
