### ISSUE TITLE
F6 does not jump to URL - previous issue #4464

### ISSUE THREAD

**Issue by MohnJadden** [brave/browser-laptop#7878]
- Did you search for similar issues before submitting this one?
Yes, it only references the original issue, 4464.

- Describe the issue you encountered:
Pressing F6 should jump to the URL entry bar and select all text in the bar.  This does not happen - nothing happens upon pressing F6 at all.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 Enterprise.

- Brave Version (revision SHA):
1db81cb

- Steps to reproduce:
    1. Press F6
    2. Attempt typing (in case it jumps but doesn't highlight the URL)
    3.
    
- Actual result:
Nothing happens

- Expected result:
All text should be highlighted, ready to type in a new URL. 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, this was done in a brand new Brave install on a machine that never had Brave before.

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by jonathansampson** [comment]
This was a minor regression, fixed with https://github.com/brave/browser-laptop/commit/5a889ccd6198906537f0c29d4b28067292a4ef78#diff-5fdd9f55221fe32ba22dea6484d4135c. I'm currently using https://github.com/brave/browser-laptop/commit/64b381abf3cbe91ec6ff007035c13100102d617b, and F6 works as expected.
