### ISSUE TITLE
Screen all blurry

### ISSUE THREAD

**Issue by TheSaltyJ** [brave/browser-laptop#7884]
Hey Guys

I would like to use the Brave Browser, however, it gets all blurry all the time (not only websites but also the preferences site). Once I move the mouse, the places where the mouse goes get correctly rendered, but again get blurry when not moving.

These are the setup: I am on w10

Brave	0.13.5
rev	1db81cb
Muon	2.56.8
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	win32
os.release	10.0.14393
os.arch	x64

https://drive.google.com/file/d/0Bzn5alBqk8OYa2tucHQ3M1VMVms/view?usp=sharing
https://drive.google.com/file/d/0Bzn5alBqk8OYVW5sbURFOHZUZHM/view?usp=sharing

I use two monitors, maybe this is the issue (issue is on both screens)?

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/two-major-problems/4989

**Comment by LaurenWags** [comment]
+1 from community using Windows10, Brave 0.18.14 - https://community.brave.com/t/when-watching-videos-or-any-movement-on-screen-text-gets-very-blurry/5670

**Comment by luixxiul** [comment]
+1 from here https://community.brave.com/t/i-got-a-blurry-font/369/20?u=suguru

![](https://cdn-standard2.discourse.org/uploads/brave/optimized/2X/3/32108c744c32e67d764593aca3d9ce10a7ed1484_1_624x500.png)

**Comment by thelinuxlich** [comment]
still happening in Windows 10 with 0.19.66 version...unusable :(

**Comment by bsclifton** [comment]
@thelinuxlich what DPI are you using? 125%? 150%?  As a test, could you try going to 100% DPI and confirming it looks correct (after that, you should switch back of course).  Testing this would help us narrow down the problem (I've solved several DPI related bugs in the past)

**Comment by bsclifton** [comment]
For folks experiencing this issue, here are two things you can try:

1. If you right click the shortcut for Brave and pick properties, you can go to the compatibility tab. There, check the box for override scaling and pick "System" instead of application
![image](https://user-images.githubusercontent.com/4733304/39228818-cf8c7d30-4814-11e8-89c1-78253b5ff111.png)


2. If the above doesn't work, try editing your shortcut for Brave. We can add extra parameters after the "Brave.exe" part in the target field: --high-dpi-support=1 --force-device-scale-factor=1
![image](https://user-images.githubusercontent.com/4733304/39228846-e87929ce-4814-11e8-9aa7-fa1029d2c6ad.png)
