### ISSUE TITLE
New private tab has a blank page favicon and NewTab text is not visible

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7912]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
New private tab has a blank page favicon and NewTab text is not visible

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	61b6b6b, b4289c0

- Steps to reproduce:
    1. Do a clean install of 0.14.0 preview 7
    2. Open a new private tab via shortcut/long press on + button
    3. Tab has a blank page favicon and the tab title `NewTab` is not visible
Issue from preview 6 onwards
    
- Actual result:
New private tab has a blank page favicon 

- Expected result:
Should not have the favicon

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24349156/121e637c-12d6-11e7-9c20-6688c14cbd70.png)

- Any related issues:
cc: @cezaraugusto

**Comment by bbondy** [comment]
This is because of the changes here:
https://github.com/brave/browser-laptop/commit/17b7cbe4c4bba688cb066cb69f692416462544ad

The changes are good but it causes a problem since we have an outstanding bug where about: pages do not load in private tabs.

Options are:
1. Get private tabs to work on private tabs.
2. Add some hacky code for about: pages only for the did-fail-provisional-load event

In particular e.currentURL will be blank, but we could hack it to be the about: page if it is a private tab. 

@bridiver thoughts? Would it be hard to get private tabs working with about: pages?

**Comment by bbondy** [comment]
I'm going to try adding an API so we can have private tab extensions
