### ISSUE TITLE
sync sometimes shows CSP error

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7965]
right now the CSP only allows connections to `https://brave-sync.s3.dualstack.us-west-2.amazonaws.com`, but @alexwykoff is seeing sync attempting to connect to `'https://brave-sync.s3.dualstack.us-east-1.amazonaws.com`

cc  @ayumi

**Comment by ayumi** [comment]
some more info.. this has happened to me sporadically while updating my network configuration. it seems to happen when the network is down.

Repro:
1. Open Sync background page/script by going to chrome-extension://cjnmeadmgmiihncdidmfiabhenbggfjm/_generated_background_page.html
2. Go to Console and observe Sync logs.
3. Disconnect internet. Wait ~1 min.
4. Errors

For example this fails:
`OPTIONS https://brave-sync.s3.dualstack.us-west-2.amazonaws.com/?list-type=2&max-ke…-after={ stuff ... } net::ERR_INTERNET_DISCONNECTED`

Then right after:
`Refused to connect to 'https://brave-sync.s3.dualstack.us-east-1.amazonaws.com/?max-keys=0' because it violates the following Content Security Policy directive: "connect-src 'self' https://sync.brave.com https://brave-sync.s3.dualstack.us-west-2.amazonaws.com".`

There is a bit in the AWS JS SDK which connects with `maxKeys = 0` to determine the bucket region. us-east-1 is the default region. This might be generating the failing request.
https://github.com/aws/aws-sdk-js/blob/b2016fa31d9bc719ea447806d27509e6bc24c863/lib/services/s3.js#L567

Despite several of these errors Sync resumed working soon after and successfully sent records so this may not be a problem.
@alexwykoff can you try to confirm (get the error, then test if syncing works right after?)

**Comment by alexwykoff** [comment]
So, I have tried to repro and am experiencing something pretty odd. 
1. Cleaned profiles on 2 machines
2. Pyramid 0 - started new sync group
3. Pyramid 1 - added to sync group
4. Pyramid 1 - turned off wifi (killed all network connections)
5. Pyramid 0 - added one bookmark and one folder
6. Pyramid 1 - turned wifi on
7. Pyramid 1 - after ~ 20 minutes, still no bookmark or bookmark folder

**Comment by diracdeltas** [comment]
seems like there are no downsides to adding `us-east-1` for now

**Comment by bsclifton** [comment]
moving to 0.14.1
