### ISSUE TITLE
Any thought on VPN?

### ISSUE THREAD

**Issue by DevShekhawat7** [brave/browser-laptop#8001]
Have you guys considered adding VPN? Since it's one of the most fundamental part of internet privacy.

**Comment by srirambv** [comment]
There is a request for VPN extension to be added. You can check the request here 
https://github.com/brave/browser-laptop/projects/1#card-1579787

Closing the issue for now. We can continue the discussion and reopen if required.

**Comment by BrendanEich** [comment]
VPN is not a fundamental part of privacy, since it moves high trust onto the VPN and its ISP in the region where the proxy decrypts and routes your traffic. There is no silver bullet. We are looking at VPNs and we already work with Private Internet Access for IP address masking in the Brave Ledger. Agree with @srirambv that an issue does not help here.

**Comment by drcayman** [comment]
@srirambv when will this plugin be made?
