### ISSUE TITLE
Installer on Windows 7 fills the memory

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8005]
**Describe the issue you encountered:**
https://community.brave.com/t/closed-win7-installer-malfunction/1906/4
<blockquote>
Hi there,

I have downloaded the setup package for Windows x64 and started it. The installer used all cores of the processor extremely, filled up my 32 GB RAM with a tempo of 60 MB/sec and gave only a white screen and a fast frozen computer as a result.

Tried the 32-bit version and happened the same.

Config:

Dell Precision T1700
Intel Xeon E3-1225 v3 3.2 GHz
32 GB RAM
Win7 Enterprise x64 SP1

Any idea?
</blockquote>

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7

**Comment by jonas0515** [comment]
Windows 7x64 Enterprise
Brave 0.13.dev
Admin account can install Brave browser only for himself. There is no question, where should it installed to, if any desktop icon is needed, and in which start menu should it to be found. The installed brave cannot use any other user.
If in a user profile is it installed as an admin, it takes the full processor in service, and with cc. 60 MB/sec fills the RAM - in my case 32 GB. Clicking on the brave icon on the task bar gives a full white screen, the computer hangs. The issue is consistent.

**Comment by luixxiul** [comment]
I'm going to close the issue as stale. Let's reopen if we still experience the issue and have steps to reproduce it 👍
