### ISSUE TITLE
bookmark name is not stable

### ISSUE THREAD

**Issue by Attrash-Islam** [brave/browser-laptop#8039]
- Did you search for similar issues before submitting this one?

Yes. But I didn't find something like this

- Describe the issue you encountered:

Unstable bookmark name
![brave_bug_bookmark_name_changed](https://cloud.githubusercontent.com/assets/7091543/24587938/d7c6c6b4-17c7-11e7-8680-0bfe63d4c8f8.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?):

Linux Mint 18.1

- Brave Version (revision SHA):

0.13.5

- Steps to reproduce:

See the GIF above (Just add YouTube for bookmark with YouTube as a name)
    
- Actual result:

bookmark name get changed when navigating 

- Expected result:

To be stable as saved in the first time

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes. Mine is fresh

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

By the GIF steps (Always)

- Extra QA steps:

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This is a weird one- when a bookmark is saved, the title gets saved too.  If the page ever updates its title (ex: same URL but different title... as shown above), the bookmark will also update itself (which is not what most users would expect).

This issue should be solved when https://github.com/brave/browser-laptop/issues/6585 is closed out.  Since this is covered by that issue, I'll close this one out as a duplicate

**Comment by Attrash-Islam** [comment]
I figured out that the bug is produced in Chrome!! Maybe it's not a Brave Browser bug

**Comment by NejcZdovc** [comment]
@Attrash-Islam it was our bug and we fix it. Maybe Chrome has a similar one :smiley:

**Comment by Attrash-Islam** [comment]
:rofl: Great to know! I thought that you have the same base webview.. Thanks for your response
