### ISSUE TITLE
Tearing off a tab causes the torn off site to display the wrong URL

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8251]
Steps to reproduce

1. Have one window open with two tabs:
- https://github.com/brave/browser-laptop/commits/dev-channel
- https://github.com/brave/browser-laptop/commits/master
2. Set some pinned tabs, if you don't already have any:
- gmail.com
- twitter.com
3. make the window take up half of your screen width
4. Drag the tab that has master out of the window. This creates a new window for the tab
5. Notice the URL for the new tab has the URL of the last pinned
6. Switch between the pinned tab and the main tab. Notice the URL stays the same
7. Reload the tab (the not pinned one) and it will show the proper URL again

**Comment by lukemulks** [comment]
FWIW @bsclifton & @bbondy I am unable to repro this in Windows 10 - 64bit

Tearoffs working well, and displaying the URL for the tab that has been torn off. 

I've tried it with authenticated domains (Gmail), and Twitter (unauthenticated), and both display the proper URL in the tab that has been torn off. 

Profile info below for reference: 

```

Brave: 0.14.2 
rev: f07c1421b982ef66e4cd369e8d928a3f9b19ffd5 
Muon: 2.57.9 
libchromiumcontent: 57.0.2987.133 
V8: 5.7.492.71 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64

```

**Comment by bsclifton** [comment]
Reproduced on Windows and also found another interesting bug... will share a picture in a moment

**Comment by bsclifton** [comment]
![tear-off](https://cloud.githubusercontent.com/assets/4733304/24979346/9de1971c-1f88-11e7-9850-690368f22af3.gif)

**Comment by lukemulks** [comment]
Wild

64bit or 32bit Windows? 

I've just tried reproducing again, and am seeing the appropriate URLs.

**Comment by bsclifton** [comment]
@lukemulks 64-bit

**Comment by bbondy** [comment]
I can reproduce np, @lukemulks maybe you didn't pin first? No worries in any case I have a fix I'm about to push.

**Comment by lukemulks** [comment]
That was it. @bbondy @bsclifton I hadn't pinned, only tore off and
re-attached, and confused "pinned" with "re-attach".Sorry about that!

Awesome work on tearoff tabs!


On Apr 12, 2017 4:31 PM, "Brian R. Bondy" <notifications@github.com> wrote:

I can reproduce np, @lukemulks <https://github.com/lukemulks> maybe you
didn't pin first? No worries in any case I have a fix I'm about to push.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brave/browser-laptop/issues/8251#issuecomment-293735730>,
or mute the thread
