### ISSUE TITLE
Startup performance decrease when there are many bookmarks

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8356]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
After importing many bookmarks a multi-second slowdown was noticed for startup.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X

- Brave Version (revision SHA):
0.14.1 vs 0.14.2 ( https://github.com/brave/browser-laptop/commit/632a9bc130e5d452493e4aa20632bf691f1ababd )

- Steps to reproduce:
    1. With a clean profile, launch 0.14.1 without bookmarks, check the time.
    2. Import a large volume of bookmarks (test set used >6000), launch 0.14.1, check the time, measure the delta vs previous run. (take average of 3 runs minimum)
    3. With a clean profile, launch 0.14.2 without bookmarks, check the time. 
    4. Import the same large volume of bookmarks, launch 0.14.2, check the time, measure the delta vs previous run. (take average of 3 runs minimum)
    
- Actual result:
0.14.2 exhibited a 1.5-2 second slowdown on startup 

- Expected result:
Startup speed should remain near constant.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, however 0.14.2 rc2 has shown worse performance.

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
https://www.youtube.com/watch?v=vScmYPa8FU4

- Any related issues:
https://github.com/brave/browser-laptop/issues/7240

**Comment by srirambv** [comment]
Run on a clean Windows install

| 0.14.1 Without BM   | 0.14.1 With BM  | 0.14.2 Without BM    | 0.14.2 With BM |
| ---- | --- | --- | --- |
| 05.55s | 7.91s | 6.85s | 7.02s | 
| 05.15s | 7.15s | 6.44s | 7.55s |
| 05.02s | 6.41s | 6.47s | 8.14s |

**Comment by bsclifton** [comment]
I don't think the slowness is related to bookmarks.  @srirambv, per your own data above:

Run on a clean Windows install

| 0.14.1 Without BM   | 0.14.1 With BM  | diff |
| ---- | --- | --- |
| 05.55s | 7.91s | +2.36s | 
| 05.15s | 7.15s |  +2s |
| 05.02s | 6.41s | +1.39s |


| 0.14.2 Without BM    | 0.14.2 With BM | diff |
| ---- | --- | --- |
| 6.85s | 7.02s | +0.17s |
| 6.44s | 7.55s | +1.11s |
| 6.47s | 8.14s | +1.67 |

It seems that bookmarks load faster now actually.  The problem here seems instead to be that the loading time WITHOUT bookmarks has gone up ~1 second

**Comment by bsclifton** [comment]
Marking as `wontfix` since there doesn't seem to be a problem with bookmarks, per the above data
