### ISSUE TITLE
Webgl antifingerprint does not work

### ISSUE THREAD

**Issue by gameb0y** [brave/browser-laptop#8448]
Win7 x64, Dev Channel Beta v0.15.0dev-RC3 x86

![untitled](https://cloud.githubusercontent.com/assets/19530450/25313336/38eee112-2824-11e7-901a-0f9ff3e7e69b.jpg)

https://browserleaks.com/webgl

**Comment by NejcZdovc** [comment]
cc @diracdeltas

**Comment by bsclifton** [comment]
for some of our other tests, we always return the same hash (instead of no hash).  I confirmed that a different hash is returned on macOS and Windows 10; this is something we should be blocking

Assigning @diracdeltas for triage

**Comment by diracdeltas** [comment]
For me, WebGL fingerprint is blank (as expected), but "Report Hash" and "Image Hash" have hex values. The description says:

> Report Hash - A hash of entire WebGL Browser Report table, which contains a listing of all above WebGL capabilities and supported extensions. The hash is taken from the highest supported WebGL context dump
> Image Hash - A hash of the array of pixels created by drawing WebGL gradient shader. The drawing function borrowed from fingerprint2.js

It may not be surprising that Report Hash varies between operating system, since the table includes the user-agent. (So if the UA changes, the hash value necessarily changes, but the attacker doesn't get any new information.)

I'm curious if you are seeing OS-specific values for both hashes, or only "Report Hash".

**Comment by bsclifton** [comment]
@diracdeltas I'm seeing OS specific values for both report hash + image hash:
**windows**
![windows](https://cloud.githubusercontent.com/assets/4733304/25678121/7ce08a0c-2ffd-11e7-97f0-8905f7480777.png)

**macOS**
![mac](https://cloud.githubusercontent.com/assets/4733304/25678123/8186742c-2ffd-11e7-956d-469df984137c.png)

**Comment by diracdeltas** [comment]
Moving into 0.15.300 because this was actually a regression since Chromium 56, which introduced the WebGL2RenderingContext API.
