### ISSUE TITLE
History is not working for Sync

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8455]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When 'Browsing history' is toggled on for Sync, it should be synced. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X for either Pyramid

- Brave Version (revision SHA):
0.15.0 RC3 for Pyramid 0
0.14.1 (current prod) for Pyramid 1

- Steps to reproduce:
    1. Enable sync for both pyramids.
    2. Enable 'Browser history' sync for both pyramids.
    3. Chill for a good long time and check every now and then (20 minutes and counting).
    
- Actual result:
History is not synced. 

- Expected result:
History should eventually sync.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Haven't tried yet.

- Can this issue be consistently reproduced?
Haven't tried yet.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Pyramid 0:
<img width="1920" alt="screen shot 2017-04-23 at 5 46 08 pm" src="https://cloud.githubusercontent.com/assets/1434040/25318116/4c5398e6-284d-11e7-9116-96cda0825257.png">

Pyramid 1:
![screen shot 2017-04-23 at 5 30 21 pm](https://cloud.githubusercontent.com/assets/1434040/25318124/80157bf4-284d-11e7-815d-82177f5c91de.png)

- Any related issues:

**Comment by diracdeltas** [comment]
When you turn on syncing for history in pyramid 1, we do not sync history from pyramid 0 that was created before 'sync history' was turned on in pyramid 1. This was a design decision we made to limit bandwidth usage.

So the following should work:

1. turn on sync history in pyramid 0
2. turn on sync history in pyramid 1
3. go to example.com in pyramid 0
4. example.com should appear in pyramid 1

However, history entries in pyramid 0 that were created before "sync history" in pyramid 1 was enabled will *not* be synced to pyramid 1.

Maybe this should be documented, or we can add a switch to 'sync history since the beginning of time'.

**Comment by alexwykoff** [comment]
Working as designed. Thanks!

**Comment by diracdeltas** [comment]
thanks @alexwykoff, i will open a separate issue to handle syncing all history
