### ISSUE TITLE
Application slowness (when opening new tabs, loading a website)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8541]
Reported from one of our users [via Twitter](https://twitter.com/fafneri/status/857645991012564992):

> hey. I've been having some problems on loading new tabs/opening websites, they take so long. Is there anything I can do?

> when I try to open something through the new tab page, it takes ~15s. when I try to open a website, ~10.

**Comment by luixxiul** [comment]
After opening the browser several hours I found the tab was not smoothly changed. It took a couple of seconds to change the tab by clicking.

![lag](https://cloud.githubusercontent.com/assets/3362943/25710594/a6436542-3127-11e7-8f51-5f8ee7277a7e.gif)

**Comment by ashkitten** [comment]
Same here, and the entire browser freezes while loading a webpage.

**Comment by Southern-Discomfort** [comment]
Exactly my problem, the browser is extremely laggy on Windows 10 x64. It is unusable at the moment. It literally takes 3 or 4 seconds to open a new tab. Crashes are common. Something has happened...I get it is only beta.

**Comment by pjv** [comment]
Until recent updates i couldn't use brave (Macos Sierra, on a very beefy new iMac) because it was too slow to tolerate. A couple days ago I downloaded the latest release:

![2017-06-02 at 10 17 am](https://cloud.githubusercontent.com/assets/327716/26732308/cb32163a-477c-11e7-8bbe-81b6f05f4f44.png)

And wonder of wonders, you guys have improved things pretty dramatically. It's actually tolerable (though still sluggish) to launch, and quite zippy opening tabs and loading pages.

But... overall moving around in the app it still has a sluggish feeling to it and closing a tab is still completely absurd. I hit command-W or click the X to close a tab and I count slowly:

- one one thousand
- two one thousand
- three one thousand

... and somewhere around three one thou the tab finally closes.

It's fine if you don't have things fully optimized. Extended beta's are great. But I think you guys should stop calling Brave "faster" than the alternatives because since (as of now) it actually feels materially slower than the alternatives in many ways, people who download it and run it and experience it as slow are going to just assume that nothing you say is credible.

I understand the principle on which you are claiming speed and I am not arguing with that. Not downloading all the crap that Brave blocks will certainly speed things up. But if the app itself performs so slowly that downloading junk is not the bottleneck in perceived snappiness in a user's experience, then marketing the browser as "fast" is going to sound untrustable.

For me personally, I can't tolerate the generally lagginess and that 3-second wait to close a tab, so Chromium remains my primary browser for now. I'll keep checking in.

**Comment by ipeychev** [comment]
I also see similar issues. Brave was my default browser for about 9 months, but recently it became much slower than Chrome. This used to be not like this.
The problem is that on opening a page, browser simply freezes for 1-2 seconds and I can't even scroll down. This is even more visible if from one page I start to open more pages in background (from example to open a few links from a news page). Checking the resources, Brave starts to consume about 50% of the processor while opening a page (I saw it to consume even 60%).

<img width="803" alt="screen shot 2017-06-05 at 22 05 02" src="https://cloud.githubusercontent.com/assets/78014/26801020/bd15b9be-4a3b-11e7-8929-09af8fa6ca33.png">

Chrome on the same machine works just fine. Here is the machine, it is powerful enough:

<img width="586" alt="screen shot 2017-06-05 at 21 58 26" src="https://cloud.githubusercontent.com/assets/78014/26800739/ad739ea0-4a3a-11e7-9791-575cf3ca71a9.png">

**Comment by zentagonist** [comment]
@ashkitten @ipeychev - Following up specifically on the reported slowness of opening a new window or a new tab. Please let us know if you're still seeing the same issue. There is a possible duplicate issue here: https://github.com/brave/browser-laptop/issues/9877 for opening a new window when no other windows are open. Thanks for helping us find performance issues with Brave!

**Comment by bsclifton** [comment]
+1 from @aumars via https://github.com/brave/browser-laptop/issues/12104
> ### Description
>After having initialised Brave, the new tab freezes the entire browser and takes about 2-4 seconds to unfreeze, this is has been happening in both my Linux and Windows builds ever since I've switched to Brave months ago.
>
> ### Steps to Reproduce
> 1. Open Brave and start immediately typing on the URL bar, or open a bookmark.
> 2. Open a new tab and do the same.
> 
> **Actual result:**
> https://ipfstube.erindachtler.me/v/QmUEqYz589bwHP9GsPZohtrRhKRfF3qX2EUHTa96stSyAC
> 
> **Reproduces how often:**
> 90% of the time.
>
> ### Brave Version
>
> **about:brave info:**
> Brave: 0.21.0 
> V8: 6.1.534.32 
> rev: 98b430bd90bdf8cafb8682e5fe376083b3c71fa1 
> Muon: 4.4.19 
> OS Release: 4.13.12-1-ARCH 
> Update Channel: Release 
> OS Architecture: x64 
> OS Platform: Linux 
> Node.js: 7.9.0 
> Brave Sync: v1.3.5 
> libchromiumcontent: 61.0.3163.79
>
> **Reproducible on current live release:**
> Yes.

**Comment by vit0** [comment]
Hi
I also experience the issue - **Windows 10**
After opening new tab a couple of seconds passes and the site loads then.
I am able to switch tabs in the meantime.

**No such lags on Linux** machine, responses are immediate.

**Comment by LaurenWags** [comment]
+1 from twitter with 0.20.30 - user reports slowness, long load times, and sometimes unresponsiveness. Only one window with 3 tabs. https://twitter.com/AngelClarkSays/status/960565215673888769

**Comment by bsclifton** [comment]
+1 from @jamesray1 via https://github.com/brave/browser-laptop/issues/13053

Repro steps:
> I think I know what the cause is, and can reproduce it.
> 
> Go to https://tokensale.civic.com/
>
> Click the Read full whitepaper button, or just click this:  https://tokensale.civic.com/CivicTokenSaleWhitePaper.pdf.
>
> Brave slows right down, and won't speed up until you close the Brave/Nautilus window prompting where to save the White Paper.

**Comment by jamesray1** [comment]
Brave was slow this morning and a few times in recent days, without downloading any files this morning. After closing it this morning and opening it again, a few minutes later, it crashed again.

 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 4.13.0-36-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by bsclifton** [comment]
Closing as this issue is a little ambiguous. There are known crash issues, but there aren't enough steps to identify a specific slowness issue(s)
