### ISSUE TITLE
Option to disable blocked count badge (on Lion)

### ISSUE THREAD

**Issue by midi** [brave/browser-laptop#8613]
Kindly add an option to disable the badge.

**Comment by bsclifton** [comment]
@midi you'd like to hide the number that's on the Lion? or hide the Lion icon all-together?

**Comment by midi** [comment]
@bsclifton Oh I mean the badge number. It doesn't serve a purpose to me, it's just visual clutter. Hence my surprise that it couldn't even turned off.
I'm aware of the Lion menu to turn off blocking things in case a site doesn't work.

**Comment by bsclifton** [comment]
@midi OK awesome, thanks! 😄   Love your name, BTW. I remember the old days on the internet (mid-90's) when people would embed MIDIs on their sites ❤️

**Comment by bsclifton** [comment]
cc: @bradleyrichter

**Comment by kumarrishav** [comment]
@bsclifton  I would like to pick this up :)  I agree with @midi .There should be option to disable the blocked count badge. Can we have input on where to put option to disable it? Thanks

**Comment by bradleyrichter** [comment]
I think we should put it in the shields prefs page to avoid clutter-growth in the panel. 

[off/on] Display block count badge on shields button

**Comment by bsclifton** [comment]
@kumarrishav perfect!  a few pointers:
- A string will need to be chosen for the setting name. [see here for an example](https://github.com/brave/browser-laptop/blob/master/js/constants/appConfig.js#L121). The setting should default to **true** so that we keep our existing behavior
- A constant should be created for the setting. [see here for an example](https://github.com/brave/browser-laptop/blob/master/js/constants/settings.js). Notice the value is the string from the first change
- Like @bradleyrichter said, the Shields tab would be the best place 😄  [You can find the code here](https://github.com/brave/browser-laptop/blob/master/js/about/preferences.js#L493)

**Comment by bsclifton** [comment]
@kumarrishav since you've been doing such a great job (all the bug fixes / PRs you've submitted recently), I added you officially to browser-laptop as a contributor!  😄 

Once you accept the invitation, you should be able to assign yourself issues and also add/remove labels from issues.  GitHub doesn't have granular permissions, so please keep in mind that you also will have write access to the repository. With great power comes great responsibility 😄

**Comment by kumarrishav** [comment]
Thanks @bsclifton .

**Comment by NejcZdovc** [comment]
Mock of this option 

![image](https://cloud.githubusercontent.com/assets/9574457/25724760/54bcbdb8-311d-11e7-8bc1-bdb2125435c3.png)

cc @bradleyrichter 

Left a comment in PR as well https://github.com/brave/browser-laptop/pull/8701#issuecomment-299307305

**Comment by philkloose** [comment]
@kumarrishav I think it's doing the opposite of whatever its set for.  If enabled, we should see the counter.

**Comment by kumarrishav** [comment]
@philkloose yeah. It behaves like that only. If enabled then it will show the counter

**Comment by philkloose** [comment]
@kumarrishav Oh, I'm wrong, it works exactly as it should.  Carry on!
