### ISSUE TITLE
All preferences options (left pane) should be accessible on a small window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8635]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered: All preferences options (left pane) should be accessible on a small window
 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.2
rev	71f7dfd 

- Steps to reproduce:
    1. Set UI scale to supersize and default zoom to 200 
    2. Close preference page and reopen 
    3. Depending on the screen size, options are not visible 
  
- Screenshot if needed:
on 1920x1080 screen 
![image](https://cloud.githubusercontent.com/assets/17010094/25635906/923023d0-2f77-11e7-8375-57760737a4f6.png)

- Any related issues:
cc: @bradleyrichter

**Comment by luixxiul** [comment]
I assume that we would change the UI size to Supersize on the very large/full HD monitor where the left pane was quite small before the option became available. ie on that monitor left pane should finally be 'normal' size with that option. It is a bug but rare to change the option to Supersize on the normal size monitor, so the bug is not a show-stopper.

**Comment by luixxiul** [comment]
This could be the solution:

![scroll](https://cloud.githubusercontent.com/assets/3362943/25700622/6f9dcc68-3103-11e7-905b-18cd211c5469.gif)

**Comment by srirambv** [comment]
Yes that looks good 👍

**Comment by luixxiul** [comment]
the problem is that by doing so the tick next to the selected item on the left menu disappears.

**Comment by NejcZdovc** [comment]
@luixxiul what if we put scrollbar on the left side?
