### ISSUE TITLE
Zombie pinned tabs (unpinned tabs resurrect themselves as pinned tabs persistently)

### ISSUE THREAD

**Issue by alechp** [brave/browser-laptop#8711]
- `Did you search for similar issues before submitting this one?`
Yes. There are similar/related issues, but this is slightly different I believe.

- `Describe the issue you encountered`:
Cannot unpin. Screencast reproduction:
https://drive.google.com/file/d/0B-5phY8L_KiAQXhvYVpnSXVJdWc/view?usp=sharing
(Publicly shared link. No sign-in required to view)

- `Platform (Win7, 8, 10? macOS? Linux distro?)`:
OS Sierra 10.12.4

- `Brave Version (revision SHA)`:
0.15.2 / af7ef42

- `Steps to reproduce`:
    1. Unpin
    2. Close browser
    3. Open browser
    
- `Actual result:`
Pinned

- `Expected result`:
Unpinned

- `Can this issue be consistently reproduced`?
Tested twice.

**Comment by bsclifton** [comment]
@alechp thanks for the detailed video 😄  I had the same problem and have fixed it (it'll be in our next release).  You can see more details in https://github.com/brave/browser-laptop/issues/8477

Basically, the problem is that the site you pinned is bookmarked and the bookmark is inside a folder.  You should be able to solve the problem by moving the bookmark to the root (top level of the bookmarks toolbar) and then unpinning.  As a work-around, that should do the trick.  Sorry for the inconvenience

**Comment by ksmithut** [comment]
@bsclifton I'm seeing this issue, but I have no bookmarks. Have there been other known causes that can be worked around?

**Comment by bsclifton** [comment]
@ksmithut you could try clearing your history?  I know this isn't ideal (and you can copy your `session-store-1` file before, just to try this fix).

Under the hood, bookmarks, pinned tabs, and history all use the same object... which is what causes this unusual complication

**Comment by ksmithut** [comment]
@bsclifton I unpinned all of my tabs and closed them, then cleared all browsing data, which prompted a restart. When it restarted, the pinned tabs came back up.

**Comment by shortstuffsushi** [comment]
Hi there, was the release you mentioned ~12 days ago released? I'm still seeing this issue as well (Windows).

**Comment by luixxiul** [comment]
@shortstuffsushi 0.15.300 is not ready yet and will be released soon.

**Comment by shortstuffsushi** [comment]
Ok, great -- thanks.
