### ISSUE TITLE
Allow for unlimited tabs (having tabs continue to resize)

### ISSUE THREAD

**Issue by jtremback** [brave/browser-laptop#879]
Chrome's tabs will resize when there are a lot of them:
![image](https://cloud.githubusercontent.com/assets/1335122/13268798/54438a92-da39-11e5-887f-02df21966fda.png)

while Brave has separate pages:
![image](https://cloud.githubusercontent.com/assets/1335122/13268847/9a625742-da39-11e5-8a04-8fc79d556753.png)

I prefer to have the tabs resize, and it's actually kept me from using Brave more. Is there any interest in changing how this is done? I can write the code to do it.

**Comment by bbondy** [comment]
we have an option in preferences to adjust tabs per page, perhaps you could set that higher? 
If you need it even higher than the max available there, maybe you could tweak the code, the smaller size was causing tab text to not be as visible.  btw we'd love pull requests for fixes.

**Comment by SJ-Diamond** [comment]
Would perhaps be a good idea for a customization option at some later point, to have tabs resizing instead of having them seperated in different pages.

The more options at some point, the more happy people. Anyway, i vote for having tabs in pages as i find that more convenient as i do not like tabs shrinked to the maximum.

**Comment by jtremback** [comment]
What's nice about Chrome is that it will resize tabs dynamically as there are more of them.

I can work on this, as a buried option, but I think Brave's design team should put some serious thought into making it the default (once I'm done). Google is notorious for doing huge amounts of testing on their simple interfaces, and I have to conclude that they built the tabs in Chrome this way for a reason.

Autoresizing tabs are a simpler interface, while the multiple pages thing seems like something better suited to power users. Power users are more likely to customize the browser in the configuration options.

**Comment by SJ-Diamond** [comment]
The question is why every browser must turn in the first place around simple users. The whole concept of Brave looks to me it is more suited for advanced users. And just because Chrome does something, Brave should not follow under all costs. Let Chrome be Chrome and Brave be Brave.

While Chrome feature parity for sure is of interest for simple users, it should not stand in between the Brave teams goal to develop a unique browser.

**Comment by Emperor-Lestat** [comment]
I also would love to see if the tab page system is staying default. As opposed to all other mainstream browsers (excluded Google for obvious reasons) Brave has the benefit to be able to make experiments with a completely unique feature set. That is the pro side of a so called non native user interface. Whoever may think that Brave will be exactly like Chrome will be disappointed because the developers have their own  Mantra which sets Chrome and Brave apart by great length.

And i and many other early supporters would not like to see it happening if Brave would turn into another one of that Chrome wanna-be's. So, dear developers, take risks and go different ways, there is zero need for a so called feature parity with another product, at least not in the same way a competitors product is offering that kind of features already.

**Comment by jtremback** [comment]
Hey, I don't know if auto-resizing tabs are better for less advanced users or if I just personally prefer them. I guess that's a question which would need to be answered by the Brave design team.

However, I would argue that settings favoring less advanced users should be the default. The reason for this is simple. Less advanced users are also less likely to customize their browser workflow by going to the settings menu. More advanced users can customize whatever advanced workflows they want in the settings and with extensions. This principle has been proven time and again over the last 30 years of interface design.

Anyway, I'll try to do a prototype of the auto-resizing tabs over the next few weeks, and let someone else decide whether or not it's a good idea.

**Comment by SJ-Diamond** [comment]
Just curious, why do you think that shrinking tabs are more preferred by simple users than what Brave does offer? I would say Brave should do it like they have done here: #886

And asking the user which way is the more preferred. I do not think that without a real actual number which feature is really preferred as standard, that such a radical shift in functionality is justified. My opinion as a normal user, nothing more and nothing less.

**Comment by fuzzyshark** [comment]
Shrunk tabs are a mess for me(when there's dozens). The page feature is nice as it is, and should be kept so(hoping so). Brave devs are doing some brave changes in what seemed to be some standard every browser vendor should chase, as mentioned in above comments and that's cool. 
The peekaboo is a decent ease-of-pain for confusion if doing shrunk tabs is a thing in future. I am excited on how some fundamental design principles will keep this better and unique even after you change these things(which i hope no one does).

**Comment by SJ-Diamond** [comment]
Exactly my opinion. Why destroying something unique when it works so well? The "UI standards" what Chrome has implemented are neither good or universally acknowledged as the only way of doing things. In general it is always bad if a browser developer becomes such a power that they are able to say what is right and what is wrong.

Even more of a reason to say no, and doing it in a different way. Google and Google Chrome are not the source of indefinite wisdom.

**Comment by bradleyrichter** [comment]
Thanks everyone for the feedback and interesting discussion. We are creating something different that is trying to improve some things about current browsers without rocking the boat too far. I hope that the benefits, power and flexibility of tab pages will outweigh the amount of learning required. My initial user research showed that some preferred chrome's approach and some preferred FX but neither was loved. Chrome quickly becomes unusable for tab hoarders because of legibility. FX becomes bothersome when a lot of scrolling is required. So far, tab sets are well received by the majority based on twitter, support calls, and press...

We have a plan to animate the tab transitions to help the first-time user understand better how it works. Power users should enjoy some of the future ideas we have that only tab sets can provide. 

One of the first will be "tab previews" where the tabs can be shown when you hover over the tab set indicator. Later we can offer some organization.

**Comment by SJ-Diamond** [comment]
Thanks, love to hear this decision and hopefully you implement more features which are neither following  the Firefox or Chrome approach. It is time for something unique, pretty sure you will deliver!

**Comment by caliston** [comment]
I've just downloaded Brave and I'm struggling with the maximum number of tabs feature.

The thing is, the maximum number of tabs really depends on your screen width.  For example, here's the 20 tabs I'm allowed to have, on a small browser window.  Because the icons are displayed, I regard this as perfectly usable:

<img width="805" alt="screen shot 2016-09-04 at 11 55 15 am" src="https://cloud.githubusercontent.com/assets/1395154/18230561/f6b483d0-7296-11e6-8b61-f858115bb61a.png">

That's 800 pixels wide.  Meanwhile, on a 40" display that's 3840 pixels wide (1:1 pixel size, no UI scaling):

![screen shot 2016-09-04 at 11 56 28 am](https://cloud.githubusercontent.com/assets/1395154/18230567/0e14b770-7297-11e6-8ef0-20a7ca6696b9.png)

In case that's a pain to see, here's the left side with the same width as the 800 pixel screenshot:
![screen shot 2016-09-04 at 12 08 01 pm](https://cloud.githubusercontent.com/assets/1395154/18230608/aebb73e8-7298-11e6-84db-f3dae8561e10.png)

To replicate the squashed-ness of the first picture on a 4K display would take about 100 tabs.  I think I'd be happy to push 150-200 tabs there (and yes, I do want to see them all).

I'm not asking for any changes in layout, just that the maximum number be substantially increased.  If it went up to 250, say, it would allow people to have the tabs-squashed-together effect if they prefer that, but allow tab grouping if they didn't.

There is a further question about what should happen if the window is resized - should more groups be created to keep tab width?  I'm of the opinion that it shouldn't: I have a cognitive model of where tabs are (eg proximity for a particular task), and to change them interferes with my view of the world.  But other people may differ.

**Comment by bradleyrichter** [comment]
@caliston Thanks for the feedback. We have a task on the roadmap to allow 100 tabs as a choice but more work needs to be done to allow this. As you can see, the icons are not aligning correctly even with 20. 

100 should satisfy the great majority of users who prefer the chrome-style shrinking tabs based on the distribution of screen sizes. 

I agree with your point about a cognitive model. Allowing tab sets to change based on browser width would probably break this in a bad way.

We want to add more organization power to the tab sets soon.

**Comment by lucaszanella** [comment]
There are times when I use 80 tabs, I downloaded TabMixPlus for Firefox, which makes the tabs multilined. I'd love this in brave.

**Comment by lucidNTR** [comment]
i think it would make sense to have a sensible "minimum tab" mode that gets activated when there are a certain number of tabs per page depending on window width. it would look much like pinned tabs and still be very usable, unlike chrome tabs that just are ridiculous after a certain size. i will upload a video later today to illustrate what it might look like...

**Comment by lucidNTR** [comment]
https://www.dropbox.com/s/70q4heggnxkkemu/minTabMode.mov?dl=0

**Comment by bsclifton** [comment]
Somewhat related: https://github.com/brave/browser-laptop/issues/6272 and https://github.com/brave/browser-laptop/issues/6692

Also, +1 from this issue (which is essentially a duplicate, but has a lot of GREAT feedback):
https://github.com/brave/browser-laptop/issues/4986

Some of that feedback:
> @unsystemizer:
> 1.) do not create tab groups by default. I'm fine with 50 tabs and don't want to horizontally scroll among them. Maybe have "Enable grouping" in {10/20/x} tabs" for those who like this way, but this isn't standard in other browsers and shouldn't be enabled by default (but I'm fine with that as long as I could disable this behavior)
> 2.) provide incremental (smooth) horizontal scrolling (not in "screen width" increments) between tab "groups"
> 3.) provide the ability to pack more tabs in one screen (if I have 45 tabs on my large monitor, I don't need or want to scroll horizontally between many tab sets)

> @bradleyrichter:
> Thanks for the detailed feedback. We will get there. : )
>
> During initial research to improve tab overflow, we found that people either prefer Firefox or Chrome but most people disliked aspects of each, and wished for something better.
>
> We found that users open a new window (in both browsers) and start more tabs. Then they have a worse problem trying to locate and keep track of the window-separated tabs because they are disconnected.
>
> Chrome turns tabs into unrecognizable nubs fairly quickly. This forces some users to start pruning in a good way. Firefox creates difficulty in locating the tabs when you can only view a subset at any given time.
>
> Brave Tab sets tries to improve this main problem and ads better visual location.
> 
> Soon, we will be adding horizontal scrolling like Firefox to what we have now. So basically, the tab set indicators will be "scroll jumpers" instead of separated sets. Combined with adjustable number of tabs per tab-set, later up to 100, you can potentially have the best of all 3 worlds.
>
> In the future, we plan to add organizational features to tab sets.

**Comment by cezaraugusto** [comment]
I'm going to postpone this to 0.13.7 since we're planning to have 100 tabs option on this release as well. Feel free to undo if that's a must-have for 0.13.6

**Comment by bsclifton** [comment]
"100 tabs should be enough for everybody" - @cezaraugusto, 2017 😅

**Comment by bsclifton** [comment]
moving to 0.14.3

**Comment by srirambv** [comment]
@bsclifton Could this be closed since the 100 tabs per set is already available?

**Comment by bsclifton** [comment]
@srirambv I don't think this is worth closing since it's a feature that people want

I do think it's worth sharing though that this isn't on our roadmap.  Patches are welcome of course

**Comment by JonnyRedHed** [comment]
I missed this one when posting mine. Sorry. 

Would be really great to have Tab bar scrolling left and right with the mouse wheel, using kinetic scrolling (with settings for speed, acceleration/deceleration etc). For those of use wanting to use 100-200+ open tabs daily. Scrolling much like FireFox has. But with your own Brave flavour of doing things.

The current option (tab Sets) is pretty good, but some of us do prefer to kinetic scroll left and right to whiz up and down (left and right) out 100-200+ daily tabs real fast.

I guess looking at what FF does by showing the full fav icon on the scrolled current focus tab and then faded the ones each side.

Could this be considered please.

**Comment by bradleyrichter** [comment]
@JonnyRedHed Scrolling combined with tab pages is planned and important. Coming soon:

#2704

**Comment by JonnyRedHed** [comment]
But still room for mouse wheel scrolling of the tab bar left and right across the top of the UI  using kinetic scrolling (with settings for speed, acceleration/deceleration etc).  Like Firefox but with your Brave flavour of doing things.   

Whizzing left and right along a tab bar of 100-200+ tabs with cool animations bringing the tab fav icon in-focus and full size along with the two semi-ghosted tabs either side of it.  I prefer tab bar kinetic scrolling.   Could also have it turned off as default, or On as default with a full settings section so it can be tuned or turned off completely.   But for 100-200, even 300+ tabs its got to be easy as pie to use.

**Comment by bradleyrichter** [comment]
I hope to avoid needing prefs to achieve a great scrolling feel but we can consider kinetic for sure.

**Comment by JonnyRedHed** [comment]
I was thinking settings for things like acceleration and deceleration curves like the smoothscroll extension [HERE](url=https://chrome.google.com/webstore/detail/smoothscroll/nbokbjkabcmbfdlbddjidfmibcpneigj?hl=en)

And to turn it off if some users prefer it that way.  Settings to suit all tastes.

**Comment by kenorb** [comment]
Why not to add _Unlimited_ option to the existing dropdown, so both sides of this issue are happy?

<img width="460" alt="screen shot 2017-09-11 at 10 24 18" src="https://user-images.githubusercontent.com/266306/30267744-725c3960-96db-11e7-89ae-221a2aaa8027.png">

**Comment by JonnyRedHed** [comment]
Just adding extra tabs to one window is not the whole answer.  You cannot see the fav icons at all with 100, so 200 would be just tiny slithers to click on.  Which is why I suggested kinetic mouse wheel scrolling back and forth along the tab bar making the tab in focus show its full width and the ones either side fade away just like Firefox does.  But with Brave's way of doing things.

**Comment by kenorb** [comment]
I usually work with lots of tabs on Chrome (e.g. 35 tabs shown below on 2800x1800 Retina display).

Full width:
<img width="1377" alt="screen shot 2017-09-11 at 22 05 52" src="https://user-images.githubusercontent.com/266306/30296867-9ca9ab6e-973d-11e7-8aba-00c16a12a2b5.png">

70% of size:
<img width="1025" alt="screen shot 2017-09-11 at 22 06 10" src="https://user-images.githubusercontent.com/266306/30296875-a21b8ef0-973d-11e7-9e07-739ed9ef49a3.png">

In Chrome size of small tabs are hard-coded in source to 61 pixels. See: [Making Google Chrome pinned tabs more compact](https://superuser.com/q/456645/87805).

Maybe in _Brave_ tab size should be more flexible or fav icons could be resized to be smaller when there are too many tabs.

**Comment by defuse** [comment]
Brave's tabs really annoy me, so I'll weigh in on this with some of the specific problems I have:

1. Often, I'll have more than a screen-width worth of tabs open, and I'll be in the leftmost tab (containing my Twitter client) and I'll middle-click a link. There's no visual feedback at all that a new tab has been opened, so I find myself clicking the link multiple times until I remember "oh, shit, it's opening over in the other page of tabs."

2. There's a discrete jump when switching between screen-width sets of tabs instead of the tab view scrolling continuously. I'll be working on two or three related tabs that cross the boundary, and it gets *really* frustrating and visually jarring to have to continually switch between sets. Every time I have to switch, I feel disoriented because some of the tabs I want to keep in mind aren't visible anymore. I always have to work around it by closing tabs to the left until the tabs I'm working on don't cross the boundary anymore.

Here are some thoughts:

- I'm good at remembering where objects exist in space. I'm not so good at scanning through lists to find something I'm looking for. So either keep all tabs visible or scroll them continuously, so that I can use my spatial awareness of the tabs to navigate them (the current design repeatedly breaks my spatial awareness because opening a few extra tabs can push other ones off the edge and radically change their position with respect to the screen).

- In my main browser (Firefox), I use an extension called Tree Style Tab that lays the tabs out vertically along the left side of the window. I like this *a lot* better because (a) many more tabs can be visible at once and (b) on a widescreen monitor, there's plenty of horizontal room to make the tab bar wide enough to show most of the tab title text. Here's what it looks like on a 1080p monitor:

![treetabs](https://user-images.githubusercontent.com/4211072/31399777-75f968b2-adbb-11e7-9f20-0e5dd961b852.png)

**Comment by NumDeP** [comment]
@defuse the extension available from the store look messy when downloaded and from your image as well.

FF's proprietary version looks far more simple functionality and has a better UI. -
 https://testpilot.firefox.com/experiments/tab-center/

**Comment by JonnyRedHed** [comment]
Try out your own Brave flavour of Kinetic mouse wheel scrolling back and forth for the tab bar, similar to FF's kinetic scrolling.   Will be very handy for those using 100-300 or so open tabs.   So when using 200 odd tabs you can clearly see the full fav icon and the ones either side as you scroll left and right.   And have settings for the kinetic scrolling control, speed, acceleration and fall off etc.

**Comment by NumDeP** [comment]
I've only just noticed FF's built-in feature at the top right hand corner where you can view tabs in a list quite neatly actually, this was probably in relation to disabling Tab Center though it's still offered as Tab Center Redux in the Add-On store. 
Perhaps you can consider this as an option so most of the window space isn't removed. 

![screenshot_2018-01-30_17-14-17](https://user-images.githubusercontent.com/31957540/35781805-c2b2e278-09e6-11e8-8e4d-b738a7c82819.png)

**Comment by bsclifton** [comment]
Closing as this issue is resolved with [brave-core](https://github.com/brave/brave-browser). We won't be fixing it in `browser-laptop`
