### ISSUE TITLE
edit bookmark names in place on the bookmarks bar

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#882]
As a user, I need an efficient shortcut to edit bookmark names on the bookmarks bar.

**Comment by bbondy** [comment]
Right click and edit isn't good enough? What do you imagine here?

**Comment by bradleyrichter** [comment]
Adding double-click as a shortcut to the current right-click and edit menu item. Nothing else needed for now.

This is P2 BTW. A "nice to have..."

**Comment by bbondy** [comment]
Long press is the way safari does this, updating title.

**Comment by bradleyrichter** [comment]
there must be a reason why double-click is not desirable. Keep as P-low.

**Comment by bbondy** [comment]
Why have a new unique way to do this when a way is already familiar and established to do the same in Safari? No benefit to be different for something like that, like shortcut keys, same thing.  Also single click already opens the bookmark, so double click would mean it starts loading the link first before it can rename it.

**Comment by bradleyrichter** [comment]
I meant, switch to long-press as you renamed. And its not a high priority item. If it doesn't cause a problem, it would be nice to emulate the finder for renaming files.

**Comment by bbondy** [comment]
Ya I think it does cause a problem for the double click. The click on selected is a bit different here because in finder the first click doesn't do an action other than select the icon.  In the bookmarks case, there is a hard action on the first click.  You could try to for example to delay the click action some period of time unless a double click event happens, but that might look like lag, and also double click time is configurable in the OS so would be buggy for some.

**Comment by bbondy** [comment]
Note to the person that takes this:

I think to do the long press to rename in place we could:
- Set contentEditable on the item
- On escape remove contentEditable
- On Enter you could rename the site like addEditBookmark.js does.

See how Safari works with regard to rename in place.

**Comment by bsclifton** [comment]
This is something we won't be fixing before moving to [brave-core](https://github.com/brave/brave-browser). Let's create an issue there if we'd still like this functionality
