### ISSUE TITLE
How to generate x86 programs？window10

### ISSUE THREAD

**Issue by drcayman** [brave/browser-laptop#8855]
How to generate x86 programs？window10

**Comment by drcayman** [comment]
@bsclifton can you help me?

**Comment by bsclifton** [comment]
@drcayman how exactly can I help you?

If you're wanting to build the executables, you can follow the steps here:
https://github.com/brave/browser-laptop/wiki/Packaging-for-bundles,-installers,-and-updates#creating-the-binaries-and-installer

This should be as easy as:
```
git clone git@github.com:brave/browser-laptop.git
cd browser-laptop
npm install
npm run build-package
```

At this point, you'll have the binaries inside of a folder.  You cannot do the installer step because you do not have access to the certificate / signing pw (only Brave Software has access to this).  If you wanted to, you could modify the `npm run build-installer` script yourself and remove the signing part (but then of course, it would not be signed)

**Comment by drcayman** [comment]
@bsclifton  Can the created program be used in a 32-bit system?

**Comment by bsclifton** [comment]
@drcayman for Windows yes- Linux unfortunately is not supported for 32 bit ☹️  What system are you trying to build for?

**Comment by drcayman** [comment]
@bsclifton  window
