### ISSUE TITLE
Imported bookmarks are not displayed in the URL bar autosuggest list

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8976]
**Describe the issue you encountered:** Imported bookmarks are not displayed in the URL bar autosuggest list.

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on debian

- Brave Version (revision SHA): 0.15.306

- Steps to reproduce:
    1. Install Firefox
    2. Open Brave
    3. Import Firefox data
    4. Make sure you have the bookmark folder in which the default bookmarks on Firefox was imported
    5. Input `Getting`
    
- Actual result: The bookmark `Getting Started` is displayed under `History` instead of `Bookmarks`

- Expected result: It should be under `Bookmarks`

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
  ![import](https://cloud.githubusercontent.com/assets/3362943/26275784/11e5aa84-3da4-11e7-877a-5a1177112f0d.gif)

- Any related issues:

**Comment by bbondy** [comment]
This is intentional since I combined bookmarks and history now.  The problem with treating them separate is you need to autocomplete over the first item, and if you create 2 hierarchies then you can't always match to the best item.  I think we should probably just get rid of the History title for the section.   CC @bradleyrichter for thoughts. I'm going to move it out of 0.15.300 though.

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/11802
