### ISSUE TITLE
Key Combinations

### ISSUE THREAD

**Issue by MrHappy45** [brave/browser-laptop#903]
Hello there Brave Team,

I was wondering, why doesn't ALT+RIGHT-ARROW or ALT+LEFT-ARROW doesn't work ?

These are, obviously, shortcuts for previous page and the previous page buttons.

Thanks for taking this into consideration.

**Comment by psimyn** [comment]
I _think_ it is mapped to ctrl+right-arrow, most of the shortcuts use ctrl/cmd (for osx).

This issue is the same as https://github.com/brave/browser-laptop/issues/351

Also, https://github.com/brave/browser-laptop/issues/812 is for allowing switching ctrl + arrow to use Alt. Can keep an eye on those for info

**Comment by twisterghost** [comment]
I think this has been solved by #949

**Comment by psimyn** [comment]
thanks @twisterghost !!
