### ISSUE TITLE
Release note modal text should be scrollable 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9121]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
With long release notes, update details modal doesn't fully show the text and covers the entire screen

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10  x64

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Set browser version to a older verision in system variables
    2. Launch browser and click on check for update
    3. Modal is extra long and doens't show all text

- Screenshot if needed:
**screenshot take at maximized window**
![image](https://cloud.githubusercontent.com/assets/17010094/26544871/724a3580-445b-11e7-9fb9-9e1c4584dec0.png)
**Screenshot taken at restored position**
![image](https://cloud.githubusercontent.com/assets/17010094/26545695/7d79fc26-445e-11e7-924f-9ec03d35935f.png)

- Any related issues: https://github.com/brave/browser-laptop/issues/7930#issuecomment-290053132

**Comment by luixxiul** [comment]
@cezaraugusto do you have a solution like you did on #7930 to solve the bug?

Integrating Messagebox with Dialog to add scrollbar, keeping the position where Dialog appears (ie not tab-modal), would be a general solution here. In that way we could avoid Dialogs like BookmarkHanger from having the scrollbar when it overflows a browser window.

This is actually a bug, but not serious because you would never the long list of updates as long as your browser has been constantly updated, ie without setting the flag to test if the update works, the list would normally not overflow (unless you would make the browser window small).

**Comment by alexwykoff** [comment]
@kjozwiak if you would like to give this a crack that'd be cool

**Comment by srirambv** [comment]
@bbondy @bsclifton can this be pulled into 0.19.x?

**Comment by bsclifton** [comment]
@srirambv sure- I updated milestone for this issue and the PR to 0.19.x
master https://github.com/brave/browser-laptop/commit/99dfe198a4b0f7808917a20e61c628a077531f73
0.20.x https://github.com/brave/browser-laptop/commit/be304b27f1b84c4e053b63257857fb771502c332
0.19.x https://github.com/brave/browser-laptop/commit/711df60b26d11904f3bf41b89b3b0214f01284a9

**Comment by srirambv** [comment]
Is this merged into 0.19.20? I still see the text overflow the modal 
![image](https://user-images.githubusercontent.com/17010094/30893355-5048a6a6-a35b-11e7-82f2-136fb5f419f1.png)

**Comment by srirambv** [comment]
Never mind its in 0.19.20
![image](https://user-images.githubusercontent.com/17010094/30893493-17a715e8-a35c-11e7-841e-2ae099f4d385.png)
