### ISSUE TITLE
PDF is downloaded when loaded in an iframe

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9144]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
PDF is downloaded instead of opening in a tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Visit http://ieeexplore.ieee.org/Xplore/home.jsp
    2. Scroll down and click on any of the links under _**Most Popular**_ or _**Just Published**_
    3. Click on **Download PDF** in the article page, PDF is downloaded instead of opening in the tab
    
- Actual result:
PDF is asked to download instead of opening in the tab

- Expected result:
Should open the PDF file

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @diracdeltas

**Comment by diracdeltas** [comment]
This is because the 'download PDF' page actually loads the PDF in an iframe. This issue also exists in 0.15.310 and I'm pretty sure it existed in previous releases too.

**Comment by diracdeltas** [comment]
test page: http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6740844

**Comment by diracdeltas** [comment]
It doesn't seem possible to fix this without re-opening https://github.com/brave/browser-laptop/issues/8365, since if we allow the PDF viewer to load in an iframe in an external page, the PDFJS extension ID can be used for fingerprinting.

IMO we should leave the behavior as-is unless there are sites which require PDFs to be loaded in an iframe. The IEEE site says 'download PDF', so Brave's behavior isn't necessarily wrong (though it differs from Chrome).

**Comment by diracdeltas** [comment]
removing milestone but leaving this open for input

**Comment by hummerh2** [comment]
I have the same issue on Mac 10.12.6, Brave 0.18.23. Attempts to download pdfs loaded in an iframe. Works fine in FF, Chrome, IE and Edge. It is happening on our Internal CRM so I can not provide a link. But same result as link above.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/two-issues-in-two-webpages/9969?u=eljuno

**Comment by LaurenWags** [comment]
+1s from community: https://community.brave.com/t/issue-opening-pdf-files/17968/5 using http://jkorpela.fi/html/iframe-pdf.html

**Comment by turhanb** [comment]
This is a blocking issue for day to day users of web based latex editors (e.g. sharelatex and overleaf) which covers a significant user base among academics. Those services compile the pdf for the working document and display it in an iframe on the fly. With brave, they do not display the pdf and a download dialogue pops up instead. That said, I totally understand the concerns about fingerprinting and wouldn't want to compromise; perhaps an option to enable on website basis could be the way to go.

**Comment by bsclifton** [comment]
Verified this is fixed with [brave-core](https://github.com/brave/brave-browser) 😄

**Comment by tzvatot** [comment]
Having the same problem with Fedora 28, Brave 0.23.105.
When is the fix expected to roll out?

**Comment by bsclifton** [comment]
@tzvatot this is something which is already fixed in our [Developer channel release](https://brave.com/download-dev), which you can download now 😄 We won't be fixing it in our current Muon based product. If you're not ready to make the upgrade yet, the new brave-core code base will be rolling over to Beta channel and then Release channel over the next few months
