### ISSUE TITLE
Alert disables UI elements and hides URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9285]
## Test plan:
https://github.com/brave/browser-laptop/pull/9656#issue-237722711
<hr>

**Describe the issue you encountered:** LastPass security check overwrites "always show URL bar" setting.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.15.314

- Steps to reproduce:
    1. Disable "always show URL bar" setting on about:preferences#general
    2. Enable LastPass
    2. Create accounts with two sites sharing login credential (such as www.rakuten.co.jp and www.rakuten-card.co.jp)
    3. Save the credentials
    4. Log in to one of the accounts
    
- Actual result:
  The URL bar is hidden. Also the lion icon has a strange color.

  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26828136/038117c6-4afb-11e7-9d63-e98b7d27cad7.jpg)

- Expected result:

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by cezaraugusto** [comment]
this happens for all alert notifications as well, like `alert()` on a page for example. 

opacity in bravery button is intended, see https://github.com/brave/browser-laptop/blob/master/app/renderer/components/navigation/navigator.js#L284.

**Comment by cezaraugusto** [comment]
given this is not critical I'm pushing back to 0.19.x. Let me know otherwise

**Comment by bsclifton** [comment]
@luixxiul @cezaraugusto sorry I didn't catch this until now (after seeing https://github.com/brave/browser-laptop/pull/9656)

This behavior is intentional.  There are actually tests in place to make sure we disable the lion icon, go into title mode, etc when an alert is shown.  The reason being: we don't want folks to navigate in the same webview while the alert is being shown

The Lion is disabled because we don't want the shields menu coming up while the alert is being displayed. You can still switch tabs while the alert is up.  After you acknowledge the alert, everything goes back to regular.

**Comment by bsclifton** [comment]
original notes / discussion in the PR https://github.com/brave/browser-laptop/pull/7107

**Comment by luixxiul** [comment]
still I believe the strange color should be fixed, which is light yellow. 

If it is disabled, it should be grey as we have.

![clipboard01](https://user-images.githubusercontent.com/3362943/27508191-d333e1ce-591a-11e7-8658-fde95b273231.jpg)

**Comment by luixxiul** [comment]
I opened an issue for ^: #9696
