### ISSUE TITLE
Scrolling in 'Bookmark view' still doesn't work

### ISSUE THREAD

**Issue by DJBigCheese** [brave/browser-laptop#9361]
Scrolling Bookmarks DOES work in regular browser view, but not in Bookmarks view. After applying this latest release v0.16.6dev & reading part of the updates included "Fixed bookmarks manager scrolling on drag and drop into folders. " I find that if you have a lot of Bookmarks in a folder, you will only be able to scroll down "so far" before having to change screen resolution to something that makes the Bookmark text illegible because it is so small. This kinda complicates Bookmark management in the Bookmarks view.

Windows 10 Home
Bookmarks view has always behaved like this since installing Brave a couple update versions ago.

**Comment by cezaraugusto** [comment]
hi @DJBigCheese thanks for reporting, nice find.

The issue you referenced was related to drag-n-drop and although the name suggests a fix for bookmark scrolling, it was addressed in a different issue: https://github.com/brave/browser-laptop/issues/9055. It was supposed to be in the same version you're looking for and we apologize it isn't.

Should be fixed in the upcoming hotfix for that same version, and you should receive a note in the update changelog regarding the fix. I'm going to close this but don't hesitate to reopen if it is still a problem.
