### ISSUE TITLE
bitwarden extension header buttons are not clickable

### ISSUE THREAD

**Issue by kspearrin** [brave/browser-laptop#9436]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: Parts of header buttons/anchors (where the text is drawn and above) in bitwarden extension header are not clickable.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.17.1dev

- Steps to reproduce:
    1. Configure and open the bitwarden password manager
    2. Click login button
    3. Hover over and click the "Cancel" and "Log In" buttons at the top header.

![image](https://user-images.githubusercontent.com/1190944/27115956-21b3dfd4-509c-11e7-9d15-770610a3cf72.png)

    
- Actual result:
Notice that the parts of the button where the text is displayed and above are not clickable. If you move outside of the text into the padding area below you can click the buttons.

If you navigate directly to the extension page in the main browser window everything works as expected. Ex: chrome-extension://nngceckbapebfimnlniiiahkandclblb/popup/index.html#/login

relevant extension source:

https://github.com/bitwarden/browser/blob/master/src/popup/app/accounts/views/accountsLogin.html#L2-L11

This happens on every page of the extension that has header buttons.

Not an issue in all other browsers (Chrome, Firefox, Opera, etc.).

- Expected result:
Buttons are clickable all over.

- Will the steps above reproduce in a fresh profile? If not what other info can be added? Not sure

- Is this an issue in the currently released version? No, bitwarden is not yet in production.

- Can this issue be consistently reproduced? Yes

- Extra QA steps: n/a

**Comment by kspearrin** [comment]
cc: @bsclifton

**Comment by jonathansampson** [comment]
I believe this is the same issue as https://github.com/brave/browser-laptop/issues/6015#issuecomment-268761257.

**Comment by kspearrin** [comment]
Also, this only seems to happen on windows. I didn't notice this on my MacBook.

**Comment by jonathansampson** [comment]
@kspearrin You're correct; I've never heard anybody complain about this on macOS or Linux.

**Comment by jonathansampson** [comment]
The issue hear appears to be with the `.tabStripContainer` also having the `.allowDragging` class, which adds `-webkit-app-region: drag` to the tab-strip element. This element's region (red) overlaps the popup element's region (orange). At the point where these two elements intersect, nothing is clickable (because the area functions instead as a drag region).

![image](https://user-images.githubusercontent.com/815158/29432927-f59b5b30-8362-11e7-9388-4d45e993c023.png)

Careful observation reveals this to be the case:

![overlap](https://user-images.githubusercontent.com/815158/29433288-285de014-8364-11e7-809e-f1bd3d55d660.gif)

Because this issue does not repro on Mac, I suspect it may be a Windows-only implementation detail. It appears as though `-webkit-app-region` does not respect `z-index`, in the case of overlapping elements.

**Comment by kspearrin** [comment]
Interesting find. I would have never guessed that was the problem just observing the issue as an outsider.

**Comment by jonathansampson** [comment]
It appears to be an issue with a history: https://github.com/electron/electron/issues/741

**Comment by jonathansampson** [comment]
The best solution, for now, maybe to add/remove `-webkit-app-region` on certain elements, depending on the present window state. So, when an popup is presented, we deactivate the tabStrip as a draggable region.

**Comment by bsclifton** [comment]
Here's the section of code we'd want to edit:
https://github.com/brave/browser-laptop/blob/master/app/common/state/windowState.js#L163-L186

if we know a way to check for if the popup is showing… we can add the check there

**Comment by jonathansampson** [comment]
@bsclifton I believe `popupWindowDetail` in state may suffice. Checking on that now.
