### ISSUE TITLE
Importing bookmarks should show progress

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#9476]
Importing bookmarks doesn't show a status or progress bar.
- When folks have a lot of bookmarks, the browser will appear to be doing nothing until it finishes (see Import bookmark causes Brave to hang momentarily before showing successful import #6699)
- the message box is tied to either bookmarks manager OR the tab that owned the modal

needs mockup

cc: @alexwykoff @bradleyrichter

**Comment by NejcZdovc** [comment]
Let's add it into 0.19 and then push it to 0.20 so that we don't forget about it. Based on @alexwykoff report community really needs this and we are losing users because of this.

**Comment by NumDeP** [comment]
I don't think this is imperative but do you think it would be good for the progress indicator to show of how many bookmarks will be imported and how many have been imported rather than a percentage? 

200/250 - 200 of 250

Particularly for users who have a hefty file also in reference to some users complaining of some bookmarks missing or bookmarks that weren't fully loaded, it may alleviate their concern.
