### ISSUE TITLE
Middle click on pinned tab causes all opened tabs to show as pinned tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9492]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Cloning a pinned tab and then middle click on it causes the cloned tab to get pinned but with close button

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.3
rev	02a7878
Muon	4.0.3

- Steps to reproduce:
    1. Open 3-4 tabs and visit pages in them and pin them
    2. Right click on the 2nd pinned tab and click on clone, ensure the cloned tab is opened 
    3. Middle click/Mouse wheel click on any pinned tab, cloned tab gets pinned but shows close button on it. Switching to it causes it to go back to being normal tab
    
- Actual result:
Cloning a pinned tab and then middle click on it causes the cloned tab to get pinned but with close button

- Expected result:
Cloned tab should remain normal and not become a pinned tab

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No, verified on 0.16.9 doesn't happen. Introduced from 0.17.1 onwards

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
No console errors
![tabpin](https://user-images.githubusercontent.com/17010094/27181564-fa63329c-51cf-11e7-8010-469d70a8a275.gif)

- Any related issues:
cc: @NejcZdovc @bsclifton @cezaraugusto

**Comment by srirambv** [comment]
This happens on all normal tabs not just the cloned tabs. Mouse hover restore backs the tab to normal state

**Comment by cezaraugusto** [comment]
- Normal tabs goes to extraSmall breakpoint rather than getting pinned. That explains close button and normal state after hover (component update)
- confirmed Sri last comment it happens to all tabs rather than only cloned tabs

Chrome, Safari, and FF all close pinned tabs with middle click. Opera does nothing.

Given closing a pinned tab is a matter for another issue, I'm going to cancel middle click over pinned tabs until #4063 is fixed.
