### ISSUE TITLE
Add welcome.properties for about:welcome localization

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9521]
**Describe the issue you encountered:** Add `welcome.properties` for about:welcome localization.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: https://github.com/brave/browser-laptop/issues/9423

**Comment by bsclifton** [comment]
The welcome page is part of https://github.com/brave/brave-website which should allow for localization 😄

**Comment by eljuno** [comment]
Since the page is already live, maybe make an announcement on Transifex to increase localizer awareness?
I'm sure not everyone know that the strings for about:welcome is on brave-website project not brave-laptop project. And the early translation is done by vendor.

Personally, I still thinking it'll better to have it as welcome.properties on brave-laptop than separate project. Since it's a feature in browser itself. :smile: 

Or maybe no need to localized this? Since first time users will have Brave in English (no option to change language when first install).

**Comment by luixxiul** [comment]
> Since first time users will have Brave in English (no option to change language when first install).

FYI that issue is tracked on https://github.com/brave/browser-laptop/issues/6435
