### ISSUE TITLE
Imported bookmarks don't show up in about:bookmark

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9716]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
[Intermittent issue]Imported bookmarks don't show up in about:bookmark

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.9
rev	2606974
Muon	4.1.4

- Steps to reproduce:
    1. Install 0.17.9
    2. Import bookmarks from HTML file
    3. Open `about:bookmarks`, doesn't show any folders/bookmarks
    4. Close and reopen browser, bookmarks and folders shown in `about:bookmarks`
    
- Actual result:
Imported bookmarks don't show up in about:bookmark

- Expected result:
Should show bookmarks and folders right away after import

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes and on upgrade

- Is this an issue in the currently released version?
No 

- Can this issue be consistently reproduced?
No, intermittent issue

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/27546823-cf91a66a-5a8b-11e7-8e73-d9d57d98740e.png)

- Any related issues:
cc: @bsclifton @darkdh

**Comment by srirambv** [comment]
cc: @NejcZdovc

**Comment by srirambv** [comment]
+1 from support https://community.brave.com/t/bookmarks-bar-working-but-bookmarks-manager-has-no-bookmarks/4519

setting milestone as 0.20.x please change if needed

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/my-bookmarks-are-not-showing-up-in-the-bookmark-manager/4573

**Comment by srirambv** [comment]
Several more reports from community https://community.brave.com/t/bookmarks-bar-working-but-bookmarks-manager-has-no-bookmarks/4519/6

**Comment by srirambv** [comment]
Moving back to 19.x as there has been several more reports on this issue.

cc: @bsclifton @bbondy

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/bookmarks-in-toolbar-but-not-in-manager/4707/

**Comment by alexwykoff** [comment]
I think this has already been fixed, certainly haven't reproduced during Sync testing. If this is still seen, please reopen and attach bookmarks file used.

**Comment by srirambv** [comment]
+1 from community for moving bookmarks to others folder and not showing up https://community.brave.com/t/various-bookmark-issues-preventing-me-to-use-brave-on-a-daily-base/4895/

**Comment by srirambv** [comment]
Reopened by mistake

**Comment by marcelbraun1985** [comment]
Hi,

I have installed Brave over Snap on Ubuntu 16.04. and after creating a bookmark it is visible but after a restart it is lost.

**Comment by illegalnumbers** [comment]
I'm seeing this too after importing Chrome Version 65.0.3325.181 bookmarks on macOS 10.11.6. 
Name | Version
-- | --
Brave | 0.21.18
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 15.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

The problem is that the expected behavior is that fuzzy string matching would pick up some of the bookmarks but it doesn't seem to in Brave. I type things that are partial matches to keywords in the bookmark but nothing comes up and it doesn't list things in the bookmarks folder at all which is really frustrating since I have hundreds of bookmarks and don't remember titles exactly. If you type several keywords exactly it'll display them though.
