### ISSUE TITLE
Brave should default download path to the downloads folder

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#9822]
## Test plan

https://github.com/brave/browser-laptop/pull/11994#issue-274395214

----

I think that brave should default the download path to the downloads folder so it automatically downloads files to that folder.

**Comment by bsclifton** [comment]
Is this not already the case? I know it may show as empty on fresh install, but it should be defaulting to the default download path when the dialog comes up

cc: @LaurenWags, @srirambv, @luixxiul

**Comment by Jacalz** [comment]
I mean without bringing up the dialog, like when you choose where to download to and you disable the option to always ask where to save files 😉

**Comment by srirambv** [comment]
I had brought this question before but guess it was lost in conversation :sweat_smile: . I think if the download path is not explicitly set then we may hide the file save dialog but again it will be an extra step for users to again change the download path. However if the default path is changed, it should add the path when it changes (which is currently missing). Also have a look at #9010

I feel the current behavior is good as it gives the user an option to change the path each time and not go into setting each time. I'd say keep the current behavior rather than removing the dialog and making users go to preferences each time they want to change the path.

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
