### ISSUE TITLE
Title mode only changes when mouse is over tabs bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9850]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Title mode only changes when mouse is over tabs bar

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
master

- Steps to reproduce:
    1. Build from master
    2. Open a new tab and visit a site
    3. Mouse over URL bar, doesn't change to URL mode from title mode, move mouse back on tabs bar changes to URL mode
    
- Actual result:
Title mode only changes when mouse is over tabs bar

- Expected result:
Should change to URL mode when mouse over tabs/URL 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![title_url](https://user-images.githubusercontent.com/17010094/27800144-0a962d38-6010-11e7-869b-b187c9d2684f.gif)

- Any related issues:

**Comment by cezaraugusto** [comment]
setting to 0.19.x to be included together with #9411

**Comment by slug23** [comment]
I see this behavior on MacOS v 0.17.13
When a site updates the title text (to show unread messages for example), the tab title for that page does not update until a mouseover, thereby failing to alert me of changes to that page.

**Comment by cezaraugusto** [comment]
this happens because window is draggable and `-webkit-app-region` cancels mouse events to allow dragging so the mouse enter/mouse leave events never happen for areas that they apply, making the message to show urlbar unreachable for some mouse positions. While all platforms share the same code it seems to be windows-specific. 

Chromium [archived](https://bugs.chromium.org/p/chromium/issues/detail?id=411217) the issue related to that property and [Electron has an issue](https://github.com/electron/electron/issues/1354) tagged as `wontfix`. Needs a workaround so labelling as `needs-investigation` and `OS/windows`.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/350
