### ISSUE TITLE
Consider integrating tabli

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#986]
My Tabli + Brave Proof of Concept
fork is here: https://github.com/antonycourtney/browser-laptop

@antonycourtney

Initial impression is that this would be a very valuable addition, needs UI polish though. 

Showing all tabs across windows with easy searching would be really great especially because of the tab pages.

**Comment by bbondy** [comment]
@bradleyrichter please try that branch above. You just need to go into a new dir, `git clone ttps://github.com/antonycourtney/browser-laptop`, `cd browser-laptop`, `npm install`, and then `npm run watch`, and then `npm start` from another terminal.

**Comment by bbondy** [comment]
The biggest thing I like is the flyout consolidated tab list with search.
I'm not aware of other browsers that by default allow you to search for opened tab title / location without having to tab hunt.

**Comment by antonycourtney** [comment]
Thanks for the positive feedback @bbondy. The current prototype is certainly rough, developed to demon the concept, determine if the integration was even possible, and to see if there's interest from Brave in adopting this before I do too much more work on it. 

For additional background it may be helpful to check out the (2 minute) screencast Tabli overview showing the production Chrome extension version of Tabli: https://www.youtube.com/watch?v=yRxOr2-urzg
May also be worth skimming screenshots in usage guide: http://www.gettabli.com/tabli-usage.html

I am fine with dropping the Tabli name and am open minded about making UI changes to make this fit more naturally / seamlessly into Brave. The prototype is a popup from the toolbar for now because that was expedient and how the Chrome extension version works. Might be more natural and intuitive to try integrate this into the top-level "Window" menu (which unfortunately just says "Brave" for every window right now...), though that will likely be a big chunk of work. And open to other ideas. Look forward to @bradleyrichter's feedback / guidance.

**Comment by bradleyrichter** [comment]
Hi @antonycourtney! Thanks for spending the time to test-flight your plugin. I was able to build and run the fork, and gave it a thorough test drive. I love some of the things this solves or improves with tab search and management. My main concern is that we have pieces and parts planned for different places such as through the searchable URL bar, and in the tab sets UI. 

So rather than adding a new menu and a button, would you be interested in helping with a tighter integration in those places?

- Brad

**Comment by antonycourtney** [comment]
@bradleyrichter: Thanks for taking the time to build and try it out.

I'd be delighted work with you on a tighter integration of this functionality into Brave. I would have loved to have had the latitude to do some of that for the Chrome version but was limited by Tabli being just an extension. Would be great to be able to build this functionality directly into the Browser (where it belongs IMO) and get the UX really right.

Let me know what you think would make sense for a next step. Happy to chat live if you are around at wework SF.
