### ISSUE TITLE
url bar suggestions are not most recent

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#9876]
If I visit http://somewhere.com/lol/rofl.html

When I type "somewhere", the first suggestion will be "http://somewhere.com" rather than the page I actually went to.

It would be nice if it autosuggested the most recent complete url that I have visited.

**Comment by rdetert** [comment]
The URL suggestions are difficult to use. What I often want is to go to the root domain instead of a page I've visited once. I have to end up typing the entire root domain name out most of the time. It would be nice if it prioritized suggestions based on when I type the full thing out and press enter. So after visiting the root domain 3 times or so, it'll know to put that first.

**Comment by bsclifton** [comment]
In Chrome, visiting the above URL and typing "somewhere" hits Google and auto-suggests "somewhere over the rainbow" (among other non-URLs). If I try visiting this URL (https://github.com/brave/browser-laptop/issues/9876)... closing tab... then open new and type "github", it does list this specific issue, but always puts the root domain at the top

I think this is expected behavior (also happens in Safari; doesn't matter if I have visited root domain or not):
![screen shot 2018-06-07 at 12 05 08 am](https://user-images.githubusercontent.com/4733304/41083641-88383e9e-69e6-11e8-8226-8cf6321daf24.png)

The ordering should always be implemented using a "frecency" type algorithm (# visits, how recent each visit was, etc).  See https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm for more info

Closing as `wontfix`

**Comment by jonathansampson** [comment]
[Some users](https://twitter.com/patrick99e99/status/1006300558339158017) report issues with suggestions; namely that the URLs presented aren't always consistent or what the user expects to see. If anybody has a solid, reproducible example to share, it would be greatly appreciated. In the meantime, it might be helpful for us to work on a small documentation that explains in sufficient detail exactly how suggestions are determined.
