### ISSUE TITLE
Toggle payment include button causes the site to be removed from the list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9938]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Toggle payment button in URL bar causes the site to be removed from the list

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

1 | 2
-- | --
Brave | 0.17.14
rev | a8631c6
Muon | 4.1.8

- Steps to reproduce:
    1. Enable payments on a clean install of 0.17.14
    2. Visit Netflix and ensure it is added to the payment list
    3. Visit couple more sites so that there are multiple entries in the ledger table
    4. Go back to netflix and click on the verified publisher icon in the URL bar
    5. Netflix entry in the payment list disappears
    6. Toggle again, netflix comes back to the list
    
- Actual result:
Toggle payment button in URL bar causes the site to be removed from the list

- Expected result:
Should only disable the include switch in ledger table 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![ledger](https://user-images.githubusercontent.com/17010094/28024181-db082102-6587-11e7-850a-cb962ac6c788.gif)

- Any related issues:
cc: @NejcZdovc

**Comment by cezaraugusto** [comment]
happens only with publishers in the exclusion list such as brave.com, google.com, netflix.com.

Verified and unverified && not in exclusion list aren't affected.

**Comment by bsclifton** [comment]
@cezaraugusto is there a way to see the full list? (ex: button should be there, like `Show all`)

**Comment by cezaraugusto** [comment]
@bsclifton big brands are usually in the exclusion list so they never appear as alloable for payments. This is default, but the user may still be willing to give money to Google for example, so they can hit the publisherToggle, and it should be visible.

The bug happens when you disable a website that is declared in the exclusion list -- ledger understands that excluded+disabled websites shouldn't be there. 

This issue doesn't happen for verified websites or other "non-excluded/big branded" websites such as wired.com.
